### ISSUE TITLE
Crash while running dynamicLinks demo proj

### ISSUE THREAD

**Issue by fattomhk** [firebase/quickstart-ios#10]
I changed the bundle id and include my GoogleService-Info.plist then run it.

Here is the error message
*** Terminating app due to uncaught exception 'com.firebase.durabledeeplink', reason: 'Configure Durable Deep Link fails.'

Pod version:
Installing Firebase (3.2.0)
Installing FirebaseAnalytics (3.2.0)
Installing FirebaseDynamicLinks (1.0.3)
Installing FirebaseInstanceID (1.0.6)
Installing GoogleAppUtilities (1.1.1)
Installing GoogleAuthUtilities (2.0.1)
Installing GoogleInterchangeUtilities (1.2.1)
Installing GoogleNetworkingUtilities (1.2.1)
Installing GoogleParsingUtilities (1.1.1)
Installing GooglePlusUtilities (1.1.1)
Installing GoogleSignIn (4.0.0)
Installing GoogleSymbolUtilities (1.1.1)
Installing GoogleUtilities (1.3.1)

Which step am I missing?

**Comment by kroikie** [comment]
The project that you used to generate the GoogleService-Info.plist file, is that a new Firebase project or a Google Developer project that you imported into Firebase?

**Comment by fattomhk** [comment]
Google Developer project
Now I fixed it by:
Go to Google Developer project console to switch on Firebase Rules API (why doesn't it turn on automatically while importing .)
