### ISSUE TITLE
Firebase Cloud Messaging: Chat App with Swift 3

### ISSUE THREAD

**Issue by lethianqt94** [firebase/quickstart-ios#100]
I can't run the FCM example. No token. I am looking for a chat app with FCM (Swift 3). I can't find here. Can some one give me a sample or references? Thanks!

**Comment by ianbarber** [comment]
No token probably means the app is not set up right. If you want, please open an issue with the details of the error you're seeing and the setup steps you've taken (getting the APNs cert, setting up the firebase console project etc.)

**Comment by lethianqt94** [comment]
@ianbarber I am sorry that I am forgot inform you. I got the token. :)
