### ISSUE TITLE
Dynamic Link is not redirect to App Store page without taping on open button in safari web page.

### ISSUE THREAD

**Issue by shubhamjoshi2601** [firebase/quickstart-ios#1016]
My purpose is to invite new user to my app using custom dynamic link. When user tap on dynamic short linking android device then user directly redirect to the Play Store but when we use the same customer dynamic url from iPhone then link open in safari and inside the safari page we have to tap on "Open" button and after that user is redirecting to the App Store.

Our Goal: We want same functionality in iPhone too, if app I s not install in the device then directly App Store should open instead of safari page.
please refer the screenshot.

We are using latest versions of the firebase pods.

![Screen Shot 2020-07-21 at 4 41 47 PM](https://user-images.githubusercontent.com/66054656/88068456-d86beb80-cb8d-11ea-8d80-00714d5a2368.png)
- Xcode Version: 11.4.1
- iOS Version: 13+ (we tested in multiple devices)
- Firebase Dynamic version: 4.2.0

**for reference please check the below custom dynamic link:**

**https://eroego.page.link/89ZXGSqj9SAuif6A8**

**Please check below zip file of videos.**

**Current Result**
[ActualResult.mov.zip](https://github.com/firebase/quickstart-ios/files/4954591/ActualResult.mov.zip)

**Expected Result**
[ExpectedResult.mov.zip](https://github.com/firebase/quickstart-ios/files/4954621/ExpectedResult.mov.zip)

Note: *Our app is not live yet and because of that you can not see the app in iTunes. We tried with the live app too but that live app is not belongs to my teamID*

Please help me to achieve my target

Thanks.

**Comment by morganchen12** [comment]
The preview page is required for exact matching of dynamic links. You can disable it, but you'll end up with weak matches on the client. You can read more at the docs [here](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages).

**Comment by shubhamjoshi2601** [comment]
@morganchen12 we already implemented the navigation parameter but somehow its not reflecting in my long link.

**linkBuilder?.navigationInfoParameters?.isForcedRedirectEnabled = true**

please let me know if we did anything wrong.

**Comment by morganchen12** [comment]
You can copy the link to check manually if the `efr` parameter is present.

**Comment by shubhamjoshi2601** [comment]
@morganchen12 I checked the link but err parameter is missing from my long link even I have added the ear parameter in my code.

**Comment by shubhamjoshi2601** [comment]
@morganchen12 thanks for your support, I resolved the issue.

**let navParam = DynamicLinkNavigationInfoParameters.init()
navParam.isForcedRedirectEnabled = true
linkBuilder?.navigationInfoParameters = navParam**

using this line of code I can see the ear parameter in my link.

Once again thanks.
