### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":   In Podfile:     Firebase/Crashlytics

### ISSUE THREAD

**Issue by Kangqj** [firebase/quickstart-ios#1027]
I can't use Firebase/Crashlytics, becouse when i pod install it, there ares some error, my cocoapod version is 1.9.3
what 's wrong of it?

[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics

None of your spec sources contain a spec satisfying the dependency: `Firebase/Crashlytics`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by morganchen12** [comment]
Can you share your Podfile? Also, does running `pod install --repo-update` fix the issue?

**Comment by satishreddyn579** [comment]
I also faced same issue I updated all **Firebase** pods.
You need to have the latest Firebase related pods(Ex: 'Firebase/Core','FirebaseMessaging' etc.)

**Comment by Kangqj** [comment]
> I also faced same issue and resolved by updating all **Firebase** pods.
> You need to have the latest Firebase related pods(Ex: 'Firebase/Core','FirebaseMessaging' etc.)
OOOh, it worked to me, THANKS!
I update Firebase to this:  **pod update Firebase**, and then I can pod install Firebase/Crashlytics
