### ISSUE TITLE
FIRDynamicLinks not handling short URL

### ISSUE THREAD

**Issue by yuriferretti-luizalabs** [firebase/quickstart-ios#105]
Hi, 
I just implemented a demo application as explained in the dynamic links video tutorial, but the method `handleUniversalLink(_: completion:)` returns `nil` for both  `error` and `dynamicLink` completion handler parameters.
Any hints?

**Comment by SyedIsmailAhamed** [comment]
@yuriferretti-luizalabs  me too facing the same issue, did you manage to get it work.

**Comment by yuriferretti-luizalabs** [comment]
@SyedIsmailAhamed unfortunately I didn't manage how to get it to work. I'm still waiting for someone from firebase team to help me

**Comment by RomainBoulay** [comment]
Same issue here!

**Comment by yuriferretti-luizalabs** [comment]
@RomainBoulay @ SyedIsmailAhamed I found a workaround outside of Firebase Dynamic links framework. We realised that we could send a `GET` request to `short link` URL and we would take a `302 Found` redirection response. Then we just passed the redirection link to our internal link handler and it was parsed successfully.

**Comment by ianbarber** [comment]
Can you try with the latest version of the SDK (3.7.0). 

If its not working can you confirm:
1) You have your bundle ID set up as a customer URL scheme (this is used for validation)
2) Tapping the dynamic link is opening your app properly
3) Any other log messages

**Comment by SyedIsmailAhamed** [comment]
@ianbarber @yuriferretti-luizalabs The short url is working in SDK version (3.7.0). Thank You.

**Comment by jpshelley** [comment]
I'm getting a similar issue now in 3.11.1 I was just on 3.11.0, updated to .1, and getting the same error. I tried reverting by deleting the Pods directory and forcing 3.11.0 but its always returning nil, nil for me.
The short link works fine on my android equivalent app.
