### ISSUE TITLE
Firebase/Crashlytics: Installation via cocoapods: Error: could not find compatible versions

### ISSUE THREAD

**Issue by shamithmukundan** [firebase/quickstart-ios#1051]
Cocoapod version: 1.9.3
Xcode version: 11.3

added "pod 'Firebase/Crashlytics'" in podfile. and ran pod install.

Error: 
```[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics

None of your spec sources contain a spec satisfying the dependency: `Firebase/Crashlytics`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Tried `pod repo update` and `pod install --repo-update`. But the same error.

Podfile: 

    pod 'Firebase/Core'
    pod 'Firebase/DynamicLinks', '~> 4.13'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage' 
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'    

Can somebody help.

**Comment by paulb777** [comment]
Crashlytics is not available in Firebase 4. Remove the version specifier in the Podfile.
