### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by GangadharNilesh** [firebase/quickstart-ios#1061]
Hi,
I downloaded app from App Store . Click on dynamic link its redirecting to App Store but already app is installed. But again I checked app other device that is iPhone X, there its working. Version also same for both devices.

**Comment by morganchen12** [comment]
Hey @GangadharNilesh, please try following the steps in [this guide](https://firebase.google.com/docs/dynamic-links/debug) and if the issue persists file a bug on the [main SDK repo](https://github.com/firebase/firebase-ios-sdk).
