### ISSUE TITLE
Remove #if FIREBASE7 protected code when Firebase 7.0.0 releases

### ISSUE THREAD

**Issue by paulb777** [firebase/quickstart-ios#1064]
In Installations Quick Start

See https://github.com/firebase/quickstart-ios/blob/master/installations/InstallationsExampleSwift/ViewController.swift#L81 and https://github.com/firebase/quickstart-ios/pull/1062#issuecomment-707214684

**Comment by morganchen12** [comment]
Closed in https://github.com/firebase/quickstart-ios/pull/1070.
