### ISSUE TITLE
tvOS won't install Firebase/Analytics

### ISSUE THREAD

**Issue by redimongo** [firebase/quickstart-ios#1067]
So I am using Firebase/Analytics for my iOS app but for some reason the pod installer can't or won't install it for tvOS?

Does firebase not support tvOS?

**Comment by morganchen12** [comment]
We're working on more Apple platforms support, but have no progress updates to share yet.

**Comment by redimongo** [comment]
Hi Megan,
Thanks for that information - we have moved to Yahoo! Flurry as they
support tvOS, iOS and Android.
But thank you anyway.
*Russell Harrower*
*Radio Media PTY LTD*
0449633425
