### ISSUE TITLE
FIRMessagingDelegate can not find declaration

### ISSUE THREAD

**Issue by Atayuksel** [firebase/quickstart-ios#107]
When I try to declare FIRMessagingDelegate in app delegate Xcode gives an error "Cannot find protocol declaration for FIRMessagingDelegate".

I imported firebase as implemented in the project 

```
#import <UIKit/UIKit.h>
#import <UserNotifications/UserNotifications.h>
#import <MessageUI/MessageUI.h>

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
@import UserNotifications;
#endif

@import Firebase;
@import FirebaseInstanceID;
@import FirebaseMessaging;

@interface AppDelegate : UIResponder <UIApplicationDelegate, UNUserNotificationCenterDelegate, FIRMessagingDelegate>
```

I imported firebase via cocoa pods and response is
Installing Firebase 3.2.1 (was 3.2.0)
Using FirebaseAnalytics (3.2.0)
Using FirebaseInstanceID (1.0.6)
Using FirebaseMessaging (1.1.0)

Everything seems fine but I could not solve the problem anyway? What could be reason for the problem?

**Comment by Benjaminm5** [comment]
I updated the cocoapod version (had 0.39.0) and now 1.0.1...

check version by entering: pod --version

then install the newest version with: gem install cocoapods

**Comment by Atayuksel** [comment]
Now I updated pods, It works well, thanks 👍

**Comment by jinguny** [comment]
"pod update" solved the problem

**Comment by MaxBerny** [comment]
I already have pod version 1.0.1 but yet I get the same problem. How to solve it

**Comment by yadavanand** [comment]
@MaxBerny  After updating to cocoapod version 1.0.1 ,
 run pod update, it will solve your problem.

**Comment by revolter** [comment]
How can you update to `1.0.1`? `1.1.1` is the latest version.

**Comment by Benjaminm5** [comment]
1.1.1 should work!

1.0.1 or newer...

Am 27. Dez. 2016, 21:03 +0100 schrieb Iulian Onofrei <notifications@github.com>:

**Comment by i6mi6** [comment]
Although I updated the pods the problem remained. I fixed it by moving `@import Firebase;
@import FirebaseInstanceID;
@import FirebaseMessaging;` above the interface declaration (it was below by mistake)

**Comment by Anilkumarkotur** [comment]
i tried all the suggestion still not working 😞. even if i go into Xcode doc of messaging() i didn't find the "remoteMessageDelegate".

**Comment by gnani1234** [comment]
i am on pod version 1.1.1 but still I didn't find the "remoteMessageDelegate".

**Comment by compbealov** [comment]
i have the same problem i haven't find remoteMessageDelegate yet

**Comment by Anilkumarkotur** [comment]
Actually this was my mistake, as i was migrating from GCM to FCM, first i need to remove the GCM framework and i have to add FCM. but i was adding FCM on top of GCM so i got into an state where i was facing duplication issue with one the class which in both GCM and FCM.  while resolve it podfile.lock was acting very weird and this is the reason for mess. 
https://developers.google.com/cloud-messaging/ios/ios-migrate-fcm

Thanks

**Comment by HaileApp** [comment]
In my case,I've tried to update the pod and it failed.Then I deleted the podfile.lock and run pod install.It finally works!
