### ISSUE TITLE
iOS 14 Paste Notification issue

### ISSUE THREAD

**Issue by muthuselvamlms** [firebase/quickstart-ios#1077]
Hi Team,
Our application using firebase dynamic Links, but from iOS 14, our users frequently getting pasteboard notification and we are getting complaints about this. Is there any future release/update are in plan to mitigate this issue? 

Thanks in advance.

![image](https://user-images.githubusercontent.com/10493255/97984275-8f6a3b00-1dfc-11eb-86f6-ca8da6094d9f.png)

**Comment by morganchen12** [comment]
You can disable pasteboard access. See this comment for more details: https://github.com/firebase/firebase-ios-sdk/issues/5893#issuecomment-657724741
