### ISSUE TITLE
Firebase Dynamic Links not working after updating the pods

### ISSUE THREAD

**Issue by mrithula-ancy** [firebase/quickstart-ios#109]
Hi,
I had updated my pods to the latest pod version for the Notifications to work in iOS 10. But after updating the pods, I lost the resource files GINInviteResources.bundle and GPPACLPickerResources.bundle for dynamic links. Also my dynamic links is not working too. Can someone help me out with this. 

Thanks,
Mrithula

**Comment by ianbarber** [comment]
Can you let us know what your Podfile looks like? Thanks!

**Comment by mrithula-ancy** [comment]
@ianbarber 

platform :ios, "8.0"
use_frameworks!

target 'ABC' do
    pod 'GoogleAppIndexing'
    pod 'Firebase'
    pod 'Firebase/Messaging'
    pod 'Firebase/Core'
    pod 'Firebase/Crash’
    pod 'Firebase/AppIndexing'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Invites'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
end

target 'ABCTests' do
end

target 'ABCUITests' do
end

**Comment by ianbarber** [comment]
I tried an app with the entries in your podfile and the contacts picker for invites loaded properly. Can you give some more details on what the precise issue you are seeing is, and some code that reproduces it if possible?

**Comment by mrithula-ancy** [comment]
@ianbarber  Thanks for responding
I am using few combinations of links. 
Here is one link I am using 
https://v6x38.app.goo.gl/?link=http://www.company.in/main/seo/movie?movie_id=12345&apn=in.company&afl=https://play.google.com/store/apps/details?test&ibi=in.Company&ifl=https://itunes.apple.com/app/company/id12345

when I click on it, my app just opens and thats bcoz the value of 'handled' (given below) returns invalid
let handled = FIRDynamicLinks.dynamicLinks()?.handleUniversalLink(userActivity.webpageURL!) { (dynamiclink, error) in
            if let url = dynamiclink!.url?.absoluteString {
            }
        }
But when I try with the following link, it works fine.
https://v6x38.app.goo.gl/?link=http://www.company.in/main/seo&apn=in.company&afl=https://play.google.com/store/apps/details?test&ibi=in.Company&ifl=https://itunes.apple.com/app/company/id12345

The only difference is that the working link doesn't have the part '/movie?movie_id=12345' in it.

What happened to the resource files of dynamic links framework?

**Comment by ianbarber** [comment]
If you try the debug mode on the link (d=1) you may see some warnings: https://v6x38.app.goo.gl/?link=http://www.company.in/main/seo/movie?movie_id=12345&apn=in.company&afl=https://play.google.com/store/apps/details?test&ibi=in.Company&ifl=https://itunes.apple.com/app/company/id12345&d=1

First thing I notice is that you have references to in.Company and in.company - i would make sure they're the same and that you have one of them registered as a custom URL scheme in XCode. 

With regards to the difference between the two links, in the first one you need to URL encode the parameters to ensure it is parsed properly. Try

https://v6x38.app.goo.gl/?link=http://www.company.in/main/seo/movie%3fmovie_id%3d12345&apn=in.company&afl=https://play.google.com/store/apps/details%3ftest&ibi=in.Company&ifl=https://itunes.apple.com/app/company/id12345

**Comment by mrithula-ancy** [comment]
URL code did the trick.. Thanks a lot @ianbarber.
