### ISSUE TITLE
Firestore Storage Quickstart broken on iOS 13

### ISSUE THREAD

**Issue by schmidt-sebastian** [firebase/quickstart-ios#1097]
Apple seems to no longer allow apps to get the URL to images picked from the image picker (as done here: https://github.com/firebase/quickstart-ios/blob/de2f381f2ff16893201b42512f18e83bff9e534a/storage/StorageExampleSwift/ViewController.swift#L80)

This results in upload failures on iOS 13 ("Failed to issue sandbox extension for file")

Similar issue reported by other apps: https://github.com/dropbox/SwiftyDropbox/issues/256#issuecomment-535667904

**Comment by paulb777** [comment]
Closing for staleness
