### ISSUE TITLE
Firestore Auto-update not happening

### ISSUE THREAD

**Issue by paulb777** [firebase/quickstart-ios#1099]
How is the auto-update configured?  It looks like it's not working for Firestore:

<img width="1016" alt="Screen Shot 2020-12-11 at 9 24 56 AM" src="https://user-images.githubusercontent.com/73870/101934757-e0571700-3b92-11eb-9485-0309d1af3d78.png">

**Comment by morganchen12** [comment]
@ulukaya can you take a look at this?

**Comment by ulukaya** [comment]
My script just finds "Podfile"s and updates them. https://github.com/GoogleCloudPlatform/repository-gardener/blob/master/use-latest-deps-ios.sh#L67
Somehow the latest Podfile update stopped it. I'll check what's going on.

**Comment by ulukaya** [comment]
I don't see any errors but looks like it got timed out. I updated manually for now, that should make the next iteration work. I'll investigate further if it gets stuck again.

**Comment by ulukaya** [comment]
https://github.com/firebase/quickstart-ios/commit/92f82d085c829271c8b2a812cd742e88c160bdae

**Comment by paulb777** [comment]
Reopening since this is still a problem as can be seen from repo's main page's directories' last update messages.

**Comment by morganchen12** [comment]
The culprit seems to be gRPC-C++:

```
Installing gRPC-C++ (1.28.2)
[!] /bin/bash -c 
set -e
sed -E -i '' 's;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g' $(find src/core -type f \( -path '*.h' -or -path '*.cc' \) -print | xargs grep -H -c '#include <openssl_grpc/' | grep 0$ | cut -d':' -f1)
    find src/core/ third_party/upb/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "upb/(.*)";#if COCOAPODS==1\
  #include  "third_party/upb/upb/\1"\
#else\
  #include  "upb/\1"\
#endif;g'
    find src/core/ third_party/upb/ -type f -name '*.grpc_back' -print0 | xargs -0 rm
    find src/core/ src/cpp/ -type f \( -name '*.h' -or -name '*.c' -or -name '*.cc' \) -print0 | xargs -0 -L1 sed -E -i'.grpc_back' 's;#include "(.*).upb.h";#if COCOAPODS==1\
  #include  "src/core/ext/upb-generated/\1.upb.h"\
#else\
  #include  "\1.upb.h"\
#endif;g'
    find src/core/ src/cpp/ -type f -name '*.grpc_back' -print0 | xargs -0 rm

sed: can't read s;#include <openssl/(.*)>;#if COCOAPODS==1\
  #include <openssl_grpc/\1>\
#else\
  #include <openssl/\1>\
#endif;g: No such file or directory
```

**Comment by paulb777** [comment]
Maybe related to the wrong `sed` on the machine? https://github.com/firebase/firebase-ios-sdk/issues/736#issuecomment-362338481

**Comment by morganchen12** [comment]
Based on this flag (`--platform=ubuntu`) in the build logs, the kokoro jobs are running on ubuntu. Moving them to macOS will probably fix the issue.

**Comment by morganchen12** [comment]
Moved jobs to macOS in cl/379353433. Will re-test and see if Firestore works now.

**Comment by morganchen12** [comment]
Kokoro is even more broken now. Going to roll the CLs back while I figure out what in the script is causing failures.

**Comment by morganchen12** [comment]
This has been fixed in the gRPC podspec, and will be fixed in Firestore whenver they update their gRPC dependency.

**Comment by morganchen12** [comment]
Will be fixed in M114.
