### ISSUE TITLE
No such module 'FirebaseUI' using Xcode 7.3

### ISSUE THREAD

**Issue by dddppp** [firebase/quickstart-ios#11]
I downloaded this demo project: [Quick-start ios](https://github.com/firebase/quickstart-ios)

Unfortunately when I try to run the DatabaseExample it gives me the following error:
**No such module 'FirebaseUI'** 

I tried to re-install the pods but didn't suffice. 

Any ideas on how to fix this?

**Comment by sabhay1996** [comment]
use 'FirebaseDatabaseUI' they'll be pushing update soon
