### ISSUE TITLE
Question: inscrutable warning "APNS environment in profile"

### ISSUE THREAD

**Issue by ivanpetrov16130** [firebase/quickstart-ios#110]
Hello!

I get tensive warning every time I run my app:
**<FIRInstanceID/WARNING> APNS Environment in profile: development**

What does it mean? 
I get my token via **[[FIRInstanceID instanceID] token]** , not **setAPNSToken** . Both certificates are uploaded. Is there a way to set "development" or "production" environment?

P.S. File "myProjectName.entitlements" has appeared since I start using XCode8, it has "APS Environment" key-value, but if I set "development" to "production", Info.plist forces me to revert it back.

Thank you!

**Comment by ianbarber** [comment]
As far as I can tell its just logging the value from the entitlement - which is correct if you're using a development key, so nothing to worry about. I have raised an issue internally about not reporting an error for this case.

**Comment by ivanpetrov16130** [comment]
@ianbarber Got it, thank you!
