### ISSUE TITLE
Как мне оставить комент ? Плохо знаю инглишь

### ISSUE THREAD

**Issue by Robin-Gad** [firebase/quickstart-ios#1104]
Как мне оставить комент ? Плохо знаю инглишь

__Originally posted by @Robin-Gad in https://github.com/Robin-Gad/github-slideshow/issues/1#issuecomment-750919925__

**Comment by morganchen12** [comment]
You may want to consult GitHub's help center, though I am unsure if their articles are localized in Russian.
