### ISSUE TITLE
Hi, i am getting the follwing error after a brand new project installation with expo init:

### ISSUE THREAD

**Issue by Robin-Gad** [firebase/quickstart-ios#1105]
Hi, i am getting the follwing error after a brand new project installation with expo init:

Module not found: Can't resolve '@babel/runtime/helpers/classCallCheck' in '..\node_modules\react-native-bootstrap-styles\src'

__Originally posted by @om1 in https://github.com/andrenerd/react-native-bootstrap-styles/issues/58__

**Comment by morganchen12** [comment]
Hey @Robin-Gad, unfortunately I don't know what the cause of this error is, but it does not seem to be Firebase related. Consider posting a question with the react-native tag on StackOverflow.
