### ISSUE TITLE
[Flutter] fatal error: 'FirebaseCore/FIRLogger.h' file not found

### ISSUE THREAD

**Issue by miamee** [firebase/quickstart-ios#1118]
Cannot build on IOS simulator. The error message is below. Do we have a solution about it? Thanks!

Xcode build done.                                            7.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Installati
    onsStore/FIRInstallationsStoredItem.m:19:
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/FIRInstall
    ationsLogger.h:19:9: fatal error: 'FirebaseCore/FIRLogger.h' file not found
    #import <FirebaseCore/FIRLogger.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Installati
    onsStore/FIRInstallationsStoredAuthToken.m:19:
    /Users/liux21/Desktop/cc/flutter_application/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/FIRInstall
    ationsLogger.h:19:9: fatal error: 'FirebaseCore/FIRLogger.h' file not found
    #import <FirebaseCore/FIRLogger.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by morganchen12** [comment]
Closing in favor of https://github.com/firebase/firebase-ios-sdk/issues/7513.
