### ISSUE TITLE
Issue with cloning an app

### ISSUE THREAD

**Issue by brironquillo** [firebase/quickstart-ios#1132]
To whom it may concern,

I tried to clone your demo app by using your provided link but it took so long to clone. I left it all night and came back seeing the same results. It kept saying, "Checking out: swiftui/PasswordlessSwiftUI/media/login_flow.gif". So I force-quitted that xcode and restarted the whole thing. Unfortunately, the result remained the same. Can somebody please help me with this?

**Comment by morganchen12** [comment]
Closing since this isn't a samples issue. You can use GitHub's [download as zip](https://github.com/firebase/quickstart-ios/archive/refs/heads/master.zip) feature in the event that a git clone isn't working.
