### ISSUE TITLE
Question about: [Action Required] Update your Firebase Remote Config SDKs before May 2, 2021

### ISSUE THREAD

**Issue by Kangqj** [firebase/quickstart-ios#1141]
I used Firebase/RemoteConfig in my iOS app, 

This is My PodFile.Lock：
  - Firebase/RemoteConfig (6.34.0):
  - Firebase/CoreOnly
  - FirebaseRemoteConfig (~> 4.9.1)
  
There are two version about FirebaseRemoteConfig, So, What is my FirebaseRemoteConfig  version number?

This is email I received：
`To continue using Remote Config, be sure to upgrade your apps to SDK version 16.3.0+ for Android and 6.3.0+ for iOS before May 2, 2021.`

My question is : Do I need to upgrade my FirebaseRemoteConfig?

**Comment by morganchen12** [comment]
No, your version of Remote Config is newer than the required 6.3.0, so you do not need to upgrade.
