### ISSUE TITLE
New Login Design Proposal -- Multiple Providers?

### ISSUE THREAD

**Issue by peterkos** [firebase/quickstart-ios#116]
The login system is vastly different between each of the examples (Authentication and Database in particular).

This is my attempt to standardize the process and provide a more real-world example of how logins might be achieved.
![screenshot 2016-10-01 11 43 30](https://cloud.githubusercontent.com/assets/2782749/19015166/158f8d54-87cd-11e6-8e9c-02461be15fcd.png)

(The Material design was done just for fun, as since the rest of the app is done in iOS style, the login should probably reflect that.)

The `iOS Design 2` is not technically allowed to be done, as per [Google's sign-in branding guidelines](https://developers.google.com/identity/branding-guidelines) ~~:grumble: :grumble:~~ so the third is more likely, with provider support (with small logos too).

That being said, some of the examples don't support multiple providers. If they all adopted this unified system, any developer who's new to Firebase would only have to learn the authentication code once, and be able to recognize it in each of the projects.  

~~And yes, I know the Google Sign-In button is butchered -- there wasn't an asset provided for the entire button, only the logo, so I had to make do with that.~~

**Comment by mcdonamp** [comment]
Have you seen [FirebaseUI](github.com/firebase/FirebaseUI-iOS)?

**Comment by peterkos** [comment]
@mcdonamp Yes, but the DatabaseExample is the only example that uses it, and only does so in the PostDataSource file (for Swift). The `signIn(_:)` function of DatabaseExample uses standard `UITextField` and `UIButton`s.

**Comment by mcdonamp** [comment]
Agreed that we should have a single way of doing it. Would it be sufficient for us to standardize on the FirebaseUI Auth flow across our examples (where it makes sense)?

**Comment by peterkos** [comment]
For apps that require login, it'd be helpful to have the same interface but with a distinction (i.e., color change and the name of the example, like "Database", below the logo or in the nav bar). 

And yea, I thought you meant that Firebase UI was already being used. I couldn't get it to run on my own machine, but (I think) the most important part for its implementation is for it to be consistent across each example.

**Comment by mcdonamp** [comment]
Yeah, it's not currently used in all our samples, but it's definitely something we should do when we use auth in an example (and don't want to show how to build our own).

**Comment by morganchen12** [comment]
As of recently all of our new quickstarts have been using FirebaseUI's auth flow.

This is pretty low priority for us, as most of the time the code people reference within the quickstarts is not auth code and we also don't want to require extra setup for quickstarts (via auth providers) that demonstrate non-Auth features.

If you feel there's a quickstart that could benefit from adopting FirebaseUI auth instead of whatever it's currently using, please flag it specifically in a separate issue.
