### ISSUE TITLE
Receive data message in ios10 in background and foreground

### ISSUE THREAD

**Issue by kit24** [firebase/quickstart-ios#118]
How does a data message (does not contain notification message) get received in ios10 in both background and foreground? All I found was "On iOS, the data payload is found in didReceiveRemoteNotification". Does this apply to both when phone is in background and in foreground?

**Comment by ulaserdegor** [comment]
Did you solve the problem? @kit24

**Comment by rsattar** [comment]
In the current API, if you are trying to send data messages (not notification messages, which are delivered over APNs), FCM needs `shouldEstablishDirectChannel` to be `true` and on iOS 10 it should implement the optional method `messaging:didReceiveRemoteMessage:` in the `FIRMessagingDelegate`. On iOS 9 and earlier, the data message will be delivered to the system callback `application:didReceiveNotification:fetchCompletionHandler:` or `application:didReceiveRemoteNotification:`, depending on which is implemented by the app delegate.

Data messages are sent over FCM's custom socket-based connection though, which is only maintained with the app is in the foreground (an app cannot maintain a socket connection while it is backgrounded).
