### ISSUE TITLE
When firebase uses analysis, there is no callback method?

### ISSUE THREAD

**Issue by chengxuyuanxiaoka** [firebase/quickstart-ios#1184]
When using firebase analysis, which method is called to receive the callback after sending the punctuation. For example, when the management fails for some reasons, I need to submit the management again or do other processing. At present, I call [firananalytics logeventwithn ame:key parameters : parameters] is there any block or delegate that supports me to determine whether the point is successful. We look forward to your reply

**Comment by morganchen12** [comment]
Currently there's no callback to determine whether or not the Analytics event was submitted successfully. Analytics will batch events on the client, so logged events may not be delivered immediately. You can debug your Analytics events by using the [debug view in console](https://firebase.google.com/docs/analytics/debugview).
