### ISSUE TITLE
How to *Detach* APNS Token

### ISSUE THREAD

**Issue by HiroshiHorie** [firebase/quickstart-ios#119]
I want to detach APNS from the FCM token when the users disables APNS,
so I can at least use the FCM's near realtime network to deliver a payload.

**Comment by HiroshiHorie** [comment]
1. If there is APNS Token attached to the FCM Token AND "notification" key is in the payload :
FCM will try to use the APNS Network to deliver the payload.

2. If there wasn't any APNS Token attached to the FCM token :
FCM would have used FCM Network to deliver the payload. (which only works on foreground)

3. If the use later disables APNS, payloads will be lost since FCM will try to use APNS Network if there is a "notification" key in the payload.

So what I am trying to achieve is to use FCM Network when the APNS is no longer valid (or disabled) so I can receive payloads at least when the app is in foreground. (with a payload with "notification" key)

In iOS, it is easily detectable that APNS has been disabled by checking **application.registeredForRemoteNotifications** so if I can detach the previously attached APNS Token I can fall back to state 2. of the above. (Which is more reliable than a lost payload in the APNS Network)

A workaround I'm currently using is **NOT** to send payloads with "notification" keys to FCM Tokens that have APNS Token attached AND **application.registeredForRemoteNotifications** is **FALSE**.

It makes more sense If I could just Invalidate the APNS Token info attached to FCM Token OR Force to regenerate a new Token with NO APNS info attached.

**Comment by ianbarber** [comment]
Thanks for the clear explanation, that makes a lot of sense! 

Had a quick chat with @kroikie and what seems to be the best route is just to [delete](https://firebase.google.com/docs/reference/ios/firebaseinstanceid/interface_f_i_r_instance_i_d.html#a51b2466dd3f41ad16756cdfb592391cc) the token entirely and set up a new one (then resubscribing to any topics, and sending the token to the back end). 

I think this is fairly uncharted waters though, so would be interesting to see how it works out!

**Comment by HiroshiHorie** [comment]
Yes, I did try to delete the token entirely and setup a new one.
But somehow the APNS information is still associated. Perhaps something related to APNS is still cached locally that attaches the APNS info to the newly generated token.

I will post some code of this attempt after I clean up some code.

**Comment by kroikie** [comment]
If you are not swizzling then you will have to manually call `setAPNSToken` to associate the APNs device token with the new IID token.

**Comment by ianbarber** [comment]
Closing for now, but please repopen if you get chance to pull together an example!
