### ISSUE TITLE
[ios] Product > Archive fails due to `FirebaseAppIndexing(FIRAppIndexing.o)' was built without full bitcode.`

### ISSUE THREAD

**Issue by roblabs** [firebase/quickstart-ios#12]
Love the Firebase tools.  We've implemented Dynamic Links, now we are attempting AppIndexing.  Apologies if this is not where we should've filed this issue.  We understand this is not a quickstarat-ios issue.

### Issue
When building our archive (Xcode Product > Archive), we get the following error.  

```
ld: bitcode bundle could not be generated because 

'<path/to/app>/Pods/FirebaseAppIndexing/Frameworks/FirebaseAppIndexing.framework/FirebaseAppIndexing(FIRAppIndexing.o)' 

was built without full bitcode. 

All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
* Can we work around this with linker flags?  

### Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
 target 'nameOfMyApp' do
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/AppIndexing'
 end
```

**Comment by kroikie** [comment]
Hi roblabs, thanks for the report, this is not the expected result so I think it would be worth submitting an issue to Firebase support.

https://firebase.google.com/support/

Closing this issue here since it is not an issue quickstart-ios

**Comment by roblabs** [comment]
Thanks.  Filed a bug report at https://firebase.google.com/support/


--
Rob Chohan
BSA@RobLabs.com
858 779 4762
Outdoor Ethics Chair, Black Mountain District,
http://sdicbsa.org/Programs/OutdoorEthics/
Leave No Trace Trainer, http://lnt.org
Northern Tier Ambassador, http://ntier.org

**Comment by kroikie** [comment]
Thanks!

**Comment by Bruno-Furtado** [comment]
@roblabs,
Someone answered you?
Could you share the link of the report?

Thanks!

**Comment by roblabs** [comment]
@Bruno-Furtado, nothing yet, this is the last I received from Firebase support.

There doesn't appear to be link that I can share a public Bug Report.


![firebase](https://cloud.githubusercontent.com/assets/118112/15975024/477d34ea-2f00-11e6-9241-abc8c3fff2c4.png)

```
Bug report	
[ios] Product > Archive fails due to `FirebaseAppIndexing(FIRAppIndexing.o)' was built without full bitcode.	
We're investigating	May 25, 2016
```

**Comment by Bruno-Furtado** [comment]
Thanks @roblabs.
I also submitted an issue to Firebase support.

Are you using the App Indexing with the bitcode disabled?

**Comment by roblabs** [comment]
No, we have not tried App Indexing with bitcode disabled.  We do rely on bitcode, as the app thinning advantages are too great for particular app suite.

**Comment by Bruno-Furtado** [comment]
😕
Let's wait...

**Comment by wimbledon** [comment]
Does anyone have update on this issue?

**Comment by kressm** [comment]
Any update on this?

**Comment by roblabs** [comment]
@wimbledon  &  @kressm —  This issue is closed/misfiled here in Github.  The recommendation is to file your own bug report at https://firebase.google.com/support.  That is probably the best way for the Firebase team to prioritize how many people are affected.  As well, this is what @Bruno-Furtado and I have done.

Thanks

**Comment by Bruno-Furtado** [comment]
@roblabs, @wimbledon & @kressm.. 
Good news! 

I received a answer from Google:

```
Thanks Bruno.

We're working on adding the bitcode for this. You should see it sometime in the future. Keep an eye out on the release notes for further updates.

Regards,
```

-

This is the link for release notes: 
https://firebase.google.com/support/releases

:smiley:

**Comment by yoman07** [comment]
any updates?

**Comment by Bruno-Furtado** [comment]
Not yet, @yoman07.

**Comment by levantAJ** [comment]
Any update now?

**Comment by jabb1123** [comment]
Any updates to this?
