### ISSUE TITLE
SwiftUI Performance Quickstart does not use implicit dependencies

### ISSUE THREAD

**Issue by jrcrespoh** [firebase/quickstart-ios#1239]
Context: https://github.com/CocoaPods/CocoaPods/issues/8729
Issue: https://github.com/firebase/quickstart-ios/pull/1238/commits/64353e112d029d767af48125b63b772d5f49d34b
Workaround: ![Screen Shot 2021-08-02 at 11 02 22](https://user-images.githubusercontent.com/8367227/127894974-ad671bcf-aedc-42b9-b467-39ed561f677d.png)

**Comment by paulb777** [comment]
In CI, we should not build for more than one platform at a time. See https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Example/Podfile

**Comment by ahmadalzdwr** [comment]
اريد فتح النت تغلق.  عليا. المساعده

في الثلاثاء، ٣ أغسطس، ٢٠٢١ ٥:٣٢ م Paul Beusterien ***@***.***>
كتب:

**Comment by jrcrespoh** [comment]
SwiftUI Performance Quickstart was transitioned from CocoaPods over to SwiftPM, invalidating the issue: https://github.com/firebase/quickstart-ios/pull/1252
