### ISSUE TITLE
BSMach Error after Enabling Persistence

### ISSUE THREAD

**Issue by otymartin** [firebase/quickstart-ios#125]
I get this error after enabling persistence in my `iMessage App`

```
MessagesExtension[1311:264775] [Common] _BSMachError: port 950f; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
MessagesExtension[1311:264775] [Common] _BSMachError: port 950f; (os/kern) invalid name (0xf) "Unable to deallocate send right"
```

When i comment out `FIRDatabase.database().persistenceEnabled = true` the error goes away.

Why?

**Comment by ianbarber** [comment]
Not sure. Can you put together a minimal repro case we can use to investigate? I don't think we've seen this one before.

**Comment by ianbarber** [comment]
Closing as part of tidying up - please reopen if you can repro in a minimal app!

**Comment by otymartin** [comment]
@ianbarber From what I read of apple docs, its one of those errors that can be ignored. It relates to their keyboard extension apps.

**Comment by ianbarber** [comment]
Ah, interesting! Thanks for the update
