### ISSUE TITLE
Firebase Login results in Thread 1 Bad Instruction: unexpectedly found nil

### ISSUE THREAD

**Issue by warhost** [firebase/quickstart-ios#128]
Hi,

so when logging in with a correct username/password combination, my App crashes, with the following error:

> fatal error: unexpectedly found nil while unwrapping an Optional value
> (lldb) 

Furthermore, there is a Thread 1 at the following line in the `didTapEmailLogin` method:

`self.ref.child("users").child(user.uid).observeSingleEvent(of: .value, with: { (snapshot) in`

>  Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

This could just be me, I am not sure, maybe someone here has a similar problem.
I am using the latest Swift 3 code by the way.

**Comment by morganchen12** [comment]
Can you post the full stack trace here?

**Comment by morganchen12** [comment]
Looks like the line of code you're referencing no longer exists in the project, so I'm going to close this issue. Re-open if it's still an issue.
