### ISSUE TITLE
Xcode Error with Crash Symbol Upload: symbolFileUploadLocation: The caller does not have permission

### ISSUE THREAD

**Issue by talkaboutdesign** [firebase/quickstart-ios#13]
I followed the guide located here:https://firebase.google.com/docs/crash/ios

But when I'm done and attempt to build, I get the following error: /Users/--/Desktop/Test2/Pods/FirebaseCrash/upload-sym-util.bash:349: error: symbolFileUploadLocation: The caller does not have permission

How do you solve this?

**Comment by kroikie** [comment]
Seems like the credentials to do the upload are not valid. Maybe try deleting and recreating the service account for the project, and use

    rm $HOME/Library/Preferences/com.google.SymbolUpload*

to reset your OAuth credentials.

**Comment by talkaboutdesign** [comment]
FYI, When I follow directions I get the following error in Firebase Settings on the website. 

<img width="506" alt="screen shot 2016-05-23 at 9 31 01 pm" src="https://cloud.githubusercontent.com/assets/2926534/15489448/d100dc52-212d-11e6-8bb1-d53ad09a7a6e.png">

<img width="507" alt="screen shot 2016-05-23 at 9 31 17 pm" src="https://cloud.githubusercontent.com/assets/2926534/15489449/d2b44ade-212d-11e6-8bdc-26b133956b36.png">

**Comment by kroikie** [comment]
Could you file this error at through the Firebase bug reporter?

https://firebase.google.com/support/contact/bugs-features

**Comment by fattomhk** [comment]
I am not sure what is the problem, here is my exp.
I faced this problem(error: symbolFileUploadLocation: The caller does not have permission) yesterday. I found that my services account isn't at Editor role(It is Editor if I create a new Firebase project and follow the steps). The problem is gone after I grant it to Editor.

**Comment by talkaboutdesign** [comment]
I tried it. However giving it Editor permission fails in the console ui
everytime.

-- 
Maksim Petriv

**Comment by talkaboutdesign** [comment]
To be precise here is the error I get when I try to set it to Editor role:

<img width="485" alt="screen shot 2016-05-25 at 9 32 11 am" src="https://cloud.githubusercontent.com/assets/2926534/15541690/a48e5e0e-225b-11e6-840c-0f717245db2d.png">

**Comment by talkaboutdesign** [comment]
This is still not resolved. No way for me to upload Symbol files. At least have an option in the console to upload a zip file.

**Comment by talkaboutdesign** [comment]
This fixes the issue. I don't know why it's not part of the documentation. Found on Stackoverflow:

**You need to first accept ToS** at https://console.cloud.google.com/

Then give editor role to your Service Account created for uploading symbols as described here: https://firebase.google.com/docs/crash/ios#set_up_crash_reporting

**Comment by skyfe79** [comment]
@kroikie Thanks kroikie. It worked for me.

**Comment by prashantwizkids** [comment]
I tried all the steps.but it still gives the same error

**Comment by zeinab-reda** [comment]
i cannot upload it always fails with me :(
