### ISSUE TITLE
Firebase does not support M1 Flutter/VSCode

### ISSUE THREAD

**Issue by arvobrendon** [firebase/quickstart-ios#1301]
fatal
    error: module 'firebase_core' not found
    @import firebase_core;

pub spec.yaml
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.7.0

main.dart
import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const MyApp());

**Comment by morganchen12** [comment]
Hi @arvobrendon, please file that on this repository instead: https://github.com/FirebaseExtended/flutterfire
