### ISSUE TITLE
FIRMessaging receiving notification in invalid state 2

### ISSUE THREAD

**Issue by choiks14** [firebase/quickstart-ios#131]
swift 3.0 
ios 10

i got "FIRMessaging receiving notification in invalid state 2" error

how can i?

**Comment by kroikie** [comment]
What version of Xcode are you using? This may occur if your app does hot have push notifications enabled. Could you double check that App > Capabilities > Push Notifications are on.

**Comment by dltlr** [comment]
my notifications work and I see this also, i iOS 9.3.5 Xcode 8.  what does it mean?

**Comment by choiks14** [comment]
ios 10.0.2
xcode 8

and i already enable push notification(App > Capabilities > Push Notifications).

please help me.

**Comment by pkuklis** [comment]
I'm getting the same warning after implementing "content_available" in my notification (but still, everything works great). Is this a warning we should worry about?

**Comment by jerembab** [comment]
@pkuklis do you still have this warning? if not , how did you get rid off it?

**Comment by ianbarber** [comment]
content_available is interesting - that's really there for background push. Can you share any more details about what your implementation looks like (ideally - a minimal repro!)

**Comment by pkuklis** [comment]
@ianbarber Here's my index.js: 

https://github.com/pkuklis/fcm_example/blob/master/index.js

**Comment by ianbarber** [comment]
Thanks! Is your app set up to run in the background (e.g. music playing or similar?) 

To answer the general question - the message is harmless, so you can ignore it. I'll file an issue internally to silence it.

**Comment by pkuklis** [comment]
@ianbarber It's all in foreground. Thanks Ian, that's great to hear! 👍

**Comment by kroikie** [comment]
Closing this, we are working on cleaning up the logs.

**Comment by saninaimayer** [comment]
@kroikie I have the same problem but i need the app receive notifications in background.

**Comment by rsattar** [comment]
@saninaimayer what version of the Firebase SDK are you using? If you are using CocoaPods, can you check the Podfile? There have been updates to how messages are handled when they are received, so testing this on the latest SDK would be useful. Thanks!
