### ISSUE TITLE
Installation token error 401

### ISSUE THREAD

**Issue by ajay2021-VTS** [firebase/quickstart-ios#1326]
FirebaseInstallations (1.7.0):
FirebaseCore (~> 6.10)
    The operation couldn’t be completed. The server responded with an error: 
 - URL: https://firebaseinstallations.googleapis.com/v1/projects/connect-by-crown/installations/davJwIwsfUkQkR-HLXcvKc/ 
 - HTTP status code: 401 
 - Response body: {
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
This is the log error, as the sdk is calling this api, what is the root cause for this error?

**Comment by paulb777** [comment]
The noted versions are very old. Does the problem still occur after `pod update` to Firebase 8.x

**Comment by morganchen12** [comment]
Closing since there hasn't been a response in a while. @ajay2021-VTS please let us know if this is still an issue on the latest version of Firebase.
