### ISSUE TITLE
iOS 15 Crash in FSRWebSocket.m

### ISSUE THREAD

**Issue by iospaveldev** [firebase/quickstart-ios#1336]
Hi!
We have 2 types of crashes on iOS 15.
Firebase Database 8.9.0
Looks like FWebSocketConnection sendStringToWebSocket: has issue.
Could you please check and help ?
Thank you!

**1)**  

Crashed: com.apple.main-thread
0  libdispatch.dylib              0x90c4 dispatch_async + 188
1  libdispatch.dylib              0x90c4 dispatch_channel_async + 188
2  FirebaseDatabase               0x4fac4 -[FSRWebSocket send:] + 765 (FSRWebSocket.m:765)
3  FirebaseDatabase               0x6ba7c -[FWebSocketConnection sendStringToWebSocket:] + 425 (FWebSocketConnection.m:425)
4  FirebaseDatabase               0x6b2fc -[FWebSocketConnection nop:] + 266 (FWebSocketConnection.m:266)
5  Foundation                     0x326ec __NSFireTimer + 104
6  CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
9  CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
10 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x138c GSEventRunModal + 164
12 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
13 UIKitCore                      0x2987f4 UIApplicationMain + 2092
14 Core                           0x6574 main + 340 (<compiler-generated>:340)
15 ???                            0x100b0da24 (Missing)

**2)** 

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x3490 objc_retain + 16
1  FirebaseDatabase               0x6ba68 -[FWebSocketConnection sendStringToWebSocket:] + 425 (FWebSocketConnection.m:425)
2  FirebaseDatabase               0x6b2fc -[FWebSocketConnection nop:] + 266 (FWebSocketConnection.m:266)
3  Foundation                     0x326ec __NSFireTimer + 104
4  CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
5  CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
6  CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
7  CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
8  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
9  GraphicsServices               0x138c GSEventRunModal + 164
10 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
11 UIKitCore                      0x2987f4 UIApplicationMain + 2092
12 Core                           0x6574 main + 340 (<compiler-generated>:340)
13 ???                            0x102b29a24 (Missing)

**Comment by morganchen12** [comment]
@iospaveldev since it's a crash in `objc_retain`, this is most likely some kind of memory corruption (but could also potentially be caused by something else, like retaining an object in a signal handler). You can try to reproduce this with diagnostic tools like tsan or asan, which may provide you with more information.
