### ISSUE TITLE
iOS 10, Xcode8 Messaging `FIRMessagingDelegate` does not called

### ISSUE THREAD

**Issue by nothing2lose** [firebase/quickstart-ios#134]
- Firebase/Messaging (3.7.1):
  - Firebase/Core
  - FirebaseMessaging (= 1.2.0)

Swift 3.0

AppDelegate.swift

```
// MARK: -  FIRMessagingDelegate
func applicationReceivedRemoteMessage(_ remoteMessage: FIRMessagingRemoteMessage) {
    XLog.debug("---------- Firebase") // does not called
}

// MARK: - UNUserNotificatinoCenterDelegate
@available(iOS 10.0, *)
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    XLog.debug("will") // called
    completionHandler([.badge, .sound, .alert])
}

@available(iOS 10.0, *)
func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
    XLog.debug("finish") // called
    completionHandler()
}
```

That issue found when I testing in `Sandbox`
User notification working well. But, FIRMessaging Delegate does not called when App background and foreground. 

I'm does not set **Handling messages with method swizzling disabled**

I can't found releated documents. 

Thanks.

**Comment by ianbarber** [comment]
I think this may be https://github.com/firebase/quickstart-ios/issues/139 - specifically needing a reference to:

    - (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler

**Comment by ianbarber** [comment]
Sorry, 

    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                   fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) 

For background fetch.
