### ISSUE TITLE
This app has 2 unprocessed crashes. Upload 1 dSYM file to process them and  Crashlytics.crashlytics().record(error: error) not working

### ISSUE THREAD

**Issue by sumrucat** [firebase/quickstart-ios#1362]
it's been more than 2 years since my project worked fine but suddenly showed a missing dsYM file. I want to log a non-fatal error on crashlytics but it's not showing on the dashboard.

firebase version-7.6.0
please suggest, I can't update the pod because some frameworks depreciated and we are using them in our project.

**Comment by morganchen12** [comment]
The App Store will periodically recompile your app from bitcode and generate new dSYMs, if you upload these from App Store Connect do the missing dSYM errors go away?

**Comment by sumrucat** [comment]
@morganchen12 bitcode is disabled for our app and in debug mode, we are facing the same issue. this issue started a few days ago before it was working fine.

**Comment by morganchen12** [comment]
Short of updating your dependency, the only thing you can really do is make sure all of your dSYMs have been uploaded to Crashlytics.

**Comment by sumrucat** [comment]
crashes are showing on the dashboard but non-fatal is not showing on the dashboard.
i am using crashlytic.crashlytic().record method for loging non-fatal errors.
-filter already checked
-data collection enabled checked

**Comment by sumrucat** [comment]
I am using 4.7.6 version, can not update to the latest one because we have other dependencies.

**Comment by morganchen12** [comment]
Can you try to reproduce this issue in a separate codebase / test project?

**Comment by sumrucat** [comment]
In Separate codebase project working fine but not in production app.

I am trying it in production app. I checked logs in console where file is
uploading successfully. Do we required some extra settings to log non-fatal
errors on crashlytic.
I already read crashlytic documentation many times and spend sufficient
time on stackoveflow and firebase git issue section. I still not getting
where i need to change. Crashes are reported but non-fatal error is not
showing on dashboard.

Some other information-
We are also using analytics for event loging, it's also working fine.
Analytics event loging can cause issue on crashlytic?

Please let me know any special settings required to log non-fatal errors.

**Comment by morganchen12** [comment]
One last thing you can check that could possibly cause this issue: Are you including Firebase from a dynamic dependency, or directly in your app? If from a dynamic dependency, you may run into issues with duplicate class definitions at runtime.

Otherwise, without a way to reproduce this issue, I won't be able to help you much.
