### ISSUE TITLE
Create branch and update tests for Firebase 9

### ISSUE THREAD

**Issue by morganchen12** [firebase/quickstart-ios#1368]
In order to maintain compatibility with both `master` and `9.0` in the upstream SDK repo, this repo will need to maintain two separate branches as well. This issue roughly outlines what needs to be done:

- [x] Create `firebase-9` branch in this repository
- [ ] Update CocoaPods sources for legacy quickstarts and SPM sources for new quickstarts to point to the [`v9b` branch](https://github.com/firebase/firebase-ios-sdk/tree/v9b) on the new `firebase-9` branch.
- [ ] Update all dependencies and fix any build/test breakages that result.
- [ ] Re-enable tests for Storage and Database and fix any breakages.

**Comment by paulb777** [comment]
For CocoaPods, it might be easier to publish the 9.0.0 podspecs to https://github.com/firebase/Specsdev and point the Podfile's there instead of pointing each pod and dependency to a branch version.
