### ISSUE TITLE
putFile snapshot throws .Unknown error

### ISSUE THREAD

**Issue by JannyKul** [firebase/quickstart-ios#138]
I'm using the Full Sample `.putFile` upload code in the docs [https://firebase.google.com/docs/storage/ios/upload-files](url) with the latest version of Firebase.

The first upload works, the second one throws an .Unknown error
`"Error Domain=FIRStorageErrorDomain Code=-13000 \"An unknown error occurred, please check the server response.\" UserInfo={object=videos/-KTzCsgv4yyHEMOHHrN_.mp4, bucket=qlip-26bd4.appspot.com, ResponseBody=Can not finalize upload.  Current size is 1334326.  Expected final size is 1772834., data=<43616e20 6e6f7420 66696e61 6c697a65 2075706c 6f61642e 20204375 7272656e 74207369 7a652069 73203133 33343332 362e2020 45787065 63746564 2066696e 616c2073 697a6520 69732031 37373238 33342e>, NSLocalizedDescription=An unknown error occurred, please check the server response., ResponseErrorDomain=com.google.HTTPStatus, ResponseErrorCode=400}"`

If i print out the total file size from `uploadTask.observeStatus(.Progress)` using `Double(progress.totalUnitCount),` it points to the first uploaded file. I've sanity checked this with `NSData(contentsOfURL: path).length` so its not an issue in the NSURL being passed to the function, it seems like something to do with the `snapshot` not being deallocated and reassigned.

For anyone else having the same issue I found using `.putData` works fine as a workaround but you get much more progress updates from `observeStatus(.Progress)` using `.putFile` which results in a smoother progress loader.

**Comment by ianbarber** [comment]
@mcdonamp FYI

**Comment by mcdonamp** [comment]
Strange. "Can not finalize upload" typically happens if there's issue with the last chunk upload (note how the error says that it expects one size but got less than that). Is this consistent, or did it only happen once?

**Comment by JannyKul** [comment]
Hey @mcdonamp

So this is essentially what I’m doing:

1. the “uploader”

`var uploadTask: FIRStorageUploadTask!

func uploadVideoFromPath(path:URL){

	//copy the full example from the website

	uploadTask = storageRef.child("videos/filename.mp4").putFile(path)
	
	//copy the rest of the example from the website
}`

2. calling the “uploader”

- The first file I upload is say 1mb in size, this will upload fine every time I restart the app

- The second file I upload lets say is 2mb in size, it will error and the message is along the lines of “Current size is 2mb. Expected final size is 1mb.” Essentially it's referencing the size of the first file. It happens every time.


What I assume is happening is the `FIRStorageUploadTask` can’t be unallocated or reassigned.


I have tried calling:

uploadTask.removeAllObservers()
uploadTask = nil

neither work.

If I change `.putFile` to `.put(try! Data(contentsOf: path))` everything works as expected

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know about this issue. I have been trying to repro this, but was unsuccessful. Would you be able to provide us with your full code sample? I'm particularly interested in the timing of your two operations.

**Comment by jerry604** [comment]
I was having the same problem as @JannyKul. I was only able to reproduce the problem on ios 9.x devices but not 10.x.

**Comment by jerry604** [comment]
@schmidt-sebastian  I'm able to reproduce this issue on ios 9.x devices but not 10.x.

**Comment by iulukaya** [comment]
We are investigating the issue.

**Comment by iulukaya** [comment]
@jerry604 We just updated the sample, can you try again?
