### ISSUE TITLE
Push notification methods missing for when app is in background

### ISSUE THREAD

**Issue by pejalo** [firebase/quickstart-ios#139]
I compiled the FCM Example app on my iOS 10 device and am able to receive push notifications while the app is in the foreground. However, when the app is in the background, and the push notification appears in the notification tray to the user, tapping the notification to open the app does not result in any of the implemented delegate methods being fired.

Thanks to [this StackOverflow answer](http://stackoverflow.com/a/39710072/4621566) I realized a crucial method implementation is missing from the FCM Example app and the [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/receive):

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler`

This is the method that gets fired when a user taps on the notification to open the app. I believe it should be part of the example app and included in all related documentation.

Also, a reference to the corresponding method for iOS 9 and below is also missing from both places:

`- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo`

**Comment by pejalo** [comment]
Upon further inspection of the [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/receive), I see this at the bottom:

> Receive and handle messages with **notification** in the payload

> When your app is in the background, iOS directs messages with the **notification** key to the system tray. A user tap on a notification opens the app, and the content of the notification is passed to the **didReceiveRemoteNotification** callback if implemented in the **AppDelegate**.

I find this confusing for a number of reasons:

1. If following along with the instructions, the reader just implemented a method with the same name: `didReceiveRemoteNotification` when this is actually referring to an entirely separate method (one that doesn't include the completion handler)
2. There is no mention here of the corresponding iOS 10 method (Although to be fair, it seems as though if the iOS 10 method isn't implemented, the iOS 9 one will be called)
3. This one paragraph appears all the way at the end of the page, as if it were an afterthought, even though this is one of the key use cases for push notifications

**Comment by zuil7** [comment]
try setting it to "FirebaseAppDelegateProxyEnabled": NO in your info.plist

**Comment by sjcrank** [comment]
I would like to strongly second this comment, as I carefully followed the instructions from the documentation, misread the last paragraph to refer to the earlier didReceiveRemoteNotification implementation, and was unable to to handle background notifications until implementing the method mentioned in this issue.

**Comment by revolter** [comment]
@pejalo, This is now implemented [here][1], though not complete yet (waiting for #195).

  [1]: https://github.com/firebase/quickstart-ios/blob/bb59dc632d1b45112a50250e41d3cf663debb302/messaging/MessagingExample/AppDelegate.m#L148-L159

**Comment by kroikie** [comment]
Merged the PR so closing this.
