### ISSUE TITLE
some device can not Subscribe topic

### ISSUE THREAD

**Issue by AOEGame** [firebase/quickstart-ios#1404]
Subscribe multi Topics at once times.  can not subscribe topic.

unity firebase version :9.1.0

my code:
Firebase.Messaging.FirebaseMessaging.SubscribeAsync(topic).ContinueWith(task =>
 {
               Debug.Log("FirebaseMessaging.SubscribeAsync:" + topic + " status:" + task.Status);
});

when user enter game. we will subscribe some topics. as free_player, server1.

some devices can not subscribe topic.

**Comment by AbsoluteZeroist** [comment]
Yas Morpurgo

**Comment by morganchen12** [comment]
What error message do you get when attempting to subscribe?

**Comment by AOEGame** [comment]
> What error message do you get when attempting to subscribe?

no error.
after set LogLevel = LogLevel.Debug.  also no error messing!

can not get callBack in "Firebase.Messaging.FirebaseMessaging.SubscribeAsync(topic).ContinueWith"

**Comment by AOEGame** [comment]
this https://github.com/firebase/quickstart-unity/issues/1294

**Comment by morganchen12** [comment]
Closing in favor of the quickstart-unity bug.
