### ISSUE TITLE
QR link changed when using DynamicLinkSocialMetaTagParameters

### ISSUE THREAD

**Issue by abhishekschetu** [firebase/quickstart-ios#1410]
Creating QR code link through the application and sharing on LinkedIn private message but when user tap that link it's redirect to LinkedIn preview page then it change's the QR code link and that QR code link is not working, basically its combine the meta tags that i have added in the code. We are following each and every step of the Firebase Dynamic link tutorial below mentioned: 

            guard let link = URL(string: "https://www.example.com/my-page") else { return }
            let dynamicLinksDomainURIPrefix = "https://XXX.com
            let linkBuilder = DynamicLinkComponents(link: link, domainURIPrefix: dynamicLinksDomainURIPrefix)
            linkBuilder?.iOSParameters = DynamicLinkIOSParameters(bundleID: "com.XXX.some")
            linkBuilder?.iOSParameters?.appStoreID = "XXXXXXX"
           linkBuilder?.androidParameters = DynamicLinkAndroidParameters(packageName: "com.XXX.some")
            linkBuilder?.socialMetaTagParameters = DynamicLinkSocialMetaTagParameters()
            linkBuilder?.socialMetaTagParameters?.title = "demo app"
            linkBuilder?.socialMetaTagParameters?.imageURL = URL(string: "https://barcode1.in/wp-content/assets/sites/16/IN-static.jpg")

**Comment by morganchen12** [comment]
Hi @abhishekschetu, please [file a support issue](https://firebase.google.com/support).
