### ISSUE TITLE
Push Notification is not received  when the app is in background mode or it is force stopped

### ISSUE THREAD

**Issue by duraiganesh0** [firebase/quickstart-ios#143]
i have implemented firebase push in ios 10. when i send push from firebase, i can receive the push message only when the app is in foreground mode. i dont receive any message when the app is in background mode or it is force stopped. code is attached here as zip
[AppDelegate.swift.zip](https://github.com/firebase/quickstart-ios/files/566342/AppDelegate.swift.zip)

**Comment by ianbarber** [comment]
Are you sending the push from the Notifications panel in the Firebase console or via the API?

**Comment by kroikie** [comment]
Hi @duraiganesh0 if you are using the API then could you add the request that you are making to send the FCM message?

**Comment by psuarez** [comment]
Same problem here, I'm trying to migrate from another service (Parse) to Firebase, XCode 8.1, iOS 10.1.1, ObjectiveC, sending notifications from Firebase Console, I've checked all the certificates, upgrading 2 different apps, using the code from the examples, I've read all the similar issues in Stackoverflow and all the blogs I could found, the notifications arrive perfectly and instantly when the app is in foreground, none receive in background or stopped.    Any ideas?

**Comment by davecoffin** [comment]
@duraiganesh0 Try setting content_available to true in the data you pass. That will force your app to "wake up" or something.

**Comment by duraiganesh0** [comment]
thanks guys for your comments. i got it. its working now
