### ISSUE TITLE
PlatformException(sign_in_failed, com.google.GIDSignIn, keychain error, null

### ISSUE THREAD

**Issue by yunusdtarla** [firebase/quickstart-ios#1446]
Hello everyone two days ago I was able to connect to the Firebase system without any problems, but now I can't login to the application. Although the accounts are correct in Google and email entries, it gives an error. Which setting do you think is broken?

**PlatformException(sign_in_failed, com.google.GIDSignIn, keychain error, null**

**Comment by morganchen12** [comment]
Can you share the full error? The keychain error code will tell you what went wrong.

**Comment by yunusdtarla** [comment]
Hi @morganchen12 It throws errors not only in google but also in email entries. 

<img width="1022" alt="Ekran Resmi 2022-10-12 19 26 53" src="https://user-images.githubusercontent.com/72821593/195397595-27e427f5-e04f-4fac-a972-725fe55769f1.png">

**Comment by morganchen12** [comment]
Please open this issue on the [Flutter repository](https://github.com/firebase/flutterfire).
