### ISSUE TITLE
Can't subscribe to topic

### ISSUE THREAD

**Issue by sendoa** [firebase/quickstart-ios#146]
I'm trying to subscribe to a topic using the following code (from device):

```swift
func connectToFcm() {
    FIRMessaging.messaging().connectWithCompletion { (error) in
        if (error != nil) {
            print("Unable to connect with FCM. \(error)")
        } else {
            print("Connected to FCM.")
            FIRMessaging.messaging().subscribeToTopic("/topics/default-notifications-channel")
        }
    }
}
```

The debugger shows the following message:

```
<FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=5 "(null)"
```
I can receive device targeted notifications so APNS configuration is working correctly.

```
Using Firebase (3.8.0)
Using FirebaseAnalytics (3.5.1)
Using FirebaseCore (3.4.4)
Using FirebaseInstanceID (1.0.8)
Using FirebaseMessaging (1.2.1)
```

Any ideas? Thank you!

**Comment by alibasta** [comment]
Same here. Registering multiple tropics at once.

**Comment by nilskassube** [comment]
I have the same issue with registering multiple topics. Always:

2016-11-09 11:22:52.106: <FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=5 "(null)"

**Comment by olegdynamo** [comment]
Yes, same here. Looping through the topics results in errors. As in https://github.com/firebase/quickstart-ios/issues/8 - which is not fixed even though it is closed. I have tried putting 1 second delay between the calls (far from optimal), but even then some of the subscribe calls fail. It would be also great to have callbacks from the subscribeToTopic and unsubscribeFromTopic methods..

**Comment by kroikie** [comment]
Hi All, we are looking into the issues when subscribing to many topics.

Also when subscribing to topics from the iOS SDK you should not prepend the topic name with /topics/ just use the topic name.

**Comment by sendoa** [comment]
Hi @kroikie, thanks for your insight.

The problem occurs even when subscribing to a unique topic. On the other hand, if I subscribe to topics from iOS without prepending the topic name with `/topics/` I get the following runtime warning (for a topic called `default-notifications-channel`):

```
2016-11-10 09:18:44.562: <FIRMessaging/WARNING> WARNING. Topic name default-notifications-channel should be prefixed with /topics/ as /topics/default-notifications-channel
```

Thank you!

**Comment by kroikie** [comment]
@sendoa you are correct, sorry, currently the iOS SDK does currently require the `/topics/` prefix.

As for the topic subscriptions failing, they should be retried automatically. Have you tried adding a delay between subscriptions as suggested by @olegdynamo?

**Comment by sendoa** [comment]
@kroikie the problem occurs even when subscribing to a **single** topic.

Thank you!

**Comment by rikoap** [comment]
I have the same issue. Anyone have solution?

**Comment by apognu** [comment]
We're having the exact same issue, and multi-topic subscriptions is very important to us.

Any news?

**Comment by revolter** [comment]
Multi-topic subscriptions is very important to anyone!

**Comment by lqsa00** [comment]
I've added in URL Types com.google.fcm and the error dissappears, I don't know why.

You can see like to add in this link [](http://stackoverflow.com/questions/37403795/app-invite-configuration-failed-firebase-ios-cocoapods).

**Comment by revolter** [comment]
I can't see `com.google.fcm` on that SO question.

**Comment by kroikie** [comment]
@sendoa If you are seeing the same error when subscribing to a single topic I would suggest you file a support ticket at firebase.google.com/support since I'm not able to reporduce that. Maybe with more information we can get to the bottom of it. Please identify me in the request so that it can be directed to me.

@all: The issue of subscribing to multiple topics is known and we are implementing a fix. Implementing a delay between subscriptions should help in the mean time.

**Comment by rikoap** [comment]
Hi @kroikie , when are you going to release the fix? Do you have estimation time?

**Comment by revolter** [comment]
A delay workaround is ok only in theory, in real world it can't be done because you can't know how long the delay should be. Looking forward for the fix.

**Comment by Codeido** [comment]
same problem here

**Comment by alibasta** [comment]
Why is Google ignoring us??

**Comment by kroikie** [comment]
@All I apologize for the delay in resolving this issue.

As an update: We have identified the issue and a fix is in the works and will be released soon.

**Comment by Codeido** [comment]
@kroikie do you have news about this issue?

**Comment by BennSandoval** [comment]
My workaround was a delay between subscriptions.

**Comment by rikoap** [comment]
@kroikie Have the fixed version already released? 
I can not found it on here https://firebase.google.com/support/release-notes/ios

**Comment by thedore17** [comment]
@kroiekie I'm getting this subscribing to even a single topic. When I subscribe to multiple (and in production I need to be able to subscribe to dozens at once), the app hangs while the SDK retries until the entire thing times out and crashes. Even running it async in the background queue.

Plus I still get this error at startup even with both dev and production certs uploaded to console, push capability toggled on, and background services to remote notifications enabled: FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)" 

Clearly a lot of people are finding this to be a very big issue for months now. You said you were looking into it two months ago. What's going on here?

**Comment by kiyotakagoto** [comment]
@kroikie  Is there any progress?

**Comment by Codeido** [comment]
Any news?

**Comment by thedore17** [comment]
@kroikie It's been over two months since you said you guys were looking into it. This is a pretty issue with the SDK and its reliability. What's going on?

**Comment by kroikie** [comment]
As an update: we have identified the issue and have a solution, we are working on getting it published ASAP, I will update here as soon as it is available.

**Comment by smarcet** [comment]
i am seeing the same behavior on droid using

 compile 'com.google.firebase:firebase-core:10.0.1'
 compile 'com.google.firebase:firebase-messaging:10.0.1'

any news about fixing it on android sdk
?
regards

**Comment by nickdnk** [comment]
Could you take a look at the inconsistency in the /topic prefix while you're at it? The latest iOS SDK documentation says

```
topic
The name of the topic, for example "sports".
```

For the first argument. However, if one supplies "sports", the console complains that it is not prefixed with "/topics/".

For this method. Which works when it looks like this:
`FIRMessaging.messaging().subscribe(toTopic: "/topics/myTopic")`

It does not work without /topics/ prefixed.
This inconsistency is very confusing.

**Comment by dekeract** [comment]
Hi! 
I'm using version FirebaseMessaging (1.2.1) for ios, and I also have this errors in console.
But I tried to send messages via curl, and it works fine. 
Seems like this is just artifact messages, like when sdk tries to send subscription request when previous is failed. Is this possible?

**Comment by nickdnk** [comment]
3.13 seems to address this issue. Diego commented on my question here: http://stackoverflow.com/questions/42233474/firebase-clear-cached-subscriptions-after-delete (which was also entirely resolved by this update).

**Comment by nfinfu** [comment]
I saw the same error when I try to subscribe to only one topic. After that I tried it in the didRegisternotificationSettings: method and error gone. If you use static topic names, you can try this. When I sent notification to that topic, it succeeded. 

func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings) {
        let topicName = "/topics/news"
        FIRMessaging.messaging().subscribe(toTopic: topicName)
    }

I hope this helps somebody else.

**Comment by nickdnk** [comment]
@nfinfu What notification do you send and from where?

**Comment by nfinfu** [comment]
@nickdnk I used postman (chrome extension to make http request) and configuration is same with firebase documents. 

**Header values:**
Content-Type: application/json
Authorization: key=YOUR_SERVER_KEY

**Request body:**
{ 
	"to" : "/topics/news",
	"data": {
        "link" : "www.google.com"
    },
    "notification" : {
        "body" : "body string",
        "title" : "title string"
    }
}

**Comment by nickdnk** [comment]
I meant what UNNotification do you send to didRegister? In Swift.

**Comment by nfinfu** [comment]
@nickdnk I did not use UNNotification, I used this configuration to take notification request in **didFinishLaunchingWithOptions** method:

let settings: UIUserNotificationSettings =
            UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
        application.registerUserNotificationSettings(settings)
        
        application.registerForRemoteNotifications()

**didRegister notificationSettings:**  is the applicationDelegate methods which invoke when you make a notification request like above.

**Comment by nickdnk** [comment]
But that's not different than waiting a bit, since didRegister returns immediately if a token exists.

Are you sure that it's not just fixed because you updated to the latest version of the SDK? (3.13). As I posted the error has been fixed.

**Comment by nfinfu** [comment]
I installed the sdk today and when i try to subscribe i saw the error on console. After move the code into didregister, error gone.

**Comment by nickdnk** [comment]
Odd. Are you sure you have the 3.13 version installed as Pod? In your Podfile.lock I mean. I changed nothing other than updating. I even deleted the app from my device entirely and reinstalled to verify that it was actually fixed. Haven't seen the error since. I don't use didRegister for anything other than:

`FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .sandbox) // or .production`

**Comment by nfinfu** [comment]
This is the my podfile.lock content:

- Firebase/Core (3.12.0):
- Firebase/Messaging (3.12.0):

I don't understand why pod installed the previous version.

**Comment by nickdnk** [comment]
Tryin doing

pod clean
pod install

And make sure you don't have a specific version set in your Podfile :)

Sent from my iPhone

On 17 Feb 2017, at 20.26, nfinfu <notifications@github.com<mailto:notifications@github.com>> wrote:


This is the my podfile.lock content:

  *   Firebase/Core (3.12.0):
  *   Firebase/Messaging (3.12.0):

I don't understand why pod installed the previous version.

**Comment by JangT** [comment]
I am using the Firebase Unity SDK.
Topic works well for AOS but not for iOS Topic.
In iOS, if send a bundle, you will receive a notification. If send it to Topic, it will not be received.

Can not subscribe to topic: / topics / *** with token: (null)
like this

**Comment by stewartmiles** [comment]
@JangT see my response on https://github.com/firebase/quickstart-unity/issues/33

**Comment by rdelrosario** [comment]
Getting the same issue here when subscribing to single or multiple topics on iOS. Any updates?

**Comment by rsattar** [comment]
If you're still having trouble subscribing to topics? What is your Firebase Messaging SDK version? I'd _highly_ recommend you upgrade to FirebaseMessaging 2.x (part of Firebase 4.x released at Google I/O. If not able to get to FirebaseMessaging 2.x, at least try and get to the latest 1.x version, as it has some bug fixes around topic subscription.

**Comment by naftaly** [comment]
@rsattar Still seeing these issues. For every subscription the following gets logged to the console in xCode:
```
[Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "(null)"
```

**Comment by rdelrosario** [comment]
Try adding this to your Info.plist:

<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.google.fcm</string>
			</array>
		</dict>
</array>

**Comment by rsattar** [comment]
@rdelrosario Hmm, that should not make any difference, as FCM doesn't do anything with URL Schemes. 

@naftaly When during app start are you subscribing to a topic? Typically you want to subscribe when you know you have a token from FCM. Also, if you set `shouldEstablishDirectChannel` to true, are you seeing any errors in the Xcode console for that? The direct channel is unrelated to topics, but failure to connect to that would suggest a possible problem.

**Comment by naftaly** [comment]
@rsattar I subscribe whenever the `FIRMessaging` system tells me theres a new FCM token, so usually a bit after startup. Definitely past `didFinshLaunching`. Not seeing anything related to `shouldEstablishDirectChannel` in the console but then again I'm not sure what to look for and FIR outputs a lot of stuff when in debug logging mode.

**Comment by naftaly** [comment]
@rsattar Not sure this is 100% relevant, but it definitely seems so. The send Der from the registration request seems to be the FCM token. If I use that same token and try and send a message through the firebase console, the result says that token is not registered. 

![screen shot 2017-08-11 at 3 37 16 pm](https://user-images.githubusercontent.com/221626/29229258-52cca99c-7eab-11e7-8546-67cacc3f1dac.png)

**Comment by naftaly** [comment]
It appears that all I Needed to do was delete the app from my phone then reinstall and everything started working correctly.

**Comment by rsattar** [comment]
Thanks for the detailed info @naftaly! I'm glad it's working now after an app reinstall. That suggests a possible bug in what was stored (either the Instance ID itself, or the token). Was there any change to the app's bundle ID, app version, the GoogleService-Info.plist, or anything else between builds of your app?

**Comment by naftaly** [comment]
@rsattar the version was bumped. Can’t think of anything else.

**Comment by jkmathew** [comment]
@kroikie @rsattar , I still have this issue when subscribing to multiple topics.
My app flow is something like,
App is listing a set of topics in a table view, on done action I am iterating through the topics.  Based on the user selection I am subscribing/unsubscribing to particular topics.  But its not registering the subscription.
I checked the subscription with `https://iid.googleapis.com/iid/info/<fcmtoken>?details=true` but its not listing any topics that I have subscribed.  
I tried subscribing to another topic(only one), that topic is listing in the above API call.

**Comment by ynstek** [comment]
IS SOLVED:
I had this problem too. After many attempts, I reached a solution.
You must run the subscription topic code after the firebase token send operation.
`FIRMessaging.messaging().subscribeToTopic("news")`
For example, 
I pulled out the json data and started the subscription after fill the table.

**Comment by morganchen12** [comment]
Hey all, 

This issue has grown long enough that it's become hard to find help for individual errors within this large thread. If you're still struggling with this issue, please **open a new issue** with the version of Firebase Messaging you're using, the code you're using to integrate Messaging, and any error messages that appear in console.

**Comment by sKuD51** [comment]
Hi, 

for me, it was an error between the bundle identifier in Xcode and my firebase configuration.

**Comment by Anujmoglix** [comment]
Hi all ,
I am getting issue Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

var myTopics = "all";
      this.fcm.subscribeToTopic(myTopics).then(success => {
          console.log("***Here is success****"+success); alert(success) },
              error => { console.log("***This is the issue****"+error); alert(error);})
          .catch(response => {
              alert(response);
              console.error('Gists error = ', response);
          });
