### ISSUE TITLE
FirebaseCore import? 

### ISSUE THREAD

**Issue by raymondwelch33** [firebase/quickstart-ios#1466]
At this link: 

https://github.com/firebase/quickstart-ios/blob/master/authentication/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift

`FirebaseCore` is imported into the class. Why? Is it necessary?

**Comment by morganchen12** [comment]
The user is required to display information about the account. Depending on your own code, you may or may not put it in the designated initializer's parameters.

The `FirebaseCore` import is redundant due to the `FirebaseAuth` import.
