### ISSUE TITLE
Deep link method not call when app is not install?

### ISSUE THREAD

**Issue by maulikshah09** [firebase/quickstart-ios#1475]
I share link to my friend. He is clicking the link it redirect the Appstore after installation deep link method not called. what is the issue. 

I checked with him after installation. 
-----------
install the app and click on the same link then it is working..

problem
======
- App is not installed 
- click the link 
- go to App Store 
- after install not getting any deeplinking data.[not called method]

Please help me as soon as possible my app is live.

Thanks

**Comment by KobbySkywalker** [comment]
Hi @maulikshah09, If I understand your problem clearly, you want to access the data from the deep linking after app installation. This will not be possible as at the time of accessing dynamic link, the app wasn't installed, hence, the redirection to the App Store as the fallback. 

To be able to access the data in the deep link, your friend should use the link to reopen the app for data to be accessible. Hope this helps.

**Comment by Nooknook88** [comment]
Deep link method not call when app is not install?

**Comment by maulikshah09** [comment]
It is solved There is problem in appdelegate method..
