### ISSUE TITLE
How-to simulate token refresh

### ISSUE THREAD

**Issue by roccozanni** [firebase/quickstart-ios#148]
Hi, 
we're migrating from GCM to FCM, and we'd like to test also the token refresh feature before going live with this update. Similarly of what we did on Android, we tried to simulate this by forcing the token deletion, this way: 

```
FIRInstanceID.instanceID().deleteIDWithHandler { (error) in
    DDLogDebug("ID deleted \(error)")
    FIRInstanceID.instanceID().getIDWithHandler { (id, error) in
        DDLogDebug("Got new ID: \(id) \(error)")
    }
}
```

but then, here on iOS, it start behaving weird:

- the notification `kFIRInstanceIDTokenRefreshNotification` is not triggered
- even if we manually setting again the APN token on `FIRInstanceID` and we re-subscribe to the topics again, we're not receving any notification. If we manually get the token with `FIRInstanceID.instanceID().token()` we can see there is a new one but it still not working.

I don't know if the mistake in our side or on the library side. Maybe we're testing it the wrong way, or maybe invalidating the token manually leads to some edge case that the SDK is not handling correctly. Has anyone experienced this? What we fear is that the whole token refresh process is not working as expected and at some point our application will suddenly stop to receive notifications when it's live in production.

Thanks,
Rocco

**Comment by kroikie** [comment]
Hi @roccozanni sorry for the delayed response, I was able to reproduce this and we are investigating I will report here with more details when we have them.

**Comment by kroikie** [comment]
Hi Jacob,

Once a token is generated then the observer of
kFIRInstanceIDTokenRefreshNotification should be called. Is your app able
to receive any notifications?

**Comment by grioja** [comment]
@kroikie user error :) misconfigured the notification handler

**Comment by cblaze22** [comment]
Misconfigured in what way?
