### ISSUE TITLE
how to received notification correctly 

### ISSUE THREAD

**Issue by AZN-Davy** [firebase/quickstart-ios#1482]
Hi,

So here is my code i am pretty desperate because i already follow many tuto from youtube or i check stackoverflow i didn't find any response. so here is my probleme :
emulator -> send notification to : iphone/ android phone
android phone -> receive notification
iphone -> didn't receive notification 

so what i want is where in my code is wrong because i can't receive notification
what i already check is  :
- notification is already on.
- i use google firebase i have an APNs Auth Key

here is my code : 
Appdelegate : 

class AppDelegate: UIResponder, UIApplicationDelegate, MessagingDelegate, UNUserNotificationCenterDelegate {
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        UserDefaults.standard.setValue(false, forKey: "_UIConstraintBasedLayoutLogUnsatisfiable")
        //google places key
        GMSPlacesClient.provideAPIKey("google key")
        
        // Configure Firebase
        FirebaseApp.configure()
        Messaging.messaging().delegate = self
        UNUserNotificationCenter.current().delegate = self
        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound]) { (granted, error) in
            if granted {
                print("User gave permissions for local notifications")
            }
        }
        application.registerForRemoteNotifications()

        return true
    }
    
    
    // Handle failing to register for push notifications
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("Failed to register for remote notifications: \(error.localizedDescription)")
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
         print(response)
     }
    
    // Handle receiving an FCM registration token
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        print("FCM registration token: \(fcmToken ?? "000")")
        // Do something with the token
    }
    
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        print("Received push notification: \(userInfo)")

        // Handle the push notification here

        completionHandler(UIBackgroundFetchResult.newData)
    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        
  
        // Set APNS device token in FCM instance
        Messaging.messaging().setAPNSToken(deviceToken, type: .prod)
        
        // Retrieve FCM token
        Messaging.messaging().token { token, error in
            if let error = error {
                print("Error retrieving FCM token: \(error.localizedDescription)")
            } else if let token = token {
                print("FCM token: \(token)")
            }
        }
    }
}

how i get my token on my ViewController: 

   func getToken(id: String, type: String) {
        // Declare observer as an UnsafeMutablePointer
        var observer: UnsafeMutablePointer<NSObjectProtocol?>?
        observer = UnsafeMutablePointer<NSObjectProtocol?>.allocate(capacity: 1)
        // Set up observer to wait for FCM token refresh
        observer?.pointee = NotificationCenter.default.addObserver(forName: Notification.Name.MessagingRegistrationTokenRefreshed, object: nil, queue: .main) { [weak self] notification in
            guard let self = self else { return }
            guard let token = Messaging.messaging().fcmToken else {
                print("Error fetching FCM registration token: No token found in notification")
                return
            }
            print("FCM registration token: \(token)")
            self.firebaseToken = token
            self.setToken(id: id, type: type, token: token)
            // Remove observer
            if let observer = observer {
                NotificationCenter.default.removeObserver(observer.pointee!)
                observer.deallocate()
            }
        }
        
        // Retrieve FCM token
        if let token = Messaging.messaging().fcmToken {
            // FCM token may be immediately available
            print("FCM registration token: \(token)")
            self.firebaseToken = token
            self.setToken(id: id, type: type, token: token)
            // Remove observer
            if let observer = observer {
                NotificationCenter.default.removeObserver(observer.pointee!)
                observer.deallocate()
            }
        }
    }
    
    here is my send notification :
    
        func sendFCMNotification(toToken token: String, title: String, body: String) {
        let urlString = "https://fcm.googleapis.com/fcm/send"
        guard let url = URL(string: urlString) else { return }
        
        let notification = ["title": title, "body": body]
        let data: [String: Any] = ["notification": notification, "to": token]
        
        var request = URLRequest(url: url)
        request.allHTTPHeaderFields = ["Content-Type": "application/json", "Authorization": "key=Firebase server key"]
        request.httpMethod = "POST"
        request.httpBody = try? JSONSerialization.data(withJSONObject: data, options: [])
        
        let task = URLSession.shared.dataTask(with: request) { data, response, error in
            if let error = error {
                print("Error sending FCM notification: \(error.localizedDescription)")
            } else {
                if let httpResponse = response as? HTTPURLResponse {
                    if httpResponse.statusCode == 200 {
                        print("FCM notification sent successfully.")
                    } else {
                        print("Error sending FCM notification. HTTP response code: \(httpResponse.statusCode)")
                    }
                }
            }
        }
        task.resume()
    }

**Comment by AZN-Davy** [comment]
up

**Comment by morganchen12** [comment]
Are you able to receive notifications directly through APNs?

**Comment by AZN-Davy** [comment]
i have generating an APNs Token and send a notification with the FireBase but it didn't work
