### ISSUE TITLE
SafariServices is not available when building for tvOS Simulator.

### ISSUE THREAD

**Issue by ccn01347** [firebase/quickstart-ios#1488]
Xcode: 14.3.1
CocoaPod: 1.12.1

Step to reproduce:
1. use xcode 14.3.1 to create a new project for apple tv.
2. Pod init
3. Open the .xcworkspace
4. add FirebaseAuth
5. pod install
6. Build on Apple TV Simulator.

and got these error message:
`SafariServices is not available when building for tvOS Simulator.`

**Comment by paulb777** [comment]
Please report at https://github.com/firebase/firebase-ios-sdk/issues with a completed template.
