### ISSUE TITLE
StorageExampleSwift Download not working

### ISSUE THREAD

**Issue by guydaher** [firebase/quickstart-ios#15]
Getting the error below when clicking on the Download button in the Swift example. Works fine in the Obj-C example. 

> Error downloading:Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response."

**Comment by iulukaya** [comment]
Can you give more detail?

**Comment by guydaher** [comment]
I simply take a photo, it gets uploaded. Then click on the download button in the app and I get the failure above. I tried in simulator and phone, same in both. That happens in Swift example, but the obj-c example works fine. 

Can you try the example on your devbox?

**Comment by jeyosman1** [comment]
Thanks for you nice friendlyChatSwift tutorial unable to type a letter. I want have user name not from the part of the email. Enter the username field the use displlayName

**Comment by jeyosman1** [comment]
Attachment is also not working only the name part of @ like jey@go.com only jey is displayed nothing else

**Comment by jeyosman1** [comment]
var photoUrl =  NSURL?.self getting error without self or var photoUrl =  NSURL()

**Comment by jeyosman1** [comment]
can explain why use :??  
AppState.sharedInstance.displayName = user?.displayName ?? user?.email what does "??" mean

**Comment by iulukaya** [comment]
https://github.com/firebase/quickstart-ios/pull/41

**Comment by jeyosman1** [comment]
still waiting if possible an answer

**Comment by TMSCH** [comment]
Hi jeyosman1, have you tried with the newest version of the app? Is your issue similar with the one guydaher had?

**Comment by jeyosman1** [comment]
Where is the newest version
