### ISSUE TITLE
There was this issue in Analytics 8.10.1 where the letter 'k' had been removed from some event and parameter names.

### ISSUE THREAD

**Issue by codybak4** [firebase/quickstart-ios#1512]
There was this issue in Analytics 8.10.1 where the letter 'k' had been removed from some event and parameter names.

https://github.com/firebase/quickstart-unity/issues/1273

It appears to be fixed in 9.1.0 however some event and parameter names are now missing.

These are the ones that are missing for me.

FirebaseAnalytics.ParameterSignUpMethod
FirebaseAnalytics.ParameterCheckoutStep
FirebaseAnalytics.ParameterCheckoutOption
FirebaseAnalytics.EventCheckoutProgress

namespace Firebase.Analytics
{
	public sealed class FirebaseAnalytics
	{
		public static string ParameterCharacter { get; }
		public static string ParameterLevelName { get; }
		public static string ParameterLevel { get; }
		public static string ParameterItems { get; }
		public static string ParameterItemVariant { get; }
		public static string ParameterItemName { get; }
		public static string ParameterItemListName { get; }
		public static string ParameterItemListID { get; }
		public static string ParameterItemId { get; }
		public static string ParameterItemCategory5 { get; }
		public static string ParameterItemCategory4 { get; }
		public static string ParameterItemCategory3 { get; }
		public static string ParameterItemCategory2 { get; }
		public static string ParameterLocation { get; }
		public static string ParameterItemCategory { get; }
		public static string ParameterIndex { get; }
		public static string ParameterGroupId { get; }
		public static string ParameterFlightNumber { get; }
		public static string ParameterExtendSession { get; }
		public static string ParameterEndDate { get; }
		public static string ParameterDiscount { get; }
		public static string ParameterDestination { get; }
		public static string ParameterCurrency { get; }
		public static string ParameterCreativeSlot { get; }
		public static string ParameterCreativeName { get; }
		public static string ParameterCreativeFormat { get; }
		public static string ParameterCoupon { get; }
		public static string ParameterItemBrand { get; }
		public static string ParameterContentType { get; }
		public static string ParameterLocationID { get; }
		public static string ParameterMedium { get; }
		public static string ParameterVirtualCurrencyName { get; }
		public static string ParameterValue { get; }
		public static string ParameterTravelClass { get; }
		public static string ParameterTransactionId { get; }
		public static string ParameterTerm { get; }
		public static string ParameterTax { get; }
		public static string ParameterSuccess { get; }
		public static string ParameterStartDate { get; }
		public static string ParameterSourcePlatform { get; }
		public static string ParameterSource { get; }
		public static string ParameterShippingTier { get; }
		public static string ParameterShipping { get; }
		public static string ParameterMarketingTactic { get; }
		public static string ParameterSearchTerm { get; }
		public static string ParameterScreenClass { get; }
		public static string ParameterScore { get; }
		public static string ParameterQuantity { get; }
		public static string ParameterPromotionName { get; }
		public static string ParameterPromotionID { get; }
		public static string ParameterPrice { get; }
		public static string ParameterPaymentType { get; }
		public static string ParameterOrigin { get; }
		public static string ParameterNumberOfRooms { get; }
		public static string ParameterNumberOfPassengers { get; }
		public static string ParameterNumberOfNights { get; }
		public static string ParameterMethod { get; }
		public static string ParameterScreenName { get; }
		public static string ParameterContent { get; }
		public static string UserPropertySignUpMethod { get; }
		public static string ParameterCampaignID { get; }
		public static string EventScreenView { get; }
		public static string EventRemoveFromCart { get; }
		public static string EventRefund { get; }
		public static string EventPurchase { get; }
		public static string UserPropertyAllowAdPersonalizationSignals { get; }
		public static string EventLogin { get; }
		public static string EventLevelUp { get; }
		public static string EventLevelStart { get; }
		public static string EventLevelEnd { get; }
		public static string EventSearch { get; }
		public static string EventJoinGroup { get; }
		public static string EventEarnVirtualCurrency { get; }
		public static string EventCampaignDetails { get; }
		public static string EventBeginCheckout { get; }
		public static string EventAppOpen { get; }
		public static string EventAddToWishlist { get; }
		public static string EventAddToCart { get; }
		public static string EventAddShippingInfo { get; }
		public static string EventAddPaymentInfo { get; }
		public static string EventAdImpression { get; }
		public static string EventGenerateLead { get; }
		public static string EventSelectContent { get; }
		public static string EventPostScore { get; }
		public static string EventSelectPromotion { get; }
		public static string ParameterCampaign { get; }
		public static string ParameterCP1 { get; }
		public static string ParameterAffiliation { get; }
		public static string EventSelectItem { get; }
		public static string ParameterAdSource { get; }
		public static string ParameterAdPlatform { get; }
		public static string ParameterAdNetworkClickID { get; }
		public static string ParameterAdFormat { get; }
		public static string ParameterAchievementId { get; }
		public static string EventViewSearchResults { get; }
		public static string ParameterAdUnitName { get; }
		public static string EventViewItemList { get; }
		public static string EventViewItem { get; }
		public static string EventViewCart { get; }
		public static string EventUnlockAchievement { get; }
		public static string EventTutorialComplete { get; }
		public static string EventTutorialBegin { get; }
		public static string EventSpendVirtualCurrency { get; }
		public static string EventSignUp { get; }
		public static string EventShare { get; }
		public static string EventViewPromotion { get; }

		public static void ExportFix();
		public static Task<string> GetAnalyticsInstanceIdAsync();
		public static void InitiateOnDeviceConversionMeasurementWithEmailAddress(string emailAddress);
		public static void LogEvent(string name, params Parameter[] parameters);
		public static void LogEvent(string name);
		public static void LogEvent(string name, string parameterName, int parameterValue);
		public static void LogEvent(string name, string parameterName, long parameterValue);
		public static void LogEvent(string name, string parameterName, double parameterValue);
		public static void LogEvent(string name, string parameterName, string parameterValue);
		public static void ResetAnalyticsData();
		public static void SetAnalyticsCollectionEnabled(bool enabled);
		public static void SetSessionTimeoutDuration(TimeSpan timeSpan);
		public static void SetUserId(string userId);
		public static void SetUserProperty(string name, string property);
	}
}

_Originally posted by @andymads in https://github.com/firebase/quickstart-unity/issues/1293_

**Comment by morganchen12** [comment]
Please comment "I am not a bot, signed codybak4" to confirm you are not a bot and I will re-open this issue.

**Comment by codybak4** [comment]
"I am not a bot, signed codybak4"

**Comment by morganchen12** [comment]
Hi Cody, the bug you are reporting is for the Unity SDK and has already been fixed. If you're still having problems, please file a new issue on the Unity repo.
