### ISSUE TITLE
Insecure IPC: Missing Sender Verification

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1591]
**Summary**
The application fails to verify the sender of a URL-based Inter-Procedure Communication (IPC) call.

**Explanation**
When a third party application or webview uses a URL to communicate with your application, the receiving application should verify that the sender matches an allow list of applications that are expected to communicate with it. The receiving application has the option to verify the origin of the calling URL using the UIApplicationDelegate application:openURL:options: or UIApplicationDelegate application:openURL:sourceApplication:annotation: delegate methods. Best practices dictate that we should always verify the sender of an IPC call and check it against a list of expected origins as a security-in-depth control.
<img width="1308" alt="Screenshot 2024-05-28 at 2 55 17 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/f5e6790a-a430-481a-b221-2df47581e7f8">
<img width="618" alt="Screenshot 2024-05-28 at 2 50 15 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/fd13be39-c051-490e-b600-ec6d50b8717d">

**Comment by morganchen12** [comment]
This is a swizzled method. No URL is being handled in the implementation.
