### ISSUE TITLE
Insecure IPC: Missing URL Validation

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1592]
**Summary**
The application fails to validate the calling URL in a URL-based Inter-Procedure Communication (IPC) call.

**Explanation**
When a third party application or webview uses a URL to communicate with your application, the receiving application should validate the calling URL before proceeding with further actions. The receiving application has the option to verify that it wants to open the calling URL using the UIApplicationDelegate application:didFinishLaunchingWithOptions: or UIApplicationDelegate application:willFinishLaunchingWithOptions: delegate methods.
The following implementation of the UIApplicationDelegate application:didFinishLaunchingWithOptions: delegate method fails to validate the calling URL and always processes the untrusted URL:
  
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NS Dictionary *)launchOptions {
return YES;
}
Best practices dictate that we should always validate the calling URL and verify it conforms to what your application expects, which may vary depending on the URL components and purpose.

<img width="959" alt="Screenshot 2024-05-28 at 4 33 03 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/8106beed-2413-449f-96b2-9ac7e90aa0a2">
<img width="1308" alt="Screenshot 2024-05-28 at 2 55 17 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/aaa13d83-3544-463e-9fa1-751da4f142b7">
<img width="600" alt="Screenshot 2024-05-28 at 4 29 13 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/ed33c8e2-576a-439c-b390-ebd1e26b31d0">

**Comment by morganchen12** [comment]
This is a swizzled method. No URL is being handled in the implementation.
