### ISSUE TITLE
Insecure IPC: URL Scheme Hijacking

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1593]
**Summary**
The application uses custom URL schemes for Inter-Procedure Communication (IPC) which is subject to "URL Scheme Hijacking".

**Explanation**
Applications may register custom URL schemes for third party applications to communicate with them. Although this is a simple IPC channel, it may expose your application to "URL Scheme Hijacking". Since any application can register a URL scheme as long as it is not reserved by Apple, a malicious application may register the same scheme used by your application which results in an undefined behavior. According to Apple's documentation: "If more than one third party app registers to handle the same URL scheme, there is currently no process for determining which app will be given that scheme". If the malicious application is installed before your application, it may register the scheme and prevent your application from installing successfully. Alternatively, if the malicious application is installed after your application and it succeeds in the scheme registration, it may hijack it from your application.

**Path**
usr/local/share/agentWork/app/App_iOS-2/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/Public/GoogleUtilities/GULAppDelegateSwizzler.h : 26

<img width="932" alt="Screenshot 2024-05-28 at 5 32 16 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/c27fbde4-cbd2-485f-b085-614d9d004d75">
<img width="1308" alt="Screenshot 2024-05-28 at 2 55 17 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/dc6709dc-59c0-476b-8f2f-fc7b93a6344e">

**Comment by morganchen12** [comment]
There's no scheme being registered in the specified code.
