### ISSUE TITLE
Insecure Storage: HTTP Response Cache Leak

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1594]
**Summary -**
On line 47 of FIRCLSFABNetworkClient.m, the method initWithSessionConfiguration:queue:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.The identified method performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.
On line 117 of GDTCCTUploadOperation.m, the method uploaderSessionCreateIfNeeded() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.
On line 149 of GULNetworkURLSession.m, the method sessionIDFromAsyncPOSTRequest:completionHandler:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.
On line 157 of GULNetworkURLSession.m, the method sessionIDFromAsyncPOSTRequest:completionHandler:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.
On line 210 of GULNetworkURLSession.m, the method sessionIDFromAsyncGETRequest:completionHandler:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses
On line 58 of SettingsDownloadClient.swift, the method lambda { (Result&lt;[String : Any], SettingsDownloaderError&gt;) -&gt; Void }() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.

**Explanation -**
The HTTP(S) responses may contain sensitive data such as session cookies and API tokens. The URL loading system will cache all the HTTP(S) responses for performance reasons, storing them unencrypted in the {app ID}/Library/Caches/com.mycompany.myapp/Cache.db* files.

<img width="948" alt="Screenshot 2024-05-28 at 6 30 30 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/de6f93a4-07c1-4d2c-a53d-754a24143753">
<img width="958" alt="Screenshot 2024-05-28 at 6 32 05 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/e8dfc363-9a77-4119-884c-6705321d4463">
<img width="934" alt="Screenshot 2024-05-28 at 6 35 06 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/b033c429-7b83-4f23-ab52-f9247181b0fe">

**Comment by morganchen12** [comment]
These requests don't cache any sensitive data.
