### ISSUE TITLE
Type Mismatch: Signed to Unsigned

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1595]
usr/local/share/agentWork/app/App_iOS-2/Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDataParsing.c : 234

In FIRCLSDataParsing.c on line 234 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSDwarfUnwind.c on line 828 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSDwarfUnwind.c on line 846 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSDwarfUnwind.c on line 854 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSHost.m on line 104 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSUtility.m on line 54 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSUtility.m on line 62 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In GDTCCTNanopbHelpers.m on line 282 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In GULReachabilityChecker.m on line 184 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In GULReachabilityChecker.m on line 195 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.
In FIRCLSUtility.m on line 58 an unsigned variable is assigned a signed number.An unsigned variable is assigned a signed number.

It is dangerous to rely on implicit casts between signed and unsigned numbers because the result can take on an unexpected value and violate weak assumptions made elsewhere in the program.

<img width="942" alt="Screenshot 2024-05-28 at 7 30 47 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/63b85f45-5032-4bf0-8f0e-7c8f3330d8b9">
<img width="961" alt="Screenshot 2024-05-28 at 7 31 14 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/4a51d5a5-9b0f-450c-860f-5f50d87c3de4">
<img width="950" alt="Screenshot 2024-05-28 at 7 34 01 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/1a59b4f9-60f2-4bbe-99b2-44fffc6045d6">

**Comment by morganchen12** [comment]
Most of these don't seem to be valid issues. The unwind code is unfortunately undocumented but seems to be intentionally mixing intptr_t and uintptr_t.

If you're running into any specific issues that are the result of signed to unsigned conversion, please comment below and I'll re-open the issue.
