### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1596]
usr/local/share/agentWork/app/App_iOS-2/Pods/FirebaseCrashlytics/Crashlytics/Shared/FIRCLSNetworking/FIRCLSMultipartMimeStreamEncoder.m : 37

The function populateRequest:withDataFromEncoder:() in FIRCLSMultipartMimeStreamEncoder.m sometimes fails to release a system resource allocated by outputStreamToMemory() on line 37.The identified function sometimes fails to release a system resource.

The function lambda { (inout DataStreamRequest.StreamMutableState) -&gt; Void? }() in Request.swift sometimes fails to release a system resource allocated by open() on line 1377.The identified function sometimes fails to release a system resource.

The program can potentially fail to release a system resource.
In this case, there are program paths on which the resource allocated in FIRCLSMultipartMimeStreamEncoder.m on line 37 is not released.
Resource leaks have at least two common causes:
- Error conditions and other exceptional circumstances.
- Confusion over which part of the program is responsible for releasing the resource.

Most unreleased resource issues result in general software reliability problems. However, if an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of service attack by depleting the resource pool.

<img width="931" alt="Screenshot 2024-05-28 at 8 11 57 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/ebab9345-78a1-4004-a719-2decc7619bd6">
<img width="946" alt="Screenshot 2024-05-28 at 7 55 53 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/0b4ce38c-a536-49d3-97a6-2c0e8646efc0">

**Comment by morganchen12** [comment]
These are totally unrelated streams (one is in AlamoFire, which is not a Firebase dependency)
