### ISSUE TITLE
Unreleased Resource: Synchronization

### ISSUE THREAD

**Issue by Sneha0523** [firebase/quickstart-ios#1597]
usr/local/share/agentWork/app/App_iOS-2/Pods/FirebaseCrashlytics/Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c : 109

The function FIRCLSMachExceptionThreadStart() in FIRCLSMachException.c fails to release a lock it acquires on line 109, which might lead to deadlock.The program fails to release a lock it holds, which might lead to deadlock.

Explanation -
The program can potentially fail to release a system resource. In this case, there are program paths on which the resource allocated in FIRCLSMachException.c on line 109 is not always released. Resource leaks have at least two common causes: - Error conditions and other exceptional circumstances. - Confusion over which part of the program is responsible for releasing the resource. Most unreleased resource issues result in general software reliability problems. However, if an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of service by depleting the resource pool.

<img width="947" alt="Screenshot 2024-05-28 at 8 24 23 PM" src="https://github.com/firebase/quickstart-ios/assets/171027703/ff0c929b-4a90-4428-b6ec-ac2cba87d3c7">

**Comment by Tred3695** [comment]
if(ois,) Or the other person who knows

**Comment by morganchen12** [comment]
The `attr` pointer is deinitialized in all code paths in the method: https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/main:Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c;l=106?q=FIRCLSMachException.c

If you have an instruments trace demonstrating the leak of this pointer, please reopen the issue.
