### ISSUE TITLE
ios sample firebase development

### ISSUE THREAD

**Issue by krishtcse** [firebase/quickstart-ios#16]
Hi,
i am trying to develope sample fire base application,i have created pod file and add command like this ( pod ‘Firebase’  ) but i can not able to install pod it is holding there '' Setting up CocoaPods master repo " .what is the solution for it.

**Comment by fattomhk** [comment]
wait, sometimes it would take a long time
may be you could use "pod install --verbose" to see the log

**Comment by krishtcse** [comment]
hi, after long time pod installed .i have installed in pod like this ( Firebase,FirebaseCrash ) its workking without error,my code is

#import "AppDelegate.h"
@import Firebase;


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    [FIRApp configure];
    
    
    return YES;
}

#import "ViewController.h"

@import FirebaseCrash;

@interface ViewController ()

@property (weak, nonatomic) IBOutlet UIButton *btn_lbl;

- (IBAction)btn:(id)sender;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
  
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
 }





- (IBAction)btn:(id)sender
{
    
    
    NSArray *arr;
    
    NSMutableArray *arrr=[[NSMutableArray alloc]init];
    
    [arrr addObject:[arr objectAtIndex:0]];
    
    FIRCrashLog(@"Cause Crash button clicked");
    assert(NO);
   
   

    
    
    
    
    
    
}
its workking fine but  firebase console not showing my crash details.

**Comment by SharadExt** [comment]
When I write in didFinishLaunchingWithOptions [FIRApp configure] then it shows undelcare identifier . Why this happened? I import Firebase SDK also
