### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by mingsai** [firebase/quickstart-ios#160]
Can you add Carthage support to the Firebase repos?

**Comment by morganchen12** [comment]
Carthage currently doesn't support shipping closed-source binaries. See https://github.com/Carthage/Carthage/issues/1308

It may be something worth contributing, as there's been a decent amount of requests for Carthage support.

**Comment by terflogag** [comment]
Seem to be ok for the next release https://github.com/Carthage/Carthage/issues/1308

**Comment by morganchen12** [comment]
We could distribute Firebase through Carthage, but there are subtle issues that arise if anyone tries to use Firebase as a dependency of a dependency.

This is probably still worth discussing with the team despite those issues, as it's uncommon that people build libraries that depend on Firebase.

**Comment by evollu** [comment]
any updates on this?

**Comment by paulb777** [comment]
Now being tracked at https://github.com/firebase/firebase-ios-sdk/issues/9
