### ISSUE TITLE
Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "(null)"

### ISSUE THREAD

**Issue by jelerson** [firebase/quickstart-ios#161]
I've tried to took for a solution to this, and as far as i understand, error code 0 is a invalid parameter error, but i'm not sure what that means. Is there any way that i can debug this or does anyone have any insight as to why this is happening?

**Comment by ianbarber** [comment]
What is the topic string you are trying to subscribe to?

**Comment by ianbarber** [comment]
Tidying up, please reopen if still an issue!
