### ISSUE TITLE
Error in phoneAuthLogin(_:): An internal error has occurred, print and inspect the error details for more information.

### ISSUE THREAD

**Issue by NickCarducci** [firebase/quickstart-ios#1619]
I'm trying to run the Firebase Authentication example with `.swift` files in Xcode 15.4. I get the above error. How can I further diagnose the issue?

<img width="1440" alt="Screenshot 2024-09-09 at 9 25 47 AM" src="https://github.com/user-attachments/assets/095b36cb-0c6f-4771-bc88-f26b4791eb54">

_In [my own project](https://github.com/NickCarducci/Passport), I'm able to open the recaptcha, but the page hangs on about: blank page instead of sending the SMS code._

**Comment by ncooke3** [comment]
Phone auth is not working in dev. environments in Firebase 11. Firebase v11.2 is scheduled to go out on Tues. Sept 10, and should fix this issue.

> In [my own project](https://github.com/NickCarducci/Passport), I'm able to open the recaptcha, but the page hangs on about: blank page instead of sending the SMS code.

I've seen this behavior when swizzling is disabled and the scene delegate is not implemented to handle opening URLs. Take a look at the fix in: https://github.com/firebase/quickstart-ios/pull/1613

**Comment by NickCarducci** [comment]
Thanks Nick, however I encountered the same exact error with firebase-ios-sdk v11.2 (in the dev. simulator).

**Comment by NickCarducci** [comment]
@ncooke3, I managed to run the quickstart-ios authentication example on a _real_ device with the correct port (and firebase-ios-sdk v11.2) and received the same error for phone authentication.

![Occurred in phoneAuthLogin(_:)](https://github.com/user-attachments/assets/af5fc8da-a94e-44cc-8f3f-e4de2eb5013e)

**Comment by ncooke3** [comment]
Could you please drop a breakpoint [here](https://github.com/firebase/quickstart-ios/blob/fdae73e08badd0244f248aeebd851b52ed061be2/authentication/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PhoneAuthViewController.swift#L35C47-L35C59), run `p (error as NSError)`, and reply with the results?

**Comment by NickCarducci** [comment]
I used `p (error as! NSError)`
```
(NSError) 0x0000600000ceaa00 domain: "FIRAuthErrorDomain" - code: 17999 {
  _userInfo = 3 key/value pairs
}
```

**Comment by ncooke3** [comment]
Thanks, could you try `p (error as! NSError).userInfo`? I'm thinking the error details should be in that dictionary and hint as to what's going wrong.

**Comment by NickCarducci** [comment]
```
([String : Any]) 3 key/value pairs {
  [0] = {
    key = "NSLocalizedDescription"
    value = "An internal error has occurred, print and inspect the error details for more information."
  }
  [1] = {
    key = "FIRAuthErrorUserInfoNameKey"
    value = "ERROR_INTERNAL_ERROR"
  }
  [2] = {
    key = "NSUnderlyingError"
    value = 0x0000600000ce90e0 domain: "FIRAuthInternalErrorDomain" - code: 3 {
      _userInfo = 2 key/value pairs
    }
  }
}
```

**Comment by ncooke3** [comment]
Ah, the third one key's value is what we want.

You may have to tweak this, but something like `p ((error as! NSError).userInfo["NSUnderlyingError"]! as! NSError).userInfo` should do.

We need to look at the _userInfo value below:

> [2] = {
>     key = "NSUnderlyingError"
>     value = 0x0000600000ce90e0 domain: "FIRAuthInternalErrorDomain" - code: 3 {
>       _userInfo = 2 key/value pairs
>     }

**Comment by NickCarducci** [comment]
My apologies, it works.  I couldn't use the example's GoogleService-Info.plist nor Target>Info>URL Type. Thanks for the debugging tutoring!
```
([String : Any]) 2 key/value pairs {
  [0] = {
    key = "FIRAuthErrorUserInfoDeserializedResponseKey"
    value = 5 key/value pairs {
      [0] = {
        key = "errors"
        value = {
          _box = {
            _value = 1 value{...}
          }
        }
      }
      [1] = {
        key = "details"
        value = {
          _box = {
            _value = 1 value{...}
          }
        }
      }
      [2] = {
        key = "status"
        value = {
          _box = (_baseHashable = "INVALID_ARGUMENT")
        }
      }
      [3] = {
        key = "code"
        value = {
          _box = (_value = 400)
        }
      }
      [4] = {
        key = "message"
        value = {
          _box = (_baseHashable = "API key not valid. Please pass a valid API key.")
        }
      }
    }
  }
  [1] = {
    key = "NSUnderlyingError"
    value = 0x0000600000cc2160 domain: "com.google.HTTPStatus" - code: 400 {
      _userInfo = 0x00006000002d3d40
    }
  }
}
```
