### ISSUE TITLE
ARCHIVE FAILED

### ISSUE THREAD

**Issue by rammohanreddy1992** [firebase/quickstart-ios#1623]
We have integrated Firebase crashlytics and when run the below script locally getting the issue.
Script:
xcodebuild -workspace "UCF/UCF iOS.xcworkspace" -scheme "UCF iOS" -sdk iphoneos -configuration Debug "GCC_PREPROCESSOR_DEFINITIONS=\"DEBUG=1\" \"FS_DATA_PIPELINE_ENABLED=1\" \"UCF_PROVISIONING_STAGING=1\" \"FS_VPN_ENABLED=1\"" "SWIFT_ACTIVE_COMPILATION_CONDITIONS= SWIFT_PACKAGE DEBUG FS_DATA_PIPELINE_ENABLED UCF_PROVISIONING_STAGING FS_VPN_ENABLED" EXCLUDED_SOURCE_FILE_NAMES=SMSProtection.appex clean build -archivePath ./release/files_to_be_send/UCF-FSPROTECTION-iOS-24_10_304003-debug.xcarchive archive

Result:

** ARCHIVE FAILED **
18:32:49  
18:32:49  
18:32:49  The following build commands failed:
18:32:49  	CompileC /Users/mbbldr/Library/Developer/Xcode/DerivedData/UCF_iOS-ecfuhthahbceaadzplqiafuepqoc/Build/Intermediates.noindex/ArchiveIntermediates/UCF\ iOS/IntermediateBuildFilesPath/GoogleDataTransport.build/Debug-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/GDTCORMetrics+GDTCCTSupport.o /Users/mbbldr/Library/Developer/Xcode/DerivedData/UCF_iOS-ecfuhthahbceaadzplqiafuepqoc/SourcePackages/checkouts/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCORMetrics+GDTCCTSupport.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'GoogleDataTransport' from project 'GoogleDataTransport')

Note: We are not using Fastline

**Comment by morganchen12** [comment]
Do you have the full error message?

**Comment by rammohanreddy1992** [comment]
This error was caused by an issue in my code, which I have now resolved. Thank you for your comment.
