### ISSUE TITLE
Cannot convert value of type 'Data' to expected argument type 'Data'

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [firebase/quickstart-ios#166]
I'm converting my Swift 2.x code to Swift 3.x. I came across this error
Please help

![screen shot 2016-11-16 at 10 15 28 am](https://cloud.githubusercontent.com/assets/21377276/20335130/f85f3b2a-abe5-11e6-852c-868940aada89.png)

**Comment by morganchen12** [comment]
This question would be better suited for StackOverflow.

**Comment by YuriAR** [comment]
Have you solved the issue? I'm having exactly the same problem.

**Comment by vaibhav-varshaaweblabs** [comment]
@YuriAR Yes

**Comment by YuriAR** [comment]
How did you do it?

**Comment by vaibhav-varshaaweblabs** [comment]
Just use the correct pods

**Comment by YuriAR** [comment]
What do you mean? I've just did a fresh pod install with exactly the same pods as the project.

**Comment by vaibhav-varshaaweblabs** [comment]
Then, 'm sorry, I can't help any further
