### ISSUE TITLE
Unable to get Firebase frameworks from Pods

### ISSUE THREAD

**Issue by sumanksk2006** [firebase/quickstart-ios#167]
Hi ,

I am new to Firebase. I am trying to setup iOS client app with Firebase SDK (Messaging).
When I try to install Pod from Terminal, I get following error message

"Unable to find a specification for `FirebaseAnalytics (= 3.5.1)` depended upon by `Firebase/Core`".

Please suggest me.

Thanks.

**Comment by morganchen12** [comment]
Try running `pod repo update` and then `pod install`.
