### ISSUE TITLE
App Delegate Print Issue

### ISSUE THREAD

**Issue by GadgetAddict** [firebase/quickstart-ios#168]
I am getting errors in App Delegate when using this example,  because  of lines like this
    print("Unable to register for remote notifications " + error)

when it should be     print("Unable to register for remote notifications \( error)"

**Comment by morganchen12** [comment]
What errors are you getting and which example are they in?

Mind opening a pull request?

**Comment by GadgetAddict** [comment]
The errors are in the app delegate in multiple “Print” commands, all in the messaging example.

**Comment by morganchen12** [comment]
These should be fixed now, thanks!
