### ISSUE TITLE
Push Notification doesn't work on the TestFlight

### ISSUE THREAD

**Issue by zjlxgxz** [firebase/quickstart-ios#169]
I tried your sample code. The push notification works fine under the development environment but it doesn't work when I install the app from TestFlight or from AdHoc.

Here are what I've done:
1. Correctly download  and upload the Push notification Certification (Both Development and Production)
2. Send notification from Firebase console.(Phone gets notification in the development but don't when the app is install from TestFlight)
3. The provisioning file is managed by XCode, I can see the push notification is enabled.

I'm so frustrated that I've spent the whole week but not solved this problem.
Please save me! Thank you!

**Comment by ianbarber** [comment]
Do you have the swizzled version enabled? I am wondering if there is an issue with the environment chosen for APNs (sandbox vs production). Do you see anything in the device logs - does the connection to FCM go through OK?

**Comment by zjlxgxz** [comment]
Thanks for your reply! It works fine now.  Also I surprisingly found that the APNS service will use cellular network whenever possible. 

> On iOS, push notifications use the cellular data network whenever possible, even if the device is currently using Wi-Fi for other network activity such as web browsing or email. However, the push service will fall back to Wi-Fi if cellular data service isn't available.
If your iOS device is capable of using the cellular data network, check that it has an active cellular data plan. Turn off Wi-Fi in Settings and see if you can still browse the web with Safari, for example. On the other hand, if the push service is using Wi-Fi, any firewalls between your device or computer and the Internet must allow TCP traffic to and from port 5223.

More detail please see here: [https://developer.apple.com/library/prerelease/content/technotes/tn2265/_index.html](url) 
Maybe my cellular network causes the APNS failure. 

I guess the FCM uses both Wi-Fi and cellular network, that's why sometimes I can receive FCM message but can't receive the push notification when the app is on the background.

**Comment by ianbarber** [comment]
Thanks for the info! That's super interesting, I didn't know that about APNs either. @kroikie : one for you debugging checklist!

**Comment by marekpridal** [comment]
Hi, it seems I have same problem. I was debugging notifications in xcode with connected iPhone and everything worked fine. I was also able to get body from notification and etc. But then I have uploaded it to Testflight and it stopped working completely. It's not working even in xcode with connected iPhone. I have tried to revoke certificates and make new ones couple of times but it didn't help either. I am sending notifications to all devices so I am not working with tokens and I have set up FirebaseAppDelegateProxyEnabled to YES. Any chance to get this working?

**Comment by adadgio** [comment]
Could it be because of.... this!? 

https://stackoverflow.com/questions/24044298/why-push-notifications-is-not-working-on-testflight

**Comment by kroikie** [comment]
@marekpridal, @adadgio has a point could you confirm if you are using a production cert for your TestFlight app?

**Comment by marekpridal** [comment]
Yes I did. I solved the problem by uninstalling debug app and making clean install from TestFlight.

**Comment by kroikie** [comment]
Cool, glad you got it working.

**Comment by gbmahili** [comment]
I also solved the problem by uninstalling the debug app and installing it from TestFlight. Thanks all.

**Comment by weihangChen** [comment]
in my case it is because I did not set the sandbox boolean value to false when I am testing the app downloaded from TestFlight, so the generated token is no good

**Comment by morsagmon** [comment]
> 

Where is this "sandbox" boolean parameter is set? Where can I find it?
