### ISSUE TITLE
Error 501 on first launch, but disappears after

### ISSUE THREAD

**Issue by 1Reinier** [firebase/quickstart-ios#174]
Hi there,

Title says it all really. I'm getting `Unable to connect to Firebase with error: Error Domain=com.google.fcm Code=501 "(null)"` the first time my app launches, and it will immediately crash on trying to insert `nil` into some internal dictionary. The second time I launch everything will work as expected.

Any ideas?

Firebase 3.10
Xcode 8.1
iOS 10.1

**Comment by ianbarber** [comment]
Any chance you can get a minimal repro (e.g. a new project set up in the same way that demonstrates the behavior?)

**Comment by 1Reinier** [comment]
Found out the issue! On first launch, retrieving the `token` from `FIRInstance` took more time after running it directly after setting the APNS token, causing it to return `nil`. Miliseconds later the notification is triggered and the right Firebase token is still found by my notification handler. On subsequent launches of the app the Firebase token is immediately found after setting the APNS token. We can close this issue now.
