### ISSUE TITLE
how to link Facebook account with already existing email/password account?

### ISSUE THREAD

**Issue by sash83** [firebase/quickstart-ios#175]
My Facebook login process throws error that says 'email already in use' which is fine in case user signed up with email and password previously. Then I want to link this Facebook account with the already existing email/password account. How can I achieve this and retrieve the credentials of the existing email/password account?
I tried to get the already in use email from error code in order to link the Facebook account with it, because I need the email/password credentials.

Is this use case even possible? I have only email/password and Facebook sign up activated. It should be possible to link the Facebook account with the email/password account.

This is my new approach (not working as email exists while linking):

`if accessToken!.tokenString != nil {
                
                let credential = FIRFacebookAuthProvider.credential(withAccessToken: FBSDKAccessToken.current().tokenString)
                
                FIRAuth.auth()?.signInAnonymously(completion: { (user, error) in
                    
                    if error != nil {
                        print(error?.localizedDescription)
                    }
                    else {
                        user?.link(with: credential, completion: { (user, error) in
                            
                            if error != nil {
                                print(error.debugDescription)
                            }
                            else {
                                
                                FIRAuth.auth()?.signIn(with: credential, completion: { (user, error) in
                                    
                                    
                                    if error != nil {
                                        print(error.debugDescription)
                                    }
                                    else {
                                        self.finaliseSignUp(user: user!)
                                    }
                                })
                            }
                            
                            
                        })
                        
                    }
                })
                
            }`

**Comment by ianbarber** [comment]
Taking a quick look, it looks like you're doing an anon sign in, then linking with the Facebook account. To link with email password, you should sign in with the email/password account, and then link with the facebook credential on that user object, rather than the one from the anon sign in.

**Comment by sash83** [comment]
Yeah I know, but the user is not signed in at that moment, so I can't get the email/password credentials in order to link it with Facebook account.

Use case:
1. User signs up via email/password
2. User logs out
3. Next time user opens the app, he/she decides to log in via Facebook. (not logged in at that time)
4. Log in via Faceook fails because email is already taken.
5. Instead of failing, the app should recognise that the user already has an account and then merge both accounts.

Problem: User is not signed in, so the previous email/password credentials are not available at this time in order to carry out linking.

I'm thinking of saving the email/password credentials in Userdefaults at first sign up. Then retrieve it to link with Facebook account ifFaceook log in fails.

**Comment by ianbarber** [comment]
Yeah, that set up is intentional. You have to get them to confirm their password. That's a really important step, else you're opening up your service to hijacking. 

Storing it in userdefaults would work, but why not prompt them? Its a one time operation for people who choose a different sign in method, and it guarantees its the same human on the other end of the transaction.

**Comment by aissa-bouguern** [comment]
@iulukaya Please bro, I'm facing now the same issue, how did you solve it ?
