### ISSUE TITLE
FIRMessaging remoteMessageDelegate does not exist

### ISSUE THREAD

**Issue by andjosh** [firebase/quickstart-ios#177]
Ref: https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExampleSwift/AppDelegate.swift#L43

In the current pod/build, this delegate is not available to be set.

**Comment by morganchen12** [comment]
What version of Firebase do you have installed?

**Comment by andjosh** [comment]
I am ashamed! I was on `3.5.x`
