### ISSUE TITLE
pod

### ISSUE THREAD

**Issue by KONGFANJI** [firebase/quickstart-ios#179]
<img width="565" alt="default" src="https://cloud.githubusercontent.com/assets/15827720/21047135/24c9b0cc-be43-11e6-837e-f33292237609.png">

**Comment by iulukaya** [comment]
I believe you had a connection problem, seems to be working for me now.

**Comment by KONGFANJI** [comment]
<img width="569" alt="default" src="https://cloud.githubusercontent.com/assets/15827720/21209178/d8f15f8c-c2ad-11e6-99c3-7fc8acf6ecc3.png">

I am not clear about this,can you tell me what is the wrong ?

**Comment by morganchen12** [comment]
@KONGFANJI, try to visit that URL directly. If you can't access it, your internet provider may be blocking access to Google's CDN.
