### ISSUE TITLE
You don’t have permission.(DatabaseExample)

### ISSUE THREAD

**Issue by sabhay1996** [firebase/quickstart-ios#18]
The file “DatabaseExample” couldn’t be opened because you don’t have permission to view it.
I'm unable to run on simulator as well as device .

**Comment by Arlen2014** [comment]
Pod installation complete! There are 3 dependencies from the Podfile and 16 total pods installed.

**[!] Unable to read the license file `/Users/arlenpereira/Downloads/SWIFT/***quickstart-ios-master_FIREBASE/database/Pods/FirebaseUI/LICENSE` for the spec `FirebaseUI (0.4.0)`**

**Comment by sabhay1996** [comment]
Why are you guys closing if you haven't provided any solution not good :/
