### ISSUE TITLE
Incorrect FIRMessagingAutoSetupEnabled in documentation

### ISSUE THREAD

**Issue by revolter** [firebase/quickstart-ios#180]
[This documentation page][1] references a `FIRMessagingAutoSetupEnabled` flag that you need to put in the `Info.plist` file, but I can't find any reference to it in other places. Didn't you mean `FirebaseAppDelegateProxyEnabled` instead?

  [1]: https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessaging#/c:objc(cs)FIRMessaging(im)appDidReceiveMessage:

**Comment by kroikie** [comment]
You are correct, thanks for flagging this. I have submitted a fix internally and will be published soon.
