### ISSUE TITLE
Incorrect iOS 10 documentation warning

### ISSUE THREAD

**Issue by revolter** [firebase/quickstart-ios#181]
[This documentation page][1] says that

> for devices running iOS 10 and above, you must assign your delegate object to the UNUserNotificationCenter object to receive display notifications

but it should be

> for devices running iOS 10 and above, you must assign your delegate object to the UNUserNotificationCenter object to receive display notifications when the app is in foreground

instead!

  [1]: https://firebase.google.com/docs/notifications/ios/console-device#register_for_remote_notifications

**Comment by kroikie** [comment]
Agreed, thanks for calling this out, a fix in in and will be published shortly.
