### ISSUE TITLE
Notifications sample show bad practice

### ISSUE THREAD

**Issue by revolter** [firebase/quickstart-ios#184]
I can't understand why is the Internet __FULL__ of bad practice examples about notifications registration. Moreso, why is even Firebase promoting this?

As you can see in [the sample's `AppDelegate.m`][1] and in [this documentation page][2], the registration is done at the app start. Is anyone working on real world applications? You don't request notifications permission at app start as no one will ever accept them, ever!

The documentation briefly states that you "can" request it at a desired point but the sample doesn't have at least any warning. Because of this, the `[[FIRMessaging messaging] setRemoteMessageDelegate:self];` usage is unclear. Does it really have to be called when registering for notifications? I guess not.

But let's say I have an existing app (99% cases) and I want to use Firebase. I already am registering for notifications at, say, level up. I come across this example that looks like I need to set the delegate in my custom method that registers for notifications, but, in fact, I just have to set it after configuring the app.

Also, the sample uses `#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0` instead of `if ([UNUserNotificationCenter class])`.

  [1]: https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExample/AppDelegate.m#L47
  [2]: https://firebase.google.com/docs/notifications/ios/console-device#register_for_remote_notifications

**Comment by ianbarber** [comment]
That's a fair point. To be honest, for a sample I'm not sure where else we'd put the registration in an example, but we should definitely include a comment on that line in the sample that notes that it will trigger a permission request, and to move it to a logical point in your app flow.
