### ISSUE TITLE
Firebase token showing invalid

### ISSUE THREAD

**Issue by shashank109** [firebase/quickstart-ios#191]
I get the FCM token using the following method

refreshedToken = [[FIRInstanceID instanceID] token];

I forward this token to the backend, but when the backend sends notifications or create a new topic, the error comes up telling the instance id is invalid or the token is not registered.

It works completely fine for some tokens and for some tokens only it throws a error.

Any help is appreciated. Thanks.

**Comment by kroikie** [comment]
When are you retrieving the token? You should be retrieving it via an [observer that is called every time a token is generated](https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExample/AppDelegate.m#L172). In some cases multiple tokens are generated and only the last one would be valid.

**Comment by shashank109** [comment]
At didFinishLaunchingWithOptions method I am calling this method:

  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:) name:kFIRInstanceIDTokenRefreshNotification object:nil];

and in this method I am creating instance of Token:

- (void)tokenRefreshNotification:(NSNotification *)notification {
    if(refreshedToken != nil){
        refreshedToken = [[FIRInstanceID instanceID] token];
    }
    [self connectToFcm];
}

**Comment by revolter** [comment]
@kroikie, Are you aware that the `kFIRInstanceIDTokenRefreshNotification` notification is sent multiple times even if the token doesn't actually change? Couldn't it detect if it's the same and not send it?

**Comment by kroikie** [comment]
@shashank109 note that uninstalling the app will invalidate the token. So if say you install and uninstall 5 instances of the app, then install a 6th instance only the final instance ID token will be valid. If your server is trying to send to all 6 then 5 of them will come back as invalid.

@revolter The token refresh callback should only be called if the IID token has been updated. An IID token will be initially generated and another one is generated after setting the APNs token. So it is not unusual to initially have a couple of calls to the token refresh callback. However after that you should only get the callback when the token actually changes.

**Comment by revolter** [comment]
I understand that it's ok to be called multiple times, but is it ok to be called multiple times with the exact same token?

```
2016-12-16 10:40:55: configure
2016-12-16 10:40:57: token: dqdl9lVe_-o:APA91bH2hN68yMtbRi3fQev9UnOD5Vz7qU9RdcTpWqSVmKJPcZLyNa_4Oyzh23zpa-XBtEp8ANXOhI0W3zLEDqdzR7VVamWSIoiCXONnC0NnkWWshv_rEx5tvo2P2JW63wiz7kmf9iHY
2016-12-16 10:41:16: deviceToken: <ab9e7a7e 8349c147 529ebab0 6fe477ca 81a8aa42 e90ff31c 6c0be6d7 d7e2dda7>, ab9e7a7e8349c147529ebab06fe477ca81a8aa42e90ff31c6c0be6d7d7e2dda7
2016-12-16 10:41:17: token: dqdl9lVe_-o:APA91bH2hN68yMtbRi3fQev9UnOD5Vz7qU9RdcTpWqSVmKJPcZLyNa_4Oyzh23zpa-XBtEp8ANXOhI0W3zLEDqdzR7VVamWSIoiCXONnC0NnkWWshv_rEx5tvo2P2JW63wiz7kmf9iHY
```

**Comment by kroikie** [comment]
@revolter is that with swizzling on or off? Also are you seeing this on every "first run"?

**Comment by revolter** [comment]
Swizzling off, and, yes, on every fresh install.

**Comment by shashank109** [comment]
When I run the app first time, I get the token and everything is working fine. But when I again run the application,  this method 

(void)tokenRefreshNotification:(NSNotification *)notification {
refreshedToken = [[FIRInstanceID instanceID] token];
[self connectToFcm];
}

won't call and I didn't get the token. So I won't be able to send the token to backend and session will not create to that user and notification will not fire. Same thing happening when user logout and login again in the app. So should I save the token locally or is there any other ways to do so?

**Comment by revolter** [comment]
@shashank109, Yes, you need to persist it yourself, it's not like the Apple's `registerForRemoteNotifications` which calls it's delegate every time. I already said that that notification should be sent when the token changes.

**Comment by bch007** [comment]
@shashank109 same issue the tokenRefreshNotification callback is called only when the app is installed at first time, but after that, if your token become invalid, nothing append in app, how to force to update the token ?

**Comment by shashank109** [comment]
In didFinishLaunchingWithOptions method you define like this-

    // Firebase Configure for notification
    [FIRApp configure];
     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:) name:kFIRInstanceIDTokenRefreshNotification object:nil];

this will automatically update your token when it become invalid. later you can define these methods-


- (void)tokenRefreshNotification:(NSNotification *)notification {
        refreshedToken = [[FIRInstanceID instanceID] token];
        NSLog(@"InstanceID token: %@", refreshedToken);
        [self connectToFcm];
}

- (void)connectToFcm {
     [[FIRMessaging messaging] connectWithCompletion:^(NSError * _Nullable error) {
        if (error != nil) {
            NSLog(@"Unable to connect to FCM. %@", error);
        } else {
            
            NSLog(@"InstanceID_connectToFcm = %@", refreshedToken);
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
                
                dispatch_async(dispatch_get_main_queue(), ^{
                    NSLog(@"instanceId_tokenRefreshNotification22=>%@",[[FIRInstanceID instanceID] token]);
                    
                });
            });
        }
    }];
}

and didRegisterForRemoteNotificationsWithDeviceToken define this-

    [[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeProd];
    
**  FIRInstanceIDAPNSTokenTypeProd is for production. you can change it for the development mode.

**Comment by bch007** [comment]
@shashank109 yes but the notification refresh callback still not called, so the token still NotRegisered

**Comment by shashank109** [comment]
It will call automatically through observer when token becomes invalid.

**Comment by bch007** [comment]
i already registered the observer ` [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:) name:kFIRInstanceIDTokenRefreshNotification object:nil];
` and the token is still notRegistered in application

**Comment by shashank109** [comment]
I think you need to persist the token locally or maintain in the cache.

**Comment by morganchen12** [comment]
Hey all, 

If you're still having token issues on the newest version of Firebase, please file an issue at [firebase/firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk/issues) and we'll try to help you.
