### ISSUE TITLE
Nil senderId warning

### ISSUE THREAD

**Issue by revolter** [firebase/quickstart-ios#192]
I keep receiving this warning:

> <FIRInstanceID/WARNING> Firebase messaging not setup correctly, nil senderID.

on every app start. What is it caused by?

In my `application:didFinishLaunchingWithOptions:` method, the only call that's related to Firebase is `[FIRApp configure]`.

**Comment by kroikie** [comment]
I assume that your GoogleServices-Info.plist file contains a valid GCM_SENDER_ID value. Getting it on every app start is strange. I'm not able to reproduce this, could you be more specific about what Firebase features you are using?

**Comment by revolter** [comment]
Yes, the sender id is present and is valid. I'm using the Messaging part.

**Comment by kroikie** [comment]
That warning would be logged if an attempt to retrieve the IID token is made before the Sender ID of the InstanceID was set. You should check to make sure that you are not calling [InstanceID token] somewhere very early. If that is not the case I will file an internal bug to dig deeper into this warning log.

If you are only using Messaging and you are getting your IID token, then you can ignore this warning and we will clean it up in a future release.

Since I'm unable to reproduce it, could you give me some specifics about the deivice and iOS version you are seeing this issue with and have you tried multiple devices?

**Comment by revolter** [comment]
And when is the Sender ID set? In the `[FIRApp configure]` call? If yes, I'm only accessing the `token` after that call. More specifically, in the `kFIRInstanceIDTokenRefreshNotification` notification handler and in the `applicationDidBecomeActive:`.

I tested it on `iPad Mini 2 Retina` with `iOS 9.1` and on a couple of `iPhone 5s`, `iPhone 6` and `iPhone 6s` with `iOS 10.1` and again on an `iPhone 6s` with `iOS 10.2`.

**Comment by kroikie** [comment]
Removing or delaying the call to [FIRApp configure] I'm able to get that log msg.

Could you add appropriate logging to confirm whether the error is occurring in the token refresh callback or in applicationDidBecomeActive?

**Comment by ToddKerpelman** [comment]
@revolter Seems like something is weird with your GoogleService-info file. Can you try re-downloading it? Head to the Firebase console, click the gear in the upper-left and select project settings, make sure your app is selected, and then click the download button labeled GoogleService-info.plist. Delete your old GoogleService file from your xcode project, then drag in the new one. See if that helps at all...

**Comment by revolter** [comment]
Firstly, how can it get corrupted? It actually downloaded it automatically for me when I went through the starting guide IIRC.
Secondly, something's fishy, I have 3 apps in Firebase, each with different `Client ID`, but after downloading the plist files again, indeed the new ones are different, but now the `Client ID` is the same between these 3 apps, and previously it was unique. Did the id generation suddenly change?

**Comment by revolter** [comment]
I downloaded the files again and this time, nothing is changed in git. So the original issue is not related to the plist files.

**Comment by revolter** [comment]
@kroikie, No, they're not the problem:

```
2016-12-19 15:45:54.387: <FIRInstanceID/WARNING> Firebase messaging not setup correctly, nil senderID.
...
2016-12-19 15:45:54.861419 Mondly Korean[3160:1017315] FIREBASE: Debug: AppDelegate.m:528 applicationDidBecomeActive: enter
2016-12-19 15:45:54.902620 Mondly Korean[3160:1017315] FIREBASE: Debug: AppDelegate.m:555 applicationDidBecomeActive: connect
2016-12-19 15:45:54.902665 Mondly Korean[3160:1017315] FIREBASE: Debug: AppDelegate.m:696 connectToFirebase enter
2016-12-19 15:45:54.907479 Mondly Korean[3160:1017315] FIREBASE: Debug: AppDelegate.m:764 connectToFirebase exit
2016-12-19 15:45:54.907528 Mondly Korean[3160:1017315] FIREBASE: Debug: AppDelegate.m:559 applicationDidBecomeActive: exit
```

As you can see, the `applicationDidBecomeActive:` is called ~475 milliseconds after the warning is printed.

**Comment by kroikie** [comment]
Hi @revolter could you check when you are getting the token, I'm thinking that you may be requesting the token before configure.

**Comment by revolter** [comment]
That's what I did for my last comment.

**Comment by morganchen12** [comment]
This issue has staled pretty significantly. The `Firebase messaging not setup correctly, nil senderID` warning has since been entirely removed from the code in InstanceID.

Sorry we were unable to resolve your issue on time.
