### ISSUE TITLE
module 'FirebaseUI' not found 

### ISSUE THREAD

**Issue by sabhay1996** [firebase/quickstart-ios#2]
FirebaseUI module not found in DatabaseExample Objective-C .

**Comment by alfiehanssen** [comment]
+1 

Same for the Swift example, it won't build. I'm using Xcode 7.3.

**Comment by sabhay1996** [comment]
Yeah there's might be an issue with their dependencies :/

**Comment by iulukaya** [comment]
Please use import FirebaseDatabaseUI instead.
We'll push the FirebaseUI header soon.
