### ISSUE TITLE
Not receiving push notifications with adHoc build

### ISSUE THREAD

**Issue by NirmitDagly** [firebase/quickstart-ios#201]
Hello,
I am integrating push notifications using FCM in my iOS app. 

In app, I am getting notifications for the development profile properly. I have set the APNs Environment to sandbox in this case and it is working fine.

Now, when I am making an AdHoc build and install it on my device, the notifications are not getting delivered. I have set APNs mode to Production in this case and also uploaded certificate properly in firebase console. 

When I am sending notifications from Console, it displayed the status as completed but no notification is received on device for any of the Foreground and Background mode. 

I am unable to print logs as It is an AdHoc build.

Any help will be appreciated.

Thanks,
Nirmit

**Comment by kroikie** [comment]
Hi @NirmitDagly have you disabled swizzling? If so could you check that when setting the APNs token you are with `setAPNSToken` that you are setting the type to production.

**Comment by shinzao** [comment]
Hi, I have exactly le same problem,

Into my .plist, I have : 
![capture d ecran 2017-01-06 a 09 41 22](https://cloud.githubusercontent.com/assets/12793476/21712303/480b61a4-d3f4-11e6-9202-3ee171c198c9.png)

And into my Delegate, I've tried many things like : 
`FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: FIRInstanceIDAPNSTokenType.sandbox)
`

or
`FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: FIRInstanceIDAPNSTokenType.prod)
`

or with .unknown also. Everything work in development but not in prod (or ad Hoc).

This is a screenshot of my code : 
![capture d ecran 2017-01-06 a 09 58 32](https://cloud.githubusercontent.com/assets/12793476/21712747/b1533676-d3f6-11e6-818f-59ab86619cbd.png)


Do you have an idea ?

Thanks in advance,
Antoine

**Comment by kroikie** [comment]
Also could you try regenerating your certificates, that has worked for some other devs. See #207

**Comment by ianbarber** [comment]
Closing old issue, feel free to reopen if you have updates, or raise a new issue for anyone seeing the same thing.

**Comment by haugeto420** [comment]
Thanks
