### ISSUE TITLE
Can't create a new user in "DatabaseExampleSwift"

### ISSUE THREAD

**Issue by yura-voevodin** [firebase/quickstart-ios#202]
When launching the "DatabaseExampleSwift" and trying to create a new user I got this error message: "An invalid API key was supplied in the request."
![simulator screen shot 22 2016 1 46 24](https://cloud.githubusercontent.com/assets/2790873/21424732/4de64498-c84d-11e6-80aa-0f903f5b8dbc.png)

**Comment by ianbarber** [comment]
Try downloading your GoogleService-Info.plist again, and see if it looks different. If it does, could you file a bug with us on https://firebase.google.com/support/contact/bugs-features/ and include both plists? There may be an issue with the config file creation in some cases.

**Comment by iulukaya** [comment]
Hi @yura-voevodin, were you able to fix your issue?

**Comment by yura-voevodin** [comment]
Thanks for response! Everything is good for now. I downloaded correct GoogleService-Info.plist from Firebase console.
