### ISSUE TITLE
Failed to fetch default token when configuring an additional firebase app 

### ISSUE THREAD

**Issue by philippefuentes** [firebase/quickstart-ios#206]
Could not initialise FCM cause of this error:
**Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"**
when using another firebase database in my project.

The workaround I found was to configure the additional app **before** the default app in AppDelegate.m

```
//initialise the secondary app, for example:
NSString *logFirebaseOptionFile = [[NSBundle mainBundle] pathForResource:@"GoogleService-LOG-Info" ofType:@"plist"];
FIROptions *firebaseOptions = [[FIROptions alloc] initWithContentsOfFile:logFirebaseOptionFile];
NSString *logAppName = @"mybands_logs";
[FIRApp configureWithName:logAppName options:firebaseOptions];

//then the default app for FCM to work
[FIRApp configure];

```

**Comment by kroikie** [comment]
Hi @philippefuentes, if the SDK attempts and fails to fetch the token then it should automatically retry. If you are trying to get tokens for a secondary project then you should use the version of the `[tokenWithAuthorizedEntity](https://firebase.google.com/docs/reference/ios/firebaseinstanceid/api/reference/Classes/FIRInstanceID#-tokenwithauthorizedentityscopeoptionshandler)` the Sender ID of the secondary project.

**Comment by ianbarber** [comment]
Closing older issue, feel free to reopen if further questions.
