### ISSUE TITLE
Not receiving push notifications in prod (or ad hoc build)

### ISSUE THREAD

**Issue by shinzao** [firebase/quickstart-ios#207]
Hi, I have exactly le same problem that the issue #201 ,

Into my .plist, I have : 
![capture d ecran 2017-01-06 a 09 41 22](https://cloud.githubusercontent.com/assets/12793476/21712303/480b61a4-d3f4-11e6-9202-3ee171c198c9.png)

And into my Delegate, I've tried many things like : 
`FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: FIRInstanceIDAPNSTokenType.sandbox)
`

or
`FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: FIRInstanceIDAPNSTokenType.prod)
`

or with .unknown also. Everything work in development but not in prod (or ad Hoc).

This is a screenshot of my code : 
![capture d ecran 2017-01-06 a 09 58 32](https://cloud.githubusercontent.com/assets/12793476/21712747/b1533676-d3f6-11e6-818f-59ab86619cbd.png)

Do you have an idea ?

Thanks in advance,
Antoine

**Comment by shinzao** [comment]
Hi guys,

Still have this problem, any idea ?

Thanks in advance

**Comment by snok3r** [comment]
Same here. Moreover, I don't get any notifications in ad hoc build (neither background or foreground).
I've tried to set _FirebaseAppDelegateProxyEnabled_ flag to YES and even remove it, it didn't help.

**Comment by smQ93** [comment]
Hello everyone,

I have the same problem... While developing an app everything works perfect (with the Firebase Console). After deploying an app to the TestFlight, push notifications stop working... Has anyone managed to resolve it?

**Comment by shinzao** [comment]
Hey guys, I just find a way to solve it.

I revoked all certification (on my apple developper account and firebase), recreated and reuploaded. Now, everything works.

**Comment by snok3r** [comment]
@shinzao Hi! Could you please be more specific, did you revoke all certificates or just for push notifications? And how do you revoke certificates on firebase?
Also, it would be very helpful if you wrote the steps you've taken. 

Thanks in advance!

Update:
I assume you sticked with _FirebaseAppDelegateProxyEnabled_ flag set to **NO**? Did you write something else except from _setAPNSToken_?

**Comment by revolter** [comment]
@snok3r, About the `Code Signing Identity` setting, [this][1] is the recommended way.

  [1]: https://developer.apple.com/library/content/qa/qa1814/_index.html#//apple_ref/doc/uid/DTS40014030-CH1-FIGURE1

**Comment by snok3r** [comment]
@revolter thanks! 

@shinzao About provisioning profiles, did you create them on your own like [Firebase tutorial](https://firebase.google.com/docs/cloud-messaging/ios/certs) says or let XCode to do it?

**Comment by snok3r** [comment]
It finally worked! 
I think right `Project` and `Target` settings and recreation of [this certificates](https://developer.apple.com/account/ios/certificate/distribution) helped!

**Comment by revolter** [comment]
@snok3r, Glad it worked, you're welcome.

**Comment by hyd00** [comment]
@shinzao  @revolter @snok3r Guys i am facing same issue. Push not working on Production or AdHoc. 

Can you please let me know we have to revoke the CERTIFICATES only or everything? profiles too? please help.. THANKS

**Comment by xhidnoda** [comment]
@snok3r
so...
This is correct?
![captura de pantalla 2017-01-16 a las 11 27 21 p m](https://cloud.githubusercontent.com/assets/862733/22005621/9a7a6604-dc43-11e6-802d-03e384ac02a0.png)

![captura de pantalla 2017-01-16 a las 11 28 03 p m](https://cloud.githubusercontent.com/assets/862733/22005626/a23a55ca-dc43-11e6-8316-574830369af4.png)

--and not revoke my Apple Push Services Certificate? from my "developer account"

**Comment by snok3r** [comment]
@xhidnoda hi! Yes, I have the same `Target` settings and `info.plist` keys. 
I've revoked the two distribution certificates:` iOS Distribution` and `Apple Push Services`. 
And don't forget to reupload your newly generated `.p12` to Firebase.

**Comment by xhidnoda** [comment]
THANKS @snok3r 

Apparently the only solution is:
1. Revoke the certificate and create new ones
2. Don't forget tu upload in firebase the new .p12 again

Will confirm this...later

**Comment by xhidnoda** [comment]
Finally work for me...
 
Here my steps:

1 - Make sure to Enable FirebaseAppDelegateProxyEnabled to YES in the info.plist
2- Revoke your certificate (APNS develop and distribution) and create a news ones
3 - NOTE: there is an error in the Firebase documentation. When you exporting the APN certificate for production from your keychain to the .p12 file you have to select the actual certificate, not the private key.
4 - Make sure you upload to the Firebase console this .p12 file in the Cloud Messaging APN certificate settings.
5- Send remote notification with Firebase Console.

Thanks to all..!

**Comment by fanals** [comment]
@xhidnoda I tried your solution starting from the beginning and it finally worked ! Not sure but the only thing I remember doing different was exporting the APN certificate by selecting both certificate and private key. This time I exported only the certificate without the private key.

**Comment by canny09** [comment]
@snok3r @revolter Hi guys! Did you have a problem about that: 
When calling ``FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: FIRInstanceIDAPNSTokenType.prod)`` in Appdelegate method, the ``tokenRefreshNotification``callBack be invoked infinitely.... By the way, the scheme I set ``release``
But in ``debug`` scheme and ``FIRInstanceIDAPNSTokenType.sandBox``, everything work fine..

**Comment by rahulgarg12** [comment]
@canny09 I am facing the same problem. Did you get any solution?

**Comment by rahulgarg12** [comment]
@canny09 Yes everything works fine when i enable Method Swizzling. But when I disable it and set token programmatically, on prod instance id is nil everytime and `tokenRefreshNotification` gets called infinitely. I want to know why this is happening.

**Comment by canny09** [comment]
@rahulgarg12 YES! The situation same as yours. En.. I also want to know the reason.

**Comment by TheBachelor** [comment]
Same here for iOS. I have the same notification sent to both Android & iOS. Android always receives them and iOS does for a while (maybe a week or 2) then suddenly stops until I go to firebase and manually send to the device. This also doesn't work at first, then it starts to work when I send my second notification.

**Comment by jrbecart** [comment]
Is is better to use the new .p8 file instead of the .p12 in firebase? Looks like easier to me.
Anyway, I'm trying to solve the same problem and I will try @xhidnoda steps.

**Comment by rsattar** [comment]
@jrbecart Yeah, the new .p8 file is Apple's new authentication system and it works much better than the previous .p12 certificates, because:
1) They don't expire every year.
2) You can use the same .p8 file to send to _all_ app in that Apple Developer account.
3) You don't need to do a hard-to-follow export process via Keychain Access. You just upload the .p8 file as Apple gave you.

Be sure you're using the new FCM iOS SDK (version 2.x, as part of Firebase 4.x rolled out in May 2017)

**Comment by jrbecart** [comment]
I think, I have the same kind of problem when app is in prod. 
I get the notification, but in a different way (other method called) and it's hard for me to debug in that way... :(
I open a new issuefor this: #296 .

**Comment by roberto-rodriguez** [comment]
Similar issue happen to me, I added Push Notifications to an existent app, tested by running using Xcode to my device and it worked well, but when when created the Archive and installed via iTunes, it didn't receive Push Notifications.
 The problem was that when I added the permissions for push notifications, my Provisioning Profile got obsolete (Invalid), so I had to generate a new Provisioning Profile, apply to my iTunes/phone, and now when I install the app it works well.

**Comment by suvarapuprasad** [comment]
xhidnoda -- your solution worked for me thanks

**Comment by vicky462** [comment]
I have faced similar issue after Enable FirebaseAppDelegateProxyEnabled to YES in the info.plist.it is working fine ios 12 but still in ios 10.3.3 push notification not working.Any one face these kinda problem ??

**Comment by norter** [comment]
Apart from what they say about rebuilding the push certificates and the possible regeneration of the provisioning profile and the upload of new p12 to Firebase. We find an error that is to kill the Apple developers. The problem took us several hours to find ... it is with the file "name_your_project.entitlements". When you see it, it is displayed correctly, the ticks appear that everything is ok, but when you export for Ad Hoc, it does not include "production" in "aps-environment", in the last step before generating the .ipa, with that push notifications do not arrive ... To solve this, it is necessary to delete the file "file name_your_project.entitlements", deactivate push notifications in Capabilities, and activate them again. This will regenerate the file "file name_your_project.entitlements", and with this, it will already generate in the last step of the Ad Hoc .ipa generation, with the aps-environment in production ...

Summarizing.-
- All the above mentioned (generation of p12, upload to firebase, etc.)
- Delete file "name_your_project.entitlements"
- Deactivate and activate push notifications in Capabilities
- Re-export for Ad Hoc and check that "aps-environment" comes as "production"

**Comment by Nephsus** [comment]
The error commented by Norter is caused because the reference to the entitlments file is lost. If you go to inactive capabilites and re-activate the push option, you will recreate it. When generating the ipa it is necessary to see that the APS Environment property comes out to production.

I'm Norter's partner: D

**Comment by hamza-gaya** [comment]
This issue is not closed at all as flutter plugins faced that or you guys would have fixed on your iphone device what about others iphone devices ??? have you all guys tested that. fluter is generating duplicate and also invalid firebase messaging token after 1 day gap they actually started sending those notifications but this is not a proper solution

**Comment by imtoori** [comment]
I'm experiencing something similar 
https://stackoverflow.com/questions/74981072/flutter-fcm-not-working-on-ios-with-release-profile
I hope someone can help me 'cause I'm really struggling here
