### ISSUE TITLE
Firebase authentication questions

### ISSUE THREAD

**Issue by revolter** [firebase/quickstart-ios#211]
1. How is the `FIRUser` cached, even between app reinstalls?

After a full app reinstall, the `FIRAuth.auth()?.currentUser` still contains a valid user.

2. How can I get the access token from a logged in user's `providerData`?

After reinstalling the app, even if the `currentUser` is not null, `FBSDKAccessToken.current()?.tokenString` is, and I need access to it.

**Comment by iulukaya** [comment]
1. The current logged in FIRUser is saved in the device's keychain, which can survive app reinstallation. Call signOut to "forget about" the current logged in FIRUser.
2. Firebase Auth does not save or maintain Facebook's (or any other IDP's) access token. It is up to the client app to save it if needed.
