### ISSUE TITLE
Using new firebaseUI on database examples and breaking changes

### ISSUE THREAD

**Issue by Rovel** [firebase/quickstart-ios#213]
I was using firebaseUI for table and collection views, but since there was a lot of breaking changes it would be nice to have the database example either with the latest firebaseUI release updates as the UI repo is or with none of it.

These breaking changes are happening really fast, so is there any advice on a better approach on updates in Firebase and FirebaseUI?

Thanks

**Comment by morganchen12** [comment]
The breaking changes were relatively small, and FirebaseUI should continue to work without requiring code changes for most use cases, especially simpler ones. The FirebaseUI repos have their own samples which you should use as reference instead of this quickstart repo (which is more intended for general Firebase). 

Do you have a breakage in particular that you're concerned with?

**Comment by Rovel** [comment]
Actually since xcode transition from 7 to 8 (swift 2 to 3) added by
firebaseUI upgrades to bitcode 0.5 and on I had quite a struggle to fix pod
updates, upgrade and functions to swift 3 and finally debugging archiving
errors.

I've been following most of the changes since google's acquisition and I
thanks all the team for the big contribution to the lib from bug fixes to
new cool stuff. Great job!

But sometimes is hard to keep up and make all thing work considering all
life demands, so it would be great to have a full functional tableview
implementation like the database example using the latest
FirebaseDatabaseUI, you know getting references from Datasource using get
query, and limiting results... you know in the sample the table is from a
fixed enum, not a childAdded or using the offline mode.

So if the database example is updated or had its own version on the latest
UI lib would be great! :)

if it won't happen, it can be a great help to let you look at some of my
code to help me, can we arrange one or another?

Thanks in advance.


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2
<http://www.umanni.com.br/>

2017-01-26 21:38 GMT-02:00 Morgan Chen <notifications@github.com>:

**Comment by morganchen12** [comment]
I'd like to avoid 1:1 help with people's code in private, since that's generally a horrendously inefficient use of open source maintainers' time. If you have a particular issue and can post the code snippet here, I'd be happy to help you, since the code you post can serve as a reference for others who run into the same issue in the future.

If you'd like to avoid having to change your codebase when a new version of FirebaseUI comes out, you can specify a major and minor version of FirebaseUI in your Podfile and CocoaPods will avoid upgrading beyond the versions you specify.

**Comment by Rovel** [comment]
Thanks,

Yes, it makes a lot of sense to avoid this 1:1 help in open source
projects, and the request for updating the database example probably is not
going to happen since you didn't mentioned it...

I'm getting some parts working again and I will post some snippets in
future issues/question.

Actually for this project in special I fixed all pods since new swift 3
pods versions usually do not work with swift 2.2 and keep a xcode 7.3 to
work the transition.

Most of the issues I've found on this migration had to do with the
transition from xcode 7 to 8 and swift 2 to 3 and not with FirebaseUI.




Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2
<http://www.umanni.com.br/>

2017-01-27 17:31 GMT-02:00 Morgan Chen <notifications@github.com>:

**Comment by Rovel** [comment]
Hey,

I'm having some trouble in some kind of implementation using datasource and
firebase ui datasource

  * Swift: 3
  * iOS version: 10
  * Firebase SDK version: latest
  * FirebaseUI version: latest
  * CocoaPods Version: 1.1.1

The problem:

I want to use a xib (call a nib ) to reuse a tableViewCell with the new
FirebaseUI (2.0.0) FUITableViewDataSource

In version 0.4 I could use something like this (database example in the
official firebase repo):

dataSource = FirebaseTableViewDataSource.init(query: getQuery(),
                                                  modelClass: Post.self,
                                                  *nibNamed:
"PostTableViewCell",*
                                                  cellReuseIdentifier:
"post",
                                                  view: self.tableView)


In the
https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/FUIIndexTableViewDataSource.h

I couldn't find a function that calls a nib anymore, am I missing
something? how can I point a nib with the new firebase UI Tableview
datasource.

Thanks


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2
<http://www.umanni.com.br/>

2017-01-30 11:23 GMT-02:00 Filipe Veloso <filipe@umanni.com.br>:

**Comment by morganchen12** [comment]
You can still use a nib with FirebaseUI, just register it manually as you would if you weren't using FirebaseUI.

https://developer.apple.com/reference/uikit/uitableview/1614937-register

**Comment by Rovel** [comment]
Thanks!  man you'r fast! 😱

Regards


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2
<http://www.umanni.com.br/>

2017-01-31 17:55 GMT-02:00 Morgan Chen <notifications@github.com>:
