### ISSUE TITLE
Auth Credentials Error

### ISSUE THREAD

**Issue by teeosx** [firebase/quickstart-ios#215]
When I try to connect FCM it's always showing up like this on console

_FIRMessaging registration is not ready with auth credentials
Unable to connect with FCM. Optional(Error Domain=com.google.fcm Code=501 "(null)")_

I recheck p12 file in firebase console many times but this error still appear
Someone please help me?

**Comment by morganchen12** [comment]
@kroikie FYI

**Comment by ThoseGuysInTown** [comment]
Also getting this error.

**Comment by teeosx** [comment]
Sorry For no update now I solve this problem already,
At first I try to use FCM with swift 2 project
later I try to migrate my current project into swift3 then update the latest pod
Now it's work fine already :D 

@ThoseGuysInTown  what is your current swift that you're using for project please?

**Comment by muhammadmuhlas** [comment]
also getting this error using swift2, xcode 7.3.1
