### ISSUE TITLE
Error while uploading the dsym file 

### ISSUE THREAD

**Issue by sundarsan** [firebase/quickstart-ios#216]

**Comment by sundarsan** [comment]
i am trying to upload the dsym file through terminal - firebase crash iOS 

command which i use 
./Pods/FirebaseCrash/batch-upload tripsy/copper-affinity-109910-firebase-crashreporting-tvzaw-b11e9957ba.json 89B0C0B7-0901-3D38-BE48-15C0D438AD48

i see tons of warning messages and finally it throws the below two line error 

./Pods/FirebaseCrash/upload-sym-util.bash:377: error: symbolFileMappings:upsert: The uploaded file is not a valid Breakpad Symbol file.
./Pods/FirebaseCrash/upload-sym-util.bash:378: note: symbolFileMappings:upsert: The metadata for the symbol file failed to update.

Note : 
dsym file is for older version and i created a service account file later .
Is there any association between service account file and dsym or is it just for authentication

**Comment by NathanVogel** [comment]
Same issue here, any help ?

**Comment by morganchen12** [comment]
Can you share a project reproducing this issue?
