### ISSUE TITLE
How to enable the swift version ?

### ISSUE THREAD

**Issue by oliviermenir** [firebase/quickstart-ios#22]
No problem to activate the "objective c" version but impossible to enable "swift" one . How to do this ?
Thks !!

**Comment by kroikie** [comment]
Which of the quickstarts are you referring to?

**Comment by oliviermenir** [comment]
I want to use exclusively Swift but don t understand how to switch from objective c to swift. Both languages are mixed in the same project. Thank you for your support.

**Comment by ianbarber** [comment]
Change the target in the drop down next to the device selector (to the right of the run button). 

Remember to add you GoogleService-Info.plist to the Swift target as well in the info panel on the right when selecting the file.
