### ISSUE TITLE
Warning: "FIRMessaging receiving notification in invalid state 2" when app is in background mode

### ISSUE THREAD

**Issue by SnitramDev** [firebase/quickstart-ios#222]
When the app is in background mode I get the following warning "FIRMessaging receiving notification in invalid state 2", using the sample "Messaging" appI've copied and pasted the whole thing. This warning only happens when the app is in background. When the app is in foreground, this warning doesn't appear.

2017-02-17 00:45:48.440: <FIRMessaging/WARNING> FIRMessaging receiving notification in invalid state 2
Message ID: 0:1487295941988340%7a89b91a7a89b91a
[AnyHashable("SentBy"): TestingFireBase, AnyHashable("gcm.message_id"): 0:1487295941988340%7a89b91a7a89b91a, AnyHashable("MsgNum"): 1229, AnyHashable("TimeStamp"): 20170217_004541.857, AnyHashable("aps"): {
    "content-available" = 1;
}]

**Comment by morganchen12** [comment]
I'm unable to reproduce this issue.
