### ISSUE TITLE
FCM your token is NotRegistered loop  

### ISSUE THREAD

**Issue by bch007** [firebase/quickstart-ios#224]
Hi, i follow this sample and it appear for some case when you token can become NotRegistered state.
After that, when your server send a notification push, fcm return that a message failure like error:NotRegistered. Even if your server remove this token, on client side app, you still get this invalid token because the callback is never call after the first installation of app. Thank for help

**Comment by morganchen12** [comment]
There's not enough information in this issue to debug. Can you clarify further? What specific errors are you getting?

Please reopen this issue if it's still relevant.

**Comment by signalpoint** [comment]
This comment helped me resolve a similar issue: https://github.com/firebase/quickstart-ios/issues/77#issuecomment-249433845
