### ISSUE TITLE
You don’t have permission.(DatabaseExample) 

### ISSUE THREAD

**Issue by sabhay1996** [firebase/quickstart-ios#23]
The file “DatabaseExample” couldn’t be opened because you don’t have permission to view it. I'm unable to run on simulator as well as device .

**Comment by ianbarber** [comment]
This is a really odd sounding error. Is this Xcode giving the error? Can you check the file permissions on the directory you have cloned the sample in to?

**Comment by sabhay1996** [comment]
read & write for current user

**Comment by iulukaya** [comment]
Is this issue resolved?

**Comment by mcdonamp** [comment]
Set your default database rules to:

```
{
  "rules": {
    ".read": true,
    ".write": false
  }
}
```

Or [enable Firebase Authentication](https://firebase.google.com/docs/auth/).
