### ISSUE TITLE
Some push notifications not received when app is in background

### ISSUE THREAD

**Issue by bihel** [firebase/quickstart-ios#233]
We are trying to push notifications to a single device. Since the payload is relatively small we will most of the time send multiple push notifications that the app can merge.

This works fine when the app is in the foreground but when the app is in the background it seems that some messages don't arrive. For these types of notifications we always send priority high and content available=true.

Is it maybe not possible to rapidly sent multiple notifications to a single device that's either in sleep mode or app in background?
We've tested sending with a small delay in between and that seems to work fine in most cases.
We've noticed that they either arrive within 5 seconds or they don't arrive at all.

Is it possible to track from firebase console which notifications have been sent successfully to a device?

**Comment by bakeddean** [comment]
In the foreground the app is using a direct socket connection to the Firebase server (reliable). In the background you are receiving your data via the murky world of the Apple Push Notification Service, which has a best-effort delivery policy.
