### ISSUE TITLE
Handle iOS data notifications with FCM

### ISSUE THREAD

**Issue by gagancdac** [firebase/quickstart-ios#235]
I am not receive data notification message in iOS.

**Comment by morganchen12** [comment]
Can you provide more details? What steps did you take?

**Comment by gagancdac** [comment]
Hi,

Normal notification messages are notified on the device but i have issue with data-messages. Data-messages are not notified in the device but when i send message from firebase console then it is shown on the device.

applicationReceivedRemoteMessage delegate method not called in appDelegate class.

rdgs
Gagan

**Comment by morganchen12** [comment]
@kroikie have you seen this before?

@gagancdac could you post the code you used to register for notifications?

**Comment by rostopira** [comment]
I'm not using FCM on iOS, but don't receiving data messages too, even with flags "content_available" and "mutable_content"
Looks like it's another Apple "innovation" in iOS 10 : https://forums.developer.apple.com/thread/67081
So issue should be closed, probably.

**Comment by morganchen12** [comment]
Thanks @rostopira!
