### ISSUE TITLE
connectToFcm fails on didBecomeActive due to nil token

### ISSUE THREAD

**Issue by mwaterfall** [firebase/quickstart-ios#236]
I've set up my app delegate identical to the example project but I'm failing to receive push notes in the background. I've noticed that when the app enters the background it disconnects from FCM, however when the app becomes active and `connectToFcm` is called, it fails to reconnect due to the token being nil.

Fails here: https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExampleSwift/AppDelegate.swift#L118

I can print the token within `didFinishLaunchingWithOptions` and it exists fine, so what could be the reason for the token suddenly not being available after coming back from the background?

Could this be a symptom of something that's causing push notifications from not appearing, even when set to high priority?

If I re-launch the app I see the message come through in the console, but it's just not appearing as an Apple push notification when backgrounded.

**Comment by morganchen12** [comment]
Closing this for now as I was unable to repro this issue and it hasn't seen any new reports. Please reopen if it's still a problem.
