### ISSUE TITLE
FIRApp.configure() lead to memory leak

### ISSUE THREAD

**Issue by takawww** [firebase/quickstart-ios#239]
Hi all

I am using the SDK in swift 3 by in Xcode 8.2.1.

Here is my setup:
1. APN Certs are uploaded to Firebase
2. Create single tab app with my registered bundle name, 
3. Import the sdk by pod, (pod update is run)
4. Include google service info plist
5. Edit the appDelegate.swift (import Firebase & FIRApp.configure() in didFinishLaunchingWithOptions )

When I run instrument, it shows leak.
but I would be find if I comment the line FIRApp.configure() 

Is there any missing on my setup?

Thanks & Regards
Taka Wong

**Comment by morganchen12** [comment]
Can you post the instruments trace?

**Comment by morganchen12** [comment]
@takawww is this still an issue?

**Comment by Afsarunnisa** [comment]
Hi, Even I'm also getting same leak in firebase config 

import Firebase & FIRApp.configure() in didFinishLaunchingWithOptions in app delegate. 


Here are the screenshots.

<img width="908" alt="screen shot 2017-04-11 at 3 23 14 pm" src="https://cloud.githubusercontent.com/assets/12713560/24903593/82b0778c-1ecb-11e7-91ec-327c89ddd098.png">

If i remove the import FIRApp.configure(), its fine. 

<img width="893" alt="screen shot 2017-04-11 at 3 26 31 pm" src="https://cloud.githubusercontent.com/assets/12713560/24903603/8bd347ea-1ecb-11e7-9d99-840d19a5dcb6.png">

**Comment by jxtmo** [comment]
Hi, I am having the same issue as well

**Comment by jxtmo** [comment]
<img width="1920" alt="screen shot 2017-04-16 at 6 50 55 pm" src="https://cloud.githubusercontent.com/assets/3809684/25070612/d04e5604-22d5-11e7-8512-b69a90e207b4.png">

**Comment by jxtmo** [comment]
some updates from my side. Seems like to me, Firebase Analytics is the one causing the leak. I personally uses Fabrics for crash logging, Google Analytics and didn't realise Firebase Analytics is also enabled by default.

Here is what I did, set FIREBASE_ANALYTICS_COLLECTION_ENABLED to NO and FIREBASE_ANALYTICS_COLLECTION_DEACTIVATED to YES. At least this works for me, for those who rely on firebase analytics this definitely is a bug

**Comment by morganchen12** [comment]
Thanks @jxtmo, this has been filed internally and I'll keep this ticket updated.

**Comment by morganchen12** [comment]
This has been fixed internally and will make its way out in a future release. Thanks for reporting!

I'll wait until the release happens to close this issue.

**Comment by morganchen12** [comment]
This should be fixed in Firebase 4.0. If you're still running into this issue, make sure you've updated your Firebase pods.

**Comment by jim-mcandrew** [comment]
Still seeing this issue, even after updating pods to 4.0.

**Comment by jim-mcandrew** [comment]
I created a brand new Firebase project and no longer saw the issue. It appears there may be something wrong with our old Firebase project.

**Comment by pekoto** [comment]
Firebase Analytics is leaking again (4.0.3).

Seems I'm not the only one having this issue:
https://stackoverflow.com/questions/39007621/firapp-configure-creating-a-memory-leak-ios

**Comment by morganchen12** [comment]
@pekoto is this still an issue in 4.1.x?

@baolocdo is this a known issue? I see b/37422060, but no specific bug pertaining to this most recent leak.

**Comment by pekoto** [comment]
Yes, I have Firebase 4.1.0 and it's happening there.

**Comment by baolocdo** [comment]
sorry, from the screenshot, I don't see any symbols related to Firebase Analytics. Can you please point out where I can find them so it would be easier to debug? Thanks.

**Comment by morganchen12** [comment]
Upon closer inspection, the leak seems to be coming from Firebase Crash and not Firebase Analytics. Filed b/65114070 internally, will keep this thread updated.

Thanks for reporting!

**Comment by shebinkoshy** [comment]
I face the same problem. its working fine for me After removing 'Firebase/Performance' from pod.

**Comment by saldous** [comment]
I'm also seeing a memory leak with Firebaseapp.configure()

Using Firebase 4.6.0, screenshot from instruments below:

![image](https://user-images.githubusercontent.com/3334306/32983652-e0672e28-cc65-11e7-8bc1-e77f34958f91.png)

**Comment by baolocdo** [comment]
Hi @saldous,
Not relevant to your question but I noticed from your code: I'd recommend to add **FirebaseApp.configure()** in **application:didFinishLaunchingWithOptions:** and after you add an IAP observer **(SKPaymentQueue.default().add(self)**) to delay configuring at init which can block your app from launching. In addition, if you add IAP observer later than 3rd party Analytics SDK, there might be a chance that your app crashes before an IAP transaction is finished and you won't get the notification because the SDK will get the notification first.
Regarding the leak, can you please go to the Call Trees and take a screenshot of the methods in the tree that caused the leaks? I know that SKPayment itself is leaky but it may appear as though Firebase is leaky. 
Thank you for reporting.

**Comment by saldous** [comment]
ok, thanks, I'll update and re-test and update you.

**Comment by baolocdo** [comment]
It looks like Firebase Crash Report is causing a leak.

**Comment by ernesto** [comment]
```Using Firebase (4.8.0)
Using FirebaseABTesting (1.0.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseAuth (4.4.1)
Using FirebaseCore (4.0.13)
Using FirebaseCrash (2.0.2)
Using FirebaseInstanceID (2.0.8)
Using FirebaseMessaging (2.0.8)
Using FirebaseRemoteConfig (2.1.0)```

Still  leaking :(

**Comment by shejis** [comment]
Firebase (4.9) has same issue , Memory leaking ,i commented out the FirebaseApp.configure() and check the memory leak issue but no issue reported from profile

**Comment by danielCarlosCE** [comment]
+1

**Comment by m3touch** [comment]
Firebase 4.9 solved the problem for me. Make sure to delete the Podfile.lock file before installing the new one.

**Comment by danielCarlosCE** [comment]
`runtime: Memory Issues - (8 leaked types): 1 instance of TAGContainerLoader leaked`

  -Firebase/Core (~> 4.9.0)
  - Firebase/DynamicLinks (~> 4.9.0)
  - Firebase/Messaging (~> 4.9.0)
  - Firebase/RemoteConfig (~> 4.9.0)

**Comment by baolocdo** [comment]
@danielCarlosCE : I see you have TAGContainerLoader. Do you have GTM by any chance?

**Comment by danielCarlosCE** [comment]
Yes I do @baolocdo! That would me the next information I would provide

**Comment by baolocdo** [comment]
It looks like GTM problem. I'll file a bug report to them. Thanks

**Comment by danielCarlosCE** [comment]
By simply adding the pod `GoogleTagManager` (last version) I had those leaks. I actually removed the pod and got no build error, so I'm not sure how the last developer was using it. I will check it out if we still need this pod somehow. In the meanwhile, can I do anything to prevent those leaks?

**Comment by eburley** [comment]
We'll look at addressing this leak in a future gtm release. The leaked object is held by a singleton, and there shouldn't be more than one of them, are you seeing more than one object being leaked?

In terms of removing the pod, GTM doesn't have a specific interface. If your application has a GTM-... named file in your app, GTM will load it when Firebase Analytics initializes. Removing the GTM pod will prevent Firebase Analytics from using GTM. This will stop the leak, as you've noticed, but it will also disable the GTM container.

**Comment by danielCarlosCE** [comment]
![screen shot 2018-02-27 at 10 25 14 am](https://user-images.githubusercontent.com/1819682/36731142-901c1536-1ba8-11e8-9b2b-cb9bfd57b941.png)
as soon as I add the pod back, @eburley, it goes from 0 to 6 leaks

**Comment by JienLee** [comment]
![firebase_leak](https://user-images.githubusercontent.com/31241214/36778304-ba737600-1caf-11e8-9378-4b154062c891.png)

I got same issue in Firebase(4.8.2).

**Comment by morganchen12** [comment]
@JienLee can you file a new issue? The memory leak in your app is in Dynamic Links, and if possible, we should keep separate memory leaks in separate issues.

**Comment by morganchen12** [comment]
Hey all, people have started reporting separate memory leaks that aren't related to each other in this thread. If you've already started receiving help, feel free to keep commenting, but if yours is a new memory leak, please file a **new issue** over at the [main SDK repo](https://github.com/firebase/firebase-ios-sdk/issues/new).

I'm going to close this issue for now since it's gone off topic, but again, if you've already started receiving help feel free to continue the discussion on this thread.
