### ISSUE TITLE
No such module 'FBSDKCoreKit'

### ISSUE THREAD

**Issue by oliviermenir** [firebase/quickstart-ios#24]
No such module 'FBSDKCoreKit' error when script executed

**Comment by ianbarber** [comment]
Try cleaning your build directory - hold down option when selecting Product > Clean in Xcode.

**Comment by quuack** [comment]
@oliviermenir in your Build Settings, look at this field: "Framework Search Paths" You should have something like this: /Users/[username]/Documents/FacebookSDK
