### ISSUE TITLE
Notifications sound not coming : Swift 3 , iOS 10 

### ISSUE THREAD

**Issue by hemanthalluri** [firebase/quickstart-ios#240]
## May I know where to place this code in AppDelegate so that push notification sound will played. 

         let content = UNMutableNotificationContent()
         content.sound = UNNotificationSound(named: "tone.aiff")

tone.aiff is available in my app bundle. 
I placed where there is possibility to hear sound. But It's not playing. 

So tell me where to place in Appdelegate to play custom sound / default sound while receiving push notifications.

**Comment by morganchen12** [comment]
Please move this question to StackOverflow, since it seems to be Firebase-agnostic assuming you're receiving notifications correctly.

If you're having issues receiving notifications, please open a separate issue.
