### ISSUE TITLE
Way too many 'unaligned pointers' warnings when adding Firebase as a pod to Xcode project

### ISSUE THREAD

**Issue by Archivus** [firebase/quickstart-ios#243]
Hello, I'm really loving Firebase so far but I've had 64 warnings issued as soon as I added the pod to my project. Everything works great but it just bothers me to have so many warnings. Is there any way of getting rid of them? Did I miss an installation step? Here are a few of the sample warnings (almost all of them dealing with unaligned pointers) 
<img width="260" alt="screen shot 2017-03-25 at 11 51 59 am" src="https://cloud.githubusercontent.com/assets/1841186/24323789/78d224ea-1151-11e7-8a43-a7f9bd5da99a.png">

**Comment by jxtmo** [comment]
I am getting the same warnings as well!

**Comment by bricecesarin** [comment]
I am getting the same warnings since update Xcode to 8.3

**Comment by morganchen12** [comment]
Can you post the steps you took when installing Firebase that led to these warnings?

**Comment by Archivus** [comment]
Followed the exact steps listed here https://firebase.google.com/docs/ios/setup

**Comment by jxtmo** [comment]
Adding on to this, this persist only on the latest Xcode 8.3

**Comment by freak4pc** [comment]
Same here. Not using Firebase but "stuck" with it because of GoogleSignIn, getting those same warnings on Xcode 8.3 GM.

![image](https://cloud.githubusercontent.com/assets/605076/24461372/8d420f66-14a9-11e7-800f-6453a69def54.png)

**Comment by morganchen12** [comment]
Got it. I've let the core SDK team know, and will keep this issue updated with progress.

Thanks for reporting!

**Comment by qclmnt** [comment]
I am getting the same warnings since update Xcode to 8.3

**Comment by baolocdo** [comment]
We are aware of this issue and will try to address this as soon as possible in the next release.

**Comment by james-ff** [comment]
Could this potentially cause any problems for a release build? I need to release a new update of my app soon but am concerned about these warnings.

**Comment by baolocdo** [comment]
@james-ff: If you have the latest Firebase Core and Firebase Analytics, it should be fine. Don't mismatch the versions since it might break your app due to some lower level implementation.

**Comment by morganchen12** [comment]
This is fixed in the latest release.

**Comment by freak4pc** [comment]
Thanks @morganchen12 , Looks like this cleared up everything ! 
Except for this stubborn one which seems also related to Firebase ? I'll try to further examine.

![image](https://cloud.githubusercontent.com/assets/605076/25039725/cea6adb6-210d-11e7-9841-0382e77a6819.png)

**Comment by morganchen12** [comment]
@freak4pc Can you provide a sample project that repros this issue? I'm not seeing it in any of my Firebase projects.

**Comment by freak4pc** [comment]
Sure, will give it a go later. Could be unrelated to Firebase. I'll report back. Thanks @morganchen12
