### ISSUE TITLE
No such module "FirebaseUI" in DatabaseExampleSwift

### ISSUE THREAD

**Issue by kutakmir** [firebase/quickstart-ios#25]
1. Download repo
2. pod install
3. open xcworkspace
4. run DatabaseExampleSwift
5. No such module "FirebaseUI" 

the same for Objective-C

**Comment by ianbarber** [comment]
Can you check you have the latest version of the sample? I think the module imports got changed. If it is the latest, which file is showing the error?

**Comment by sabhay1996** [comment]
import FirebaseDatabaseUI
