### ISSUE TITLE
Issue with mutable_content

### ISSUE THREAD

**Issue by TagCommander** [firebase/quickstart-ios#251]
Hello ! I'm quite at a loss there, so I'm trying to write a message there.

So I want to display a rich notification with a nice image in iOS 10+.

For this I'm using FCM and an UNNotificationServiceExtension which, if I understood correctly, should get the Data payload, find the image URL and load it before modifying the UNNotificationContent.

I'm tried many many ways to send data in the payload of my call to https://fcm.googleapis.com/fcm/send and the issue I have is that I can't get a hold of the "data" I should handle in the UNNotificationServiceExtension.

My understanding is that it's the only way to do this kind of push, and make them work when the application is not launched.

I created a SO question some times ago with more details about what I'm doing and what is sent : [using-data-in-rich-push-notification-on-ios-with-fcm](http://stackoverflow.com/questions/42693019/using-data-in-rich-push-notification-on-ios-with-fcm)

Could you help me pointing the issue there or tell me if I juste need to wait a little for this feature to be available?

Thanks a lot!

**Comment by rsattar** [comment]
Based on your SO description and this one, I think you might be expecting that the rich media is automatically retrieved for you within the UNNotificationServiceExtensions. It looks like the payload you're receiving is as expected:
1. `mutable-content` is `1` within `aps`
2. `mediaUrl` is included outside of `aps`

It's the developer's job to take whatever data is in the payload, and convert that to a `UNNotificationContent` object, with media attachments.

**Comment by TagCommander** [comment]
How can I get the data that are outside of aps ? The object received 'UNNotificationRequest' doesn't contain anything that is outside of aps.
