### ISSUE TITLE
FCM works for a while and then stops working

### ISSUE THREAD

**Issue by facundomedica** [firebase/quickstart-ios#252]
I've been trying to debug the notifications in my own app and because I couldn't get it to work as it should I decided to download this example and try it out. The problem is that this works exactly as my app.

I've followed all the steps and it works, I was amazed of how fast the notifications were and suddenly it just stops and then without changing anything it works again.

Description of problem: the notifications seems to be very unreliable. Working very well for a while and then I stop receiving them even though FCM server always respond with success.

I've tried with this website: http://pushtry.com/ and with my own web service in Go.

```Go
package main

import (
	"fmt"
	"log"

	fcm "gopkg.in/maddevsio/fcm.v1"
)

func main() {

	data := map[string]string{
		"msg": "Hello World1",
		"sum": "Happy Day",
	}
	c := fcm.NewFCM("SERVER KEY")
	token := "THE TOKEN"
	response, err := c.Send(&fcm.Message{
		RegistrationIDs:  []string{token},
		Data:             data,
		ContentAvailable: true,
		Priority:         fcm.PriorityHigh,
		Notification: &fcm.Notification{
			Title: "Hello123",
			Body:  "World123",
			Sound: "default",
			Badge: "1",
		},
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Status Code   :", response.StatusCode)
	fmt.Println("Success       :", response.Success)
	fmt.Println("Fail          :", response.Fail)
	fmt.Println("Canonical_ids :", response.CanonicalIDs)
	fmt.Println("Topic MsgId   :", response.MsgID)
	fmt.Println(response.Results)

}
```

I've tried with and without data, priority and everything else. Sometimes it seems that it works but after some minutes it stops working. Sometimes when testing with 2 devices one of them gets the notifications and the other doesn't.

I've tried with the app opened, closed, killed, screen locked, screen unlocked and every combination, I can't find any kind of pattern.

I **ALWAYS** get status code 200 and Success form the FCM server.

**Comment by facundomedica** [comment]
More data: I open the app and then there all the notifications arrive. So the APNS is not working or something like that.

Is there a limit of notifications I can send in development? (I'm not using a crazy amount, maybe 4 per minute at the most)

**Comment by victorlsn** [comment]
I believe you have the same problem I do:
https://github.com/firebase/quickstart-ios/issues/273
When the FCM token is updated/refreshed, the APNS stops working.

Did you find a solution?

**Comment by facundomedica** [comment]
@victorlsn I don't think so, but currently when we are debugging the app notifications stop working but they seem to work better on test flight.

**Comment by rolinger** [comment]
I am having somewhat of a similar issue with FCM.  Mine is with a different plugin and testing on Android -I haven't even begun to test with iOS yet.  Please see my post on this and let me know what you think.  

[FCM worky no worky](https://stackoverflow.com/questions/44789260/cordova-fcm-works-then-suddenly-stops-working)

This is quite frustrating.  I even have a case open with Firebase; i think the issue lies with them.  If my code isn't changing and it works and then stops working...then logic says its their issue.

**Comment by mannerism** [comment]
Do you have updates on this issue? Did you find any solution?

**Comment by rolinger** [comment]
@mannerism  - I left this plugin LONG ago.  I have been using cordova-plugin-fireabasex for almost the last 2 years now.  Its well supported and works without issue.

**Comment by jpetro416** [comment]
Anyone ever figure this out?
