### ISSUE TITLE
Firebase signInWithCredential error occur

### ISSUE THREAD

**Issue by vikrant88** [firebase/quickstart-ios#253]
I am using Firebase in iOS using swift language. I am trying to signIn with Facebook. I am getting FBSDKAccessToken using with graphRequest. When I am using Firebase  signIn method of Facebook then getting following error 
    

>     > UserInfo={NSUnderlyingError=0x608000059560 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)"
> UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
>         code = 400;
>         errors =     (
>                     {
>                 domain = global;
>                 message = "Unsuccessful debug_token response from Facebook: {\"error\":{\"message\":\"(#4) Application request limit
> reached\",\"type\":\"OAuthException\",\"is_transient\":true,\"code\":4,\"fbtrace_id\":\"En2h2Q0L7TP\"}}";
>                 reason = invalid;
>             }
>         );
>         message = "Unsuccessful debug_token response from Facebook: {\"error\":{\"message\":\"(#4) Application request limit
> reached\",\"type\":\"OAuthException\",\"is_transient\":true,\"code\":4,\"fbtrace_id\":\"En2h2Q0L7TP\"}}";
>     }}}, error_name=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for
> more information.}

    And my complete code is 
    
        {
            let login : FBSDKLoginManager = FBSDKLoginManager()
            login.logOut()
            login.logInWithReadPermissions(["public_profile","email"], fromViewController: self, handler:  { (result, error) -> Void in
                if (error == nil){
                    let request: FBSDKGraphRequest = FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "id,email,first_name,middle_name,last_name,picture"], HTTPMethod: "GET")
                    request.startWithCompletionHandler({ (connection : FBSDKGraphRequestConnection!, result : AnyObject!, error : NSError!) -> Void in
                        if error == nil
                        {
                            let userDetail : NSDictionary = result as! NSDictionary
                            
                            
                            
                            
                        let token = FBSDKAccessToken.currentAccessToken().tokenString
                            
                           let credential =  FIRFacebookAuthProvider.credentialWithAccessToken(token)
                           FIRAuth.auth()?.signInWithCredential(credential, completion: { (user, error) in
                                
                                if error == nil
                                {
                                    
                                    let homeVC = self.storyboard?.instantiateViewControllerWithIdentifier("PageController") as? PageController
                                    self.navigationController?.pushViewController(homeVC!, animated: true)
                                    
                                    print(userDetail)
                                }
                                else
                                {
                                     print("Signing  Failed ")
                                    
                                }
                               
                                
                            })
                           
                            
                            
                        }
                        else
                        {
                            print("Error Getting Info \(error)");
                        }
                    })
                }else{
                    print("Login Failed")
                }
            })
    
            return;
        }

**Comment by morganchen12** [comment]
Looks like you're running into the Facebook API rate limit.

>message = "Unsuccessful debug_token response from Facebook: {"error":{"message":"(#4) >Application request limit reached"

Try posting this question over at StackOverflow.

**Comment by vikrant88** [comment]
I have posted already http://stackoverflow.com/questions/43519458/firebase-signinwithcredential-giving-error-using-facebook-sdk
But what is the solution. Sorry I didn't get

**Comment by Kottidev** [comment]
I have same probleme

**Comment by zerlik** [comment]
And I have same probleme

**Comment by zerlik** [comment]
but in my other application, Facebook works fine

**Comment by nayong** [comment]
I solve this problem by change the **FacebookAppID** in info.plist and URL. :)
I used the one which is unconnected with Firebase application. (old one)
