### ISSUE TITLE
FirebaseCrash problem when submitting to iOS App Store

### ISSUE THREAD

**Issue by mrgingles** [firebase/quickstart-ios#255]
Hi all,
I've installed Firebase Crash into my app (without using CocoaPods) but, when I try to submit it to the iOS App Store, I get the following error: 
 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'xxxx.app/dump_syms' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

Same error has been posted on StackOverflow (not by me) http://stackoverflow.com/questions/41056047/firebase-crash-report-dump-syms-is-not-permitted-in-itunes-connect-upload 

Please note that, if I remove the `dump_syms` file from the bundle resources, the crash is correctly reported into Firebase but is not symbolized.

Someone suggested to read your issue #46 where you say that the warning problem during the build has been resolved, but it is **not**. I'm using the latest version of Firebase.

**Comment by morganchen12** [comment]
`dump_syms` shouldn't end up in your app bundle when archiving. What steps did you take when integrating Firebase Crash? Wonder if we've left something out of our docs somewhere.

**Comment by mrgingles** [comment]
I followed [this guide](https://firebase.google.com/docs/crash/ios) (but without using CocoaPods)

I downloaded the latest version of Firebase and dragged it into my project, with all the needed dependencies (see attached screenshots).

![screen_2](https://cloud.githubusercontent.com/assets/7009056/25378136/c10afa32-29a9-11e7-8b50-0a4e5026faf9.png)
![screen_1](https://cloud.githubusercontent.com/assets/7009056/25378137/c116d53c-29a9-11e7-86f4-ca70bcec970b.png)

Then I put all the other files needed by Firebase Crash into another folder named "Crash" and configured the "Run Script" section in the "Build Phases".

![screen_3](https://cloud.githubusercontent.com/assets/7009056/25378135/c104330a-29a9-11e7-87a5-0ba303e6de9a.png)

Please note that everything is working fine (crash report have been created during tests) except for the `dump_sys` files inside my bundle and 999+ warnings during build (see your issue #46)

![screen_4](https://cloud.githubusercontent.com/assets/7009056/25378134/c0d00cd8-29a9-11e7-93cb-44a02a72b549.png)

**Comment by morganchen12** [comment]
`dump_syms` should *not* be in the Copy Bundle Resources phase. It just needs to exist in your source tree so Xcode's run script phase can execute it. It doesn't need to be visible in your project file at all otherwise.

If you remove it and the other executables from the Copy Bundle Resources phase, do your errors go away?

**Comment by mrgingles** [comment]
If I remove the `dump_syms` file from the bundle resources, I can correctly upload the built to the iTunes Store, the crash is correctly reported into Firebase but is not symbolicated. I think that it is something related to Apple's Bitcode. (https://developer.apple.com/library/content/technotes/tn2151/_index.html, Bitcode section).

The warnings are there in both cases.

**Comment by morganchen12** [comment]
Can you check and make sure`upload-sym` is invoked on every build and archive? There's no reason removing the file from your bundle should cause the executable to not be symbolicated.

**Comment by mrgingles** [comment]
I already did this test (removing from the "Copy Bundle" all the files you see in my "Crash" folder -see previous screenshot-).

The "run script" phase is correctly executed (I can still see the 999+ warnings and the action "Running custom shell scripts" going) and the build can be uploaded to iTunes Connect. The problem is that, when a crash occurs, it is not symbolicated on Firebase Crash Console.

Don't you think that this could be related to the Apple's Bitcode? If you read Apple Docs, you'll see 

> Important: The binary compiled by the App Store will have different UUIDs than the binary that was originally submitted

So, since the Firebase script is executed **only** locally on my mac **before** the submission to Apple, it will have `XXX-XXX` as UUID. When the build arrives on Apple's servers it will have another UUID (maybe `YYY-YYY`) so the link made by your script is no longer valid.

**Comment by morganchen12** [comment]
If you test this theory by building without bitcode, are the crashes correctly symbolicated?

**Comment by mrgingles** [comment]
I uploaded two different builds on iTunes Connect, the former with Bitcode enabled and the latter without Bitcodes. In both of them, I added 
```swift
FIRCrashMessage("Cause Crash button clicked")
fatalError()
```
Obviously, `FIRCrashMessage` has a different message for each build.

So I launched an internal Testflight for both the builds but, unfortunately, the crashes are not reported at all in Firebase Crash Console (maybe Firebase Crash is not working with Testflight?). **I have waited several hours before posting this message!**

However, looking for more information inside the Firebase docs, I found the section [Bitcode support](https://firebase.google.com/docs/crash/ios#bitcode_support) which, implicitly, seems to admit that a manual action must be done by the developer if Bitcode is enabled. If this is true, what said in the [Upload symbol files](https://firebase.google.com/docs/crash/ios#upload_symbol_files) section should be not valid with this scenario.

Assuming that all the above if right (please correct me if I'm wrong), another problem comes out: since Apple can recompile the build at any time, and this causes the generation of new UUIDs, we can never be sure that the dSYMS files uploaded to Firebase are in sync with the ones used in the Apple's build and -I think- the only way to solve this is to include `dump_syms` inside the build so it can be executed on each Apple rebuild.

**Comment by vincenzo-mennella** [comment]
Do you have updates about this?

**Comment by mrgingles** [comment]
Do you have updates about this?

**Comment by morganchen12** [comment]
From what I understand, the process of downloading your dSYMs from Apple and reuploading them to Firebase Crash exists to get around this limitation. It's not great, because it requires basically manually updating the dSYMs in crash on every unsymbolicated crash log (i.e. recompile). 

Including `dump_syms` in the app binary itself won't help as there's no way to execute it.

**Comment by mrgingles** [comment]
> From what I understand, the process of downloading your dSYMs from Apple and reuploading them to Firebase Crash exists to get around this limitation.

Yes, that's right. But I think that this would be a big limitation to Firebase Crash.

> Including dump_syms in the app binary itself won't help as there's no way to execute it.

Shouldn't it be executed on every build? With Bitcode, Apple rebuilds the package and (I think) `dump_syms` would be re-executed.

**Comment by morganchen12** [comment]
It's only executed on every build in your local setup because of a Run Script Phase in Xcode. Apple's building from bitcode process is probably entirely different and I'd imagine they wouldn't want to be running arbitrary shell scripts from the app bundle.

**Comment by mrgingles** [comment]
OK. Are we sure that this problem is related to bitcode? I think so, but did you investigate by your side?

**Comment by mikehaney24** [comment]
Hi, I work on Firebase Crash. What Morgan has been saying is correct. dump_syms is an OS X binary, not an ARM binary that runs on iOS. It should only be run by the upload-sym script when run by the build phase script. To symbolicate a bitcode-enabled app, you must manually download the dSYM from Apple and upload it by running the batch-upload script. It's not a great system, and we're working with our new colleagues in Crashlytics to address this at some point in the future. For now, I'd just recommend disabling bitcode. Crash processing latency is about 1-3m, so you needn't wait hours to see a crash appear. If the crash didn't appear, it could be for several reasons: Crashes are uploaded on app start, and if multiple crash reports are stored on a device, it will upload about 1 per minute. If the fatalError() you placed occurs before the SDK has a chance to upload, that would cause it to not show up.

**Comment by mrgingles** [comment]
Thank you @morganchen12 and @mikehaney24 for your support. Maybe a little update to the docs to clarify this situation would help other users :)

Have a great day!

**Comment by patelnirav48** [comment]
@morganchen12 I still getting this error Firebase-4.3.0 while archiving. Please help Thanks

**Comment by morganchen12** [comment]
The dump_syms Xcode warnings aren't the main focus of this issue. Please open a new issue with more information and we'll try to help you out.
