### ISSUE TITLE
how to handle foreground push notification and show the badge ?

### ISSUE THREAD

**Issue by MahmoudAbunaji** [firebase/quickstart-ios#256]
**I'm using google firebase document
I receive Notification when app is in background but  my issue is in foreground as the following method :** 

// Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let userInfo = notification.request.content.userInfo
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        
//        completionHandler(UIBackgroundFetchResult.newData)

        
        // Change this to your preferred presentation option
        completionHandler([])
    }

**completionHandler([])   <- what it should be to show the notification ?**

**Comment by morganchen12** [comment]
Please move this question to StackOverflow.
