### ISSUE TITLE
Cannot Upload to App Store

### ISSUE THREAD

**Issue by adf47** [firebase/quickstart-ios#257]
HI all, 

I keep getting this error when uploading to the App Store:

iTunes Store Operation Failed. No suitable application records were found. Verify your bundle identifer 'org.cocoapods.GoogleToolboxForMac'

Any ideas as to what might be going wrong?

**Comment by morganchen12** [comment]
If you change your bundle identifier to something that's not a framework bundle identifier, does it fix the issue?

**Comment by adf47** [comment]
@morganchen12 I get the same exact error

**Comment by morganchen12** [comment]
You should be using the bundle identifier that you have provisioned in iTunesConnect. Take a look at [this](http://stackoverflow.com/questions/30110757/xcode-error-when-uploading-to-app-store-no-suitable-application-records-were-f) StackOverflow answer for more information.

I'm going to close this bug as this isn't a Firebase-specific error.

**Comment by adf47** [comment]
@morganchen12 I have seen this already. The bundle identifier is the same as the one I have set up on iTunes connect. This 'org.cocoapods.GoogleToolboxForMac' that is giving me the error is from the pod file, the pods.xcproject. Am I supposed to set up a bundle identifier for all of the pods I am using in itunes connect?

**Comment by morganchen12** [comment]
Looks like there's no good discussion around this, gonna reopen and hopefully this thread will turn into a helpful reference for others who run into the same issue.

I'm not sure what's causing this bug, but it could be CocoaPods related or just a bug in iTunesConnect.

**Comment by morganchen12** [comment]
@adf47 is this still an issue?

If you make a blank new project with Firebase and try uploading it, does it fail as well?
