### ISSUE TITLE
Unresolved identifier 'FIRDynamicLinkComponents'

### ISSUE THREAD

**Issue by MarksCode** [firebase/quickstart-ios#259]
Trying to use Dynamic Links in Swift 3 project. I've pod installed 'Firebase' and 'Firebase/DynamicLinks' as well as 'import Firebase' in my viewController. Copied the code in the [documentation](https://firebase.google.com/docs/dynamic-links/ios/create).

Getting the error:

> Use of unresolved identifier 'FIRDynamicLinkComponents'

on this line:

`let components = FIRDynamicLinkComponents(link: link, domain: domain)`

Is Dynamic Links working in Swift3/iOS10?

**Comment by morganchen12** [comment]
Can you upload your project?

**Comment by MarksCode** [comment]
My repo is private but I just made this one with the same configuration as mine: https://github.com/MarksCode/TestProj

**Comment by morganchen12** [comment]
The sample you uploaded doesn't compile, but after deleting all the code with errors and running `pod update` I'm able to build and run the project just fine.

If you haven't already, update your `cocoapods` installation to `1.2.1` and try again.

**Comment by MarksCode** [comment]
@morganchen12 I updated to 1.2.1  and ran pod update, my Dynamics Links is now v1.4. However, it still doesn't work. Can you check out my repository by any chance please?

**Comment by morganchen12** [comment]
I did. Your `ViewController.swift` file has a bunch of syntax errors. [This](https://github.com/MarksCode/TestProj/blob/master/TestProj/ViewController.swift#L14) isn't a valid way of initializing a dictionary, nor does it convey any type information.

Sometimes the Xcode gives stale or meaningless error messages, but once you fix all your syntax errors your code should compile fine.

**Comment by MarksCode** [comment]
In my actual project's repository I fixed the dictionary syntax errors. The only ones I'm getting are the original error I posted. On the line `let components = FIRDynamicLinkComponents(link: link, domain: domain)` I'm getting `Use of unresolved identifier 'FIRDynamicLinkComponents'`. If I give you access rights to my repo can you please take a look?

**Comment by morganchen12** [comment]
No, please don't do that. GitHub's issue tracker isn't really for 1:1 help. If you've got an issue and can post its cause here, then I'm happy to help you as the solution will serve as a reference for others who run into the same issue, but if you seek help in private then suddenly that reference doesn't exist and it's much less valuable time spent for open source maintainers.

In your case the dictionary syntax issue wasn't the only issue, but the first of many syntax issues. 

If you clean (Cmd+Shift+K) and rebuild, does Xcode produce more useful errors?

**Comment by rostopira** [comment]
Clean build worked for me

**Comment by bpdubey87** [comment]
Hello , I am also having the same issue. I could not found the class 'FIRDynamicLinkComponents' while integrating FirebaseDynamicLink in iOS. Actually  'FIRDynamicLinkComponents'  class is not available in the framework also. My pod version is 1.2.1. Please help me with this issue

**Comment by MarksCode** [comment]
@bpdubey87 I've had no luck solving it, let me know if you find out.

**Comment by bpdubey87** [comment]
@MarksCode  I just solved the issue in following step:-
1. GO to project path where pod file is present.
2. run 'pod update' in terminal
3. again add    pod 'Firebase/DynamicLinks' in pod file
4. run command 'pod install'
5. You will see one extra class 'FDLURLComponents.h' inside the framework.

If you are having still issue then I am attaching class here :- 
[FDLURLComponents.h.zip](https://github.com/firebase/quickstart-ios/files/991973/FDLURLComponents.h.zip)

**Comment by MarksCode** [comment]
@bpdubey87 I'll try that. I thought I already installed pod 'Firebase/DynamicLinks' before but maybe they changed something.
