### ISSUE TITLE
Removing Listeners

### ISSUE THREAD

**Issue by troy21688** [firebase/quickstart-ios#260]
After learning Firbease for Android, I learned to add Firebase subscriptions to onStart() and to remove at onStop().

What is the counterpart in Swift/iOS? Obviously there is the viewDidLoad() method, but I wanted to confirm where to subscribe and unsubscribe accordingly.

**Comment by morganchen12** [comment]
`viewWillAppear(_:)` and `viewWillDisappear(_:)` are good places for this.

This applies to most update models and not just Firebase, though--Please refrain from using the issue tracker as a place for asking generic iOS questions.
