### ISSUE TITLE
FIRStorageDownloadTask cancel  Problem

### ISSUE THREAD

**Issue by LeoTuring** [firebase/quickstart-ios#262]
```Swift
var task : FIRStorageDownloadTask?

func download() {
   self.task = imageRef.dataWithMaxSize(downloadSize, completion:{ (data: NSData?, error: NSError?) in
      // self.task cancel but this block data always return 
  )
}
```
**How cancel this task ? ? ?**

**Comment by morganchen12** [comment]
The block is always invoked. In a case where the task is cancelled, the block will be invoked with an error representing the cancellation. The task is still successfully cancelled.

您發現`completion`調用以後`task`還沒撤消了嗎？

**Comment by LeoTuring** [comment]
正在进行下载的时候 可以cancel掉吗? 
目前 task 即使cancelled 之后, data依然会返回.

**Comment by morganchen12** [comment]
>正在进行下载的时候 可以cancel掉吗?
應該可以。

>目前 task 即使cancelled 之后, data依然会返回.
那`cancel`調用以後`completion`裡`data`和`error`全都不是`nil`嗎？
這好像是我們Firebase的故障。
