### ISSUE TITLE
Multiple accounts with 1 email

### ISSUE THREAD

**Issue by MarksCode** [firebase/quickstart-ios#264]
I have my firebase authentication set to prevent multiple accounts for the same email, but it doesn't seem to be doing that. See following pictures:

1) http://imgur.com/jAhjSSo

2) http://imgur.com/tlYOLeZ

Is this a known issue?

**Comment by MarksCode** [comment]
By the way, I made a SO question about this issue, should I delete it?

http://stackoverflow.com/questions/43813595/two-accounts-made-with-same-email-bug-firebase-auth

**Comment by samtstern** [comment]
@MarksCode let's discuss on StackOverflow

**Comment by morganchen12** [comment]
Closing here, we'll keep the StackOverflow ticket updated if there's news on our end.
