### ISSUE TITLE
google.plist file is missing in Storage example!

### ISSUE THREAD

**Issue by Jkurbs** [firebase/quickstart-ios#27]
could not find a valid GoogleServices-Info.plist in your project.

**Comment by grantkemp** [comment]
You need to download your Google Services from your account when you create an app in the Firebase admin site.

**Comment by paulb777** [comment]
It would be nice if the GoogleServices-Info.plist download instructions and any other prerequisite instructions for opening, building  and running from xcode project file were included in the README.md

**Comment by iulukaya** [comment]
https://firebase.google.com/docs/ios/setup#add_firebase_to_your_app
