### ISSUE TITLE
Pod update delete dependencies from firebase messaging

### ISSUE THREAD

**Issue by karmol19** [firebase/quickstart-ios#271]
Hello, i have the next problem:

I had to update my pod with pod update, but when i had update cocoapods deleted dependencies from Firebase/messaging 
![captura de pantalla 2017-05-19 a la s 17 48 46](https://cloud.githubusercontent.com/assets/4308122/26269647/9cfe8d5a-3cbb-11e7-97a8-b1d80ffe1488.png)

When these frameworks were deleted, my project  could not compile for this
![captura de pantalla 2017-05-19 a la s 17 57 48](https://cloud.githubusercontent.com/assets/4308122/26269824/bcd75458-3cbc-11e7-842f-d54008004f79.png)
 frameworks

I've tried:
Add pod IphoneUtilities in podfile getting the error: DuplicateSymbols for Reachability,
Clean project and delete derived data
Remove cocoapod for my project and install again
pod update again
Update cocoapods version to 1.2.1
Update Git to 2.13.0

In all cases, i always getting the some result

I hope they could advise me on how to solve this problem

**Comment by morganchen12** [comment]
Can you upload a sample project that reproduces this issue? Can you share your Podfile as well?

**Comment by karmol19** [comment]
In the link you can download the sample project with the pods that i use.  

https://bitbucket.org/karmol19/example-pod/get/e31de402436a.zip

**Comment by morganchen12** [comment]
Your project has a number of issues.

- Your project contains Swift, but `use_frameworks!` isn't enabled in your Podfile.
- Your project is missing some dependencies and doesn't compile out of the box.
- There are spurious `-framework` flags in your project's `Other Linker Flags`. Frameworks listed here that are not linked will lead to linker errors; duplicate frameworks listed here will lead to duplicate class definitions at runtime.
- Some dependencies aren't managed through CocoaPods and are instead copy-pasted into the source of your project. I _highly_ encourage you avoid doing this, as pods may have dependencies on frameworks that have been pasted into your project whose versions CocoaPods cannot resolve.

Also, make sure you're using the latest version of CocoaPods (`1.2.1` as of this comment) and Xcode.
