### ISSUE TITLE
Can't create the CMF token from a device token.

### ISSUE THREAD

**Issue by KazuyaTomita** [firebase/quickstart-ios#277]
Now I am trying to create the CMF token from the device token in iOS by using firebase.  However, there is a big block in translating the device token into the CMF token.  My approach is like this.  In the 
`application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)`, I made attempts of both `InstanceID.instanceID().setAPNSToken(deviceToken, type: InstanceIDAPNSTokenType.sandbox)` and `Messaging.messaging().setAPNSToken(deviceToken, type: .prod)`. However, still I couldn't get the CMF token.  What should I do?  I imported the `Firebase` module.  What in the world is lacking?

**Comment by KazuyaTomita** [comment]
Sorry

**Comment by rsattar** [comment]
Glad you found the issue. You should also just have to set:

    Messaging.messaging().apnsToken = deviceToken

And not have to set the type to `.prod` or `.sandbox`. It'll use automatic detection of the token type.

**Comment by KazuyaTomita** [comment]
Now I am lacking:
`Messaging.messaging().apnsToken = deviceToken`
However, it works.  Why do we need that?
