### ISSUE TITLE
FIRApp.configure asking for 'GoogleService-Info.plist'.

### ISSUE THREAD

**Issue by alokc83** [firebase/quickstart-ios#28]
I dont see anything on firebase.google.com nor instructions provided there are relevant. 
I am getting following this error "Could not locate configuration file: 'GoogleService-Info.plist'."
when do FIRApp.configure.

**Comment by fattomhk** [comment]
Maybe here: https://firebase.google.com/docs/ios/setup#add_firebase_to_your_app
