### ISSUE TITLE
Where is shouldEstablishDirectChannel?

### ISSUE THREAD

**Issue by bakeddean** [firebase/quickstart-ios#283]
Hi, I'm trying to figure-out where this property is. It is referred to in the examples and reference, but the compiler says there is no member named shouldEstablishDirectChannel, and it is not in the publicly available header. I've tried:
 
```
Messaging.messaging().shouldEstablishDirectChannel = true
FIRMessaging.messaging().shouldEstablishDirectChannel = true
```
Our server sends notification and data messages, but nothing shows up in:
```
func applicationReceivedRemoteMessage(_ remoteMessage: FIRMessagingRemoteMessage) 
```

**Comment by paulb777** [comment]
Have you updated to Firebase 4.0 and FirebaseMessaging 2.0? https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/Public/FIRMessaging.h#L303

**Comment by bakeddean** [comment]
Thanks. I see it is in the latest SDK, but I haven't be able to install Firebase 4.0 and FirebaseMessaging 2.0 via Cocoapods without first deleting the 'Google/SignIn' pod we are using. There seems to be an inter-dependency that prevents  pod update from installing these latest versions. When I installed the 'Google/SignIn' pod after installing the latest Firebase pods, it installed a down-graded version of 'Google/SignIn' and would not allow that to be updated. Hmm ... still working on this one.

**Comment by paulb777** [comment]
Google/SignIn should not have a dependency on Firebase - https://github.com/CocoaPods/Specs/blob/master/Specs/d/4/0/GoogleSignIn/4.0.2/GoogleSignIn.podspec.json.

Are you able to share your Podfile?

**Comment by bakeddean** [comment]
Some progress.
It seems 'Google/SignIn' and 'GoogleSignIn' are not freely interchangeable.
I created an empty project with just the 'GoogleSignIn' pod, and these pods are installed:
```
Using GTMOAuth2 (1.1.4)
Using GTMSessionFetcher (1.1.10)
Using GoogleSignIn (4.0.2)
Using GoogleToolboxForMac (2.1.1)
``` 
And if I create an empty project and just install the 'Google/SignIn' pod, these pods are installed:
```
Using FirebaseAnalytics (3.9.0)
Using FirebaseCore (3.6.0)
Using FirebaseInstanceID (1.0.10)
Using GTMOAuth2 (1.1.4)
Using GTMSessionFetcher (1.1.10)
Using Google (3.0.3)
Using GoogleSignIn (4.0.2)
Using GoogleToolboxForMac (2.1.1)
```
The Firebase dependencies prevent the most recent version of 'Firebase/Messaging' from being installed. Replacing 'Google/SignIn' with 'GoogleSignIn' did allow me to update my FirebaseMessaging pod. The signin documentation references the 'Google/SignIn' pod,
https://developers.google.com/identity/sign-in/ios/start-integrating
and I had to change:
```
GGLContext.sharedInstance().configureWithError(&configureError) 
```
to
```
GIDSignIn.sharedInstance().clientID = "<MY_CLIENT_ID>.apps.googleusercontent.com"
```
I'm still having problems with the GoogleService-Info.plist files. Do I need to have one of these for GoogleSignIn and another for Firebase, or can I use the same plist file?

**Comment by paulb777** [comment]
Good find!  Your conclusion make sense, since the Google pod has not been kept up to date and will soon be deprecated. The GoogleSignIn pod should be directly referenced, instead of via a Google pod subspec.

You should be able to use the same GoogleService-Info.plist for both Firebase and GoogleSignIn.

**Comment by bakeddean** [comment]
Hi, more progress. GoogleSignIn is working ok and the latest messaging pods are installed. We are currently using Firebase notification messages both for live chat and status notifications, but are having real problems with the reliability of APNS (I know that they don't guarantee timely delivery or even delivery at all). The Android dev's are using data-messaging and their app is working well.

After lots of experimenting with sending data-messages with Postman I believe I am closer.
If I send a data-message (no notification field), with "content_available" : true, my app receives these  in:
```
application(_ application: UIApplication,
                     didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)
```
in both the foreground & background. I can process these successfully and update the app or post a Local Notification if in the background. The function
```
func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage)
```
Is not called, which is fine.
So can you confirm that this is using the Firebase socket connection in both the foreground & background and not the (unreliable APNS)? I've read the documentation multiple times but I'm still not clear on this. The Android documentation seems a bit clearer on this.

Thanks.

**Comment by bakeddean** [comment]
And also, if not using APNS, does this mean I don't need to bother uploading an APNs Authentication Key or APNs Certificate?

**Comment by rsattar** [comment]
On iOS, it's not possible to maintain a socket connection when the app is backgrounded, so data messages are sent over APNs as (unreliable) silent notifications (e.g "content_available"). For that reason, you'll want an APNs Authentication Key or Certificate.

**Comment by bakeddean** [comment]
Yeah, I realise iOS is pretty restrictive when it comes to background processes.
So it sounds like the in the scenario I'm describing, the Firebase server detects whether the socket connection is established, and directs messages accordingly (socket/APNS). And I presume this means the application didReceiveRemoteNotification ... method is swizzled also.

So this is my understanding of how things work at the moment (assuming swizzling enabled) :
  
|App-state |Data message|Data message<br>(content_available=true)<br>|Data + notification message|
|---|---|---|---|
|foreground|Channel: FCM<br>Method: 1|Channel: FCM<br>Method: 2|Channel: APNS<br>Method: 3|
|background| - |Channel: APNS<br>Method: 2|Channel: APNS<br>Method: 3|
|terminated| - |-|-|

Methods:

|Number|Protocol|Method|
|---|--------|--------|
|1|Messaging Delegate|```func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage)```|
|2|UIApplicationDelegate|```optional func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)```|
|3|UNUserNotificationCenterDelegate|```optional func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)```|

Notes:

Data messages require ```shouldEstablishDirectChannel = true```

**Comment by bakeddean** [comment]
And I see that a data-message with content_available = true, will only get executed in the background if the user has enabled Background App Refresh (Settings > General > Background App Refresh), where as a notification message doesn't have this restriction.

**Comment by bakeddean** [comment]
Can anybody tell me if Firebase supports a mode where the socket connection to FCM is used in the foreground, and a regular (not silent) push notification is used in the background? Thanks.

**Comment by bakeddean** [comment]
Getting of topic here so I'll close and move to a new issue.
