### ISSUE TITLE
Firebase shortened dynamic link not extracting the original link in iOS app

### ISSUE THREAD

**Issue by rajeevfp** [firebase/quickstart-ios#284]
Firebase shortened dynamic link is opening app but unable to fetch the original link which is used to create dynamic link in iOS device.  I tried to fetch the original url from the below method. except the incoming url rest of the objects are **nil**. App id prefix and bundle id is verified in firebase console. surprisingly in iOS simulator original link can be extracted.

`- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *))restorationHandler {`

**Comment by morganchen12** [comment]
This should be fixed in the latest version of Firebase (4.8.1).
