### ISSUE TITLE
FCM Push notification is not working in Background 

### ISSUE THREAD

**Issue by naga1985** [firebase/quickstart-ios#286]
Hi 
I am new to swift development. Now i am working on FCM with push notifications, my application working fine. 
But issue is when application in Background state FCM notification not getting. when the Application in Fourground Getting the FCM notifications 
in Four Ground 
![test](https://cloud.githubusercontent.com/assets/29070536/26600218/de463a34-4598-11e7-90ef-5eb414751c8d.jpeg)

Back ground I am getting json msg 
![screen shot 2017-05-30 at 11 44 13 pm](https://cloud.githubusercontent.com/assets/29070536/26600020/252457ca-4598-11e7-982b-8e985a4558e8.png)
my code is 

import UIKit
import UserNotifications

import Firebase

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
    let gcmMessageIDKey = "gcm.message_id"
    
    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        // Register for remote notifications. This shows a permission dialog on first run, to
        // show the dialog at a more appropriate time move this registration accordingly.
        // [START register_for_notifications]
        if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
        } else {
            let settings: UIUserNotificationSettings =
                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            application.registerUserNotificationSettings(settings)
        }
        
        application.registerForRemoteNotifications()
        
        // [END register_for_notifications]
        FirebaseApp.configure()
        
        // [START set_messaging_delegate]
        Messaging.messaging().delegate = self
        // [END set_messaging_delegate]
        return true
    }
    
    // [START receive_message]
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
        // If you are receiving a notification message while your app is in the background,
        // this callback will not be fired till the user taps on the notification launching the application.
        // TODO: Handle data of notification
        // With swizzling disabled you must let Messaging know about the message, for Analytics
        Messaging.messaging().appDidReceiveMessage(userInfo)
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        
        // Print full message.
        print(userInfo)
       // completionHandler()
       
       
        
      
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
      
        switch application.applicationState {
            
        case .inactive:
            print("Inactive")
            //Show the view with the content of the push
            completionHandler(.newData)
            
        case .background:
            print("Background")
            //Refresh the local model
            completionHandler(.newData)
            
        case .active:
            print("Active")
            //Show an in-app banner
                              //
            
             completionHandler(UIBackgroundFetchResult.newData)
        }
        
        // If you are receiving a notification message while your app is in the background,
        // this callback will not be fired till the user taps on the notification launching the application.
        // TODO: Handle data of notification
        // With swizzling disabled you must let Messaging know about the message, for Analytics
        // Messaging.messaging().appDidReceiveMessage(userInfo)
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        print("application is running")
       
    }
//    // [END receive_message]
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("Unable to register for remote notifications: \(error.localizedDescription)")
    }
    
    // This function is added here only for debugging purposes, and can be removed if swizzling is enabled.
    // If swizzling is disabled then this function must be implemented so that the APNs token can be paired to
    // the FCM registration token.
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("APNs token retrieved: \(deviceToken)")
        
        // With swizzling disabled you must set the APNs token here.
        // Messaging.messaging().apnsToken = deviceToken
    }
}

// [START ios_10_message_handling]
@available(iOS 10, *)
extension AppDelegate : UNUserNotificationCenterDelegate {
    
    // Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let userInfo = notification.request.content.userInfo
        
        // With swizzling disabled you must let Messaging know about the message, for Analytics
        Messaging.messaging().appDidReceiveMessage(userInfo)
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        // Change this to your preferred presentation option
        completionHandler([])
     // completionHandler()
     
       }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        completionHandler()
      
    }
}
// [END ios_10_message_handling]

extension AppDelegate : MessagingDelegate {
    // [START refresh_token]
    func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
        print("Firebase registration token: \(fcmToken)")
    }
    // [END refresh_token]
    // [START ios_10_data_message]
    // Receive data messages on iOS 10+ directly from FCM (bypassing APNs) when the app is in the foreground.
    // To enable direct data messages, you can set Messaging.messaging().shouldEstablishDirectChannel to true.
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("Received data message: \(remoteMessage.appData)")
    }
    // [END ios_10_data_message]
}

please help me..

**Comment by rsattar** [comment]
Hi @naga1985,

It seems like your are receiving push notifications in the background, but they are not displaying? Can you confirm the app settings in Settings.app > Notifications > TestPushNotification, that notifications are shown in the Lock Screen and are shown as Banners?

**Comment by naga1985** [comment]
Hi @rsattar 
notifications are showing when screen lock 
how can i display the banners when application in Back ground  mean application am using

**Comment by naga1985** [comment]
Hi @rsattar  
when i send the notification in screen lock it is showing this msg 
![p_20170531_010406](https://cloud.githubusercontent.com/assets/29070536/26601491/a520e948-459d-11e7-86e4-c6c9823a6908.jpg)

**Comment by rsattar** [comment]
Okay great. So to confirm, you want to show the iOS notification when the app is running in the _foreground_, but nothing shows, right?

If that's the case, iOS 10.0+ lets you use the UserNotifications framework to let you do this easily. On iOS 9 and below, nothing will happen, and you have to implement your own UI to show the notification while the app is running in the foreground.

For iOS 10.0+, in `willPresentNotification:` you need to return the types you want:

    // Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                            willPresent notification: UNNotification,
                            withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        // Change this to your preferred presentation option
        completionHandler([.alert, .badge, .sound]) // <-----
    }

**Comment by naga1985** [comment]
Hi @rsattar  
problem is resolved 
FCM notification is getting in foreground.
thank you very much ;)

**Comment by naga1985** [comment]
Hi @rsattar  
FCM is working fine in ios 10+ , foreground and Background notification are showing. when i am working with ios 9 Back ground Working fine 
foreground is not showing any notification, How can show notification in IOS 9

**Comment by rsattar** [comment]
Hi @naga1985, as I mentioned in [the last comment](https://github.com/firebase/quickstart-ios/issues/286#issuecomment-304992090), this is something you'll have to build yourself. Usually by receiving the remote notification in `application:didReceiveRemoteNotification:fetchCompletionHandler:` and create a `UILocalNotification` with the same contents of the push notification.

**Comment by minamichel** [comment]
hi sir i am receiving the push notification in the console but i didnt receive it  as banner i dono y ???
 AnyHashable("from"): 401305107427, AnyHashable("collapse_key"): com.imperialcreation.Shhhhh]
Received data message: [AnyHashable("notification"): {
    body = HIIIIIII;
    e = 1;
}, AnyHashable("from"): 401305107427, AnyHashable("collapse_key"): com.imperialcreation.Shhhhh]

**Comment by rpinto18** [comment]
@naga1985 help me please, write me to email rapiaven1890 @ gmail.com

**Comment by thallasiva** [comment]
Fcm update plugin with onNotification not navigate to new page in ionc  3.please help me
