### ISSUE TITLE
how do I remember a users login? :)

### ISSUE THREAD

**Issue by kahnary** [firebase/quickstart-ios#288]
Is there a better way to make a user automatically login to the app as long as they have logged in in the past; other than saving their login details directly to the storage which may be insecure?

Thanks

**Comment by morganchen12** [comment]
If you're on iOS, you should be storing user credentials in Keychain. The security details are left to Apple.

Take a look at the [Keychain Services Programming Guide](https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html).
