### ISSUE TITLE
Dynamic Links disabled on iOS 9

### ISSUE THREAD

**Issue by viralmoonlight** [firebase/quickstart-ios#289]
![dynamiclink forwarding](https://cloud.githubusercontent.com/assets/19497139/26688861/d437b4f8-46c1-11e7-9586-c1be5c4d3b8c.jpg)

On the image provided, If I were to click ‘linkedin.com,’ (at the top right corner) it would open up Safari and permanently disable Universal Links for my device. There are few ways to re-enable them, but for all intents and purposes, a user would never figure it out.

Is there a way to get around this ?

**Comment by morganchen12** [comment]
No, this is an iOS behavior that exists outside of Firebase. The rationale is if the user sought to use the website over the app for a given link, then the system should remember that preference.

**Comment by rsattar** [comment]
@morganchen12 is right, and unfortunately it's not an easy-to-recover-from action. The best thing I've found is to long-press on a linkedin.com link in Safari, and you'll get an option to "Open in app". That resets the behavior, enabling universal links for that domain.
