### ISSUE TITLE
FCM background messages

### ISSUE THREAD

**Issue by cinatic** [firebase/quickstart-ios#293]
Hello,

just a quick questions. Can my ios app receive "remote"/"payload only" notification when the app is forced quit / killed?

Thanks best regardas
Florijan

**Comment by ppamorim** [comment]
No. It's a iOS limitation. Your push notification goes to a queue if it is a silent notification. If it is not, like a message, it will work.

**Comment by cinatic** [comment]
this is a very confusing thing compared to android, ty for clarification
