### ISSUE TITLE
Unable to submit ad-free application with FirebaseAnalytics.framework (IDFA rejection)

### ISSUE THREAD

**Issue by bushev** [firebase/quickstart-ios#298]
Hello, guys!

I'm, trying to submit my application to AppStore.

1. If I click "Yes" near "Do you use IDFA" iTunes expected to check one of these options:
![image](https://user-images.githubusercontent.com/7535766/27287852-9e18dbae-550d-11e7-9fa1-c91b2b888963.png)

I can't move forward with not options selected. But if I clicked some options iTunes reviewers asked me to specify where ads are available in the app. (in short: no ads - no IDFA in the app)

2. If I click to "No", iTunes detects that IDFA is used in the application, so I can't move forward.

Problem: I **unable to upload an application with FirebaseAnalytics without a real advertisements**. (https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SubmittingTheApp.html#//apple_ref/doc/uid/TP40011225-CH33-SW8)

--

I used Google Analytics before FirebaseAnalytics (https://github.com/danwilson/google-analytics-plugin/issues/218). GA uses `AdSupport.framework` dynamically. So I was able to remove `AdSupport.framework` and GS still works without Gender/Age/etc tracking well. I don't want to switch back to GA, but I can't use FirebaseAnalytics too...

**Comment by baolocdo** [comment]
Have you tried clicking on the last 2 options? I think they are the appropriate ones. You don't need to serve ads in your app to attribute them. Sometimes, a Search Ad (say Apple Store Search Ads) can lead to an app installation and the IDFA helps attributing the installation to that Search Ad.

**Comment by bushev** [comment]
Thanks, I will try to submit.

**Comment by morganchen12** [comment]
@bushev closing this issue since it's staled, feel free to reopen if you're still running into App Store issues.

**Comment by iad24** [comment]
@bushev im on situation now. Did Apple accepted ur app after doing what @baolocdo said?
Thanks
