### ISSUE TITLE
Swift: Use of unresolved identifier 'Use of unresolved identifier 'PhoneAuthProvider''

### ISSUE THREAD

**Issue by machouz** [firebase/quickstart-ios#300]
I can't compile because the compiler throw error Use of unresolved identifier 'PhoneAuthProvider'.
I am
- Using Firebase (3.17.0)
- Using FirebaseAnalytics (3.9.0)
- Using FirebaseAuth (3.1.1)
- Using FirebaseCore (3.6.0)
- Using FirebaseDatabase (3.1.2)
```
import UIKit
import Firebase
class PhoneAuthentificationViewController:UIViewController{
    @IBOutlet weak var phone_number:UITextField!
    
    @IBAction func validate_phone(_ sender: UIButton) {
        PhoneAuthProvider.provider().verifyPhoneNumber(phoneNumber) { (verificationID, error) in
            if let error = error {
                self.showMessagePrompt(error.localizedDescription)
                return
            }
    
         }
    }
}
```
Google and Facebook authentification work very well
Thank you for your help

**Comment by paulb777** [comment]
The quickstarts are integrated with the current Firebase versions. Please update to Firebase 4.x.

**Comment by machouz** [comment]
This is my Podfile how can I do to update Firebase:
```
target 'MyApp' do
  use_frameworks!

  # Pods for Shopinzon
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'GooglePlaces'
end
```

**Comment by paulb777** [comment]
Do not use the deprecated Google pod.  Change `pod 'Google/SignIn'` to `pod 'GoogleSignIn'`

**Comment by machouz** [comment]
Thank you for your help I Change `pod 'Google/SignIn' ` to  `pod 'GoogleSignIn'` but this doesn't make cocoa pods update Firebase to 4.x.
So I am still using 
- Using Firebase (3.17.0)
- Using FirebaseAnalytics (3.9.0)
- Using FirebaseAuth (3.1.1)
- Using FirebaseCore (3.6.0)
- Using FirebaseDatabase (3.1.2)
- Using FirebaseInstanceID (1.0.10)

**Comment by machouz** [comment]
It's fine thank you I change my pod file to this
This is my Podfile how can I do to update Firebase:
```
target 'MyApp' do
  use_frameworks!

  # Pods for App
  pod 'Firebase', '~> 4.0'
  pod 'FirebaseCore', '~> 4.0'
  pod 'FirebaseAuth', '~> 4.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'GoogleSignIn'
  pod 'GooglePlaces'
end
```

**Comment by SirOlaoluwani** [comment]
I cant compile because xcode throws Use of unresolved identifier 'Auth'. I am using 

- Using Firebase (4.6.0)
- Using FirebaseAnalytics (4.0.5)
- Using FirebaseAuth (4.3.2)
- Using FirebaseCore (4.0.11)
- Using FirebaseDatabase (4.1.1)
- Using FirebaseInstanceID (2.0.6)
- Using FirebaseStorage (2.0.2)
- Using GTMSessionFetcher (1.1.12)
- Using GoogleToolboxForMac (2.1.3)
- Using leveldb-library (1.20)
- Using nanopb (0.3.8)

```
import UIKit
import Firebase

@objc func handleRegister(){
        guard let email = emailTextField.text, let password = passwordTextField.text else  {
            print("Form is not valid")
            return
        }
        Auth.auth().createUser(withEmail: email, password: password) { 
            (user, error) in
            if let error = error {
                print(error)
                return
            }
            print("\(user!.email!) created")
        }
    }

```

I am new to swift.
Please help!! 
Thanks.

**Comment by mahirahmed691** [comment]
@SirOlaoluwani i am getting the exact same error, did you manage to fix it?

**Comment by morganchen12** [comment]
`import FirebaseAuth`
