### ISSUE TITLE
TableView not reloading anymore after leaving and coming back to it

### ISSUE THREAD

**Issue by warhost** [firebase/quickstart-ios#301]
Hey,

I have a tableview bound to a query, and doing live updates to the database shows the child immediately in the tableview, however only as long as I am still on the first "instance" of that tableview. When I leave to a different view and come back, there are no more updates to it. I am following the practices from the [example](https://github.com/firebase/quickstart-ios/blob/master/database/DatabaseExampleSwift/PostListViewController.swift) like such:

```
func getQuery() -> DatabaseQuery {
    let myTopPostsQuery = (ref.child("users")).child(getUid()).child("data").queryOrderedByPriority()
    return myTopPostsQuery
}

override func viewDidLoad() {
    super.viewDidLoad()
    
    ref = Database.database().reference()
    
    dataSource = FUITableViewDataSource.init(query: getQuery()) { (tableView, indexPath, snap) -> MGSwipeTableCell in
        let cell = tableView.dequeueReusableCell(withIdentifier: "linksCellident", for: indexPath) as! LinksCell
        
        
        guard let post = LinksPost.init(snapshot: snap) else { return cell }
        
        cell.ogImageView.sd_setImage(with: URL(string: post.ogImageURL))
        cell.titleLabel.text = post.title
        cell.urlLabel.text = post.url
        
        return cell
    }
    
    dataSource?.bind(to: linksTableView)
    linksTableView.delegate = self
}

override func viewWillAppear(_ animated: Bool) {
    self.linksTableView.reloadData()
}
override func viewWillDisappear(_ animated: Bool) {
    getQuery().removeAllObservers()
}
```

When the view disappears, the oberserer is removed, but doesn't it need to be "re-attached" in the `viewWillAppear`? Or is that done automatically by reloading the data? Anyway, it doesn't reload the data.

**Comment by morganchen12** [comment]
You should move this issue to the FirebaseUI-iOS repository.
