### ISSUE TITLE
i can't cancel "setValue" request by the purgeOutstandingWrites()

### ISSUE THREAD

**Issue by tkachV** [firebase/quickstart-ios#302]
Ok. I check network link condition on my iPhone, set to 100% lost, and tryed send "setValue" request. Then, after by the 10 seconds, i cancel request by the "FIRDatabase.database().purgeOutstandingWrites() ". Completion of "setValue" Is called with an error. But when i change condition of Network link conditioner to Wi-fi, firebase automatically resend previously canceled request.

Why this happens?

**Comment by morganchen12** [comment]
Hey, please file this over at firebase/firebase-ios-sdk.
