### ISSUE TITLE
Cant build under iOs

### ISSUE THREAD

**Issue by isipisi281** [firebase/quickstart-ios#304]
Mybe somone could help me with this buld error?

`Undefined symbols for architecture arm64:
  "_nano_encode_repeated_string", referenced from:
      _firapb_set_string_filter_encoders in FirebaseAnalytics(firapb_string_filter_encoder_f42092f1ba2fa9d559b019faba84cc6a.o)
  "_nano_encode_repeated_uint64", referenced from:
      _firapb_set_result_data_encoders in FirebaseAnalytics(firapb_result_data_encoder_373a816d02f878f3857bb6d0ba8021a2.o)
  "_nano_encode_string", referenced from:
      _firapb_set_event_encoders in FirebaseAnalytics(firapb_event_encoder_0c153acc04fdbe51594c94848d0368b0.o)
      _firapb_set_event_config_encoders in FirebaseAnalytics(firapb_event_config_encoder_b76c27c645bff35f43c88abf3308a055.o)
      _firapb_set_event_filter_encoders in FirebaseAnalytics(firapb_event_filter_encoder_622d09830d24d1c5bf26be1b23f22eb3.o)
      _firapb_set_event_param_encoders in FirebaseAnalytics(firapb_event_param_encoder_fb98584a84d6fa363809bc8f957886cc.o)
      _firapb_set_filter_encoders in FirebaseAnalytics(firapb_filter_encoder_d28bfc4dffa3c4e05d93004539cd7c73.o)
      _firapb_set_measurement_bundle_encoders in FirebaseAnalytics(firapb_measurement_bundle_encoder_e7a36a02602e2fe11129d880f043b544.o)
      _firapb_set_measurement_config_encoders in FirebaseAnalytics(firapb_measurement_config_encoder_3181c28b3408a1f4c47b43a54bb352cc.o)
      ...
  "_pb_encode_tag_for_field", referenced from:
      _firapb_encode_repeated_audience in FirebaseAnalytics(firapb_audience_encoder_72c4ae8dbc6687ec3f3995499df06f95.o)
      _firapb_encode_repeated_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_encoder_6cbefb9d90fdddfe6d231875ed5b6a81.o)
      _firapb_encode_repeated_event in FirebaseAnalytics(firapb_event_encoder_0c153acc04fdbe51594c94848d0368b0.o)
      _firapb_encode_repeated_event_config in FirebaseAnalytics(firapb_event_config_encoder_b76c27c645bff35f43c88abf3308a055.o)
      _firapb_encode_repeated_event_filter in FirebaseAnalytics(firapb_event_filter_encoder_622d09830d24d1c5bf26be1b23f22eb3.o)
      _firapb_encode_repeated_event_param in FirebaseAnalytics(firapb_event_param_encoder_fb98584a84d6fa363809bc8f957886cc.o)
      _firapb_encode_repeated_filter in FirebaseAnalytics(firapb_filter_encoder_d28bfc4dffa3c4e05d93004539cd7c73.o)
      ...
  "_pb_encode_submessage", referenced from:
      _firapb_encode_repeated_audience in FirebaseAnalytics(firapb_audience_encoder_72c4ae8dbc6687ec3f3995499df06f95.o)
      _firapb_encode_repeated_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_encoder_6cbefb9d90fdddfe6d231875ed5b6a81.o)
      _firapb_encode_repeated_event in FirebaseAnalytics(firapb_event_encoder_0c153acc04fdbe51594c94848d0368b0.o)
      _firapb_encode_repeated_event_config in FirebaseAnalytics(firapb_event_config_encoder_b76c27c645bff35f43c88abf3308a055.o)
      _firapb_encode_repeated_event_filter in FirebaseAnalytics(firapb_event_filter_encoder_622d09830d24d1c5bf26be1b23f22eb3.o)
      _firapb_encode_repeated_event_param in FirebaseAnalytics(firapb_event_param_encoder_fb98584a84d6fa363809bc8f957886cc.o)
      _firapb_encode_repeated_filter in FirebaseAnalytics(firapb_filter_encoder_d28bfc4dffa3c4e05d93004539cd7c73.o)
      ...
  "_nano_two_pass_encoding", referenced from:
      _firapb_encode_audience in FirebaseAnalytics(firapb_audience_encoder_72c4ae8dbc6687ec3f3995499df06f95.o)
      _firapb_encode_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_encoder_6cbefb9d90fdddfe6d231875ed5b6a81.o)
      _firapb_encode_event in FirebaseAnalytics(firapb_event_encoder_0c153acc04fdbe51594c94848d0368b0.o)
      _firapb_encode_event_config in FirebaseAnalytics(firapb_event_config_encoder_b76c27c645bff35f43c88abf3308a055.o)
      _firapb_encode_event_filter in FirebaseAnalytics(firapb_event_filter_encoder_622d09830d24d1c5bf26be1b23f22eb3.o)
      _firapb_encode_event_param in FirebaseAnalytics(firapb_event_param_encoder_fb98584a84d6fa363809bc8f957886cc.o)
      _firapb_encode_filter in FirebaseAnalytics(firapb_filter_encoder_d28bfc4dffa3c4e05d93004539cd7c73.o)
      ...
  "_pb_read", referenced from:
      _firapb_decode_repeated_audience in FirebaseAnalytics(firapb_audience_decoder_8f2b7f20b40a4bf280eef0193d412fed.o)
      _firapb_decode_repeated_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_decoder_18719ebed44aede4ae1b5366ad8ab378.o)
      _firapb_decode_repeated_event in FirebaseAnalytics(firapb_event_decoder_b12f86d34ef07b7785c71e30f0f2bdec.o)
      _firapb_decode_repeated_event_config in FirebaseAnalytics(firapb_event_config_decoder_cde32d44905cc0603c340053f5acc2cc.o)
      _firapb_decode_repeated_event_filter in FirebaseAnalytics(firapb_event_filter_decoder_ec6b4dfae7767911eff6ccffc13f7296.o)
      _firapb_decode_repeated_event_param in FirebaseAnalytics(firapb_event_param_decoder_44c77717d048228f22bd72a81dca7cf5.o)
      _firapb_decode_repeated_filter in FirebaseAnalytics(firapb_filter_decoder_8f86ab1b6526e1718ca4d06d5548ff97.o)
      ...
  "_pb_istream_from_buffer", referenced from:
      _firapb_decode_audience in FirebaseAnalytics(firapb_audience_decoder_8f2b7f20b40a4bf280eef0193d412fed.o)
      _firapb_decode_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_decoder_18719ebed44aede4ae1b5366ad8ab378.o)
      _firapb_decode_event in FirebaseAnalytics(firapb_event_decoder_b12f86d34ef07b7785c71e30f0f2bdec.o)
      _firapb_decode_event_config in FirebaseAnalytics(firapb_event_config_decoder_cde32d44905cc0603c340053f5acc2cc.o)
      _firapb_decode_event_filter in FirebaseAnalytics(firapb_event_filter_decoder_ec6b4dfae7767911eff6ccffc13f7296.o)
      _firapb_decode_event_param in FirebaseAnalytics(firapb_event_param_decoder_44c77717d048228f22bd72a81dca7cf5.o)
      _firapb_decode_filter in FirebaseAnalytics(firapb_filter_decoder_8f86ab1b6526e1718ca4d06d5548ff97.o)
      ...
  "_nano_decode_repeated_string", referenced from:
      _firapb_set_string_filter_decoders in FirebaseAnalytics(firapb_string_filter_decoder_d279bdc4fc19ad96130cf7cf6c4931a9.o)
      _firapb_decode_string_filter in FirebaseAnalytics(firapb_string_filter_decoder_d279bdc4fc19ad96130cf7cf6c4931a9.o)
  "_pb_decode", referenced from:
      _firapb_decode_audience in FirebaseAnalytics(firapb_audience_decoder_8f2b7f20b40a4bf280eef0193d412fed.o)
      _firapb_decode_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_decoder_18719ebed44aede4ae1b5366ad8ab378.o)
      _firapb_decode_event in FirebaseAnalytics(firapb_event_decoder_b12f86d34ef07b7785c71e30f0f2bdec.o)
      _firapb_decode_event_config in FirebaseAnalytics(firapb_event_config_decoder_cde32d44905cc0603c340053f5acc2cc.o)
      _firapb_decode_event_filter in FirebaseAnalytics(firapb_event_filter_decoder_ec6b4dfae7767911eff6ccffc13f7296.o)
      _firapb_decode_event_param in FirebaseAnalytics(firapb_event_param_decoder_44c77717d048228f22bd72a81dca7cf5.o)
      _firapb_decode_filter in FirebaseAnalytics(firapb_filter_decoder_8f86ab1b6526e1718ca4d06d5548ff97.o)
      ...
  "_nano_set_float", referenced from:
      _firapb_populate_event_param_info in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_copy_event_param in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_populate_user_attribute_info in FirebaseAnalytics(firapb_user_attribute_b26a78b3bad2a90be2094a881eb97c61.o)
      _firapb_copy_user_attribute in FirebaseAnalytics(firapb_user_attribute_b26a78b3bad2a90be2094a881eb97c61.o)
  "_nano_set_bool", referenced from:
      _firapb_populate_audience_leaf_filter_result_info in FirebaseAnalytics(firapb_audience_leaf_filter_result_c413bff9da18cdddbaa73cbb5c7def80.o)
      _firapb_copy_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_c413bff9da18cdddbaa73cbb5c7def80.o)
      _firapb_populate_event_config_info in FirebaseAnalytics(firapb_event_config_afe76bf279850b3cd658ea098e943519.o)
      _firapb_copy_event_config in FirebaseAnalytics(firapb_event_config_afe76bf279850b3cd658ea098e943519.o)
      _firapb_populate_event_filter_info in FirebaseAnalytics(firapb_event_filter_8d99c35049e7e57e81018aa38d2a70f4.o)
      _firapb_copy_event_filter in FirebaseAnalytics(firapb_event_filter_8d99c35049e7e57e81018aa38d2a70f4.o)
      _firapb_populate_filter_info in FirebaseAnalytics(firapb_filter_7eec245959dd656f27dab5ec96e661f2.o)
      ...
  "_nano_set_double", referenced from:
      _firapb_populate_event_param_info in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_copy_event_param in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_populate_user_attribute_info in FirebaseAnalytics(firapb_user_attribute_b26a78b3bad2a90be2094a881eb97c61.o)
      _firapb_copy_user_attribute in FirebaseAnalytics(firapb_user_attribute_b26a78b3bad2a90be2094a881eb97c61.o)
  "_nano_decode_repeated_uint64", referenced from:
      _firapb_set_result_data_decoders in FirebaseAnalytics(firapb_result_data_decoder_91972d47cd4b944f4ef30100213edfe1.o)
      _firapb_decode_result_data in FirebaseAnalytics(firapb_result_data_decoder_91972d47cd4b944f4ef30100213edfe1.o)
  "_nano_set_string", referenced from:
      _firapb_copy_event in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_copy_event_config in FirebaseAnalytics(firapb_event_config_afe76bf279850b3cd658ea098e943519.o)
      _firapb_copy_event_filter in FirebaseAnalytics(firapb_event_filter_8d99c35049e7e57e81018aa38d2a70f4.o)
      _firapb_copy_event_param in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_copy_filter in FirebaseAnalytics(firapb_filter_7eec245959dd656f27dab5ec96e661f2.o)
      _firapb_copy_measurement_bundle in FirebaseAnalytics(firapb_measurement_bundle_9ebceb096cde88551a2b0dc40054ec9d.o)
      _firapb_copy_measurement_config in FirebaseAnalytics(firapb_measurement_config_4dcce8e8cf91365665d09449058a2326.o)
      ...
  "_NANOGetString", referenced from:
      _FIRAAudienceIsValidNumberFilter in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      _FIRAAudienceEvaluateNumberFilterWithDouble in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      _FIRAAudienceEvaluateNumberFilterWithDecimalNumber in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      -[FIRAMeasurement uploadData] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___104-[FIRAMeasurement filteredBundlesWithCompatibleAppID:resettableDeviceID:vendorDeviceID:bundlesToUpload:]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___72-[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:]_block_invoke.1388 in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ...
  "_nano_free_string", referenced from:
      _firapb_free_event_field in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_free_event_config_field in FirebaseAnalytics(firapb_event_config_afe76bf279850b3cd658ea098e943519.o)
      _firapb_free_event_filter_field in FirebaseAnalytics(firapb_event_filter_8d99c35049e7e57e81018aa38d2a70f4.o)
      _firapb_free_event_param_field in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_free_filter_field in FirebaseAnalytics(firapb_filter_7eec245959dd656f27dab5ec96e661f2.o)
      _firapb_free_measurement_bundle_field in FirebaseAnalytics(firapb_measurement_bundle_9ebceb096cde88551a2b0dc40054ec9d.o)
      _firapb_free_measurement_config_field in FirebaseAnalytics(firapb_measurement_config_4dcce8e8cf91365665d09449058a2326.o)
      ...
  "_nano_init_array_info", referenced from:
      _firapb_free_audience_field in FirebaseAnalytics(firapb_audience_498220436514c3e0ce1a58b1b945a3fa.o)
      _firapb_free_event_field in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_free_event_filter_field in FirebaseAnalytics(firapb_event_filter_8d99c35049e7e57e81018aa38d2a70f4.o)
      _firapb_free_measurement_batch_field in FirebaseAnalytics(firapb_measurement_batch_10215b5b58bc83d38472ad432bae300e.o)
      _firapb_free_measurement_bundle_field in FirebaseAnalytics(firapb_measurement_bundle_9ebceb096cde88551a2b0dc40054ec9d.o)
      _firapb_free_measurement_config_field in FirebaseAnalytics(firapb_measurement_config_4dcce8e8cf91365665d09449058a2326.o)
      _firapb_free_result_data_field in FirebaseAnalytics(firapb_result_data_cabd2395335989912a3b69fa621b3fe5.o)
      ...
  "_NANOClearField", referenced from:
      ___72-[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:]_block_invoke.1388 in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___68-[FIRADatabase insertRawEvent:metadataFingerprint:isRealtime:error:]_block_invoke in FirebaseAnalytics(FIRADatabase_84ed5b1bb5aa17bc006eddf42b4c0463.o)
      -[FIRAAudience resultsForBundling:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
  "_nano_set_uint64", referenced from:
      _firapb_populate_event_info in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_copy_event in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_populate_event_param_info in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_copy_event_param in FirebaseAnalytics(firapb_event_param_2592bf3e04bc4020e5c304daf8ae9c1f.o)
      _firapb_populate_measurement_bundle_info in FirebaseAnalytics(firapb_measurement_bundle_9ebceb096cde88551a2b0dc40054ec9d.o)
      _firapb_copy_measurement_bundle in FirebaseAnalytics(firapb_measurement_bundle_9ebceb096cde88551a2b0dc40054ec9d.o)
      _firapb_populate_measurement_config_info in FirebaseAnalytics(firapb_measurement_config_4dcce8e8cf91365665d09449058a2326.o)
      ...
  "_NANOSetInt32", referenced from:
      -[FIRAMeasurement createRawEventMetadataWithUserAttributes:] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAAudience resultsForBundling:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
  "_NANOSetMessage", referenced from:
      -[FIRAAudience resultsForBundling:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
  "_NANOGetInt64", referenced from:
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRADatabase rawEventDataFromDictionary:error:] in FirebaseAnalytics(FIRADatabase_84ed5b1bb5aa17bc006eddf42b4c0463.o)
      -[FIRADatabase insertBundle:isRealtime:error:] in FirebaseAnalytics(FIRADatabase_84ed5b1bb5aa17bc006eddf42b4c0463.o)
      -[FIRARemoteConfig version] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRARemoteConfig parseRemoteConfigFromMeasurementConfig:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRAEvent(ProtoBuffer) initWithEventProto:] in FirebaseAnalytics(FIRAEvent+ProtoBuffer_51a532abde89ab535c396ab1fd0828b0.o)
  "_NANOGetDouble", referenced from:
      -[FIRADatabase rawEventDataFromDictionary:error:] in FirebaseAnalytics(FIRADatabase_84ed5b1bb5aa17bc006eddf42b4c0463.o)
      -[FIRAEvent(ProtoBuffer) initWithEventProto:] in FirebaseAnalytics(FIRAEvent+ProtoBuffer_51a532abde89ab535c396ab1fd0828b0.o)
  "_NANOGetMessage", referenced from:
      +[FIRAAudience isValidAudienceProto:usedAudienceIDs:error:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      _FIRAAudienceEvaluateEventFilter in FirebaseAnalytics(FIRAAudienceFilterEvaluator_791a92acd72f46073e8a603f0178a53e.o)
      _FIRAAudienceEvaluateFilterWithValue in FirebaseAnalytics(FIRAAudienceFilterEvaluator_791a92acd72f46073e8a603f0178a53e.o)
      _FIRAAudienceEvaluatePropertyFilter in FirebaseAnalytics(FIRAAudienceFilterEvaluator_791a92acd72f46073e8a603f0178a53e.o)
  "_NANOGetArray", referenced from:
      ___72-[FIRAMeasurement networkRemoteConfigFetchCompletionHandler:data:error:]_block_invoke.1388 in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRADatabase rawEventDataFromDictionary:error:] in FirebaseAnalytics(FIRADatabase_84ed5b1bb5aa17bc006eddf42b4c0463.o)
      -[FIRARemoteConfig parseRemoteConfigFromMeasurementConfig:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRAAudience updateAudiences:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      -[FIRAAudience resultsForBundling:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      +[FIRAAudience isFilterResult:trueForFilterID:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      +[FIRAAudience updatedFilterResultWithFilterID:audienceID:currentFilterResult:newEvaluationResult:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      ...
  "_nano_set_uint32", referenced from:
      _firapb_populate_audience_info in FirebaseAnalytics(firapb_audience_498220436514c3e0ce1a58b1b945a3fa.o)
      _firapb_copy_audience in FirebaseAnalytics(firapb_audience_498220436514c3e0ce1a58b1b945a3fa.o)
      _firapb_populate_audience_leaf_filter_result_info in FirebaseAnalytics(firapb_audience_leaf_filter_result_c413bff9da18cdddbaa73cbb5c7def80.o)
      _firapb_copy_audience_leaf_filter_result in FirebaseAnalytics(firapb_audience_leaf_filter_result_c413bff9da18cdddbaa73cbb5c7def80.o)
      _firapb_populate_event_info in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_copy_event in FirebaseAnalytics(firapb_event_18e7b1480b9dc9886df479410632fc75.o)
      _firapb_populate_event_filter_info in FirebaseAnalytics(firapb_event_filter_8d99c35049e7e57e81018aa38d2a70f4.o)
      ...
  "_nano_decode_string", referenced from:
      _firapb_decode_event in FirebaseAnalytics(firapb_event_decoder_b12f86d34ef07b7785c71e30f0f2bdec.o)
      _firapb_decode_event_config in FirebaseAnalytics(firapb_event_config_decoder_cde32d44905cc0603c340053f5acc2cc.o)
      _firapb_set_event_filter_decoders in FirebaseAnalytics(firapb_event_filter_decoder_ec6b4dfae7767911eff6ccffc13f7296.o)
      _firapb_decode_event_param in FirebaseAnalytics(firapb_event_param_decoder_44c77717d048228f22bd72a81dca7cf5.o)
      _firapb_set_filter_decoders in FirebaseAnalytics(firapb_filter_decoder_8f86ab1b6526e1718ca4d06d5548ff97.o)
      _firapb_set_measurement_bundle_decoders in FirebaseAnalytics(firapb_measurement_bundle_decoder_bc1bba412b809b51d3d8b74383f892b1.o)
      _firapb_set_measurement_config_decoders in FirebaseAnalytics(firapb_measurement_config_decoder_ae62e73cccfb0feb0ef32b761c811a7f.o)
      ...
  "_NANOSetInt64", referenced from:
      -[FIRAEvent protoEvent] in FirebaseAnalytics(FIRAEvent_8daa1c66d878f542eb8516fbb193c28a.o)
      -[FIRAUserAttribute protoUserAttribute] in FirebaseAnalytics(FIRAUserAttribute_51beb1a814652e6a5b860ddba0a0c76a.o)
      -[FIRAMeasurement uploadData] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAMeasurement createRawEventMetadataWithUserAttributes:] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
  "_NANOSetString", referenced from:
      -[FIRAEvent protoEvent] in FirebaseAnalytics(FIRAEvent_8daa1c66d878f542eb8516fbb193c28a.o)
      -[FIRAUserAttribute protoUserAttribute] in FirebaseAnalytics(FIRAUserAttribute_51beb1a814652e6a5b860ddba0a0c76a.o)
      -[FIRAMeasurement createRawEventMetadataWithUserAttributes:] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAAudience updateAudiences:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
  "_NANOSetBool", referenced from:
      -[FIRAMeasurement createRawEventMetadataWithUserAttributes:] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAAudience resultsForBundling:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
  "_NANOGetBool", referenced from:
      -[FIRARemoteConfig isEventBlacklisted:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRARemoteConfig isEventCustomConversion:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      +[FIRAAudience isValidAudienceProto:usedAudienceIDs:error:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      _FIRAAudienceEvaluateFilterWithValue in FirebaseAnalytics(FIRAAudienceFilterEvaluator_791a92acd72f46073e8a603f0178a53e.o)
      _FIRAAudienceInternalIsValidStringFilter in FirebaseAnalytics(FIRAAudienceStringFilter_31799b83295dd848e65f7d38ee594c0f.o)
      _FIRAAudienceEvaluateStringFilterWithString in FirebaseAnalytics(FIRAAudienceStringFilter_31799b83295dd848e65f7d38ee594c0f.o)
  "_NANOGetInt32", referenced from:
      _FIRAAudienceIsValidNumberFilter in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      _FIRAAudienceEvaluateNumberFilterWithDouble in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      _FIRAAudienceEvaluateNumberFilterWithDecimalNumber in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAAudience updateAudiences:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      +[FIRAAudience isValidAudienceProto:usedAudienceIDs:error:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      _FIRAAudienceInternalIsValidStringFilter in FirebaseAnalytics(FIRAAudienceStringFilter_31799b83295dd848e65f7d38ee594c0f.o)
      ...
  "_NANOSetDouble", referenced from:
      -[FIRAEvent protoEvent] in FirebaseAnalytics(FIRAEvent_8daa1c66d878f542eb8516fbb193c28a.o)
      -[FIRAUserAttribute protoUserAttribute] in FirebaseAnalytics(FIRAUserAttribute_51beb1a814652e6a5b860ddba0a0c76a.o)
  "_NANOSetArray", referenced from:
      -[FIRAEvent protoEvent] in FirebaseAnalytics(FIRAEvent_8daa1c66d878f542eb8516fbb193c28a.o)
      -[FIRAMeasurement uploadData] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAMeasurement createRawEventMetadataWithUserAttributes:] in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      ___34-[FIRAMeasurement bundleRawEvents]_block_invoke in FirebaseAnalytics(FIRAMeasurement_78431add5886f7a64f080bb6c3f99898.o)
      -[FIRAAudience updateAudiences:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
      +[FIRAAudience updatedFilterResultWithFilterID:audienceID:currentFilterResult:newEvaluationResult:] in FirebaseAnalytics(FIRAAudience_2296b753fb53b83066f3d0749b0cb575.o)
  "_NANOHasField", referenced from:
      _FIRAAudienceIsValidNumberFilter in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      _FIRAAudienceEvaluateNumberFilterWithDecimalNumber in FirebaseAnalytics(FIRAAudienceNumberFilter_bd696ddf0d62d45ae8d17bb75d1fc590.o)
      -[FIRADatabase rawEventDataFromDictionary:error:] in FirebaseAnalytics(FIRADatabase_84ed5b1bb5aa17bc006eddf42b4c0463.o)
      -[FIRARemoteConfig isEventBlacklisted:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRARemoteConfig isEventCustomConversion:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRARemoteConfig version] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      -[FIRARemoteConfig parseRemoteConfigFromMeasurementConfig:] in FirebaseAnalytics(FIRARemoteConfig_837edd22ee2d481454f086c83e2ac372.o)
      ...
ld: symbol(s) not found for architecture arm64`

**Comment by baolocdo** [comment]
It looks like NanoPb is missing. Do you use pod or just drop the frameworks into your project?

**Comment by isipisi281** [comment]
fixed it thx

**Comment by rick-kln** [comment]
Same problem here, get these errors when building with:
```
Apple Swift version 4.0 (swiftlang-900.0.52 clang-900.0.29)
Target: x86_64-apple-macosx10.9
Xcode 9.0
Build version 9M174d
Firebase 4.0.4
```
Rolling back to 4.0.3 fixes the issue for now. When rolling back cocoa pods does say: `Removing nanopb` so it is getting included somewhere in 4.0.4 just not correctly.

**Comment by paulb777** [comment]
Does removing DerivedData fix the issue? (rm -rf ~/Library/Developer/Xcode/DerivedData/) 

If not, would you share the Podfile or even better, a reproducible example?

**Comment by alper** [comment]
Same here, updated Firebase on iOS and now…

```
Undefined symbols for architecture x86_64:
  "_nano_encode_repeated_string", referenced from:
      _firapb_set_string_filter_encoders in FirebaseAnalytics(firapb_string_filter_encoder_31bdd30f08496dd0d5483f963cac4130.o)
```

**Comment by alper** [comment]
I fixed it by moving back to `'Firebase/Core'` notation. I had moved to pod names without slashes because something else that wasn't working previously.

**Comment by m4rr** [comment]
I fixed it by delete Pods folder and then install them again. Like:
```sh
$ rm -rf Pods
$ pod install
```

**Comment by OkiRules** [comment]
Thanks m4rr,

THIS WORKED :)

```
$ rm -rf Pods
$ pod install
```

**Comment by anniewey** [comment]
Can anyone share their podfile? What `'Firebase/Core'` version that you guys are using?
