### ISSUE TITLE
I can't find this messaging:didRefreshRegistrationToken: in FIRMessagingDelegate

### ISSUE THREAD

**Issue by y0unghe** [firebase/quickstart-ios#305]
I am using Cocoapods to install `pod 'Firebase/Messaging'`. The installed pod version is `3.17.0`. I have looked in the header file `FIRMessaging.h`. There is no `messaging:didRefreshRegistrationToken:` which mentioned in the document: https://firebase.google.com/docs/cloud-messaging/ios/client#monitor-token-generation

Did I not install the latest version?

**Comment by morganchen12** [comment]
The newest version is 4.x. Run `pod update` and make sure your Podfile isn't pinning Firebase to 3.x.
