### ISSUE TITLE
IOS Notification cannot subscribe to topic and user ID is null

### ISSUE THREAD

**Issue by AIR-TECH** [firebase/quickstart-ios#307]
//
//  AppDelegate.swift
//  asoriba
//
//  Created by Bright Ahedor on 14/12/2016.
//  Copyright © 2016 Asoriba Inc. All rights reserved.
//

import UIKit
import Fabric
import Answers
import FBSDKLoginKit
import RealmSwift
import UserNotifications

import Firebase
import FirebaseInstanceID
import FirebaseMessaging
import IQKeyboardManagerSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
    let fcmMessageIDKey = "AAAA1AxS3OA:APA91bH1c9RxbxYtID31Zdela0Dm0Z5ESptX9_wqr1FSrxzDH160dViAXgAbchGYAbgzVZ7nW5Ob5yPqJgjpCrdN4pXNBtwguPjk3VScamKJAiODG1z4DZLx6HYy4axv0D8aNm4jyCWJ8gfMS_hev_-zPHQf_JP4Xg"
    
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        
        //realm migration
        let config = Realm.Configuration(
            schemaVersion: 3,
            migrationBlock: { migration, oldSchemaVersion in
                if (oldSchemaVersion < 1) {
                    
                }
        })
        Realm.Configuration.defaultConfiguration = config
        //ending the migration
        
        
        FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
        
        UINavigationBar.appearance().tintColor = UIColor.white
        
        let color = Mics.hexStringToUIColor(hex: AllKeys.primaryHexCode)
        UINavigationBar.appearance().barTintColor = color
        application.statusBarStyle = .lightContent
        
        
        UINavigationBar.appearance().tintColor = UIColor.white
        UINavigationBar.appearance().titleTextAttributes = [NSForegroundColorAttributeName : UIColor.white]
        
        
        UITabBar.appearance().barTintColor = UIColor.white
        UITabBar.appearance().tintColor = color
        
        //keyboard library
        IQKeyboardManager.sharedManager().enable = true
        
        Fabric.with([Answers.self])
        
        //register device
        registerForPush(application: application)
        
        //is from notification
        let notification: [AnyHashable: Any]? = (launchOptions?[UIApplicationLaunchOptionsKey.remoteNotification] as? [AnyHashable: Any])
        if notification != nil {
            self.startController(userInfo: notification!)
            self.application(application, didReceiveRemoteNotification: notification!)
            print("print \(String(describing: notification))")
        } else {
            /**************** app controler checks and login *******/
            var nextViewController: UIViewController
            let storyboard = UIStoryboard(name: AllKeys.mainStoryBoard, bundle: nil)
            if DataOperation.userIsEmpty() {
                nextViewController = storyboard.instantiateViewController(withIdentifier: AllKeys.onboardViewController)
            } else if (DataOperation.getUser().firstName.isEmpty)  {
                nextViewController = storyboard.instantiateViewController(withIdentifier: AllKeys.updateNameController)
                //update with all gateways
                let api = ApiService()
                api.getPaymentGetways()
                //
            }else {
                nextViewController = storyboard.instantiateViewController(withIdentifier: AllKeys.mainController)
                //update with all gateways
                let api = ApiService()
                api.getPaymentGetways()
            }
            
            /**************end of checks *************/
            self.window?.rootViewController = nextViewController
            self.window?.makeKeyAndVisible()
            
        }
        
        return true
    }
    
    
    func registerForPush(application:UIApplication)  {
        if #available(iOS 10.0, *) {
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
            
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            // For iOS 10 data message (sent via FCM)
            Messaging.messaging().delegate = self as? MessagingDelegate
            
        } else {
            let settings: UIUserNotificationSettings =
                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            application.registerUserNotificationSettings(settings)
        }
        
        application.registerForRemoteNotifications()
        
        // [END register_for_notifications]
        FirebaseApp.configure()
        
        // Add observer for InstanceID token refresh callback.
        NotificationCenter.default.addObserver(self,selector: #selector(self.tokenRefreshNotification),
                                               name: .InstanceIDTokenRefresh,
                                               object: nil)
        
        
        //subscibe for messages
        Messaging.messaging().subscribe(toTopic: "asoriba_ios")
        
    }
    
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        return FBSDKApplicationDelegate.sharedInstance().application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
    }
    
    func applicationWillResignActive(_ application: UIApplication) {
        FBSDKAppEvents.activateApp()
    }
    
    
    func applicationDidEnterBackground(_ application: UIApplication) {
        Messaging.messaging().shouldEstablishDirectChannel = false
        
        let notificationCount = UserDefaults.standard.integer(forKey: AllKeys.notificationCount)
        UIApplication.shared.applicationIconBadgeNumber = notificationCount
    }
    
    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        FBSDKAppEvents.activateApp()
        connectToFcm()
    }
    
    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
    
    
    // [START receive_message]
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
        print(userInfo)
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        if let messageID = userInfo[fcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        completionHandler(UIBackgroundFetchResult.newData)
        
    }
    
    
    // [START refresh_token]
    func tokenRefreshNotification(_ notification: Notification) {
        connectToFcm()
    }
    
    func connectToFcm() {
        guard InstanceID.instanceID().token() != nil else {
            return;
        }
        //Messaging.messaging().disconnect()
        Messaging.messaging().connect { (error) in
            if error != nil {
                print("Unable to connect with FCM. \(String(describing: error))")
            } else {
                print("Connected to FCM.")
            }
        }
    }
    // [END connect_to_fcm]

    //check to see if notification registration fails
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("Unable to register for remote notifications: \(error.localizedDescription)")
    }
    
    //check to see if notification registration is successful
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        if let refreshedToken = InstanceID.instanceID().token() {
            print("InstanceID token: \(refreshedToken)")
            if !DataOperation.userIsEmpty() {
                let apiService = ApiService()
                apiService.subscribeToTopics()
            }
        }
    }
    
    
    func startController(userInfo:[AnyHashable:Any]) {
        
        if let action = userInfo["click_action"] as? String {
            print("Action \(action)")
            let homeStoryboard = UIStoryboard(name: AllKeys.mainStoryBoard, bundle: nil)
            let vc  = homeStoryboard.instantiateViewController(withIdentifier: AllKeys.mainController) as! MainTabController
            let feedDetail = homeStoryboard.instantiateViewController(withIdentifier: AllKeys.feedDetailController) as! FeedDetailController
            
            switch action {
            case "COMMENT":
                let id = userInfo["content_id"] as! String
                
                let feed = Feed()
                feed.id = id
                feedDetail.feed = feed
                
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                let controller = vc.viewControllers?.first as! UINavigationController
                controller.pushViewController(feedDetail, animated: true)
                
                break
            case "USER_HAS_FOLLOWED":
                let id = userInfo["user_id"] as! String
                
                let profileDetail = homeStoryboard.instantiateViewController(withIdentifier: AllKeys.userProfileController) as! ProfileViewController
                
                let member = Member()
                member.id = id
                
                profileDetail.user = member
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                
                let controller = vc.viewControllers?.first as! UINavigationController
                controller.pushViewController(profileDetail, animated: true)
                
                break
            case "TYPE_PAYMENT_COMPLETED":
                let _ = userInfo["record_id"] as! String
                
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                vc.selectedIndex = 2
                
                let paymentHistory = homeStoryboard.instantiateViewController(withIdentifier: AllKeys.paymentHistoryController) as! PaymentHistoryController
                let controller = vc.viewControllers?[2] as! UINavigationController
                controller.pushViewController(paymentHistory, animated: true)
                
                break
            case "JOIN_CHURCH_APPROVED":
                break
            case "PERSONAL_MESSAGE":
                
                let id = userInfo["content_id"] as! String
                
                let feed = Feed()
                feed.id = id
                feedDetail.feed = feed
                
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                let controller = vc.viewControllers?.first as! UINavigationController
                controller.pushViewController(feedDetail, animated: true)
                
                break
            case "APP_UPDATE":
                
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                vc.selectedIndex = 0
                
                break
            case "USER_POST_PROMPT":
                break
            case "CHURCH_CONTENT":
                let id = userInfo["content_id"] as! String
                
                let feed = Feed()
                feed.id = id
                feedDetail.feed = feed
                
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                let controller = vc.viewControllers?.first as! UINavigationController
                controller.pushViewController(feedDetail, animated: true)
                
                break
            default:
                self.window?.rootViewController = vc
                self.window?.makeKeyAndVisible()
                
                break
            }
            
            print("PASS \(action)")
            
        }
        
        
    }
        
}

// [START ios_10_message_handling]
@available(iOS 10, *)
extension AppDelegate : UNUserNotificationCenterDelegate {
    
    // Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        
        let userInfo = notification.request.content.userInfo
        // Print full message.
        print("Arrived \(userInfo as! [String:AnyObject])")
        
        let notificationCount = UserDefaults.standard.integer(forKey: AllKeys.notificationCount)
        UIApplication.shared.applicationIconBadgeNumber = notificationCount + 1
        completionHandler([.alert, .badge, .sound])
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        
        let userInfo = response.notification.request.content.userInfo
        UIApplication.shared.applicationIconBadgeNumber = 0
        startController(userInfo: userInfo)
        let action = response.actionIdentifier
        print("Action taken \(action.capitalized)")
        completionHandler()
    }
}

extension AppDelegate : MessagingDelegate {
    func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
        print("print the fcmKey \(fcmToken)")
    }
    
    // Receive data message on iOS 10 devices while app is in the foreground.
    func application(received remoteMessage: MessagingRemoteMessage) {
        print(remoteMessage.appData)
    }
}

**Comment by rsattar** [comment]
You may be trying to subscribe to a topic too early; at that point of calling Firebase.configure(), Messaging has barely had time to create an FCM token. You should wait until you receive an FCM token before subscribing to a topic. Also, it looks like you’re still using an old version of FirebaseMessaging. InstanceID is no longer a developer-facing SDK, and Messaging should wrap all the necessary calls to InstanceID. 

You’ll need to add the subscription logic in two different places. One after initializing Firebase (as you’re doing), but with a check first if you have a token:

```
if Messaging.messaging().fcmToken != nil {
    Messaging.messaging().subscribe(toTopic: “foo”)
}
```

and also when a token is refreshed:
```
func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
    Messaging.messaging().subscribe(toTopic: “foo”)
}
```

I’m not sure what you mean by UserID being null. Are you able to send the device a notification from the Firebase console, using it’s FCM registration token?

**Comment by AIR-TECH** [comment]
Thank you very much boss for your response, integrating that for result.

**Comment by AIR-TECH** [comment]
yes i am able to send the device a notification from the firebase console.

**Comment by morganchen12** [comment]
@AIR-TECH is this still an issue?

**Comment by AIR-TECH** [comment]
On Wed, Nov 1, 2017 at 11:18 PM Morgan Chen <notifications@github.com>
wrote:

> @AIR-TECH <https://github.com/air-tech> is this still an issue?
>

Yes please it is

**Comment by morganchen12** [comment]
Did you move your topic subscription code as Riz mentioned above? Also, please update to the latest FCM and InstanceID versions.

**Comment by AIR-TECH** [comment]
Yes I did

**Comment by morganchen12** [comment]
And are you able to send notifications via Firebase Console?

**Comment by AIR-TECH** [comment]
Yes

**Comment by morganchen12** [comment]
If you're able to send notifications through the console and receive them on your device (even when backgrounded), then everything on the FCM backend is probably set up correctly. There's likely something else going on in your app implementation preventing your app from successfully subscribing to topics.

If you suspect an issue in your app implementation, we'll need more information to debug further.

If you suspect an issue in FCM, please share a project that consistently reproduces the issue so we can effectively debug it.

**Comment by AIR-TECH** [comment]
Ok then I will have to share my app delegate with you or do I have to share
my entire project

**Comment by morganchen12** [comment]
The AppDelegate above doesn't seem to have any issues. If you can share your whole app, that would be ideal, as well as any runtime logs around the issue (i.e. the userID you're trying to print that's null).

**Comment by AIR-TECH** [comment]
Ok then I will send you my project. Thank you

**Comment by AIR-TECH** [comment]
please kindly give me your email so that i can share the project with you
on bitbucket.

**Comment by AIR-TECH** [comment]
please kindly give me your email so that i can share the project with you
on bitbucket.

**Comment by morganchen12** [comment]
morganchen@google

**Comment by AIR-TECH** [comment]
Hello,
        I have not received any response with respect to our topic
subscription issues on Firebase.

**Comment by morganchen12** [comment]
Your code currently only sets the messaging delegate on iOS 10 and above, and thus will not handle token refreshes on OS versions below iOS 10.

Your code may have other errors, which you should look through on your own since they're mostly general programming errors and not entirely Firebase-specific.

**Comment by AIR-TECH** [comment]
The first part of your response is not clear to me “Your code currently
only sets the messaging delegate on iOS 10 and above, and thus will not
handle token refreshes on OS versions below iOS 10.”

**Comment by ynstek** [comment]
**IS SOLVED for** 
**<Error> [Firebase/Messaging][I-FCM002010] Cannot subscribe to topic: /topics/news with token: (null)**
I had this problem too. After many attempts, I reached a solution.
You must run the subscription topic code after the firebase token send operation.
`FIRMessaging.messaging().subscribeToTopic("news")`
For example, 
I pulled out the json data and started the subscription after fill the table.
