### ISSUE TITLE
Does firebaseAnalytics support podspec

### ISSUE THREAD

**Issue by chandrashekharhm** [firebase/quickstart-ios#308]
Hi Team,

I'm trying to integrate firebaseAnalytics as podspec in my Swift application. After integration I'm getting the below error during compile time.

"Umbrella for module 'appName' already covers this directory". Do the firebaseAnalytics support podspec in Swift codebase.

**Comment by morganchen12** [comment]
What version of CocoaPods are you using? What does your Podfile/podspec look like?

**Comment by chandrashekharhm** [comment]
Pod Version: 1.3.0.beta.3
		s.subspec 'Firebase' do |firebase|
			
			firebase.pod_target_xcconfig = {
				'OTHER_SWIFT_FLAGS[config=Debug]' => '-DFIREBASE_ENABLED',
				'OTHER_SWIFT_FLAGS[config=Release]' => '-DFIREBASE_ENABLED',
				'OTHER_SWIFT_FLAGS[config=Release_Test]' => '-DFIREBASE_ENABLED'
			}
			firebase.ios.vendored_frameworks = 'Shared/Externals/Firebase/*'
			firebase.ios.source_files = 'Shared/Externals/Firebase/FirebaseAnalytics.framework/Headers/*'
		end

**Comment by chandrashekharhm** [comment]
And there is one more exception if i miss to set "-ObjC" linker flag 
2017-07-27 13:43:08.559 TestFirebaseDependency[19196:1114168] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString fira_UTF32Length]: unrecognized selector sent to instance 0x6000000229c0'

**Comment by morganchen12** [comment]
Can you upload a sample project?
