### ISSUE TITLE
Unity-iOS: [Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"

### ISSUE THREAD

**Issue by BlackMB** [firebase/quickstart-ios#310]
Hi Guys,
My issue is: when i "Build and Run" my project from Xcode to my iPhone, i see in log this type of error:

2017-08-01 01:44:00.868946+0430 GameName[3540:934225] [Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"

i do all things step by step from web site, and all of my plugins and applications are updated.
i use firebase analytics and adMob. 
Please help me...

**Comment by farshadjahanmanesh** [comment]
hi, i was facing this problem too, in IRAN, thanks to all google... **we are blocked** ... i was facing this problem about 5 days and try every tutorial in net... but nothing solve my problem, Domain=com.firebase.iid not responds and it doesnt give me a token... but when i connect to a **VPN** then connection between device and iid.firebase.com domain established and token generated, **try connecting to VPN and check again**.

**Comment by BlackMB** [comment]
Yeah, Thanks Farshad, it was not a real problem, i done it a day after i post this question, but its too crazy, because i couldn't debug any problem in such these cases... thanks again for your answer and your time to solve it.

**Comment by ashkanpower** [comment]
Will it be fixed in distribution mode?

**Comment by ipouya** [comment]
why android can connect but from ios app we can't use fcm cloud message without VPN ?
