### ISSUE TITLE
404 URL

### ISSUE THREAD

**Issue by emansih** [firebase/quickstart-ios#312]
### Step 1: Describe the problem:
The URL in README.md for preformance folder leads to a 404 page (https://firebase.google.com/docs/performance) 
#### Steps to reproduce:
1. Click on the above mentioned URL.

#### Observed Results:

Sees 404 page
  
#### Expected Results:

  * What did you expect to happen?
Page should not be 404
  

#### How to fix

Replace the above mentioned URL with this instead. https://firebase.google.com/docs/perf-mon/

**Comment by morganchen12** [comment]
Fixed, thanks!
