### ISSUE TITLE
Linker command failed with exit code1

### ISSUE THREAD

**Issue by glorment** [firebase/quickstart-ios#315]
after run the pod install at the xcode and compile have following error

![image](https://user-images.githubusercontent.com/22617300/29404945-1118cf30-836f-11e7-8337-5c188c087aa3.png)

anyone can help for this ?

**Comment by paulb777** [comment]
Make sure you're opening the .xcworkspace and not the .xcproject file in Xcode.

**Comment by glorment** [comment]
is work ! thx

**Comment by lamlephamngoc** [comment]
thanks
