### ISSUE TITLE
<my-app-scheme>://google/link/?is_weak_match=1 when opening app normally in simulator

### ISSUE THREAD

**Issue by matcartmill** [firebase/quickstart-ios#317]
Hello,

We are experiencing an issue with Dynamic Links. Passing in and parsing REAL dynamic links works fine for us and we are thrilled that they are, as they're a powerful tool. However, we're noticing that on app startup, even though we're just launching the app regularly through Xcode, that a `<my-app-scheme>://google/link/?is_weak_match=1` link is being passed to the `openURL` method. This invokes our attempt to parse, etc...

Right now we added some error handling to just resume the app normally if the link is not parseable, however this is not ideal as it means that the user has no idea if the link worked. If we add an alert, then every user will get that alert whether or not they attempted to open the app from a Dynamic Link.

Any ideas?

**Comment by Skorch** [comment]
@matcartmill I found a reference to this issue (I've also noticed this)

https://github.com/firebase/firebase-ios-sdk/issues/233#issuecomment-327863307

Hope that helps.

**Comment by morganchen12** [comment]
cc @OleksiyA

**Comment by Skorch** [comment]
What ended up being my problem, is that I wasn't parsing the dynamic link properly in the scenario where I've clicked on the dynamic link, then installed (via app store, or launched via simulator).

per the docs:

https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app

```swift

func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
  let dynamicLink = DynamicLinks.dynamicLinks()?.dynamicLink(fromCustomSchemeURL: url)
  if let dynamicLink = dynamicLink {
    // Handle the deep link. For example, show the deep-linked content or
    // apply a promotional offer to the user's account.
    // ...
    return true
  }

  return false
}
```

the line `let dynamicLink = DynamicLinks.dynamicLinks()?.dynamicLink(fromCustomSchemeURL: url)` parsed it correctly, and also acknowledged the server that I've opened it.  W/o that line, I would get the link passeed in on every launch.

Hope that helped

**Comment by OleksiyA** [comment]
@matcartmill Sorry for late update.
FDL iOS SDK will pass found dynamic link to your App when dynamic link is found. If dynamic link is not found, you will see link similar to <my-app-scheme>://google/link/?is_weak_match=1. This link notifies your App that FDL tried to find pending dynamic link but did not found any.

Best way to handle this case:

```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
  let dynamicLink = DynamicLinks.dynamicLinks()?.dynamicLink(fromCustomSchemeURL: url)
  if let dynamicLink = dynamicLink {
    if let deepLink = dynamicLink.url {
      // Handle the deep link. For example, show the deep-linked content or
      // apply a promotional offer to the user's account.
      // ...
    } else {
      // dynamic link is not available or error occurred
    }
    return true
  }
  return false
}
```
