### ISSUE TITLE
MyAppSchema://google/link/?dismiss=1&is_weak_match=1

### ISSUE THREAD

**Issue by nhuomtv** [firebase/quickstart-ios#318]
I tested ios 4.1.0 in 10 devices ios, three device receive dynamic link "MyAppSchema://google/link/?dismiss=1&is_weak_match=1". Please check new release firebase dynamic link service. May 2017 i tested with 10 device above it work normaly. Now three device dynamic link not work.

**Comment by jcarlosestela** [comment]
I have the same problem, when I open the app the first time after opening a dynamic link I receive this url scheme.

**Comment by morganchen12** [comment]
moved to https://github.com/firebase/firebase-ios-sdk/issues/233
