### ISSUE TITLE
Push messages getting dropped.

### ISSUE THREAD

**Issue by mannyvw** [firebase/quickstart-ios#320]
Hi 

Testers are reporting some messages are getting dropped when using GCM, particularly if they come in fast.

Have taken your latest messaging example and latest pod libraries. Which are :-

Installing Firebase (3.6.0)
Installing FirebaseAnalytics (3.4.2)
Installing FirebaseInstanceID (1.0.8)
Installing FirebaseMessaging (1.2.0)
Installing GoogleIPhoneUtilities (1.2.1)
Installing GoogleInterchangeUtilities (1.2.1)
Installing GoogleSymbolUtilities (1.1.1)
Installing GoogleUtilities (1.3.1)

Had to modify it slightly as two lines no longer build. 

In AppDelegate.m Changed :-
`[FIRMessaging messaging].delegate = self;`
to : 
`[FIRMessaging messaging].remoteMessageDelegate = self;`

In ViewController.m Changed 
`[FIRMessaging messaging].FCMToken`
to
`NSString *fcmToken = [FIRInstanceID instanceID].token;`

and added my GoogleServices-Info.plist file.

Have a script then sends 10 push messages to the device, incrementing the number in message each time. After running as you can see from my screen shot below, 4, 8 & 10 are missing. However if I open the app last message "10" comes through.

![img_0001](https://user-images.githubusercontent.com/402626/30283083-06160608-970f-11e7-9c66-e22282adceb9.PNG)

Have done same test sending regular (via Apple) push notifications also from command line. All 10 comes through with no problem. 

Am testing with a iPhone 5 on 10.3.1, but it happens on an iPhone6 too. 

Cant see any difference on console logs example below 

Message 4 arriving 

```
default	15:50:56.708572 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSPushHistory: 0x16e8ac30> receivedPushWithTopic com.elementfortynine.pushme token <0a064555 b2e73e8f f33f9ada 47133dfa f91d67d3 57455217 792aa27a 46edc672> payload <7b226170 73223a7b 22616c65 7274223a 22204669 72656261 73652034 222c2273 6f756e64 223a2270 696e672e 61696666 227d2c22 67636d2e 6d657373 6167655f 6964223a 22303a31 35303531 34313435 36333339 32363725 39346163 39656166 39346163 39656166 227d> timestamp 2017-09-11 14:50:56 +0000
default	15:50:56.708939 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSCourier: 0x16e88f80>: Received message for enabled topic 'com.elementfortynine.pushme' with payload '{
    aps =     {
        alert = " Firebase 4";
        sound = "ping.aiff";
    };
    "gcm.message_id" = "0:1505141456339267%94ac9eaf94ac9eaf";
}' onInterface: NonCellular  for device token: NO  with priority 5
default	15:50:56.709610 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSMessageStore: 0x16e8c820> deleting low-priority incoming messages for topic com.elementfortynine.pushme environment development
default	15:50:56.710063 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: APSMessageStore - APSIncomingMessageRecordDeleteMessagesForTopic com.elementfortynine.pushme 1 environment development
default	15:50:56.927226 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSPushHistory: 0x16e8ac30> timestampForTopic? com.elementfortynine.pushme token <0a064555 b2e73e8f f33f9ada 47133dfa f91d67d3 57455217 792aa27a 46edc672>
default	15:50:56.941184 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSPushHistory: 0x16e8ac30> hasPayload? <7b226170 73223a7b 22616c65 7274223a 22204669 72656261 73652035 222c2273 6f756e64 223a2270 696e672e 61696666 227d2c22 67636d2e 6d657373 6167655f 6964223a 22303a31 35303531 34313435 36363130 36343325 39346163 39656166 39346163 39656166 227d> forTopic com.elementfortynine.pushme token <ed197db7 9c018941 7077dc47 512e4e52 a171ed8f b77e946e 6f496f6a 14513221>
default	15:50:56.962923 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: copyAppSpecificTokensWithDomain - sandbox.push.apple.com for topic com.elementfortynine.pushme account 88DDAA10-E829-40B0-AF79-92D23C19D329,ffffffee1bffffffc3ffffffe510586fffffff962e67ffffff89314e75ffffffb3fffffff8ffffffe37d3378
```

Message 5 arriving

```
default	15:50:56.963554 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSPushHistory: 0x16e8ac30> receivedPushWithTopic com.elementfortynine.pushme token <0a064555 b2e73e8f f33f9ada 47133dfa f91d67d3 57455217 792aa27a 46edc672> payload <7b226170 73223a7b 22616c65 7274223a 22204669 72656261 73652035 222c2273 6f756e64 223a2270 696e672e 61696666 227d2c22 67636d2e 6d657373 6167655f 6964223a 22303a31 35303531 34313435 36363130 36343325 39346163 39656166 39346163 39656166 227d> timestamp 2017-09-11 14:50:56 +0000
default	15:50:56.964068 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSCourier: 0x16e88f80>: Received message for enabled topic 'com.elementfortynine.pushme' with payload '{
    aps =     {
        alert = " Firebase 5";
        sound = "ping.aiff";
    };
    "gcm.message_id" = "0:1505141456610643%94ac9eaf94ac9eaf";
}' onInterface: NonCellular  for device token: NO  with priority 5
default	15:50:56.964798 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: <APSMessageStore: 0x16e8c820> deleting low-priority incoming messages for topic com.elementfortynine.pushme environment development
default	15:50:56.965138 +0100	apsd	2017-09-11 15:50:56 +0100 apsd[88]: APSMessageStore - APSIncomingMessageRecordDeleteMessagesForTopic com.elementfortynine.pushme 1 environment development
default	15:50:57.135835 +0100	apsd	2017-09-11 15:50:57 +0100 apsd[88]: <APSPushHistory: 0x16e8ac30> timestampForTopic? com.elementfortynine.pushme token <0a064555 b2e73e8f f33f9ada 47133dfa f91d67d3 57455217 792aa27a 46edc672>
default	15:50:57.179408 +0100	apsd	2017-09-11 15:50:57 +0100 apsd[88]: <APSPushHistory: 0x16e8ac30> hasPayload? <7b226170 73223a7b 22616c65 7274223a 22204669 72656261 73652036 222c2273 6f756e64 223a2270 696e672e 61696666 227d2c22 67636d2e 6d657373 6167655f 6964223a 22303a31 35303531 34313435 36383738 36373525 39346163 39656166 39346163 39656166 227d> forTopic com.elementfortynine.pushme token <ed197db7 9c018941 7077dc47 512e4e52 a171ed8f b77e946e 6f496f6a 14513221>
default	15:50:57.220244 +0100	apsd	2017-09-11 15:50:57 +0100 apsd[88]: copyAppSpecificTokensWithDomain - sandbox.push.apple.com for topic com.elementfortynine.pushme account 88DDAA10-E829-40B0-AF79-92D23C19D329,ffffffee1bffffffc3ffffffe510586fffffff962e67ffffff89314e75ffffffb3fffffff8ffffffe37d3378
```

Complete  console logs here 
[firebase logs.txt](https://github.com/firebase/quickstart-ios/files/1293261/firebase.logs.txt)

Any ideas ?

thanks 

Neil

**Comment by morganchen12** [comment]
APNs [doesn't guarantee](https://developer.apple.com/library/content/technotes/tn2265/_index.html) that multiple notifications sent in quick succession will be delivered in order. In their technical Q&A, Apple only says the last one will be delivered.

Also, the newest Firebase libraries are 4.0+; we likely need to update the samples.

**Comment by rsattar** [comment]
Hi @mannyvw,

> Installing Firebase (3.6.0)
> Installing FirebaseAnalytics (3.4.2)
> Installing FirebaseInstanceID (1.0.8)
> Installing FirebaseMessaging (1.2.0)
> Installing GoogleIPhoneUtilities (1.2.1)
> Installing GoogleInterchangeUtilities (1.2.1)
> Installing GoogleSymbolUtilities (1.1.1)
> Installing GoogleUtilities (1.3.1)

FYI, this is not the latest Messaging SDK, and your changes to make the code work unfortunately are the _old_ way of integrating.

Thanks for including the console logs! It's strange that the notifications are arriving with `priority 5` according to Apple. That indicates "low" priority, and could explain why some messages are not getting shown (even though they have arrived). Could you try setting `priority: high` in your JSON request when you send the notification via FCM? If that fixes it, this might indicate a bug on our backend (messages should be high priority by default).

Also, for future issues, you should create issues in firebase/firebase-ios-sdk, where we have open-sourced many of the client SDKs. Thanks!

**Comment by mannyvw** [comment]
Thanks @rsattar , yep missed that thanks. it was set to normal, set to high and its as speedy as using apple directly. thanks

**Comment by rsattar** [comment]
Great! 👍 

FYI, I would advise _not_ setting the `priority` parameter _unless_ you specifically want a certain behavior. With that property omitted, FCM tries to do the right thing for each platform. For example, Android is low-by-default, and iOS is high-by-default. By setting the priority to "normal", it forces the iOS priority to become `5`. 

If you _weren't_ setting priority before, and still getting `priority 5` (please let me know if that's the case), then that wold indicate a bug on our backend.

**Comment by mannyvw** [comment]
no its all good, if i remove the priority it goes back to 10. think my main problem we not realising 5 was normal/low priority didn't realise it went up to 10. thanks
