### ISSUE TITLE
Failed to receive notifications (background only)

### ISSUE THREAD

**Issue by shinkicker** [firebase/quickstart-ios#321]
Hi,

I've implemented the Cloud Messaging example in my own code but don't receive the notification on the phone (foreground or background) even though the message status is success.  Any assistance will be appreciated.

My environment is as follows:

.plist has FirebaseAppDelegateProxyEnabled set to NO

iOS: 10.3.3
Swift 3
xCode: 8.3.3
Firebase 4

CODE:
-------------------------
import UIKit
import UserNotifications

import Firebase
import Foundation

// MARK: - AppDelegate Start
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    // MARK: Properties
    var window: UIWindow?
    let gcmMessageIDKey = "gcm.message_id"
    
    var notificationReceived = false
    var appIsActive = false
    
    var verificationCode : Int = 0 // Default value of 0
    var orientationLock = UIInterfaceOrientationMask.all
    
    //lock orientation
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        return self.orientationLock
    }
    
    // MARK: - application calls
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
        [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        FirebaseApp.configure()
        
        // [START set_messaging_delegate]
        Messaging.messaging().delegate = self
        Messaging.messaging().shouldEstablishDirectChannel = true
        // [END set_messaging_delegate]
        // Register for remote notifications. This shows a permission dialog on first run, to
        // show the dialog at a more appropriate time move this registration accordingly.
        // [START register_for_notifications]
        if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
        } else {
            //for phones running OS < 10
            let settings: UIUserNotificationSettings =
                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            application.registerUserNotificationSettings(settings)
        }
        
        application.registerForRemoteNotifications()
        // [END register_for_notifications]
      
        return true
    }
    
    // MARK: - Receive APNS Token
    func application( _ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken
        deviceToken: Data ) {
      
        //with swizzling enabled
        Messaging.messaging().apnsToken = deviceToken
        
        let token = Messaging.messaging().fcmToken//deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        print("APNs Device Token: --\(token!)--")
       
    }
    
    // MARK: - Receive_apns_token_error
    func application( _ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError
        error: Error ) {
        print("Device token for push notifications: FAIL -- \(error)")
    }
    
    // MARK: Static Functions
    // [START receive_message]
    func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject], fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) -> Void) {
        // Let FCM know about the message for analytics etc.
        Messaging.messaging().appDidReceiveMessage(userInfo)
        // handle your message
        
        // Print full message.
        print(userInfo)
        
    }
   
    // MARK: Displaying message when app is in the foreground
    func application( _ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        print("Received Remote Notification: \(userInfo)")
        
        // With swizzling disabled you must let Messaging know about the message, for Analytics
        Messaging.messaging().appDidReceiveMessage(userInfo)
        
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        completionHandler(UIBackgroundFetchResult.newData)
    }
    
    // MARK: Enter/Return from Background management
    func applicationDidEnterBackground(_ application: UIApplication) {
        // Load the Login view, as we have moved out of focus of app.
        appIsActive = false
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        
        // Reset the Icon Badge, as the Badge is only to show that a message was received.
        UIApplication.shared.applicationIconBadgeNumber = 0
        
        appIsActive = true
      
    }
    
}

@available(iOS 10, *)
extension AppDelegate : UNUserNotificationCenterDelegate {
    
    // Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        
        let userInfo = notification.request.content.userInfo
        
        // With swizzling disabled you must let Messaging know about the message, for Analytics
         Messaging.messaging().appDidReceiveMessage(userInfo)
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        // Change this to your preferred presentation option
        completionHandler([])
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo
        // Print message ID.
        if let messageID = userInfo[gcmMessageIDKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print(userInfo)
        
        completionHandler()
    }
}
// [END ios_10_message_handling]

extension AppDelegate : MessagingDelegate {
    // [START refresh_token]
    func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
        print("Firebase registration token: \(fcmToken)")
    }
    // [END refresh_token]
    // [START ios_10_data_message]
    // Receive data messages on iOS 10+ directly from FCM (bypassing APNs) when the app is in the foreground.
    // To enable direct data messages, you can set Messaging.messaging().shouldEstablishDirectChannel to true.
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("Received data message: \(remoteMessage.appData)")
    }
    // [END ios_10_data_message]
}

**Comment by shinkicker** [comment]
The foreground messages are now received, I've refactored the code to have all my extensions at the bottom of the file.  I should add that I'm sending the following FCM message:

{ 
	"content_available": true,
	"data": {
   "title": "FCM Message",
   "body": "Hallo, this is my message"
 },
 "to" : "d8l08w....."
}

**Comment by rsattar** [comment]
Thanks for including the JSON of the message you’re sending! There’s a difference between “data” messages and “notification” messages. “notification” is what you need to send user-visible notifications. 

Change your “data” to “notification”, and remove “content_available” for user notifications. 

For data-only messages, send “data”. That is only received when the app is in the foreground, and if you have ‘shouldEstablishDirectChannel’ enabled. To send it over APNs, send the combination of “data” and “content_available”. Hope that helps!

**Comment by shinkicker** [comment]
Thanks for the response, I've changed the message but still don't receive any notifications if the application is in the background or not running.  The message now reads:

{ 
	"notification": {
   "title": "FCM Message",
   "message_body": "Hallo, this is my message"
 },
 "to" : "d8l08w"
}

I do receive this message as well but the app must be running and in the foreground

**Comment by shinkicker** [comment]
After spending many hours on researching this I still cannot find a solution.  To enable messages to be pushed when the application is in the background I've setup a service which communicates directly with APNS.  This works 100%.  

My conclusion based on what I've learned thus far (and I might be incorrect, any assistance to help change this will help) is that FCM can send notifications to Apple if and only if the app is in the foreground.  It will queue the messages send if your app is not running and process them when the app is running

To be able to send notifications when the app is either not started or in the background use direct integration into APNS.

**Comment by shinkicker** [comment]
It would seem that your hardware also has an impact.  My initial tests was performed on an iPhone 5, this did not work.  After running tests on a 6 the FCM started to work on both 5 and 6.  Not sure why there will be different libraries used for these as the OS version was precisely the same.

**Comment by rsattar** [comment]
Thanks for the additional info @shinkicker, that'll help us figure out what's happening.

> My conclusion based on what I've learned thus far (and I might be incorrect, any assistance to help change this will help) is that FCM can send notifications to Apple if and only if the app is in the foreground.

FCM is designed to be a wrapper for APNs, so notifications _absolutely_ work in the background as well as the foreground. We just have to figure out why it's not working for you.

> To enable messages to be pushed when the application is in the background I've setup a service which communicates directly with APNS. This works 100%.

This is actually great! Was this on the same exact app which is currently failing with the FCM SDK? This might point to some other issue, in the FCM SDK, then. Do you by chance have `Keychain Sharing` enabled for that app?

> After running tests on a 6 the FCM started to work on both 5 and 6.

Hmm, you mean FCM actually worked _both_ in background and foreground on a 6?

> The message now reads:
Just in case there might be any formatting issues, here's a sample JSON object that works (note `body` instead of `message_body`) and sends over APNs:
```
{
  "notification": {
    "title": "A very fancy title",
    "body": "A very fancy message body",
    "sound": "default",
    "badge": "0"
  },
  "to": "YOUR_FCM_TOKEN"
}
```

**Comment by shinkicker** [comment]
Hi,

I've written my own service that communicates with APNs and used this service to send the notification to iPhone with success.  

After I've uninstalled and reinstalled the app on the iPhone 5 and sent messages via my own wrapper the messages went through via FCM.  

It can thus be one of two things in my opinion, 
1. either the uninstall, reinstall reset something on the phone
2. the registration on the APN happended on my service and afterwards it all worked.

Don't know if it assist much but at least it is working.

**Comment by midhun-narayan** [comment]
Hi,
I am having a problem like notifications are working perfectly in iphone 6 (ios 11.2) but in case of iphone 8 (ios 11.2) only background notifications are working. i dont have a iphone 8 so i couldint see what happening there. I think FCM is recieving but not posting to the notification handler. How to post FCM recieved in appdelegate to one viewcontroller 

```
// [START ios_10_message_handling]
@available(iOS 10, *)
extension AppDelegate : UNUserNotificationCenterDelegate {
    
    // Receive displayed notifications for iOS 10 devices.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let userInfo = notification.request.content.userInfo
        
        // With swizzling disabled you must let Messaging know about the message, for Analytics
         Messaging.messaging().appDidReceiveMessage(userInfo)
        // Print message ID.
        if let messageID = userInfo[messageKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print("fcm-->\(userInfo)")
        
        // Change this to your preferred presentation option
        
        
        completionHandler([.alert,.sound])
        
        
        NotificationCenter.default.post(name: Notification.Name(rawValue: messageKey), object: nil,userInfo: userInfo)
    }
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo
        // Print message ID.
        if let messageID = userInfo[messageKey] {
            print("Message ID: \(messageID)")
        }
        
        // Print full message.
        print("fcm-->1\(userInfo)")
        NotificationCenter.default.post(name: Notification.Name(rawValue: messageKey), object: nil,userInfo: userInfo)
        completionHandler()
    }
}
// [END ios_10_message_handling]

extension AppDelegate : MessagingDelegate {
    // [START refresh_token]
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        print("Firebase registration token: \(fcmToken)")
        
        updateGCMIdInServer(fcmToken)
        
    }
    
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("Received data message 10 +: \(remoteMessage)")
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: messageKey), object: nil, userInfo: remoteMessage.appData)
    }
    
    
    
    // [END ios_10_data_message]
}
```

**Comment by morganchen12** [comment]
Please file a new issue and include the payload you're trying to send to the device.
