### ISSUE TITLE
Do Not Receive FCM Token and Zero Push Notifications

### ISSUE THREAD

**Issue by JamWils** [firebase/quickstart-ios#322]
I'm trying to setup Firebase Cloud Messaging on our iOS app.  I keep getting the same error whenever I launch the app:

**[Firebase/InstanceID][I-IID003009] Failed to fetch default token Error Domain=com.firebase.iid Code=1003**

I've attempted to use the new APNs Keys as well as certificates (which worked in the past with Urban Airship).  I am receiving a call for

`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) { }`

However, I never receive a notification that the FCM Token has been updated.  In addition,  `InstanceID.instanceID().token()` and `Messaging.messaging().fcmToken` are always nil.

I've tried to fetch a token manually by calling:

```
InstanceID.instanceID().getID { (instanceID, error) in
            log.warning(InstanceID.instanceID().token() ?? "No Instance ID Token")
            let options: [String: Any] = [
                "apns_token": deviceToken,
                "apns_sandbox": 1
            ]
            InstanceID.instanceID().token(withAuthorizedEntity: "\(instanceID!)", scope: "FCM", options: options, handler: { (token, error) in
                log.error(token ?? "No token") // There is a token
                log.warning(Messaging.messaging().fcmToken ?? "No FCM Token") // There is no token
            })
        }
```

While I do receive a token it is never attached to the messaging object.  If I take the token from that response and manually call it with a POST
```
curl -X "POST" "https://fcm.googleapis.com/fcm/send" \
     -H "Authorization: key="TRIED_BOTH_LEGACY_AND_SERVER_KEY" \
     -H "Content-Type: application/json" \
     -d $'{
  "notification": {
    "body": "Testing with direct FCM API",
    "title": "Test Message",
    "badge": "0",
    "sound": "default"
  },
  "registration_ids": [
        "RESPONSE_FROM_TOKEN_WITH_AUTHORIZED_ENTITY"
  ]
}'
```
I get

**{"multicast_id":8290952520639069568,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}**

The one key thing I am doing different is that I have a beta and production version for this app that point to two different Firebase projects.  I load the beta plist manually with the following code:

```
guard let filePath = Bundle.main.path(forResource: "GoogleService-Info-Beta", ofType: "plist"),
                let fileOptions = FirebaseOptions.init(contentsOfFile: filePath) else {
                    assert(false, "Couldn't load config file")
                    return
            }
            
            FirebaseApp.configure(options: fileOptions)
```

I am able to use the Auth, Analytics, Database, and Storage with this method, but messaging is not working.  I updated to the latest version of the SDK yesterday 4.1.1. I am using Xcode 9 GM and building on iOS 11 GM.

Any help would be appreciated.

**Comment by rsattar** [comment]
Thanks for the details in the bug report. Error `1003` indicates a bad Authorized Entity, which is your GCM Sender ID. That would explain why you're not receiving a token and why sending a message to that token is resulting in a "MismatchSenderID" error.

Are you using the correct `GoogleService-Info.plist` file in your app? The `GCM_SENDER_ID` there should match the `Sender ID` in:

**Firebase Console > Project Settings > Cloud Messaging**

**Comment by JamWils** [comment]
Sorry, I've been away for the last week.  The two IDs definitely match in the project and the beta.plist.

**Comment by JamWils** [comment]
Can I provide any other information? I still cannot get this to work.  I even removed all of the custom `GoogleService-Info.plist` for dev, beta, and production.  I have verified the IDs, but I continue to get the same error.  Any help would be appreciated.

**Comment by JamWils** [comment]
Ok, got to revisit this issue over the last day.  We had manually added the Firebase framework instead of using Cocoapods.  I ditched this idea and removed it and updated all of my xcconfigs then added Cocoapods support.  It removed the error above, but then I still wasn't able to receive messages even though I now had an FCM token.  I went to the **capabilities** section for the project and turned off push notifications then deleted the **aps-environment** fields from the entitlements file.  When I turned push notifications back on in the **capabilities** section I started receiving remote notifications from Firebase.

I'm not sure what was wrong with my manual setup with Firebase, but obviously there was an issue.  Thanks.

**Comment by CheKuiLi** [comment]
Hi, JamWils.
I am having just the same status with you.

**Comment by CheKuiLi** [comment]
Could you kindly help me?
I can see the  didRefreshRegistrationToken method is never fired in real device.
But it is fired properly on the simulator.
I think I am on the previous same page of you.
Please help me.
It would be great help for me...

**Comment by kroikie** [comment]
@CheKuiLi FCM on iOS needs to be tested on a real device, please ignore the results on the simulator. Could you provide some more details of your problem in a new issue:

- error logs
- any adjustments you are making to the sample
- confirm you are using the correct GoogleServices-Info.plist file
