### ISSUE TITLE
Failed to receive remote notification to verify app identity within 5 second(s)

### ISSUE THREAD

**Issue by nezhyborets** [firebase/quickstart-ios#323]
Hi guys. 

I use Firebase Auth UI to authenticate user with phone number.
When I submit the phone number I get following error:
> <Error> [Firebase/Auth][I-AUT000014] Failed to receive remote notification to verify app identity within 5 second(s)

Though after few seconds of loading it goes to 6-digits code screen, so it's not that critical.
But AppDelegate does receive push notification, and userInfo of it does go to `canHandleNotification`, so I'm not sure why this might happen.

Here is my `didRegisterForRemoteNotificationsWithDeviceToken` code, which works fine evidently:
```
let tokenType: AuthAPNSTokenType
#if DEBUG
    tokenType = .sandbox
#else
    tokenType = .prod
#endif

firebaseAuth.setAPNSToken(deviceToken, type: tokenType)
```

Where `firebaseAuth` is simply `Auth.auth()`, `DEBUG` is TRUE

Please let me know how I can help you to debug it.

**Comment by morganchen12** [comment]
@nezhyborets if you believe this is an Auth issue, please file it over at https://github.com/firebase/firebase-ios-sdk.

**Comment by kindnesswall** [comment]
I have the same issue.
