### ISSUE TITLE
Firebase Auth: unlink provider doesn't remove the email of the provider

### ISSUE THREAD

**Issue by umarhussain15** [firebase/quickstart-ios#324]
When trying to remove a provider using unlink method the firebase removes it from the list but it does not remove the email id of the provider from user id. 
```
Auth.auth().currentUser?.unlink(fromProvider: providerID!) { (user, error) in
  // ...
}
```
So for example I have hotmail email from Facebook and gmail email from Google and currently my gmail is set as identifier. Now if I unlink the Google provider, now the identifier should be set to the hotmail email. 
But problem is that the provider is removed but email is still set to the removed identifier's email.
The unlink process works fine in Android but here this issue exists. 
Is there any solution?

**Comment by morganchen12** [comment]
Hey, if this is still an issue, please file it over at https://github.com/firebase/firebase-ios-sdk.
