### ISSUE TITLE
Firebase Messaging QS - TIC TCP Conn Failed in iOS 11

### ISSUE THREAD

**Issue by dusianandakumar** [firebase/quickstart-ios#325]
Getting crash when build with Xcode 9.Please fix this issue .Not able to open the app

TIC TCP Conn Failed [3:0x604000363240]: 3:-9802 Err(-9802)

**Comment by morganchen12** [comment]
Hey, please update this ticket with a stack trace and/or repro steps, then reopen.

**Comment by dusianandakumar** [comment]
I am Getting error like this . on opening the app , app  getting closed with this error.I am not able to launch the app also.
  
TIC TCP Conn Failed [3:0x6000001660c0]: 3:-9802 Err(-9802)
 TIC TCP Conn Failed [6:0x604000166f00]: 3:-9802 Err(-9802)

Please find the attached stack trace here.

[StackTrace.pdf](https://github.com/firebase/quickstart-ios/files/1328405/StackTrace.pdf)

**Comment by AhmedShammala** [comment]
+1
