### ISSUE TITLE
could not open the document LaunchScreen.xib" because it does not exist.

### ISSUE THREAD

**Issue by yop289** [firebase/quickstart-ios#33]
Hi
I got this error when trying to build te app

AuthenticationExampleSwift Group
/Users/rrtrtetretetr/Desktop/shared/LaunchScreen.xib
/Users/rrtrtetretetr/Desktop/shared/LaunchScreen.xib: Interface Builder could not open the document LaunchScreen.xib" because it does not exist.

BR
DAvid

**Comment by sabhay1996** [comment]
getting the same error in Authentication.

**Comment by iulukaya** [comment]
There is a dependency on the "shared" directory one below up from any quickstart.
If you clone the whole quickstart-ios repo, it will be in there.
https://github.com/firebase/quickstart-ios/tree/master/shared
