### ISSUE TITLE
Token Refresh when logged in with facebook not working 

### ISSUE THREAD

**Issue by nschucky** [firebase/quickstart-ios#330]
I'm getting this issue after logging in with facebook and opening the app 1 day after:
[Firebase/Auth][I-AUT000003] Token auto-refresh re-scheduled in 02:00 because of error on previous refresh attempt.

**Comment by morganchen12** [comment]
Hey, please re-file this issue with more information (code snippets/steps you took when authenticating with Facebook) on our [main repo](https://github.com/firebase/firebase-ios-sdk), then close this issue. Thanks!

**Comment by XiangtianDai** [comment]
@nschucky What you're seeing is just a warning that scheduled token auto-refresh wasn't successful. ID tokens are automatically refreshed before they expire when the app is running on foreground if Firebase Database (or another Firebase product that uses Firebase Auth) is used to ensure uninterrupted service, but the refresh can fail, for example, when network isn't available. This is not generally an issue, and as such we have downgraded the logging level of this message in the latest release of the SDK that it shouldn't appear in your app for app store builds.

**Comment by nschucky** [comment]
Thanks for the answer but unfortunately after this message it starts updating and downloading any kind of data from Firebase until I log out and log in again
