### ISSUE TITLE
FCM says token is valid/request success after app is uninstalled

### ISSUE THREAD

**Issue by ordinaryman09** [firebase/quickstart-ios#332]
I was testing the push notification tokens, and I uninstall the app from the device after token was generated. Then I tried to send push notification with that token which I expect to be invalidated/unregistered. However, I'm still getting a success message with that token.
When will tokens get invalidated after uninstall? I don't want the server to keep sending the request if the token is no longer valid.

**Comment by morganchen12** [comment]
Hey @ordinaryman09, sorry for the late response.

Instance IDs will become invalidated _eventually_ after an uninstallation. There's no callback on iOS on app uninstalls, so there's no way for us to invalidate every token immediately upon uninstall.

If you find that your tokens are unusually long-lived, please [file a support ticket](https://firebase.google.com/support/contact/troubleshooting/) and we'll take a look.

**Comment by ysdelahoz** [comment]
Hi 

I am also having the same issue as @ordinaryman09. When you say "eventually", what does that mean?. Is that days, months, years?. Can you please clarify ?

**Comment by morganchen12** [comment]
I don't have an exact number, but I'll update this issue once I find out.

**Comment by renanvs** [comment]
Hi @morganchen12,

In iOS, when I Uninstall a app, eventually the Token will be invalidate.

But who is the responsible for this invalidation, some Google service, or Apple service?

**Comment by kroikie** [comment]
FCM is responsible for invalidating the InstanceID token. Apple is responsible for invalidating the APNs token.

**Comment by cw-udaysolanki** [comment]
Is There anything we can detect for android??

**Comment by deejaygeroso** [comment]
hi @kroikie do you have any link for that information? 

So if apple invalidates APN token will that also results to FCM invalidating its instaceID token?

**Comment by kroikie** [comment]
@deejaygeroso The instance ID token is mapped to an APNs token so if the APNs token is invalidated then you will get a new Instance ID token that is mapped to the new APNs token.

[docs](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in)

**Comment by morganchen12** [comment]
To clarify, FCM sends to iOS devices will succeed if the APNs token has not yet been invalidated. Following an uninstall, APNs token invalidations are non-deterministic and are handled by iOS (see [this thread](https://forums.developer.apple.com/thread/86702) for more details).

Otherwise, a send to the FCM token (with invalid APNs token) will cause the FCM token to be invalidated as well.

**Comment by jayarajm** [comment]
I am facing the same issue event after 2 days. Anyone can help me out. FCM token didn't get expired until I install the app again.
