### ISSUE TITLE
Where can I set the token after it gets refreshed? 

### ISSUE THREAD

**Issue by nschucky** [firebase/quickstart-ios#333]
When I log into the app the notifications work perfectly but about 1 hour later when the token gets refreshed everything stops working and I can't even download or update any data from firebase and I get this 
`
[Firebase/Auth][I-AUT000003] Token auto-refresh re-scheduled in 02:00 because of error on previous refresh attempt.
`

I am setting the token here: 

```swift
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    // Pass device token to auth
    Auth.auth().setAPNSToken(deviceToken, type: AuthAPNSTokenType.sandbox)
    Messaging.messaging().apnsToken = deviceToken
}
````

and I'm getting the new refreshed token here but still doesn't work
```swift
func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
        Auth.auth().setAPNSToken(messaging.apnsToken!, type: AuthAPNSTokenType.sandbox)
        Messaging.messaging().apnsToken = messaging.apnsToken
    }
```

**Comment by morganchen12** [comment]
What version of Firebase Messaging are you using? If you're using 2.0.3, try downgrading to 2.0.0 and see if that resolves your issue. There's a regression in 2.0.3 that can prevent FCM tokens from being associated with the APNs device token if `UIApplication.shared.registerForRemoteNotifications()` is not called early enough.

**Comment by nschucky** [comment]
I'm using the 2.0.0, I keep getting this message `Token auto-refresh re-scheduled in 02:00 because of error on previous refresh attempt.`

**Comment by morganchen12** [comment]
Does this log message occur around any noticeable issues? This is a pretty normal log message that will be less prevalent in a future release, and is not an indicator of an issue in your app.

**Comment by nschucky** [comment]
nothing relevant I just get this message when I try to write anything to firebase `An unknown error occurred, please check the server response.` it looks like the token expired but the Auth.auth().currentUser is not nil

**Comment by nschucky** [comment]
looks like the problem is about Auth, after one hour logged in I'm not allowed to access the data from firebase even though the Auth.auth().currentUser is not nill and I get this response when I try to write to firebase `An unknown error occurred, please check the server response.
`

**Comment by morganchen12** [comment]
What does the server response say?
