### ISSUE TITLE
iOS phone-auth error_name=ERROR_MISSING_APP_TOKEN

### ISSUE THREAD

**Issue by srgzah** [firebase/quickstart-ios#335]
Hi,
During the authorization through the phone on iOS app I get this error:

`FUIAuth: Error Domain=FIRAuthErrorDomain Code=17053 "There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth" UserInfo={NSLocalizedDescription=There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth, error_name=ERROR_MISSING_APP_TOKEN}`

I set up Firebse as written in the [documentation](https://firebase.google.com/docs/cloud-messaging/ios/certs)
I can not understand what the problem is. Everything seems to be right.

How can i solve this? Thanks.

**Comment by morganchen12** [comment]
The documentation you've linked goes to the FCM setup, not the Phone Auth setup. While Phone Auth does use silent notifications, it also has a failure mode for when those notifications are not deliverable. Please re-integrate Phone Auth into your project by following the instructions [here](https://firebase.google.com/docs/auth/ios/phone-auth); if you're still running into issues, please file them at the [main sdk repo](https://github.com/firebase/firebase-ios-sdk).

**Comment by wemersonjanuario** [comment]
I have the same problem with iOS.
@srgzah How did you solve this?

Any help is apreciated! thank you

**Comment by hsyyid** [comment]
Hi, I know this is an old issue but I wanted to share a solution:

> the solution was that I needed to go the **Capabilities** of the app and then make sure **Background Modes** as well as **Push Notifications** (this was already enabled) were enabled. Then under **Background Modes** I had to enable **Remote notifications**.
> 
> Then I had to delete the app from my device and reinstall. This solved my issue and called the necessary functions for registering for notifications.

Credit to: https://stackoverflow.com/a/46717155/5112933
