### ISSUE TITLE
Firebase registration token is not updated when app is restored on a new iphone device

### ISSUE THREAD

**Issue by mgorkani** [firebase/quickstart-ios#337]
scenario:
I updated my phone from iPhone 7 to iPhone 8. My app uses the callback method:
 (void)messaging:(nonnull FIRMessaging *)messaging didRefreshRegistrationToken:(nonnull NSString *)fcmToken
to get a new firebase token (we allow the swizzling of the didRegisterForRemoteNotificationForDeviceToken) and save to our backend server. If I reinstall our app, this method is called with a new firebase token after user allows remote notifications. When I upgrade from my phone restoring my backed up app to a new iphone, this method was not called when the app is first launched. Our backend server still thinks the firebase token is the same, but we are no longer able to send notifications using it. According to Apple documentation, a new APNS token is generated when you restore your app to a new device. Since the other apps on my phone are sending notifications, I'm wondering if there's a bug for Firebase for this scenario. We are using FirebaseMessaging (= 2.0.2) and FirebaseInstanceID (~> 2.0)

**Comment by morganchen12** [comment]
What's the version of FirebaseInstanceID you're using? If you haven't already, does upgrading to 2.0.4 fix the issue?

**Comment by mgorkani** [comment]
It is using version 2.0.0 for FirebaseInstanceID. Let me update to the latest version to see if that resolves this issue.

**Comment by morganchen12** [comment]
@mgorkani is this still an issue?
