### ISSUE TITLE
An SSL error has occurred and a secure connection to the server cannot be made

### ISSUE THREAD

**Issue by Sea-Eagle** [firebase/quickstart-ios#339]
While running my app with iOS 11 and XCode 9 I'm getting this error , some times not frequesnlty ? till iOS 10 and XCode 8 it worked fine. 

**Error 1:** 

Failed to subscribe to topic Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c0449f00 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://iid.googleapis.com/iid/register, NSErrorFailingURLStringKey=https://iid.googleapis.com/iid/register, _kCFStreamErrorDomainKey=3}

**Error 2:** 
TIC TCP Conn Failed [3:0x6040003627c0]: 3:-9802 Err(-9802)
2017-10-10 12:51:47.059149+0530 MyApp[11781:227385] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
2017-10-10 12:51:47.059353+0530 MyApp[11781:227385] Task <91287390-CC8A-4F32-8403-929E95353B4B>.<1> HTTP load failed (error code: -1200 [3:-9802])
2017-10-10 12:51:47.060064+0530 MyApp[11781:227383] Task <91287390-CC8A-4F32-8403-929E95353B4B>.<1> finished with error - code: -1200
2017-10-10 12:52:39.286401+0530 MyApp[11781:228768] TIC Read Status [5:0x0]: 1:57
2017-10-10 12:52:39.286849+0530 MyApp[11781:228768] TIC Read Status [5:0x0]: 1:57
2017-10-10 12:52:43.375836+0530 MyApp[11781:228768] TIC Read Status [6:0x604000366540]: 1:57
2017-10-10 12:52:43.376470+0530 MyApp[11781:228768] TIC Read Status [6:0x604000366540]: 1:57
2017-10-10 12:52:43.377415+0530 MyApp[11781:228768] TIC Read Status [6:0x604000366540]: 1:57
2017-10-10 12:54:38.998920+0530 MyApp[11781:230845] TIC Read Status [2:0x600000361440]: 1:57
2017-10-10 12:54:38.999998+0530 MyApp[11781:230845] TIC Read Status [2:0x600000361440]: 1:57
2017-10-10 12:54:39.000339+0530 MyApp[11781:230845] TIC Read Status [2:0x600000361440]: 1:57
2017-10-10 13:09:16.756803+0530 MyApp[11781:246165] [Client] Discarding message for event 0 because of too many unprocessed messages

**Comment by mr-fixit** [comment]
I stumbled on your question while researching my own version of it.  My version of problem1 was solved by tweaking various settings inside the `NSAppTransportSecurity` dictionary inside `Info.plist`.

**Comment by ankitaswap1690** [comment]
@mr-fixit Could you please provide the settings you changes in info.plist?
I have added "Allow arbitrary Loads" as Yes under NSAppTransportSecurity. And I am getting this error for iOS11. It is resolved for iOS 10 and lower.

**Comment by JasonGreenAmerica** [comment]
Firebase is down
https://status.firebase.google.com/

**Comment by ramunasjurgilas** [comment]
For me same problem.

**Comment by morganchen12** [comment]
Hey all, 

There's not enough information in this issue to accurately debug it. If you're running into this problem, try cloning the sample projects in this repository and running them. If the problem goes away, that means there's something wrong with your project configuration. Otherwise, please share your network conditions and how to reproduce the error in a **new issue** and we'll try to help you out.

**Comment by agueroveraalvaro** [comment]
Same error here,

`Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x60000044f450 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.mydominio.cl:40001/ApiRest/api/login?user=admin&pass=3b24fa7sddasaae14555a1912e5bc2198f8e075&app=9&os=3`

`https://api.mydominio.cl:40001/ApiRest/api/login?user=admin&pass=3b24fa7sddasaae14555a1912e5bc2198f8e075&app=9&os=3`

Maybe is there a problem with the port ?

**Comment by morganchen12** [comment]
The URL provided in your error isn't a Firebase or Google URL. Try posting over at StackOverflow.

**Comment by Hassan-Aftab** [comment]
I am also getting same error

**Comment by saudahmed** [comment]
I am also getting the same error. Using iOS SDK, Xcode 10, iOS 11. Previously i never got this. APNs Authentication key is already set. NSAppTransportSecurity is already set to true.

TIC TCP Conn Failed [4:0x1c0362f40]: 3:-9802 Err(-9802)
TIC TCP Conn Failed [5:0x1c0363840]: 3:-9802 Err(-9802)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Task <8EF885D2-B87F-4752-8D14-D2ECCC7958B8>.<1> HTTP load failed (error code: -1200 [3:-9802])
Task <8EF885D2-B87F-4752-8D14-D2ECCC7958B8>.<1> finished with error - code: -1200
2018-12-17 19:48:10.439556+0500 ZZizzle-mobile[1248:1538516] <Firebase/Network/ERROR> Encounter network error. Code, error: -1200, Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c405f890 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://play.googleapis.com/log, NSErrorFailingURLStringKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=3}
[Firebase/Core][I-NET901017] <Firebase/Network/ERROR> Encounter network error. Code, error: -1200, Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c405f890 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://play.googleapis.com/log, NSErrorFailingURLStringKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=3}
[Firebase/Core][I-COR000020] Error posting to Clearcut: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c405f890 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://play.googleapis.com/log, NSErrorFailingURLStringKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=3}, with Status Code: 0

**Comment by romulomtelles** [comment]
same error!

NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://cast2.audiostream.com.br:2000/stream, NSUnderlyingError=0x600002a4cc90 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9836, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9836}}, _kCFStreamErrorCodeKey=-9836} [-1200]


Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made.


What I realized, it happens when I pass an URL that probably it is not safety, even if being https.

**Comment by aasyria** [comment]
any sulition ?

**Comment by sinnkirou** [comment]
same issue here, any progress?

**Comment by voyager163** [comment]
Having same issues

**Comment by shahla00** [comment]
Anyone was able to figure it out?

**Comment by umair2ooo** [comment]
I am still facing this issue

**Comment by Lupobb** [comment]
Lupobb


Il gio 29 dic 2022, 07:21 umair2ooo ***@***.***> ha scritto:
