### ISSUE TITLE
<FIRAnalytics/ERROR> Transaction failed

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-ios#34]
In my app, I am calling `[FIRApp configure];` not exactly in `application didFinishLaunchingWithOptions` but early enough before anything else starts.

And when I look at the xcode console, it says:

```
<Notice>: <FIRAnalytics/INFO> Firebase Analytics v.3200000 started
<Notice>: <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
<Notice>: <FIRAnalytics/INFO> Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
<Notice>: <FIRAnalytics/INFO> Firebase Analytics enabled
<Notice>: Sandbox: myappname(2327) deny(1) file-write-create /private/var/mobile/Containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP
```

Which seems good, accept for the last line which I don't understand what it's about!

The actual problem is the following error message which happens as soon as I click on a test Admob banner. When my app switches to Safari browser, Firebase throws this error. but this does not crash the app at all. everything seems normal.

```
<Error>: <FIRAnalytics/ERROR> Data loss. Cannot record raw event. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=3 "Database operation "execute statement" failed with sqlite code 20 and error message "could not convert floating point value to integer without loss of data."" UserInfo={FIRAMonitorContext=execute statement,20,A,3, NSLocalizedDescription=Database operation "execute statement" failed with sqlite code 20 and error message "could not convert floating point value to integer without loss of data."}
<Error>: <FIRAnalytics/ERROR> Transaction failed
```

Now, what this problem leads? in my Firebase console, I am not seeing reports! we have created two projects in our Firebase console, one for our Android app and another one for the iOS. We are able to see the analytic on the Android side but the iOS side still shows `0 monthly active users`.

Please give us an advice on what could be the problem?

> `[FIRApp configure];` This method should be called after the app is launched and before using Firebase services.

NOTE: Because of some reasons, we can NOT call `[FIRApp configure];` from `application didFinishLaunchingWithOptions` but we do call it a bit later. If this is the problem, which I don't think it is because if it was, the console logs should have said so, what solution do we have?

Thanks a lot in advanced and  we can't wait to start developing using Firebase. It's just so awesome.

**Comment by myflashlab** [comment]
I should add that the app we are testing, is not uploaded itunesConnect yet... I hope That's not the reason, is it?

**Comment by myflashlab** [comment]
No Updates on this? I wonder?

**Comment by myflashlab** [comment]
Still waiting for "any" hint? we are totally stuck at this stage...

**Comment by baolocdo** [comment]
Thanks for reporting in details. The last line 
`<Notice>: Sandbox: myappname(2327) deny(1) file-write-create /private/var/mobile/Containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP`
is a known bug and we are on it. 
Can you please turn on debug using application argument -FIRAnalyticsDebugEnabled and provide the debug log?

**Comment by myflashlab** [comment]
Thanks for getting back to us on this. About turning on the
-FIRAnalyticsDebugEnabled
parameter, unfortunately we can't do that because we are compiling the
project in Adobe Air and that debug parameter can run on xCode only (if I'm
not wrong) do you have any other advice?

On Wednesday, July 6, 2016, Alex Do <notifications@github.com> wrote:

> Thanks for reporting in details. The last line
> <Notice>: Sandbox: myappname(2327) deny(1) file-write-create
> /private/var/mobile/Containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP
> is a known bug and we are on it.
> Can you please turn on debug using application argument
> -FIRAnalyticsDebugEnabled and provide the debug log?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firebase/quickstart-ios/issues/34#issuecomment-230823806>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFKIUiLTiPHM1OR_MSObTzd7uf86bks5qS9TggaJpZM4IuHfq>
> .
>


-- 
Sent from iPhone

**Comment by baolocdo** [comment]
I don't know much about Adobe Air to advise. However, we think we found the problem and will try to produce the fix soon. Thanks for reporting.

**Comment by myflashlab** [comment]
cool, waiting for the new release. as soon as it's released, we will test it and let you know the results.

**Comment by myflashlab** [comment]
I just updated to iOS V3.6.0 and we are still having the very same problem. Let me know how I can help you in finding and fixing the problem on your side.

**Comment by baolocdo** [comment]
Due to some technical issues, we have not pushed the fix for this bug out yet. Sorry for the late response.

**Comment by baolocdo** [comment]
Update: The bug regarding this
`<Notice>: Sandbox: myappname(2327) deny(1) file-write-create /private/var/mobile/Containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP`
was fixed and should not show up in the latest release of Firebase Analytics.
However, regarding Adobe Air support, we still have not released the fix yet due to some technical issues. Thanks for reporting.

**Comment by myflashlab** [comment]
@baolocdo Thanks for your update. We are totally looking forward to the other fix. You know, the whole Adobe AIR community is currently dependent on us to have this feature of the Firebase project available to them along with the other pieces. https://github.com/myflashlab/Firebase-ANE

I'm sure a lot AIR developers will be happy as soon as you fix the ```<FIRAnalytics/ERROR> Data loss``` issue :) Thanks.

**Comment by TimKoppers** [comment]
@baolocdo Thanks for the headsup. Would be great if you guys can fix this error, I'm depending on it to integrate Firebase analytics in our game (iOS and Android).

Thanks a lot!

**Comment by mrgoonie** [comment]
Hi @baolocdo @myflashlab , just curious, do you guys have any ideas regarding estimating the release date of the fix? 

My app is about to release soon & this is our final step. I'm on fire, mates 😃 

Thanks,

**Comment by baolocdo** [comment]
Unfortunately, we don't have an estimate fix for this bug. We have to prioritize other bug fixes and features but we do have an eye on this bug and we are trying to fix it as soon as we can. Sorry for keeping you waiting.

**Comment by mrgoonie** [comment]
Thanks for the notice @baolocdo . Please keep us posted! Really appreciated for your team's effort, keep going strong!

**Comment by adammendoza** [comment]
I'm getting this error too. Are there any work arounds?

**Comment by baolocdo** [comment]
Currently, there is no work around. We have the fix and it will probably be released in the next release.

**Comment by myflashlab** [comment]
@baolocdo Awesome :) we are eagerly waiting for that. If that's happening in the next updated release, we will test it imminently and let you know the results.

**Comment by ambient-sky** [comment]
Thanks @baolocdo, we're eagerly awaiting this, too, as we're about to start a big AdWords campaign and are only able to collect attribution data on Android without this fix. We really want to be able to collect attributation data for iOS, too. We'd be happy to beta test and confirm your fix.

**Comment by baolocdo** [comment]
Good news: The fix has just been released in Firebase Analytics 3.7.0. Please upgrade to the latest version and let us know if it fixes this error. Thanks for reporting!

**Comment by myflashlab** [comment]
Awesome @baolocdo I can confirm that it works fine now :)

**Comment by baolocdo** [comment]
Great! Thanks for confirming that it works!
