### ISSUE TITLE
No able to install firestore via pods

### ISSUE THREAD

**Issue by abdulKarim002** [firebase/quickstart-ios#340]
all other pods are working fine but after adding firestore to pod list it give me this error

    `Analyzing dependencies
     [!] Unable to satisfy the following requirements:

    - `Firebase/Firestore` required by `Podfile`

    Specs satisfying the `Firebase/Firestore` dependency were found, but they required a higher minimum deployment target.`

My app pod file

    `platform :ios, '8.0'
     use_frameworks!

    target 'MyApp' do
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Google/SignIn'
    pod 'Kingfisher', '~> 3.0'
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
    pod 'IQKeyboardManager'
    pod 'Fabric'
    pod 'Crashlytics', '~>  3.8'
    pod 'Google/Analytics'
    pod 'GoogleIDFASupport'
    pod 'Analytics', '~> 3.0'
    pod 'IBAnimatable'
    pod 'SwiftyJSON'
    pod 'Mixpanel-swift'
    pod 'ReverseExtension'
    pod 'Zip','~> 0.7'
    end

    target 'MyAppTests' do

    end

     target 'MyAppUITests' do

    end

```
Other version details
Swift - 3x
Xcode - 9
ios deployment target - iOS 9
cocoapod version - 1.3.1
```

**Comment by morganchen12** [comment]
if you run `pod update` does the issue go away? Your podfile looks fine at first glance.

**Comment by abdulKarim002** [comment]
@morganchen12  I have updated the pods which I was using previously and I guess some of the other pod is the issue which not allows firestore to install. because if I comment all the pod and just install 
` pod 'Firebase/Firestore'` then the installation works.

**Comment by morganchen12** [comment]
What's the minimum deployment target of your app?

**Comment by abdulKarim002** [comment]
every version details are mention above 
`ios deployment target - iOS 9`

**Comment by morganchen12** [comment]
I'm unable to reproduce this issue with your Podfile. Here's the output when I run `pod install`.

```
morganchen-macbookpro:TestProj morganchen$ pod install
Analyzing dependencies
Downloading dependencies
Using Analytics (3.6.7)
Using BoringSSL (9.0)
Using Crashlytics (3.9.0)
Using Fabric (1.7.0)
Using Firebase (4.3.0)
Using FirebaseAnalytics (4.0.4)
Using FirebaseAuth (4.2.1)
Using FirebaseCore (4.0.8)
Using FirebaseDatabase (4.1.0)
Using FirebaseFirestore (0.8.0)
Using FirebaseInstanceID (2.0.4)
Using GTMSessionFetcher (1.1.12)
Using Google (2.0.4)
Using GoogleAnalytics (3.17.0)
Using GoogleAppUtilities (1.1.2)
Using GoogleAuthUtilities (2.0.2)
Using GoogleIDFASupport (3.14.0)
Using GoogleInterchangeUtilities (1.2.2)
Using GoogleNetworkingUtilities (1.2.2)
Using GoogleSignIn (3.0.0)
Using GoogleSymbolUtilities (1.1.2)
Using GoogleToolboxForMac (2.1.3)
Using GoogleUtilities (1.3.2)
Using IBAnimatable (5.0.0)
Using IQKeyboardManager (5.0.3)
Using Kingfisher (3.13.1)
Using MBProgressHUD (0.9.2)
Using Mixpanel-swift (2.2.1)
Using OneSignal (2.5.6)
Using Protobuf (3.4.0)
Using ReverseExtension (0.4.8)
Using SwiftyJSON (3.1.4)
Using Zip (0.8.0)
Using gRPC (1.6.5)
Using gRPC-Core (1.6.5)
Using gRPC-ProtoRPC (1.6.5)
Using gRPC-RxLibrary (1.6.5)
Using leveldb-library (1.18.3)
Using nanopb (0.3.8)
```

Try clearing out your CocoaPods cache (`rm -rf ~/Library/Caches/CocoaPods`) and see if running `pod install` again resolves the issue.

**Comment by abdulKarim002** [comment]
@morganchen12 thanks know after clearing the cache its works
