### ISSUE TITLE
 FirebaseCrash 999+ warnings when submitting to iOS App Store 

### ISSUE THREAD

**Issue by patelnirav48** [firebase/quickstart-ios#342]
Hi @morganchen12 & All,

I've installed Firebase Crash into my app (without using Pods) but, when I try to submit it to the iOS App Store, I get the following warnings:

Shell Script Invocation Warning

warning: dump_syms: /Users/keyur/Library/Developer/Xcode/DerivedData/AppName-fqjjngsvfgfketelvyyfcbrycjgz/Build/Intermediates.noindex/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/AppName.app.dSYM/Contents/Resources/DWARF/AppName, architecture : in compilation unit '/Users/keyur/Desktop/CCG/Live_Current_Projects/SVNLIVEPROJECTS/AppName/AppName/ThirdPartyCode/DateTimePicker/AAPickerView+Helper.swift' (offset 0x4f7b8):

warning: dump_syms: /Users/keyur/Library/Developer/Xcode/DerivedData/AppName-fqjjngsvfgfketelvyyfcbrycjgz/Build/Intermediates.noindex/ArchiveIntermediates/AppName/BuildProductsPath/Release-AppName/AppName.app.dSYM/Contents/Resources/DWARF/AppName, architecture : the DIE at offset 0x78634 has a DW_AT_abstract_origin attribute referring to the die at offset 0x78647, which either was not marked as an inline, or comes later in the file

![screen shot 2017-10-11 at 12 32 31 am](https://user-images.githubusercontent.com/1640319/31405246-18694b2a-ae1c-11e7-91a5-5d4efd3ecbae.png)

![screen shot 2017-10-11 at 12 38 25 am](https://user-images.githubusercontent.com/1640319/31405417-a1d27f44-ae1c-11e7-8489-69f1aa96d460.png)

![screen shot 2017-10-11 at 12 45 32 am](https://user-images.githubusercontent.com/1640319/31406042-8ba1d5ca-ae1d-11e7-90f7-4138fa615972.png)

Please help. Thanks!

**Comment by patelnirav48** [comment]
@morganchen12  I am using Firebase-4.3.0

**Comment by patelnirav48** [comment]
@morganchen12  Can you please help me on this? Any update please?

**Comment by morganchen12** [comment]
I don't have a definitive solution, but if you'd like to get rid of the warnings, you can do so by cleaning out your DerivedData (they'll appear the next time you archive, though). The warnings aren't indicative of an issue in your app so you shouldn't have any problems uploading to iTunesConnect.

Can you share a project that reproduces this?

**Comment by morganchen12** [comment]
Filed internally, will keep this ticket updated with info.

**Comment by patelnirav48** [comment]
Hi @morganchen12 Thanks for your reply, I did cleaning out derived data but warnings were there still. There is no issue with my app even i submitted app to store with warnings. but just concerned why there are lots of warnings.

Can you share a project that reproduces this? 
Sorry what you mean by this? you wants the link to download the app ?

**Comment by morganchen12** [comment]
If you have an Xcode project that you're willing to share, it'll help the crash reporting folk solve the issue faster as they can diagnose it directly in the project.
