### ISSUE TITLE
Problems to receive push notifications in my iOS app (send to all users segment)

### ISSUE THREAD

**Issue by pedro-lopez** [firebase/quickstart-ios#345]
I´m having problems to receive push notifications in my iOS app from Firebase web composer if I send it to "all users" (everything ok with send to topic or single device). I made no changes on my app (only update CocoaPods dependencies). Last week works perfectly.

I receive OK in the Android app and never in iOS app (the same message to "all users"). Certificates are correct because I receive the push notification OK if I send it for topic or single device.

Same problem with Firebase with quickstart-ios example app connected to my instance.

Looks like my installed app is not included in the all users segment.

Does anyone else have this problem?

Thanks in advance.

**Comment by Nightstep** [comment]
The same problem. Subscribed 2 devices, first device receives, second - nothing. Used latest firebase sdk installed via cocoapods

**Comment by 5tr0k3** [comment]
Same here some people receive notification, and some dont

**Comment by lsalvoni** [comment]
+1, I have 3 devices running iOS 9, 10 and 11. (all public releases, no betas) Sending a push notification to a single device works great in the background & foreground.

However, sending to the iOS 10 device whilst part of a "all users" segment for the app does not work, and the device never receives the push notification.

**Comment by mborsten** [comment]
Same problem. Just setting up a new app and when testing with sending to a specific iOS device it works as expected, but when sending to a segment no push messages are received.

**Comment by amervil** [comment]
Same issue here. Only receive notification if it's sent to unique device. Nothing happens when trying "all users"
iOS 11, swift 4, Firebase 4.4.0, FirebaseMessaging 2.0.5

**Comment by lsalvoni** [comment]
Just updated to FirebaseCore 4.0.9 and FirebaseMessaging 2.0.5 using Cocapods and still get the same results as my previous message above. (iOS 10 device not receiving push notification when part of a user segment by app ID)

**Comment by ooCHURIoo** [comment]
We have the same problem, a ticket is open to the firebase support. The technical team investigate.

**Comment by teto100** [comment]
+1 Same Problem, I always receive the push notifications when targeting a single device (Token) and never receive notifications when sending to a User Segment .  Additionally notifications do not come to the foreground.

pod 'FirebaseInstanceID', '2.0.4'

**Comment by gabber3000** [comment]
Hello to all.
I have configured a .p8 certificate in the firebase console successfully.
Unfortunately, I only send a token notification.
If I through console try to send a normal notification to my iphone does not work.
Can someone help me ?
thank you.

**Comment by hungchicheng** [comment]
Same problem. Sent to unique device is fine.
But when sent to all users, some iOS 10 devices aren't received.

**Comment by ooCHURIoo** [comment]
@teto100 no it's email exchanges

**Comment by gabber3000** [comment]
hi guys after two days i got it !!! :)
To display the notification message correctly, set the priority to send to the status -> NORMAL **<-** and not high.
I would never have thought of this stupid grrrrrr

**Comment by ooCHURIoo** [comment]
@gabber3000  your solution doesn't work for us

**Comment by gabber3000** [comment]
@ooCHURIoo I have installed the new certified. p8 did you use the old procedure?

**Comment by shomscheidt** [comment]
@gabber3000 Does that work for you using User Segment after a fresh install of your app?

**Comment by gabber3000** [comment]
this morning everything worked properly now it does not work anymore :( this framework does not seem to work well.

**Comment by teto100** [comment]
@gabber3000 I have updated to version 2.0.5 but it still does not work, I have also changed the priority of the message (only
I get high and a half) but it does not work for a segment of users.

**Comment by kroikie** [comment]
Hi All, the issue with messages sent to user segments is actively being worked on internally, we will update here as soon as a resolution is available.

**Comment by ooCHURIoo** [comment]
th support juste send me a reponse

> We've implemented a potential solution for new registrations. We'll continue to monitor and make further fixes if necessary. You can keep an eye out on our release notes for further updates.

> 

I will try this morning.

**Comment by kroikie** [comment]
@ooCHURIoo  is correct. Closing this issue now, please open another if this type of issue returns.
