### ISSUE TITLE
can receive notification from firebase console but not from own server on iOS

### ISSUE THREAD

**Issue by damathryx** [firebase/quickstart-ios#347]
In android it works fine I get both notification  from firebase console as well as my own notification server but in iOS i can only receive notification from firebase. Am I missing a setup?

podfile
```
  pod 'Firebase/Core', '4.0.0'
  pod 'FirebaseMessaging'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
```
this is in my AppDelegate.m
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  [RNFIRMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
}

#if defined(__IPHONE_11_0)
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler
{
  [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
#else
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)())completionHandler
{
  [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
#endif

-(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [RNFIRMessaging didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [RNFIRMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
```

ios: 11
xcode: 9
react-native-fcm:  10.0.1
react-native: 0.47.1

**Comment by damathryx** [comment]
sorry wrong place

**Comment by fredbt** [comment]
I'm actually having the same problem here :)

**Comment by morganchen12** [comment]
@fredbt there's most likely something wrong with the payload you're sending to FCM. What's your server sending?

**Comment by fredbt** [comment]
Thanks @morganchen12 ... it is very likely you have nailed it. I've moved from react-native-push-notification to react-native-fcm today and did not update my payload format. It is not an issue for Android, but for iOS it is, apparently.

I cannot test now but after reading your comment and watching this video (https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html which is not actually about react-native-fcm but has a good content anyways) I am almost we will figure this out.

Again, thank you so much!

**Comment by morganchen12** [comment]
Take a look at Apple's [APNs payload key reference](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1) as well. If you're sending to iOS, your FCM payload must produce a valid APNs payload as well, or APNs won't deliver your notification.
