### ISSUE TITLE
@import Firebase; OR @import FirebaseAnalytics;

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-ios#35]
[Documentations](https://firebase.google.com/docs/ios/setup#initialize_firebase_in_your_app) says to import this module
```
@import Firebase;
```
but that's not found! instead I am importing:
```
@import FirebaseAnalytics;
```

Is it OK? if it is, I think you should fix the documentations unless I'm missing something? please advice.

**Comment by iulukaya** [comment]
You should be able to import Firebase. Analytics is only one of the dependencies that's packaged inside Firebase module.
Try using the cocoapods 1.0 and do a pod update.
Cheers

**Comment by jmrobison** [comment]
I did the manual install method (Firebase.zip file), and FirebaseAnalytics.h is not in the supplied file. Does it get generated? Is there a missing dependency in the .zip file?
