### ISSUE TITLE
Firebase Dynamic links behaviour on iOS 8 vs. iOS 10

### ISSUE THREAD

**Issue by ondrokrc** [firebase/quickstart-ios#350]
I have an app already on App Store that has a custom URL scheme registered.
I implemented Firebase Dynamic Links for the new version of the app.
When testing the new links, when I open a FDL with the old App installed on iOS 10, I get redirected to the App Store to update the app.
When I open a FDL with the old App installed on iOS 8, the old app is opened because openUrl for my URL scheme is triggered. My app crashes because of this, because the old app is unable to handle such link.
I expected  that on iOS 8 it would also redirect me to the App Store to update the App as it does on iOS 10.

Even sending imv=min_app_version (as described [here](https://firebase.google.com/docs/dynamic-links/create-manually)) as a part of the FDL does not help.

Why is this behavior different between iOS 8 and 10? Is there any way how to stop this happening on iOS 8?
Thank you.

**Comment by morganchen12** [comment]
Hey, please move this issue over to https://github.com/firebase/firebase-ios-sdk/issues.
