### ISSUE TITLE
The file “MessagingExample” couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by nikolas7892** [firebase/quickstart-ios#351]
This suddenly came up out of no where...
<img width="407" alt="screen shot 2017-10-15 at 1 02 51 pm" src="https://user-images.githubusercontent.com/11046180/31588590-39568d44-b1a9-11e7-9761-ad2d19ad31d7.png">

**Comment by morganchen12** [comment]
This seems to be a macOS permissions issue?

https://support.apple.com/kb/PH25247?locale=en_US&viewlocale=en_US
