### ISSUE TITLE
FCM Swift - Application does not receive message data in background - iOS 11

### ISSUE THREAD

**Issue by abharku** [firebase/quickstart-ios#360]
It was all working for me till I upgraded my iPhone to 11.0.3 and now I can only send notification messages and silent messages just won't arrive on the phone. Our app functionality includes performing some background task before notifying user with what has been done so a notification message which immediately display in the tray with data being processed only when user clicks the notification doesn't cut it. I guess its to move to APNs directly as I also read that data message are stored by FCM to be delivered when an active connection with app is made which doesn't help at all.

These are the pods we use:
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/AdMob'
pod 'Firebase/Crash'
And we are sending message to a token as we target individual users. Since then I have tried every combination of message we have found on the web but nothing has worked. The one that was working earlier is:

$fields = array (
            'registration_ids' => array (
                    $id
            ),
            'priority'=>"high",
            'content_available' => true,
            'data' => array (
                    "message" => $message
            ),
            'time_to_live' => 300
    );

**Comment by kroikie** [comment]
Hi @abharku the format of your message looks fine to me, so I would expect that your device would receive a silent notification in this case. Could you confirm the response you are getting from FCM when you send the message?

**Comment by abharku** [comment]
@kroikie it just doesn't arrive. So I am assuming it's not going pas APNs at all. At the same time if I add a notification to the message:

   notification' => array (
                    "body" => "message",
                    "title" => "App Name"
            ),
It appears straight away but obviously nothing is done in the background which is what we want to achieve and also the notification string is worked out on the phone so we use local notification after finishing our tasks

**Comment by abharku** [comment]
@kroikie Sorry not your issue. Apparently my appdelegate never liked it because we were using location service and app needs two new permissions to work in IOS 11. One of the functions of notification was to access location and it was never reaching print statement:

NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription 

After adding these everything works as designed.

**Comment by kroikie** [comment]
@abharku glad you got it sorted!
