### ISSUE TITLE
Impossible to compile project with Firestore 

### ISSUE THREAD

**Issue by jamesTheKid** [firebase/quickstart-ios#361]
I can't compile my project with Firestore. I'm having `ld: framework not found GRPCClient`

Everything was working fine before I decide to try Firestore.

<img width="853" alt="screen shot 2017-10-21 at 03 31 48" src="https://user-images.githubusercontent.com/631062/31846811-0c5c00dc-b611-11e7-98cc-bca73515184f.png">

**Comment by morganchen12** [comment]
What version of CocoaPods are you using? You'll need to make sure the GRPCClient framework is visible to your Xcode project (check your framework search paths).

**Comment by jamesTheKid** [comment]
Am using cocoapod 1.1.1 .

**Comment by morganchen12** [comment]
Update to the latest version of CocoaPods and double check your framework search paths.

**Comment by moebiussurfing** [comment]
i am having the same problem. also updated to the last cocoa pod...

I followed the tutorial and added this:
 ```
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'
```
    
also:

`pod install --repo-update`

open StorageExample.xcworkspace/

**Comment by moebiussurfing** [comment]
it worked here, sorry.
hey @jamesdaniels :
I only added: 
`platform :ios, '8.0'`
to the Podfile.

Not this lines:
 `pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'`

and just: 
`pod install `(without the --repo args)

pod version 1.4.0.beta.2 here.
