### ISSUE TITLE
.sendEmailVerification stalling or not sending an email 

### ISSUE THREAD

**Issue by carlosdelamora** [firebase/quickstart-ios#366]
I have the following function  
    
     fileprivate func sendEmailVerification() {
             FIRAuth.auth()?.currentUser?.sendEmailVerification(completion: { (error) in
                guard error == nil else {
                    print("we got error with the email")
                    return
                }
            
                print("we sent verification")
            })
        }

It does get called and "we sent verification" gets printed. However, the email takes forever to arrive, or it never reaches. Any idea what might be wrong?

**Comment by morganchen12** [comment]
This is something you should file through Firebase Support's [troubleshooting page](https://firebase.google.com/support/contact/troubleshooting/), since this issue is not likely to be caused by your implementation.
