### ISSUE TITLE
messaging: warning completionhandler

### ISSUE THREAD

**Issue by dermaaarkus** [firebase/quickstart-ios#37]
After runningthe sample project for messaging i've send an notification to the app. The notification does arrive, but the logs says:

> Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

please add `completionHandler(UIBackgroundFetchResultNewData);` to avoid this warning and let developers do not forget this line by copying your code ;)

**Comment by revolter** [comment]
This was fixed in #189. @ianbarber, please close this.
