### ISSUE TITLE
I am also facing same issue

### ISSUE THREAD

**Issue by maheshmobile** [firebase/quickstart-ios#372]
i am receiving notification in both foreground and background but i need to et badge icon when app is in background state. but i am unable to do because the both methods didReceiveRemoteNotification,didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) not triggered

**Comment by morganchen12** [comment]
Please share your code and describe the steps you took to integrate FCM.
