### ISSUE TITLE
Firebase Cloud Messaging Settings requires iOS Team ID not App Prefix

### ISSUE THREAD

**Issue by johncovele** [firebase/quickstart-ios#381]
Not sure where the proper place to submit this is, but the docs needs to be updated here and on the firebase web portal, too. After banging my head against the wall for 3 days, I finally stumbled across a user comment that solved my issue so I wanted to share. The problem is getting a failed push notification with "Invalid APNs Certificate" message (and you will only see this message when sending to an individual device).

Most of the time, this problem seems to be caused by improper configuration, such as a typo in the bundle name, bad entitlements in App ID, etc. However, if all else fails, you need to use your developer "Team ID" instead of the "App Prefix" in the Firebase App Settings. I am using the newer push auth key method, not the push certificate method, so when you think about it this makes sense (the auth key applies to ALL your apps, the certificates apply to one app only).

**Comment by morganchen12** [comment]
Which docs are you referring to in particular?

**Comment by johncovele** [comment]
I guess as I look through the docs that come with this project, you don't really go into details about the console settings and don't mention app prefix, so there is no misinformation here. However, it would be nice to have a troubleshooting checklist here that shows all the ways you can screw up if pushes are not working.

Ultimately these docs needs to get updated:

--The help bubble next to "App Prefix" on the Project Settings page (in console)

--This page in the console docs: https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by morganchen12** [comment]
That docs change doesn't specify the App ID prefix as an input anywhere. I'll see about getting the console text changed, since it should really say "App ID Prefix or Team ID".

**Comment by morganchen12** [comment]
For context, normally these two values (app ID prefix and team ID) are identical. Can you try to figure out why yours aren't? I'm curious to see what conditions can make this error more likely.

**Comment by johncovele** [comment]
That is a really good question. When I create a new App ID in the developer account, the default Prefix at the top of the list is labeled "team ID". I also have 8 other ID's in the list, presumably these are ID's that got used in the past. I have been developing apps since way back in 2008, so I can only guess that early versions of the developer portal (or maybe Xcode) did some strange things. All my recent apps seem to have the proper team ID, but the legacy app that had the problem was created in 2013.

**Comment by morganchen12** [comment]
Can you check the team ID in the APNs certificate you're using? That one should be the source of truth.

Ultimately I don't think we should recommend "Team ID or App ID prefix" in situations where they may be different, since this leaves it up to the developer to guess and check until their notifications work. I think it makes more sense to put a warning dialogue in our docs saying the ID must match the one in the console.

**Comment by johncovele** [comment]
I'm using the newer auth key, not a certificate, so it doesn't show any app prefix or team ID. It's global to the entire developer account.

It's looking like in the vast majority of cases, saying "app prefix" will lead people to do the right thing.  However, based on some troubleshooting advice online, I very carefully made sure the app prefix ID in the developer account matched the ID in the console, and it did. My problem was that I had a unique app ID prefix not equal to Team ID. So, I don't think that advice alone is enough. 

It almost seems like the proper label for that field in the console should be "Team ID" rather than "App ID Prefix", and the help bubble/docs should say "Most of the time your team ID is the same as the app ID prefix". As developers start getting used to using the new auth keys method in which the key applies to every app in the developer account, it makes sense that you would enter a (global) team ID rather than the app id prefix.

One question that comes to mind is whether google uses the app ID prefix anywhere else besides push notifications, and will this lead to a problem with another service? So far I have only used Analytics and Messaging.

**Comment by morganchen12** [comment]
Yeah, looks like Team ID is the way to go, especially as more devs switch to APNs keys over certificates. I'll talk to the docs folks about it.

Thanks for the extra info!

**Comment by kahyoung** [comment]
Running into this, but even when I use the Team ID it's still saying it's invalid.

I've trashed and recreated my keys 4 times because of the "Invalid APNS certificate" error and quadruple checked that all the details are correct, but still getting the error message.

**Comment by morganchen12** [comment]
@kahyoung are you able to send directly through APNs (without FCM)?

**Comment by levsero** [comment]
@morganchen12 Having the same issue where even when using the Team ID it's still saying it's invalid.

I am able to successfully send messages directly to APNs without FCM using the same .p8 key.

**Comment by morganchen12** [comment]
@levsero please file a new issue.

**Comment by kroikie** [comment]
@Krishnaprasad66 if you .p8 key is valid and the Firebase console is indicating that it is not then please file an issue with Firebase support with more details about the key and we will get that resolved.

Also maybe try a new key and see if that helps.
