### ISSUE TITLE
Can send notifications through Firebase console but not custom backend

### ISSUE THREAD

**Issue by jose46moreno** [firebase/quickstart-ios#392]
If I send the push from the Firebase console (to a specific token or to a segment) if I receive it, but I send it through my backend implementation, it does not.

Any ideas?

I've tried hundreds of version configurations of the pods.

**Comment by morganchen12** [comment]
What's your notification payload?

**Comment by jose46moreno** [comment]
This.

![archivo 21-11-17 19 18 21](https://user-images.githubusercontent.com/8105593/33089449-e698f168-cef0-11e7-94e7-3dbb2b15ca3a.jpeg)

**Comment by morganchen12** [comment]
How are you checking for notification delivery on the client?

**Comment by jose46moreno** [comment]
With this: https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExampleSwift/AppDelegate.swift

In iOS 10, they are delivered and shown. They work perfectly.

**Comment by morganchen12** [comment]
What's the payload you're sending through Firebase console (not the backend)?

**Comment by jose46moreno** [comment]
With Firebase console, I use the this.

<img width="1439" alt="captura de pantalla 2017-11-22 a las 21 11 22" src="https://user-images.githubusercontent.com/8105593/33147845-bebb342e-cfc9-11e7-8977-48a4f54c0fcb.png">

**Comment by morganchen12** [comment]
You're sending user-visible notifications through Firebase console but silent (content_available) notifications through your server backend, which is why they're not showing up on the client. Remove the `content_available=true` parameter from your backend implementation and the notifications should start appearing on the client.

**Comment by jose46moreno** [comment]
Remove or set false?

**Comment by morganchen12** [comment]
Remove.

**Comment by jose46moreno** [comment]
It does not work.

I do not get to receive them, because I can not even print them by console.

I'm trying to install the tablets with the previous version that seems to work but now it will not let me.

With the version of the pods that is green (before updating) if they worked.

￼￼
<img width="357" alt="captura de pantalla 2017-12-06 a las 10 52 08" src="https://user-images.githubusercontent.com/8105593/33665209-6e47ad92-da96-11e7-92be-fc320dc08e58.png">

But when I put that in the pod:

    pod 'Alamofire', '~> 4.5'
    pod 'NVActivityIndicatorView'
    pod 'Cluster'
    pod 'Firebase', '4.4.0'
    pod 'Firebase/Core', '4.0.9'
    pod 'Firebase/Messaging', '2.0.5'
    pod 'FirebaseInstanceID', '2.0.5'

It returns the following error.

<img width="527" alt="captura de pantalla 2017-12-06 a las 11 25 41" src="https://user-images.githubusercontent.com/8105593/33665250-9591b276-da96-11e7-874a-92d8a93cfc65.png">

**Comment by morganchen12** [comment]
You should use the latest versions of the pods, but there's no issue on your client if you're able to send and receive through FCM console when the app is both foregrounded and backgrounded.

There's most likely something wrong with your server implementation. Take a look at the [FCM HTTP protocol reference](https://firebase.google.com/docs/cloud-messaging/http-server-ref).
