### ISSUE TITLE
Your project does not own Dynamic Links domain

### ISSUE THREAD

**Issue by abdulKarim002** [firebase/quickstart-ios#393]
Your project does not own Dynamic Links domain while creating short link, i have posted the issue on stackoverflow [link to question](https://stackoverflow.com/questions/47345179/your-project-does-not-own-dynamic-links-domain) but didnt get any thing

How to solve it.

**on AppDelegate**
```
let customURLScheme = "https://x1abc.app.goo.gl"
FirebaseOptions.defaultOptions()?.deepLinkURLScheme = self.customURLScheme
```

**config settings:-**

    `case link = "app_code.app.goo.gl"
    case source = "ios"
    case medium = "referral"
    case campaign = "invite"
    case term = "Term"
    case content = "Content"
    case bundleID = "my bundel id"
    case fallbackURL = "fallback URL"
    case minimumAppVersion = "2.19"
    case customScheme = "dlscheme"
    case appStoreID = "1234567"
    case affiliateToken = "Affiliate Token"
    case campaignToken = "Campaign Token"
    case providerToken = "Provider Token"
    case packageName = "Package Name"
    case androidFallbackURL = "fall back url 2"
    case minimumVersion = "49"
    case title = "my app name"
    case descriptionText = "custom text"
    case imageURL = "Image URL"
    case otherFallbackURL = "www.demo.com"`

**Comment by abdulKarim002** [comment]
The app id is mismatch thats why i getting the error.

**Comment by voghDev** [comment]
I'm having the same error. The Error itself suggests [this link](https://firebase.google.com/docs/dynamic-links/rest#create_a_short_link_from_parameters) for further information. I'm working to fix it ATM and will post any solution that I may find
