### ISSUE TITLE
 Command /bin/sh failed with exit code 1  

### ISSUE THREAD

**Issue by SimbaHJ** [firebase/quickstart-ios#394]
when l try to archive 
/bin/sh -c /Users/OneStepBeyond/Library/Developer/Xcode/DerivedData/EmuziWallet-dbwlbpiynatbozbbhfjfzbmltiol/Build/Intermediates.noindex/ArchiveIntermediates/EmuziWallet/IntermediateBuildFilesPath/EmuziWallet.build/Release-iphoneos/EmuziWallet.build/Script-CDADC9431FC5613000A5E425.sh
Command /bin/sh failed with exit code 1

my Script like this
GOOGLE_APP_ID=1:****:ios:***
${PODS_ROOT}/FirebaseCrash/upload-sym  /Users/OneStepBeyond/Desktop/emuziCode/emuziioscode/EmuziWallet/test.json

**Comment by morganchen12** [comment]
There's not enough information here to debug your issue.

**Comment by Lingyj** [comment]
I have the same problem. 

Screen shot & code like this:
![f921beff-0685-4839-bd5a-9ee9a8a8a102](https://user-images.githubusercontent.com/3283295/33703409-ea3cf566-db62-11e7-9e5c-62b8087e18b9.png)
![aebe0023-f440-4074-ada3-7436ebd44345](https://user-images.githubusercontent.com/3283295/33703412-ec017bc4-db62-11e7-90fe-967c8c124eb2.png)

**Comment by morganchen12** [comment]
@Lingyj this is an error raised by Firebase Crash when it tried to upload your dSYM files. Can you show where in the script the error was raised?

**Comment by Lingyj** [comment]
How to find it?

**Comment by saeedHjzd** [comment]
I have the exact same problem as @Lingyj .
How to find where in the script the error was raised?
And how to fix this issue?
