### ISSUE TITLE
Unable to log as E-Commerce

### ISSUE THREAD

**Issue by AyusSalleh** [firebase/quickstart-ios#396]
I have issue with latest library of Firebase v(4.6.0) + Swift 3

Right now, my ecommerce event tracked as normal event. i dont know what caused this issue. is it library or my code.

Track ECommerce add_to_wishlist
```
AnalyticsManager.sharedInstance.firebaseTrackEvent(eventName: AnalyticsEventAddToWishlist, eventParameter: ["Route": "\(originCode)-\(destinationCode)" as NSObject, "no_of_passenger": "\(self.adultCount)\(self.childCount)\(self.infantCount)" as NSObject, "CampaignType": "\(defaults.string(forKey: "campaignType")!)" as NSObject])
```

Global function
```
func firebaseTrackEvent(eventName: String, eventParameter: [String: NSObject]) {
    Analytics.logEvent(eventName, parameters: eventParameter)
}
```

![image](https://user-images.githubusercontent.com/20343677/33239374-0d03c51e-d2dc-11e7-93e6-16b28caf2388.png)

This is happen to add_to_wishlist(AnalyticsEventAddToWishlist), view_search_results(AnalyticsEventViewSearchResults), add_payment_info(AnalyticsEventAddPaymentInfo) but for ecommerce_purchase, im unable to track it as e-commerce tracking. 
![image](https://user-images.githubusercontent.com/20343677/33239427-d7eb3122-d2dc-11e7-8ea6-f88390961f2b.png)

**Comment by baolocdo** [comment]
sorry, I am still not clear of what you meant " unable to track it as e-commerce tracking" as I could see on the debug view that there was an ecommerce_purchase event. Can you show us how you track the ecommerce_purchase event (the code with the parameters)? Also, can you provide some console log when the event is logged to see what went wrong? Thanks

**Comment by AyusSalleh** [comment]
As you can see inside my screenshot. The indicator for add_to_wishlist is as general event and the icon is as user engagement (screenshot 1), not as conversion event and the icon is flag (Screenshot 2).

Code of ecommerce_purchase
`AnalyticsManager.sharedInstance.firebaseTrackEvent(eventName: AnalyticsEventEcommercePurchase, eventParameter: [AnalyticsParameterCurrency: commerceCurrency, AnalyticsParameterValue: commerceValue, "Points": commercePoints, AnalyticsParameterTransactionID: commerceTransactionId, AnalyticsParameterNumberOfPassengers: commerceNumberPassengers, AnalyticsParameterOrigin: commerceOrigin, AnalyticsParameterDestination: commerceDestination, "Flight_Date_To": commerceFlightDateTo, "Flight_Redemption_Depart": commerceFlightRedemptionDepart, "Flight_Type": commerceFlightType, "Flight_Date_From": commerceFlightDateFrom, "Flight_Redemption_Return": commerceFlightRedemptionReturn, "CampaignType": "\(defaults.string(forKey: "campaignType")!)" as NSObject])`

I cant see any of debug event on latest version of library. Already insert the argument. but no debug displayed.

![image](https://user-images.githubusercontent.com/20343677/33247397-c5050ade-d358-11e7-8eae-8bdf6a3d97e1.png)

**Comment by baolocdo** [comment]
Regarding debug log, are you using a device or simulator? I think simulators should show some logs. 
I am confused with your statement:

> As you can see inside my screenshot. The indicator for add_to_wishlist is as general event and the icon is as user engagement (screenshot 1), not as conversion event and the icon is flag (Screenshot 2).
The second screenshot shows an ecommerce_purchase with a green flag indicating that it's a conversion event, so it should be correct, while you said that it's "not as conversion event". Is there some typos here? Ecommerce_purchase events are marked as conversion by default so that's why you could see a green icon on the debug view.
If you wish to make the event add_to_wishlist as a conversion event, you will need to go to Analytics dashboard and mark add_to_wishlist as conversion yourself. The SDK won't do it automatically.
I hope this answers your question.

**Comment by morganchen12** [comment]
@AyusSalleh, is this still an issue?
