### ISSUE TITLE
MessagingExample app: ld: framework not found GoogleToolboxForMac

### ISSUE THREAD

**Issue by Mehuge** [firebase/quickstart-ios#399]
Trying to build the MessagingExample app, and I get this error.

The process I followed was:

    git clone https://github.com/firebase/quickstart-ios
    open messaging/MessagingExample.xcodeproj
    (changed bundle ID and selected team)
    brew install cocoapods
    pod install
      Analyzing dependencies
      Downloading dependencies
      Installing Firebase (4.0.4)
      Installing FirebaseAnalytics (4.0.2)
      Installing FirebaseCore (4.0.4)
      Installing FirebaseInstanceID (2.0.0)
      Installing FirebaseMessaging (2.0.0)
      Installing GoogleToolboxForMac (2.1.1)
      Installing Protobuf (3.3.0)
      Installing nanopb (0.3.8)
      Generating Pods project
      Integrating client project
    back in Xcode Product -> Run
      ld: warning: directory not found for option '-F/Users/.../Library/Developer/Xcode/DerivedData/MessagingExample-gmgvmxzjygbmcacyxxpbydmcqfuv/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac'
      ld: warning: directory not found for option '-F/Users/.../Library/Developer/Xcode/DerivedData/MessagingExample-gmgvmxzjygbmcacyxxpbydmcqfuv/Build/Products/Debug-iphonesimulator/Protobuf'
      ld: warning: directory not found for option '-F/Users/.../Library/Developer/Xcode/DerivedData/MessagingExample-gmgvmxzjygbmcacyxxpbydmcqfuv/Build/Products/Debug-iphonesimulator/nanopb'
      ld: framework not found GoogleToolboxForMac
      clang: error: linker command failed with exit code 1 (use -v to see invocation)

Platform is macOS 10.13.1

**Comment by paulb777** [comment]
After `pod install`, open messaging/MessagingExample.xcworkspace instead of messaging/MessagingExample.xcodeproj

**Comment by Mehuge** [comment]
Silly me, thank you that solved it.
