### ISSUE TITLE
Consuming Firebase iOS SDK Seems to Require Cocoapods 1.0

### ISSUE THREAD

**Issue by alfiehanssen** [firebase/quickstart-ios#4]
My podfile looks like this: 

```Ruby
platform :ios, '9.0'

use_frameworks!

target 'MyTarget' do
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'FirebaseUI'
end

target 'MyTargetTests' do

end

target 'MyTargetUITests' do

end
```

Running Cocoapods 0.39.0 with this podfile in an iOS9+ Swift project (Xcode 7.3) anytime I `import FirebaseDatabase` and use a class defined in that module I get a segmentation fault. 

Upgrading to Cocoapods 1.0 fixed the issue.

Might want to note this in the documentation.

**Comment by kroikie** [comment]
We do recommend the use of 1.0.0 or later. Thanks for catching that, we will make it clearer in the docs.
