### ISSUE TITLE
Google FCM ios-quickstart error on click local notification - unrecognized selector sent to instance

### ISSUE THREAD

**Issue by hungud** [firebase/quickstart-ios#40]
After push message from Google Firebase Console, The push message notification show on top of ios iphone device and then I click the message and xcode thow exception as below:

[UIConcreteLocalNotification setAlertTitle:]: unrecognized selector sent to instance 0x17e1a810

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIConcreteLocalNotification setAlertTitle:]: unrecognized selector sent to instance

here this code:

//show notification to status bar
UILocalNotification *local_notification = [[UILocalNotification alloc] init];

local_notification.userInfo = userInfo;
local_notification.alertBody = userInfo[@"notification"][@"body"];
local_notification.alertTitle = userInfo[@"notification"][@"title"] ? userInfo[@"notification"][@"title"]: @"VietAir.tv Thông báo";
local_notification.fireDate = [NSDate dateWithTimeIntervalSinceNow:0]; // todo item due date (when notification will be fired). immediately here

 [[UIApplication sharedApplication] scheduleLocalNotification:local_notification];
Please help me, thanks for your suggestion

**Comment by ssatyal** [comment]
jerk.
