### ISSUE TITLE
Swift: Use of unresolved identifier 'Auth'

### ISSUE THREAD

**Issue by SirOlaoluwani** [firebase/quickstart-ios#402]
I cant compile because xcode throws Use of unresolved identifier 'Auth'. I am using 

- Using Firebase (4.6.0)
- Using FirebaseAnalytics (4.0.5)
- Using FirebaseAuth (4.3.2)
- Using FirebaseCore (4.0.11)
- Using FirebaseDatabase (4.1.1)
- Using FirebaseInstanceID (2.0.6)
- Using FirebaseStorage (2.0.2)
- Using GTMSessionFetcher (1.1.12)
- Using GoogleToolboxForMac (2.1.3)
- Using leveldb-library (1.20)
- Using nanopb (0.3.8)

```
import UIKit
import Firebase

@objc func handleRegister(){
        guard let email = emailTextField.text, let password = passwordTextField.text else  {
            print("Form is not valid")
            return
        }
        Auth.auth().createUser(withEmail: email, password: password) { 
            (user, error) in
            if let error = error {
                print(error)
                return
            }
            print("\(user!.email!) created")
        }
    }

```

I am new to swift.
Please help!! 
Thanks.

**Comment by morganchen12** [comment]
Make sure you're using the `.xcworkspace` file and not the `.xcodeproj` file.

If you change your import to `import FirebaseAuth`, does the error go away?

**Comment by SirOlaoluwani** [comment]
Changing the import to `import FirebaseAuth` made the error go away.

Thanks a lot. 👍
