### ISSUE TITLE
Push notification not working with .p8 certificate

### ISSUE THREAD

**Issue by lucamicheli** [firebase/quickstart-ios#410]
Hi there,

I'm trying to sort out this issue by hours. I tried everything but still doesn't work.

The strange thing is that the result of the request is sent and give me the message_ids.
I tried to send messages from the Firebase console as well, but I didn't receive anything yet.

This is what I tried:
- Requested another .p8 Certificate 
- Uploaded the new on Firebase
- Requested another Server Key
- Checked the project settings, bundle ID, GoogleService-info.plist

Do you have any Ideas how to solve?
Apparently, Firebase says me that everything is fine when it's not.

Thanks in advance

**Comment by morganchen12** [comment]
Can you send directly through APNS?

**Comment by lucamicheli** [comment]
After a deep research on Internet, I found so many threads about this issue and nobody seems has the problem solved. 

After half day of work lost I decided to switch my entire project to OneSignal. 
Worked Perfectly after only 5 minutes of work.

I think you should work more on it. 
This is something that you could not expect from Google.

**Comment by revolter** [comment]
We switched to OneSignal too.
