### ISSUE TITLE
Crash in FIRDLDefaultRetrievalProcessV2

### ISSUE THREAD

**Issue by AbhijitKG** [firebase/quickstart-ios#412]
[com.phonepe.phonepeapp_issue_1663_crash_dafa9637299a4e64b554211a005048cf_dc4cf661e55d11e78fd856847afe9799_0_v2.txt](https://github.com/firebase/quickstart-ios/files/1574768/com.phonepe.phonepeapp_issue_1663_crash_dafa9637299a4e64b554211a005048cf_dc4cf661e55d11e78fd856847afe9799_0_v2.txt)

**Comment by morganchen12** [comment]
Please post the reproduction steps for this crash as well as the versions of Firebase you're using and how you've set it up in code, then reopen this issue.
