### ISSUE TITLE
Sending Notification to Single Device not working

### ISSUE THREAD

**Issue by kahyoung** [firebase/quickstart-ios#414]
I'm using the latest method of generating a key for APNs (Keys > All > +), which gives me a .p8 file.

I've followed all the steps to set up APNs on Firebase, including creating the Provisioning file. The AppId has already been made.

I upload my .p8 file into Firebase project settings, and provide the correct App ID and Prefix ID - the Prefix ID matches my Team ID.

When I try to send a notification via Single Device, I get an error saying "Invalid APNS certificate"

I've trashed and re-made the APNS key 4 times already, and have also trashed and remade the app to start from scratch and still running into the same issue.

Any ideas?

**Comment by morganchen12** [comment]
@kahyoung, are you able to send directly through APNs (bypassing FCM)?

**Comment by kahyoung** [comment]
@morganchen12 Woke up this morning to give it another shot, and it worked.

Looks like the problem wasn't on the doc - something must've happened with my configs or with Apple... 

Thanks for getting back to me!

Sorry about that.
