### ISSUE TITLE
Couldn't receive notification when the app is open. 

### ISSUE THREAD

**Issue by shirishpickup** [firebase/quickstart-ios#415]
iOS version: 10.3.3
firebase versions - latest
Have implemented, didReceiveRemoteNotification fetchCompletionHandler method.
When the app is in background mode or not running, i could able to receive notifications.

Currently its completely unreliable, planning on moving to Voip based push notifications to make sure notifications are delivered always.

**Comment by shirishpickup** [comment]
#Update. This is not reliable. I receive the notification sometimes, when the app is open too.

Our company does something similar to Uber, an on demand delivery service. 
Notifications are the way for us to offer runs to our drivers, and if it can't be delivered, there will be a service fail. 
What do you guys suggest ?? 
Any idea, what Uber/Lyft does with their ride offering system ??

**Comment by morganchen12** [comment]
There's not enough information here to debug your issue. What kind of notifications are you sending? How are you handling received notifications on the client? Can you share some of your code?

**Comment by shirishpickup** [comment]
From the server side, we are sending both Data notification and Regular notification in the payload.
On iOS client side, i have implemented the same steps acc to documentation.

  //MARK: - PUSH NOTIFICATIONS
    func registerForPushNotifications() {
        
        if #available(iOS 10, *) {
            
            UNUserNotificationCenter.current().delegate = self
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(options: authOptions) {
                (granted, error) in
                
                guard error == nil else {
                    self.showNotificationsErrorAlert(message: ErrorAlertMessages.notification_access_error)
                    return
                }

                UNUserNotificationCenter.current().getNotificationSettings { (settings) in
                    print("Notification settings: \(settings)")
                    guard settings.authorizationStatus == .authorized else {
                        self.showNotificationsErrorAlert(message: ErrorAlertMessages.notification_access_denied);
                        return
                    }
                }
            }
        } else {
            let setting = UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            UIApplication.shared.registerUserNotificationSettings(setting)
        }
        UIApplication.shared.registerForRemoteNotifications()
    }


  //MARK: - NOTIFICATION DELEGATE METHODS
    func application(_ application: UIApplication,
                     didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)
    {
        if UserInformation.shared.isUserLoggedIn {
            PushNotificationsManager.shared.handleNotification(userInfo: userInfo as! [String : AnyObject])            
        }
        completionHandler(.newData)
    }
    
    func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings) {
        if notificationSettings.types != .none{
            UIApplication.shared.registerForRemoteNotifications()
        }
        else {
            self.showNotificationsErrorAlert(message: ErrorAlertMessages.notification_access_denied)
        }
    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        if let token = Messaging.messaging().fcmToken {
            print("Firebase push notification Token \(token)")
            PushNotificationsManager.shared.updatePushTokenToServer(token: token)
        }
    }
    
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("failed to register \(error)")
        self.showNotificationsErrorAlert(message: ErrorAlertMessages.notification_access_error)
    }

and FirebaseApp.configure() in didFinishLaunchingWithOptions

**Comment by morganchen12** [comment]
Looks like you haven't implemented the `userNotificationCenter(_:willPresent:withCompletionHandler:)` method for handling foreground notifications on iOS 10+.

**Comment by shirishpickup** [comment]
UserNotifications primarily is for LocalNotifications but works for remote too as per documentation. But didReceiveRemoteNotification fetchCompletionHandler is supposed to work in all conditions right ?
But when the app is in killed state, we are missing few notifications. 
Is there some kinda of throttling of how many pushes we can send ? If yes, how can we increase the limits.

**Comment by morganchen12** [comment]
If you are sending silent push notifications, they will stop being delivered when the app is killed by the user and will be throttled when the app is backgrounded. This throttling is done by iOS itself and not FCM or APNs in order to reduce power usage on the platform; there's nothing you can do to work around it.
