### ISSUE TITLE
In FDL how to Open Desired Controller from App Delegate?

### ISSUE THREAD

**Issue by chnouman** [firebase/quickstart-ios#416]
i'm confused whether i can handle the dynamic links from other then app delegate class.
if not then how to handle the coming dynamic link and open specific view controller from app delegate and pass data to it.
i have search on stackoverflow but didn't get anything out of it.

**Comment by morganchen12** [comment]
Dynamic links must be handled from the app delegate class. Your app delegate can then pass a callback to a different class, but that's up to you to design your own code.
