### ISSUE TITLE
Remove delete code from firestore sample

### ISSUE THREAD

**Issue by samtstern** [firebase/quickstart-ios#417]
Context:
https://github.com/firebase/quickstart-android/issues/405

We have already removed Android/iOS/Web collection deletion snippets from the docs since deletion of a whole collection should almost always be done from a server.

**Comment by morganchen12** [comment]
It turns out FrientlyEats iOS never implemented the delete feature, and the [security rules](https://github.com/firebase/quickstart-ios/tree/master/firestore#rules) also don't allow for it.
