### ISSUE TITLE
Dynamic linking not working for me

### ISSUE THREAD

**Issue by chnouman** [firebase/quickstart-ios#418]
When each time app starts   it gives the alert
Deep-link Data 
App Url:
Match Confidence: Strong 
Minimum App Version: 

i tried both with opening app using dynamic link and with normal app click opening. in both cases it gives me the same alert!

**Comment by morganchen12** [comment]
What code are you using to present the alert? What Firebase version are you using?

Please edit your post to add the above information, then reopen this issue.
