### ISSUE TITLE
Authentication Documentation inadequate

### ISSUE THREAD

**Issue by jtressle** [firebase/quickstart-ios#420]
Hi,

Please fix these vague instructions "In Xcode, add a custom URL scheme for your reversed client ID.
You can find this in the GoogleService-Info.plist".

Either link to more documentation "https://developers.google.com/identity/sign-in/ios/start-integrating" or provide instructions on how to add a custom url.

Thanks,

**Comment by morganchen12** [comment]
Fixed in b2640f3.
