### ISSUE TITLE
Firebase on 1st Launch during UNUserNotification, crash the whole app

### ISSUE THREAD

**Issue by hansheung** [firebase/quickstart-ios#421]
My app crash when I first launch and when the app pop up the notification centre. The app will successfully get the token but it doesn't want to connect to FCM and crashed.

But during second launch without the pop up notification, everything works fine, I can manage to send and receive notifications. 

Please help. 

[Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
GXLAOMA[283] <Notice> [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
GXLAOMA[283:13118] http://gxlaoma.broservices.net/apps/neweventout.asp
GXLAOMA[283:13199] [Firebase/Analytics][I-ACS023007] Firebase Analytics v.4001000 started
GXLAOMA[283] <Notice> [Firebase/Analytics][I-ACS023007] Firebase Analytics v.4001000 started
GXLAOMA[283:13199] [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
GXLAOMA[283] <Notice> [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
GXLAOMA[283:13199] [Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
GXLAOMA[283] <Notice> [Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
GXLAOMA[283:13118]  **14 : APNs token retrieved: <eb95a489 87759c91 79a7651a 531b9064 3f9a97cb 19b820ac 58e66388 691ffd7b>
GXLAOMA[283:13202] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
GXLAOMA[283:13202] [MC] Reading from public effective user settings.
GXLAOMA[283:13222] [Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
GXLAOMA[283] <Notice> [Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
GXLAOMA[283:13222] [Firebase/Analytics][I-ACS032005] Search Ad Campaign attribution alarm is already scheduled
GXLAOMA[283] <Warning> [Firebase/Analytics][I-ACS032005] Search Ad Campaign attribution alarm is already scheduled
GXLAOMA[283:13118] -[FIRA_AppDelegate-1518409346644 messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x146ecf80
GXLAOMA[283:13118] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRA_AppDelegate-1518409346644 messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x146ecf80'

[AppDelegate_m.docx](https://github.com/firebase/quickstart-ios/files/1715338/AppDelegate_m.docx)

**Comment by hansheung** [comment]
I just found the solution pod update

**Comment by morganchen12** [comment]
If you still need help, please re-open this issue.
