### ISSUE TITLE
No Proper UI for FireBaseInvite Dialog

### ISSUE THREAD

**Issue by vinodgleecus** [firebase/quickstart-ios#422]
Implemented FireBse Invite in my current project everything is working as expected but the dialog box for sending invitations doesn't load the UI properly, Actually it has to show sent invitation button along with user details. but there is no such button. In documentation, it is mentioned as its actions can be handled implicitly so there no chance of adding it manually and hitting corresponding delegate method.

Have Anyone faced this issue?

**Comment by morganchen12** [comment]
Firebase Invites is definitely lacking in flexibility. It's unlikely to change in the near future though.

If the issue you're describing sounds like a bug in Firebase Invites, can you include a sample project?
