### ISSUE TITLE
App crashing by only installing pod 'Firebase/Invites'

### ISSUE THREAD

**Issue by akshayagarwaldev** [firebase/quickstart-ios#425]
Error : 

dyld: Symbol not found: _OBJC_CLASS_$_GTMMIMEDocument
  Referenced from: /private/var/containers/Bundle/Application/0670F220-70F4-4770-80EE-72B720127BF7/4lio.app/Frameworks/GoogleAPIClientForREST.framework/GoogleAPIClientForREST
  Expected in: /private/var/containers/Bundle/Application/0670F220-70F4-4770-80EE-72B720127BF7/4lio.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher
 in /private/var/containers/Bundle/Application/0670F220-70F4-4770-80EE-72B720127BF7/4lio.app/Frameworks/GoogleAPIClientForREST.framework/GoogleAPIClientForREST
(lldb) 

Stack Trace: 

dyld`__abort_with_payload:
    0x10238af40 <+0>:  mov    x16, #0x209
    0x10238af44 <+4>:  svc    #0x80
->  0x10238af48 <+8>:  b.lo   0x10238af60               ; <+32>
    0x10238af4c <+12>: stp    x29, x30, [sp, #-0x10]!
    0x10238af50 <+16>: mov    x29, sp
    0x10238af54 <+20>: bl     0x10238a5d8               ; cerror_nocancel
    0x10238af58 <+24>: mov    sp, x29
    0x10238af5c <+28>: ldp    x29, x30, [sp], #0x10
    0x10238af60 <+32>: ret

**Comment by paulb777** [comment]
GTMMimeDocument should be built from the GTMSessionFetcher pod - 

<img width="1183" alt="screen shot 2018-03-03 at 6 26 09 am" src="https://user-images.githubusercontent.com/73870/36935366-eed380f4-1eab-11e8-9dba-56d8359918db.png">

If you're still stuck, let us know the contents of your Podfile.
