### ISSUE TITLE
Does FirebaseOptions work with Crashlytics ?

### ISSUE THREAD

**Issue by PatrickSCLin** [firebase/quickstart-ios#431]
I've been notified that Crashlytics will replace Crash Report in this September
How do I setup multi targets (dev/staging/production) with Crashlytics if I've never use Crashlytics before.

Does FirebaseOptions work with Crashlytics ?

**Comment by morganchen12** [comment]
cc @TKBurner, @baolocdo

I don't think FirebaseOptions works with Crashlytics, Crashlytics is still using the Fabric setup. You may be able to setup Crashlytics with multiple schemes via Run Script phases, subbing in a different API key for each target.

**Comment by TKBurner** [comment]
Classically we've had users do this by having users setup multiple Fabric orgs (different API keys) this maps to Firebase projects, so I don't think it's perfect on the Firebase side. For now I'd suggest differentiating with bundle IDs if possible. com.app.test com.app.debug com.app.prod.

I'll raise this with the team here so we can think about adopting FirebaseOptions.

**Comment by PatrickSCLin** [comment]
I was thinking like that way too, but one of our android team member said that he could see  crashlytics data from firebase dashboard in his own android project without create any accounts or projects in fabric, so it makes me confused.

**Comment by PatrickSCLin** [comment]
also it always shows an error popup message when I try to do next step (either yes or no)
![screen shot 2018-03-13 at 10 36 55 am](https://user-images.githubusercontent.com/2464698/37319580-b47de050-26aa-11e8-94b2-81e5ddd6d4c8.png)

**Comment by TKBurner** [comment]
@PatrickSCLin for the second issue please reach out to Firebase support. Our team will need to look at your account on the backend, and we prefer not to do that on public forums. 

I had a chance to talk with the team yesterday and they are working on better ways to add environment support. You should see something in the coming month or two.

Thanks!

**Comment by DrankoLQ** [comment]
I also had problems with FirebaseOptions in my migration from Firebase Crash Reporting to Firebase Crashlytics: I have a target with various schemes (local, sandbox and production server) and thanks to a script I found in this [article](https://medium.com/rocket-fuel/using-multiple-firebase-environments-in-ios-12b204cfa6c0) I've get rid of FirebaseOptions and now Crashlytics works perfectly (before this, crashes wasn't been uploaded to Firebase console)

**Comment by fjtrujy** [comment]
Hello. I'm currently suffering the same issue.
I need to instantiate Firebase at runtime using the `FirebaseOptions`, everything is working so far except `Crashlytics`
I didn't see any problem at all in the debugger console, but so far the crashes are not appearing in Firebase in the Crashlytics section.

Any idea about how can I solve this issue?

Thanks

**Comment by madhuch073** [comment]
@fjtrujy Did you find any. solution?

**Comment by fjtrujy** [comment]
Hello @madhuch073 ,
No, I didn't. But I didn't try either if the newer versions are working fine.

Thanks
