### ISSUE TITLE
Error with RestaurantDetailViewController

### ISSUE THREAD

**Issue by beertengoku** [firebase/quickstart-ios#437]
Tried to compile the latest pull and getting the error
Cannot convert value of type '([String : Any]) -> Restaurant?' to expected argument type '((key: String, value: Any)) -> String?'

at line 146
guard let restaurant = restaurantSnapshot.data().flatMap(Restaurant.init(dictionary:)) else

**Comment by morganchen12** [comment]
I'm unable to reproduce this build failure. What version of Swift are you using?

**Comment by beertengoku** [comment]
I've tried using Swift 3.2 to build it.

**Comment by starkindustries** [comment]
@beertengoku I am getting the exact same error. I tried using Swift 3.2 and 4.0

**Comment by morganchen12** [comment]
What versions of Firestore are you using?

**Comment by beertengoku** [comment]
I pulled the latest commit 7f5b7f5 which was updated recently.

**Comment by morganchen12** [comment]
Make sure your Firestore dependency (the one in your `pod install` output) is the most recent one--there was an API change in this area recently that could be causing the compiler error.
