### ISSUE TITLE
FirebaseAppIndexing(FIRAppIndexing.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

### ISSUE THREAD

**Issue by DonTharaka** [firebase/quickstart-ios#44]
I have integrated FirebaseAppIndexing SDK using cocoapods. It complies and runs fine. But when I try to archive the build I receive this error:

**_FirebaseAppIndexing(FIRAppIndexing.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7_**

What could be the possible fix for this?

**Comment by bernikowich-cedoni** [comment]
@DonTharaka disable bitcode, looks like AppIndexing does not support it.

**Comment by vinceis1337** [comment]
Also have this issue.

Copied from https://github.com/googlesamples/google-services/issues/238#issuecomment-229123007

> Issue https://github.com/googlesamples/google-services/issues/95 was closed again, however I continue to recieve this error in GoogleAppIndexing version 2.0.3 and also Firebase/AppIndexing version 3.2.1.
> 
> ```
> ld: bitcode bundle could not be generated because '........path......Pods/GoogleAppIndexing/Frameworks/GoogleAppIndexing.framework/GoogleAppIndexing(GSDAppIndexing.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
> ```
> 
> The Firebase error is nearly the same except the Pod is Firebase, of course.

We would like to use app thinning and have full bitcode support. This is the only SDK blocking these features.

According to the changelogs, bitcode support was implemented in Firebase since version 2.4.0:

![screen shot 2016-06-28 at 4 50 08 pm](https://cloud.githubusercontent.com/assets/5994871/16433578/9a1b06d8-3d50-11e6-8233-2c38cb405d7b.png)

**Comment by federicocappelli** [comment]
Confirmed! please fix it, my entire project with dozen of dependencies is stuck without bitcode for this framework

**Comment by vinceis1337** [comment]
Any movement on this? This is one of the only codebases blocking bitcode support.

**Comment by vinceis1337** [comment]
Attention all interested parties (including @DonTharaka, @bernikowich-cedoni, @federicocappelli):

Please attempt to use [Firebase/AppIndexing version 3.4.0](https://cocoapods.org/pods/Firebase#changelog).

**It uploaded successfully with bitcode to the App Store.**

**Comment by ianbarber** [comment]
Thanks for updating Vince!
