### ISSUE TITLE
Universal Links not working

### ISSUE THREAD

**Issue by juanjo72** [firebase/quickstart-ios#440]
Hello,

I just integrated the Firebase SDK using pod 'Firebase/Core'. We have noticed then when using universal links and URI Scheme Links, the app delegate methods "continue userActivity" and "open url" respectively are not called anymore.
It seems there is a conflict with Localytics
What can I do?

**Comment by baolocdo** [comment]
Can you please provide the Podfile.lock? Also, can you provide the version of the SDKs, iOS version and whether it was run on device or simulator? Thanks

**Comment by chetandobariya** [comment]
this problem still exits. please somebody open the issue again
