### ISSUE TITLE
Push notifications not working correctly on iPad devices

### ISSUE THREAD

**Issue by TheEye2108** [firebase/quickstart-ios#443]
I'm testing Firebase's push notifications for iOS. Everything is set up properly. When the app runs in the background of the phone the push notifications pops up normally and everything works fine on iPhone, iPod and iPad devices. But, when the app is totally closed they only show up on iPhone and iPod devices, not on the iPads. I'm using 2 iPads for testing: Air 2 (v10.0.2) and Mini 3 (v9.3.5). Why this happens?

**Comment by morganchen12** [comment]
What kind of notifications are you sending, and how are you sending them?
