### ISSUE TITLE
Crash reporting - IOS Objective C

### ISSUE THREAD

**Issue by Raulkg** [firebase/quickstart-ios#45]
Users/testeuphony/Library/Developer/Xcode/DerivedData/innerVoice-fkokqiykrziydyhhujludfggkytb/Build/Intermediates/innerVoice.build/Debug-iphonesimulator/InnerVoice.build/Script-0EB62B041D13493D0096F953.sh: line 12: /Users/testeuphony/Desktop/innerVoice_Git/InnerVoice/iOS/Pods/FirebaseCrash/upload-sym: No such file or directory

This error popped when tried to integrate the crash reporting.

**Comment by eikebartels** [comment]
same for me

**Comment by ianbarber** [comment]
The upload sym file should be present in all recent builds - will close this but please reopen if you still arent seeing it!
