### ISSUE TITLE
Dynamic Linking on iOS

### ISSUE THREAD

**Issue by quetool** [firebase/quickstart-ios#454]
Hi! I have tried the past 3 days to implement Dynamic Links on iOS (Swift 4) but I can't really understand what I am doing wrong (if I am doing something wrong). Let see...

I have the following function in order to create dynamic link programatically

```
func createFirebaseDynamicLink(shopItem: ShopItemData, completion: ((URL?, Array<String>?, Error?) -> Void)!) {
    
    var title = shopItem.name
    var params: String = "title=" + title
    params += "&description=" + shopItem.description
    params += "&terms=" + shopItem.terms
    params += "&bid=" + shopItem.brandId
    params += "&iid=" + shopItem.id
    params += "&image=" + shopItem.image.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
    
    let stringUrl: String = "https://mydomain.co/sharedshopitem.php?" + params
    let link: URL = URL(string: stringUrl.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)!
    
    let components = DynamicLinkComponents(link: link, domain: "abc123.app.goo.gl")
    components.iOSParameters = setiOSParams(bundleID: "my.ios.bundleid",
                                            fallBack: link,
                                        customScheme: "mycustomscheme",
                                          appStoreID: "123456789",
                                          minVersion: "2.5.2")
    components.androidParameters = setAndroidParams(packageName: "my.package.android",
                                                       fallBack: link,
                                                     minVersion: "2.5.2")
    components.socialMetaTagParameters = setSocialParams(title: title,
                                                   description: shopItem.description,
                                                         image: shopItem.image)
    
    components.navigationInfoParameters = DynamicLinkNavigationInfoParameters()
    components.navigationInfoParameters?.isForcedRedirectEnabled = true
    
    components.options = DynamicLinkComponentsOptions()
    components.options?.pathLength = .unguessable
    print("long link: " + (components.url?.absoluteString)!)
    
    components.shorten { (shortURL, warnings, error) in
        print("short link: " + (shortURL?.absoluteString)!)
        completion(shortURL, warnings, error)
    }
}
```
I can not reach my desired behavior. What I want is:

When I click the generated dynamic link in social networks do:
1. If App is installed open the app without showing firebase autogenerated preview page, parse my own "link" getting parameters "bid" and "iid" and open relative screen.
2. If App is not installed open App Store for download it saving my own link in order to get it when app installation is finished and opened.

Now, I can reach one of those behaviors not both at the same time.

My doubts:
- I understand that fallBack link is the url is opened if user click cancel on alert showing up when click on dynamic link, right?
- Not sure for what is the customScheme parameter. Yes, I know what are url schemes in iOS but not sure how I can use here or what are the advanteges.

I hope I made myself clear...

**Comment by quetool** [comment]
I am thinking there is a bug. I followed step by step this video tutorial https://www.youtube.com/watch?v=sFPo296OQqk , in case I was missing something, but my dynamic link always trying to open App Store, no matter if app is installed or not

**Comment by quetool** [comment]
Is it possible dynamic link not working when opened via Twitter App? Just showing me the typical web view with my custom preview html

**Comment by quetool** [comment]
Anyway, I am still dealing with original post. Not opening App Store if app is not installed

**Comment by morganchen12** [comment]
Twitter (and Messenger/Facebook) will try to prevent links from being opened in other apps even if they're valid deep links. Try opening your link from the Notes app.

I don't have time to look into this issue now, but I'll try to get you a more detailed response later.

**Comment by quetool** [comment]
@morganchen12 I know that behavior from Facebook/Messenger but that is not the problem. Im okey with that, the app is opening from facebook/messenger inner webview. The problem is I am not being able to make the dynamic link to open the app store if app is not installed. Neither if I enable the app preview page from firebase by commenting this lines

```
components.navigationInfoParameters = DynamicLinkNavigationInfoParameters()
components.navigationInfoParameters?.isForcedRedirectEnabled = true
```

**Comment by ToddKerpelman** [comment]
A few things to check:

1. If you add &d=1 to the end of your generated URL and open that in a browser, that will bring up a flow chart of what the dynamic link should do in a variety of situations. Does it match up with what you're expecting?
2. Did you try running `DynamicLinks.performDiagnostics(completion: nil)` in your app to run the self-diagnostic tool?
3. I'd probably drop the custom scheme parameter unless you know for a fact that you're using a different custom scheme in your app than the default. That's most likely causing unnecessary confusion.
4. Does the link work if you use it outside of Twitter / Facebook? I would first try getting it to work in something like Notes, to eliminate any interference from social apps
5. If you just add a link to `_abc123_.app.goo.gl` (using whatever your actual domain is) in an app like Notes and then click on it, does it take you to your app? 

If none of that works, please file a ticket with support, since this isn't really a bug with the iOS quickstart. :)

**Comment by quetool** [comment]
Hi @ToddKerpelman 
1. I don't really understand the flow generated but I can tell you it does not work as I expect. You can check it https://h8kkc.app.goo.gl/WdF6L5YgHqQFPbJm2?d=1 (I am running iOS >= 9.0)
2. Not yet, I will try right now
3. Custom schemes was created before I started using Dynamic Link, I can delete it, no problem.
4. No. It does not work anywhere. I mean, meanwhile the app is installed it is working just great from everywhere (I tested on Mail App, Whatsapp, Notes, Facebook, Twitter), but when I delete my app and click on the link it does not taking me to the app store, just showing me the preview page (mine or the firebase preview page, depending whether the isForcedRedirectEnabled true or false) without asking me anything.
5. Like I said, it does taking me to the app , yes, if it is installed. It does not taking me to the App Store if it is not installed.

Sorry for my bad english, I hope you understand

**Comment by quetool** [comment]
@ToddKerpelman this is the diagnostics output 

```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 2.2.0
System information: OS iOS, OS version 11.3, model iPhone
Current date 2018-04-25 14:01:04 +0000
Device locale es-AR, timezone America/Argentina/Cordoba
	Specified custom URL scheme is co.apperto.Appertomvp and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: XXXXXXX9Z, Team ID: XXXXXXX9Z, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----
```

**Comment by quetool** [comment]
I tried everything and still not being able to open App Store when app isn't installed.
I think configuration is fine...

Firebase console configuration
![captura de pantalla 2018-04-25 a la s 11 24 44](https://user-images.githubusercontent.com/14978705/39252311-c7153a9a-487b-11e8-870f-916f59d33071.png)

Capabilities
![captura de pantalla 2018-04-25 a la s 11 24 11](https://user-images.githubusercontent.com/14978705/39252313-c73fedb2-487b-11e8-95bb-7c5924680142.png)

App configuration on developers.apple
![captura de pantalla 2018-04-25 a la s 11 26 16](https://user-images.githubusercontent.com/14978705/39252314-c76f618c-487b-11e8-9fbe-cff28792e87d.png)

Associated domains (don't know which one is the correct)
![captura de pantalla 2018-04-25 a la s 11 26 38](https://user-images.githubusercontent.com/14978705/39252317-c7990604-487b-11e8-9453-76ba7a0a4bdf.png)

**Comment by quetool** [comment]
Ok I finally found the problem. There is some king of bug with fallBack parameter? I commented it and it start working like it supposed to work. But, now I can not take the user to a fallBack link if user click "Cancel" when system ask to "Show this app in App Store"...

```
func setiOSParams(bundleID: String, fallBack: URL, customScheme: String, appStoreID: String, minVersion: String) -> DynamicLinkIOSParameters {
    let iOSParams = DynamicLinkIOSParameters(bundleID: bundleID)
//    iOSParams.fallbackURL = fallBack
//    iOSParams.customScheme = customScheme
    iOSParams.appStoreID = appStoreID
//    iOSParams.minimumAppVersion = minVersion
    return iOSParams
}
```

**Comment by ToddKerpelman** [comment]
Ahh, right! That's how the fallbackURL parameter is supposed to work -- you provide that when you want the dynamic link to do something other than take the user to the app store. 

Anyway, it sounds like you're on the right track. If you run into further issues, please file them with the support team. Thanks!
