### ISSUE TITLE
Push Notifications not working after update even testing in the console

### ISSUE THREAD

**Issue by MontsserratCisne** [firebase/quickstart-ios#455]
I tried every step on the issue #290 
Push Notifications not working after update to Firebase 4.0 
(problem with ios)
But it's not working, first I realized that I had problems with my APNS, because firebase don't recognize it, so I uploaded again and I tested directly from the console, like many times I did, but now it's not working the console too...

**Comment by morganchen12** [comment]
are you able to send directly through APNs?

**Comment by MontsserratCisne** [comment]
I did the test with http://thrysoee.dk/apns/ <- this script and i think that I did something wrong because It returns 403 response, can you help me please? 
![response](https://user-images.githubusercontent.com/38703968/39215794-d2809598-47de-11e8-8b66-f86b537dbaa2.jpg)

 I have a doubt in device token because my app returns APNs token retrieved: 32 bytes and I converted with  
let token = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
    print(token) 
my Data

deviceToken=973e63c047e3b4e2786fce1f51f5088cfb2bd2757181bffd51880f4dc357c426
authKey=""./AuthKey_XU2XY883LX.p8"
authKeyId=XU2XY883LX
teamId=TEAM123456 .   <- I have a doubt here too
bundle=net.exagono.Netcar-Dealers
endpoint=https://api.development.push.apple.com

Thank you for your answer.
