### ISSUE TITLE
Fatal Exception: RepoExists createRepo called for Repo that already exists.

### ISSUE THREAD

**Issue by picturehit** [firebase/quickstart-ios#457]
Hello everybody, 

I have this bug on Crashlytics 

Fatal Exception: RepoExists
0  CoreFoundation                 0x1da0bb3d __exceptionPreprocess
1  libobjc.A.dylib                0x1cc93067 objc_exception_throw
2  CoreFoundation                 0x1da0ba85 -[NSException initWithCoder:]
3  LoisirsEncheres                0x29ff4b +[FRepoManager createRepo:config:database:]
4  LoisirsEncheres                0x28a7e9 -[FIRDatabase ensureRepo]
5  LoisirsEncheres                0x28a037 -[FIRDatabase referenceWithPath:]
6  LoisirsEncheres                0x111df8 specialized User.(getFirebaseToken(completion : (Bool) -> ()) -> ()).(closure #1).(closure #1) (User.swift:298)
7  LoisirsEncheres                0x1182f0 partial apply for User.(getFirebaseToken(completion : (Bool) -> ()) -> ()).(closure #1).(closure #1) (User.swift)
8  LoisirsEncheres                0xf9c48 @callee_owned (@owned User?, @owned Error?) -> ()Error (User.swift)
9  libdispatch.dylib              0x1d0d9797 _dispatch_call_block_and_release
10 libdispatch.dylib              0x1d0d9783 _dispatch_client_callout
11 libdispatch.dylib              0x1d0ddd05 _dispatch_main_queue_callback_4CF

I already saw the answer about the main thread, here is my code : 

Auth.auth().signIn(withCustomToken: self.firebase_token) { (user, error) in
                        print(user ?? "")
                        print(error ?? "")
                        if (error == nil && user != nil) {
                            DispatchQueue.main.async {
                                self.refFirebaseUser = Database.database().reference(withPath:"/users/" + String(User.sharedUser.numUser))
                                self.observeFirebaseUser()
                            }
                        }
                    }

Did i miss something ? 
Can i check if the repo already exists ? 
Thank you and have a good day ! 

Ps : if you want the full stack trace, do not hesitate, i can post it

**Comment by morganchen12** [comment]
What version of Firebase are you using?
