### ISSUE TITLE
When i open firebase url listener not work application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any)

### ISSUE THREAD

**Issue by freeslx** [firebase/quickstart-ios#461]
Hi,

When i open `FirebaseApp.configure()` 

```
 func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        
        print(url)
        return false
    }
```

This method not work but if i comment `FirebaseApp.configure()` that function become running ?

https://stackoverflow.com/questions/49731000/ios-uiapplicationopenurloptionskey-not-work-with-firebase

**Comment by morganchen12** [comment]
Can you try disabling swizzling in Firebase?

**Comment by morganchen12** [comment]
Add a value `FirebaseAppDelegateProxyEnabled` in your Info.plist and set it to `NO`.

**Comment by freeslx** [comment]
I tried still now work 
![screen shot 2018-05-14 at 12 57 37](https://user-images.githubusercontent.com/6368988/39990876-6fa6452e-5776-11e8-9f59-5dbf88cf126d.png)

```
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        print(url)
        return true
    }
```

This method getting crash app if `FirebaseApp.configure()` with this code

**Comment by morganchen12** [comment]
can you share your code?

**Comment by freeslx** [comment]
[AppDelegate.txt](https://github.com/firebase/quickstart-ios/files/2003899/AppDelegate.txt)

This class is enough ?

**Comment by ToddKerpelman** [comment]
What exactly is not working? Are you crashing? If so, what's the crash error message?

**Comment by freeslx** [comment]
I could not get any error message, i tried this ways https://www.natashatherobot.com/xcode-debugging-trick/

**Comment by freeslx** [comment]
Thread 1: EXC_BAD_ACCESS (code=2, address=0x16f70ffc0)
<img width="1172" alt="screen shot 2018-05-28 at 10 30 06" src="https://user-images.githubusercontent.com/6368988/40602675-264c9602-6262-11e8-8810-ff6e52d497a5.png">

**Comment by freeslx** [comment]
I updated XCode and All pods crash fixed.
