### ISSUE TITLE
Unable to Detect Text Recognition (OCR) in sample app MLKit 

### ISSUE THREAD

**Issue by ajaybeniwal** [firebase/quickstart-ios#462]
The sample app to detect recognition (OCR) is not working right now it is failing with error failed to run text detector because self is nil

**Comment by chriseenberg** [comment]
I've got the exact same error. Console says `instantiated GMVTextDetector: xxxx ` then, prints failed to run text detector because self is nil..

Is there a workaround to this?

Kind regards Chris

**Comment by ulukaya** [comment]
https://stackoverflow.com/questions/50246800/firebase-mlkit-text-recognition-error is the solution indeed.
