### ISSUE TITLE
MLKit: VisionTextDetector gets deallocated while detection

### ISSUE THREAD

**Issue by erikhric** [firebase/quickstart-ios#465]
In MLKit example your VisionTextDetector instance gets deallocated during text recognition.
I'm getting error saying that self is nil.
VisionTextDetector is just a local variable in func detectTexts().
I fixed this by making this VisionTextDetector class property.
Other VisionDetectors may be problematic as well. I haven't tested them yet.

**Comment by morganchen12** [comment]
@ulukaya recently fixed this by assigning the text detector to an instance variable, but it looks like he hasn't pushed the fix yet.

**Comment by ulukaya** [comment]
@erikhric looks like the previous fix wasn't merged properly.
https://github.com/firebase/quickstart-ios/commit/fa09feccac2b1693f8d8e824dee6e09cd470e722 fixes the issue.
