### ISSUE TITLE
Firebase Remote Config doesn't support multiple firebase applications

### ISSUE THREAD

**Issue by v-lavrentikov** [firebase/quickstart-ios#466]
I need to use multiple firebase applications for dev/prod environment but Remote Config doesn't support this feature.
Firebase multiple applications function is supported by FirebaseCore:
https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseApp#configurenameoptions

**Comment by morganchen12** [comment]
Can you file this over at https://github.com/firebase/firebase-ios-sdk ?

Thanks!
