### ISSUE TITLE
can't set custom attributes to an FIRTrace instance

### ISSUE THREAD

**Issue by mradamfrancis** [firebase/quickstart-ios#467]
I receive the error:
`No visible @interface for 'FIRTrace' declares the selector 'setValue:forAttribute:'`
for the following line of code:
`FIRTrace *trace = [[FIRPerformance sharedInstance] traceWithName:@"myTrace"];
[trace setValue:@"wifi" forAttribute:@"networkType"];`

I have Firebase/Performance sdk (1.0.6) and i'm referring to the following documentation:
https://firebase.google.com/docs/perf-mon/custom-attributes#create_custom_attributes

also tried it in Swift and got the same error

**Comment by morganchen12** [comment]
Did you make sure to import FirebasePerformance? The header file you're looking for is `FIRPerformanceAttributable.h`.

**Comment by mradamfrancis** [comment]
Thanks for the response Morgan. I had the import included already, but I figured out the problem. Without specifying a version in pod file, I had Firebase/Performance 1.0.6, even though version 2.0.0 is available. Once I updated Firebase sdk (from 4.6 to 5.0), Firebase/Performance 2.0.0 was available and now it recognises `setValue:forAttribute` :)
