### ISSUE TITLE
MLVisionTextModel uses private APIs from Apple

### ISSUE THREAD

**Issue by jugutier** [firebase/quickstart-ios#469]
After uploading to app store the following errors appear from itunes:
The app references non-public symbols in <app_name>: _udata_close, _udata_getMemory, _udata_openChoice, _uhash_close, _uhash_compareChars, _uhash_get, _uhash_hashChars, _uhash_open, _uhash_put, _uhash_setKeyDeleter, _uhash_setValueDeleter

```
grep -r '_uhash_get' .
Binary file ./Pods/GoogleMobileVision/TextDetector/Frameworks/TextDetector.framework/TextDetector matches
```

```
grep -r '_uhash_hashChars' .
Binary file ./Pods/GoogleMobileVision/TextDetector/Frameworks/TextDetector.framework/TextDetector matches
```

Using through cocoapods:

`pod 'Firebase/MLVisionTextModel' , '~> 5.0.1' `

**Comment by morganchen12** [comment]
Tracked internally at b/80053706.

**Comment by jugutier** [comment]
Hi @morganchen12 any updates on this issue? Do you have a rough estimate on when to expect a fix for this?

**Comment by morganchen12** [comment]
It's currently being worked on, but I don't have an estimate for when it'll be fixed.

**Comment by smifsud** [comment]
I'm having the same exact issue. hopefully this will be fixed soon 👍

**Comment by smifsud** [comment]
Appears to work now for me. Looks like the GoogleMobileVision framework was updated to 1.3.2 and fixed the offending classes.

**Comment by morganchen12** [comment]
This should be fixed in GoogleMobileVision 1.3.2 and higher. Please upgrade and comment here if you're still having issues.

Thanks all for your patience.

**Comment by DanEdgarTarget** [comment]
Is there a projected date when this change will land in the Carthage distribution?

See also: https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

There is a 5.4.0 version in the Carthage distribution, but it doesn't appear to have this fix, and we are getting this error when using the 5.4.0 Carthage distribution of the whole Firebase suite.

**Comment by morganchen12** [comment]
@paulb777 is there a difference between the 5.4.0 binary in CocoaPods and the one in the Carthage distribution?

**Comment by paulb777** [comment]
@morganchen12 @DanEdgarTarget  The Carthage distribution is still experimental and will occasionally lag the CocoaPods and zip releases. Currently, Carthage is still at 5.4.0 versus 5.5.0 for the official releases.  I'm hoping to get Carthage back in sync in the next week or so.

In the meantime, a workaround would be to grab the GoogleMobileVision framework from the [CocoaPods](https://github.com/CocoaPods/Specs/blob/master/Specs/0/4/2/GoogleMobileVision/1.3.2/GoogleMobileVision.podspec.json#L151) or [zip](https://firebase.google.com/docs/ios/setup#frameworks) releases.
