### ISSUE TITLE
Can't get FCM token in production

### ISSUE THREAD

**Issue by RockoDev** [firebase/quickstart-ios#47]
I've implemented Parse push notifications in my app and now I'm replacing it with Firebase Cloud Messaging.

Everything works well in a development build. But when I published the app to the app store, the FIRInstanceID.instanceID().token() method always returns nil.

Also, the console prints this (many times):

    Unable to connect with FCM. Error Domain=com.google.fcm Code=2001 "(null)"

I had to enable some logs and update the app in the app store to know what is going on... :/

My AppDelegate.swift looks like:

```swift
import UIKit
import Firebase
import FirebaseInstanceID
import FirebaseMessaging

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        let uns: UIUserNotificationSettings = UIUserNotificationSettings(forTypes: [.Alert, .Badge, .Sound], categories: nil)
        application.registerUserNotificationSettings(uns)
        application.registerForRemoteNotifications()
        
        FIRApp.configure()
        
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(self.tokenRefreshNotification), name: kFIRInstanceIDTokenRefreshNotification, object: nil)

        if let token = FIRInstanceID.instanceID().token() {
            sendTokenToServer(token)
        }
        
        return true
    }
    
    func application(application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
        
        Utilities.Log.debug("didRegisterForRemoteNotificationsWithDeviceToken()")
        
        // if FirebaseAppDelegateProxyEnabled === NO:
        FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Sandbox)
        
        Utilities.Log.debug("APNS: \(deviceToken)")
        
    }
    
    func application(application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: NSError) {
        Utilities.Log.debug("Registration for remote notification failed with error: \(error.localizedDescription)")
    }
    
    func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject], fetchCompletionHandler handler: (UIBackgroundFetchResult) -> Void) {

        Utilities.Log.debug("didReceiveRemoteNotification()")
        
        //if FirebaseAppDelegateProxyEnabled === NO:
        FIRMessaging.messaging().appDidReceiveMessage(userInfo)
        
        handler(.NoData)

    }

    func applicationDidEnterBackground(application: UIApplication) {
        FIRMessaging.messaging().disconnect()
        Utilities.Log.debug("Disconnected from FCM.")
    }

    func applicationDidBecomeActive(application: UIApplication) {
        connectToFcm()
    }
    
    func sendTokenToServer(currentToken: String) {
        Utilities.Log.debug("sendTokenToServer() Token: \(currentToken)")
        // Send token to server ONLY IF NECESSARY
    }
    
    func connectToFcm() {
        FIRMessaging.messaging().connectWithCompletion { (error) in
            if error != nil {
                Utilities.Log.debug("Unable to connect with FCM. \(error!)")
            } else {
                Utilities.Log.debug("Connected to FCM.")
            }
        }
    }
    
    func tokenRefreshNotification(notification: NSNotification) {
        Utilities.Log.debug("tokenRefreshNotification()")
        if let token = FIRInstanceID.instanceID().token() {
            Utilities.Log.debug("InstanceID token: \(token)")
            sendTokenToServer(token)
            FIRMessaging.messaging().subscribeToTopic("/topics/global")
            Utilities.Log.debug("Subscribed to: /topics/global")
        }
        connectToFcm()
    }

}

```

What does "Error Domain=com.google.fcm Code=2001" means?
And why this only fails in a production build?

Thank you.

**Comment by maxydon** [comment]
Same poblem here

**Comment by RockoDev** [comment]
I'm not sure but, I suspect this only happens with devices that already have registered for push notifications with Parse.

Only about < 1% of my users are registering for push notifications since the update that replaces Parse with Firebase. I think they are new users.

I also noticed that the elapsed time between **_didRegisterForRemoteNotificationsWithDeviceToken_** and **_tokenRefreshNotification_** it's about 20-25 SECONDS!!! (when it succeed).

What happens if the user installs the app and closes it before **_tokenRefreshNotification_** method gets called?

**Comment by Captain-Q** [comment]
I am having the same problem as well.. The only way to get the instance ID to work again is to re-install..

**Comment by kroikie** [comment]
I think you may be using the wrong APNS token type, try prod instead of sandbox.

**Comment by RockoDev** [comment]
@kroikie That makes sense...

What I did was set the value of **FirebaseAppDelegateProxyEnabled** to **YES** and remove the extra code. Then, the number of registrations started going up much more quickly. But the elapsed time between didRegisterForRemoteNotificationsWithDeviceToken and tokenRefreshNotification is still about 20-25 seconds.

Thank you.

**Comment by aldo-jlaurenstin** [comment]
I'm having a similar issue.I've setup FirebaseAppDelegateProxyEnabled to YES But still not working Does anyone have an idea?

**Comment by Captain-Q** [comment]
I kind of found a way to get around this.  If you add a title attribute to the notification block,  this will allow your IOS devices to receive the push notification while active and in background (without firing the actual notification).  However,  this will only work for about 5 mins before everything stop completely...  So if anyone have anything more permanent please chime in! 

samples:
json: {
                        "priority": "high",
                        "notification": {
                            "title": "AlarmTimeUpdate"
                        },
                        "data": {
                            "content_available": true,
                        }, 
}

**Comment by darthmarku** [comment]
Instead of 

```
FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Sandbox)
```

have you tried

```
FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Unknown)
``` 

or

```
FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Prod)
```

?

**Comment by hellohelloye** [comment]
Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

**Comment by Cireten** [comment]
Hello,
I have the same problem.
Did someone found a solution ?

**Comment by RockoDev** [comment]
@Cireten The problem that I had was solved replacing:
```swift
//For debug build:
FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Sandbox)
```
With:
```swift
//For production build:
FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Prod)
```

**Comment by Captain-Q** [comment]
I was able to get it to work with this : FIRInstanceID.instanceID().setAPNSToken(deviceToken, type: .Unknown)

Also,  I did something like this to get it working:
1. unchecking the push notification checkbox 
2. close XCode 
3. Open XCode again
4. re-checking the push notification checkbox.

**Comment by Heckfer** [comment]
@RockoDev if I could i would kiss you!
Thank you very much!!!

**Comment by ThoseGuysInTown** [comment]
This saved my life
