### ISSUE TITLE
Cannot subscribe to topic: /topics/test with token: (null)

### ISSUE THREAD

**Issue by romuye123** [firebase/quickstart-ios#470]
**Editor**: Xcode 8.3.2
**Device**: iPhone 5s ( iOS 10.3.2 )
**Language**: Objective-C

**Solutions tried before raising this issue**
1. Clean Xcode, delete App and reinstall.
2. Subscribing to topic after some delay and after FCM token is received.
3. Updated PODS to latest version.
4. Only subscribing to **ONE** topic.
5. **/topics/**  is prefixed.

**NOTE** 
1. The subscription works perfectly fine in Android and immediately gets appeared in Firebase console drop down. 
2. I am able to get FCM token and receive push notification on iOS when sent using Bundle ID(APP).

**CODE**
`[[FIRMessaging messaging] subscribeToTopic:@"/topics/test"];`

**Comment by morganchen12** [comment]
What version of Firebase are you using? You shouldn't have to prefix topics with `/topics/`.

**Comment by romuye123** [comment]
Thanks. Its working now... 👍 
I was unable to start debugger. So could not capture the exact error. https://github.com/firebase/quickstart-ios/issues/471 solved my debugging problem.

Changed the code from 
`[[FIRMessaging messaging] subscribeToTopic:@"/topics/test"];
`
to
`[[FIRMessaging messaging] subscribeToTopic:@"test"];
`

Initially I get following error:
`[Firebase/Messaging][I-FCM002010] Cannot subscribe to topic: test with token: (null)
`
But later I get :
`Topic subscription request: sender=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

And now i can receive push notification on a topic on iOS as well.
