### ISSUE TITLE
Cannot enable debugger

### ISSUE THREAD

**Issue by romuye123** [firebase/quickstart-ios#471]
**Editor**: Xcode 8.3.2
**Device**: iPhone 5s ( iOS 10.3.2 )
**Language**: Objective-C

**Solutions tried before raising this issue**
1. Clean Xcode, delete App and reinstall.
2. Added FIRDebugEnabled and FIRAnalyticsDebugEnabled in arguments.

**ERROR**
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.40005000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)

![screen shot 2018-05-31 at 7 16 10 pm](https://user-images.githubusercontent.com/1880131/40785917-61c41424-6507-11e8-86fb-44df16b7c1a9.png)

**Comment by morganchen12** [comment]
Looks like you're missing a hyphen at the start of the argument (`-FIRAnalyticsDebugEnabled`).

You can also use [this method](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRConfiguration#/c:objc(cs)FIRConfiguration(im)setLoggerLevel:) to set the log level at runtime.

**Comment by romuye123** [comment]
@morganchen12 
Thanks for quick reply. :).
Yes i did forgot to prefix a hyphen. Basically copy pasting didn't captured it. 
It is working. Also thanks for log level.
