### ISSUE TITLE
Firebase Crashlytics: Unable to run unit tests - *** Terminating app due to uncaught exception 'FABException', reason: '[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.'

### ISSUE THREAD

**Issue by halinebr** [firebase/quickstart-ios#473]
Hi there!

I am trying to run unit tests and I have happened upon this error.

Here is the call stack:

*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110de51e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010f9f4031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110e5a975 +[NSException raise:format:] + 197
	3   eulerity-ios dev                    0x0000000106f92efb -[Fabric validFabricConfigFromInfoPlist:] + 353
	4   eulerity-ios dev                    0x0000000106f92bd1 -[Fabric fabricConfig] + 127
	5   eulerity-ios dev                    0x0000000106f92d03 -[Fabric APIKey] + 258
	6   eulerity-ios dev                    0x0000000106f5c627 -[Crashlytics APIKey] + 55
	7   eulerity-ios dev                    0x0000000106f68475 -[CLSCrashReportingController APIKey] + 57
	8   eulerity-ios dev                    0x0000000106f67af1 -[CLSCrashReportingController startWithProfilingMark:betaToken:] + 258
	9   eulerity-ios dev                    0x0000000106f5bfd8 __20-[Crashlytics start]_block_invoke + 637
	10  libdispatch.dylib                   0x00000001122ad779 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001122aec0a dispatch_once_f + 55
	12  eulerity-ios dev                    0x0000000106f5bd55 -[Crashlytics start] + 106
	13  eulerity-ios dev                    0x0000000106f5c18a +[Crashlytics initializeIfNeeded] + 48
	14  LNRDStagingUnitTests                0x0000000130ffa360 __15+[Fabric with:]_block_invoke + 538
	15  libdispatch.dylib                   0x00000001122ad779 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x00000001122aec0a dispatch_once_f + 55
	17  LNRDStagingUnitTests                0x0000000130ffa144 +[Fabric with:] + 222
	18  LNRDStagingUnitTests                0x0000000130ffbd8f __14+[Fabric load]_block_invoke + 844
	19  Foundation                          0x000000010afec324 -[__NSObserver _doit:] + 298
	20  CoreFoundation                      0x0000000110d80b8c \__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	21  CoreFoundation                      0x0000000110d80a65 _CFXRegistrationPost + 453
	22  CoreFoundation                      0x0000000110d807a1 ___CFXNotificationPost_block_invoke + 225
	23  CoreFoundation                      0x0000000110d42422 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	24  CoreFoundation                      0x0000000110d415a1 _CFXNotificationPost + 609
	25  Foundation                          0x000000010aface57 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	26  eulerity-ios dev                    0x00000001070691fa +[FIRApp sendNotificationsToSDKs:] + 442
	27  eulerity-ios dev                    0x00000001070675e9 +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 457
	28  eulerity-ios dev                    0x0000000107067345 +[FIRApp configure] + 501
	29  eulerity-ios dev                    0x0000000106e73e60 _T016eulerity_ios_dev11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0G16LaunchOptionsKeyVypGSg022didFinishLaunchingWithJ0tF + 608
	30  eulerity-ios dev                    0x0000000106e7880a _T016eulerity_ios_dev11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0G16LaunchOptionsKeyVypGSg022didFinishLaunchingWithJ0tFTo + 186
	31  UIKit                               0x000000010ce1275b -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
	32  UIKit                               0x000000010ce141d2 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4123
	33  UIKit                               0x000000010ce1962b -[UIApplication _runWithMainScene:transitionContext:completion:] + 1677
	34  UIKit                               0x000000010d1dbe4a __111-[\__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	35  UIKit                               0x000000010d5ae909 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	36  UIKit                               0x000000010d1dba86 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	37  UIKit                               0x000000010d1dc2a7 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 675
	38  UIKit                               0x000000010db4d4d4 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 299
	39  UIKit                               0x000000010db4d36e -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	40  UIKit                               0x000000010d83162d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
	41  UIKit                               0x000000010da2c387 _performActionsWithDelayForTransitionContext + 100
	42  UIKit                               0x000000010d8314f7 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	43  UIKit                               0x000000010d5adfb0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	44  UIKit                               0x000000010ce17f0c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	45  UIKit                               0x000000010d3eaa97 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	46  FrontBoardServices                  0x00000001168fc2f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 331
	47  FrontBoardServices                  0x0000000116904cfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 225
	48  libdispatch.dylib                   0x00000001122ad779 _dispatch_client_callout + 8
	49  libdispatch.dylib                   0x00000001122b2931 _dispatch_block_invoke_direct + 317
	50  FrontBoardServices                  0x0000000116930470 \__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	51  FrontBoardServices                  0x000000011693012e -[FBSSerialQueue _performNext] + 439
	52  FrontBoardServices                  0x000000011693068e -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	53  CoreFoundation                      0x0000000110d87bb1 \__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	54  CoreFoundation                      0x0000000110d6c4af __CFRunLoopDoSources0 + 271
	55  CoreFoundation                      0x0000000110d6ba6f __CFRunLoopRun + 1263
	56  CoreFoundation                      0x0000000110d6b30b CFRunLoopRunSpecific + 635
	57  GraphicsServices                    0x0000000115171a73 GSEventRunModal + 62
	58  UIKit                               0x000000010ce1b0b7 UIApplicationMain + 159
	59  eulerity-ios dev                    0x0000000106e80ad7 main + 55
	60  libdyld.dylib                       0x0000000112322955 start + 1
	61  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException

SIGABRT exception in line 393 of FIRApp.m 

I am assuming this has to do with some sort of pod setup for my unit testing target and was hoping someone could help point me in the right direction of how to solve this? Querying previous issues and StackOverflow has proved unhelpful.  

I followed the guide [here](https://firebase.google.com/docs/crashlytics/get-started) - added the appropriate cocoa pods to my main target (pod 'Fabric', '\~> 1.7.7'
pod 'Crashlytics', '\~> 3.10.2'), added the Crashlytics runscript to my main target, and I am inheriting complete search paths in my unit testing target.

If there's any more information I can provide, let me know. Thanks!

**Comment by morganchen12** [comment]
Can you share the raw text of your Info.plist file, replacing any confidential string values with placeholders?

**Comment by halinebr** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>LNRD</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>LNRD</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>[PLACEHOLDER]</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.[PLACEHOLDER]</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>lnrdStaging123456</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.eulerity.eulerity-Dev</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>76</string>
	<key>FacebookAppID</key>
	<string>[PLACEHOLDER]</string>
	<key>FacebookDisplayName</key>
	<string>LNRD</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>comgooglemaps</string>
		<string>googlechromes</string>
		<string>fbapi</string>
		<string>fb-messenger-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>Allow LNRD to access your camera to help you create beautiful ads.</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Allow LNRD to access your current location to help you find your business.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Allow LNRD to access your current location to help you find your business.</string>
	<key>NSLocationUsageDescription</key>
	<string>Allow LNRD to access your current location to help you find your business.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Allow LNRD to access your current location to help you find your business.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Allow LNRD to access your photo library to help you create beautiful ads.</string>
	<key>UIAppFonts</key>
	<array>
		<string>Cardo-Bold.ttf</string>
		<string>CherrySwash-Regular.ttf</string>
		<string>CherrySwash-Bold.ttf</string>
		<string>OpenSans-Bold.ttf</string>
		<string>Tahoma-Bold.ttf</string>
		<string>Cardo-Regular.ttf</string>
		<string>Tahoma.ttf</string>
		<string>Sofia-Regular.otf</string>
		<string>OpenSans-Regular.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by morganchen12** [comment]
Got it. This looks fine to me, Fabric should be pulling necessary info from your Firebase config. @TKBurner, do you know what could be causing this?

**Comment by TKBurner** [comment]
Thanks. Can you share your run script build phase? It looks like your info.plist is correct.

I suspect we aren't sure wether to go to Fabric or Firebase.

**Comment by halinebr** [comment]
<img width="839" alt="screen shot 2018-06-04 at 6 14 37 pm" src="https://user-images.githubusercontent.com/11284259/40944546-34f91768-6823-11e8-98ef-32f409c7f449.png">
Here's a screen shot of the build phases for the target under test. 

Correct me if I am wrong, but I don't need to include the run script for my unit test target, correct?

**Comment by TKBurner** [comment]
Interesting. Do you have a Fabric.with statement in your app somewhere? That would be the third place that could cause this issue.

**Comment by halinebr** [comment]
<img width="331" alt="screen shot 2018-06-04 at 6 18 01 pm" src="https://user-images.githubusercontent.com/11284259/40944676-a63c45f8-6823-11e8-9881-1fb56e1b7288.png">

Above are the only places in my workspace with that statement - appears to be coming from Pods.

**Comment by TKBurner** [comment]
Thanks. Is this only for your test target?

**Comment by halinebr** [comment]
Yes - specifically a unit testing target that tests our development app. Running the development app or performing UI tests work just fine. It's only when conducting unit tests.

Just now I tested a unit test pointing to the production version of our app and it appears to work fine (should have tried this sooner - oops). Trying to compare Podfile set up between the two test targets but not seeing a difference. 

The two versions of the app have separate Firebase projects both with Crashlytics set up and working. There are no changes made to GoogleService-Info.plist when you set up Crashyltics, right? I am maintaining two separate GoogleService-Info.plist with target membership to the appropriate Prod/Dev target. I'm trying to think of where there could be a discrepancy in set up...

**Comment by halinebr** [comment]
Found my error! 
For the test target in my pod file I had `inherit!: complete`.
Changing this to `inherit!: search_paths` fixed the issue. 

Thanks for the help and apologies for the confusion.

**Comment by mafer-bc** [comment]
Hi!
I'm having the exact same issue only when runing my Unit Tests. But I haven't found the way to fix it.
Here is the error:
> *** Terminating app due to uncaught exception 'FABException', reason: '[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001166f11e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001149ee031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000116766975 +[NSException raise:format:] + 197
	3   MyApp                          0x000000010c6d7c2b -[Fabric validFabricConfigFromInfoPlist:] + 353
	4   MyApp                          0x000000010c6d7901 -[Fabric fabricConfig] + 127
	5   MyApp                          0x000000010c6d7a33 -[Fabric APIKey] + 258
	6   MyApp                          0x000000010c6a1357 -[Crashlytics APIKey] + 55
	7   MyApp                          0x000000010c6ad1a5 -[CLSCrashReportingController APIKey] + 57
	8   MyApp                          0x000000010c6ac821 -[CLSCrashReportingController startWithProfilingMark:betaToken:] + 258
	9   MyApp                          0x000000010c6a0d08 __20-[Crashlytics start]_block_invoke + 637
	10  libdispatch.dylib                   0x0000000117b28709 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000117b29b9a dispatch_once_f + 55
	12  MyApp                          0x000000010c6a0a85 -[Crashlytics start] + 106
	13  MyApp                          0x000000010c6a0eba +[Crashlytics initializeIfNeeded] + 48
	14  MyAppTests                     0x000000013409c520 __15+[Fabric with:]_block_invoke + 538
	15  libdispatch.dylib                   0x0000000117b28709 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x0000000117b29b9a dispatch_once_f + 55
	17  MyAppTests                     0x000000013409c304 +[Fabric with:] + 222
	18  MyAppTests                     0x000000013409df4f __14+[Fabric load]_block_invoke + 844
	19  Foundation                          0x000000010ffed324 -[__NSObserver _doit:] + 298
	20  CoreFoundation                      0x000000011668cb8c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	21  CoreFoundation                      0x000000011668ca65 _CFXRegistrationPost + 453
	22  CoreFoundation                      0x000000011668c7a1 ___CFXNotificationPost_block_invoke + 225
	23  CoreFoundation                      0x000000011664e422 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	24  CoreFoundation                      0x000000011664d5a1 _CFXNotificationPost + 609
	25  Foundation                          0x000000010ffade57 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	26  MyApp                          0x000000010c75a60c +[FIRApp sendNotificationsToSDKs:] + 460
	27  MyApp                          0x000000010c758664 +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 564
	28  MyApp                          0x000000010c758339 +[FIRApp configure] + 537
	29  MyApp                          0x000000010c453d2e _T010MyApp15FirebaseServiceC9configureyyFZ + 238
	30  MyApp                          0x000000010c56cd67 _T010MyApp11AppDelegateC04initC8Services33_838A56DC8C0BC1F853B8DAFFEACD2690LLySo13UIApplicationCF + 407
	31  MyApp                          0x000000010c56a107 _T010MyApp11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tF + 679
	32  MyApp                          0x000000010c56a5fa _T010MyApp11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tFTo + 186
	33  UIKit                               0x0000000111f246fb -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
	34  UIKit                               0x0000000111f26172 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4123
	35  UIKit                               0x0000000111f2b5cb -[UIApplication _runWithMainScene:transitionContext:completion:] + 1677
	36  UIKit                               0x00000001122edf7e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	37  UIKit                               0x00000001126c0a39 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	38  UIKit                               0x00000001122edbba -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	39  UIKit                               0x00000001122ee3db -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 675
	40  UIKit                               0x0000000112c5f614 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 299
	41  UIKit                               0x0000000112c5f4ae -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	42  UIKit                               0x000000011294375d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
	43  UIKit                               0x0000000112b3e4b7 _performActionsWithDelayForTransitionContext + 100
	44  UIKit                               0x0000000112943627 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	45  UIKit                               0x00000001126c00e0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	46  UIKit                               0x0000000111f29eac -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	47  UIKit                               0x00000001124fcbcb -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	48  FrontBoardServices                  0x000000011898f2f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 331
	49  FrontBoardServices                  0x0000000118997cfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 225
	50  libdispatch.dylib                   0x0000000117b28709 _dispatch_client_callout + 8
	51  libdispatch.dylib                   0x0000000117b2d8c1 _dispatch_block_invoke_direct + 317
	52  FrontBoardServices                  0x00000001189c3470 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	53  FrontBoardServices                  0x00000001189c312e -[FBSSerialQueue _performNext] + 439
	54  FrontBoardServices                  0x00000001189c368e -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	55  CoreFoundation                      0x0000000116693bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	56  CoreFoundation                      0x00000001166784af __CFRunLoopDoSources0 + 271
	57  CoreFoundation                      0x0000000116677a6f __CFRunLoopRun + 1263
	58  CoreFoundation                      0x000000011667730b CFRunLoopRunSpecific + 635
	59  GraphicsServices                    0x0000000119258a73 GSEventRunModal + 62
	60  UIKit                               0x0000000111f2d057 UIApplicationMain + 159
	61  MyApp                          0x000000010c571717 main + 55
	62  libdyld.dylib                       0x0000000117b9d955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
>

My Podfile had always have the `inherit! :search_paths` in the tests targets. And the Info.plist **doesn't** have the Fabric dictionary, as Firebase doesn't need this.
If I search for `Fabric.with` in my Workspace it shows the same shown above.
My pods versions are:
- Crashlytics (3.10.2)
- Fabric (1.7.7)
- Firebase/Core (5.3.0)

I've tried:
- Adding the Run Script `"${PODS_ROOT}/Fabric/run"` to my UnitTest target
- Adding to the test target of my Podfile the `Firebase/Core` pod, as mentioned [here](https://stackoverflow.com/a/49901141/5909661)
- Cleaning the project and trying the test again.. and again

I'm out of options, any suggestions on what else I could be missing?

**Comment by morganchen12** [comment]
@mafer-bc Please [file a support ticket](https://firebase.google.com/support/) or open a new issue.

**Comment by tedgonzalez** [comment]
any updates to this? I have same issue

**Comment by morganchen12** [comment]
@tedgonzalez Please [file a support ticket](https://firebase.google.com/support/) or open a new issue.

**Comment by raiffeisennet** [comment]
Same issue here

**Comment by marah-sh** [comment]
Same issue. 
for now I am checking if UnitTests is running before Firebase configure 
```
func isRunningUnitTests() -> Bool {
    let env = ProcessInfo.processInfo.environment
    if let injectBundle = env["TEST_MODE"] {
        return injectBundle == "enable"
    }
    return false
}
```
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        if !isRunningUnitTests() {
            // Firebase
            FirebaseApp.configure()
         }
}
```

**Comment by acevif** [comment]
Thanks @halinebr
@halinebr's solution worked for me.

(Maybe `inherit!: search_paths` is a typo and `inherit! :search_paths` is correct.)

**Comment by anishparajuli555** [comment]
I still have this issue. Any suggestions?

**Comment by lucianosky** [comment]
@halinebr solution worked for me, thanks @halinebr!

**Comment by acevif** [comment]
@anishparajuli555 Have you tried @halinebr solution?

How about deleting Pods/ directory and Derived Data/ directory before running unit tests?

**Comment by anishparajuli555** [comment]
@acevif  Adding `inherit! :search_paths` in test target worked for me.

**Comment by acevif** [comment]
@anishparajuli555 😸

**Comment by eharo2** [comment]
> Same issue.
> for now I am checking if UnitTests is running before Firebase configure
> 
> ```
> func isRunningUnitTests() -> Bool {
>     let env = ProcessInfo.processInfo.environment
>     if let injectBundle = env["TEST_MODE"] {
>         return injectBundle == "enable"
>     }
>     return false
> }
> ```
> ```
> func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
>         
>         if !isRunningUnitTests() {
>             // Firebase
>             FirebaseApp.configure()
>          }
> }
> ```

My issue was a SIGABRT in Firebase at test time in sendNotificationToSDK().
@marah-sh solution worked for me.  By pass Firebase in testing (only used for Crashlytics and Google Vision).      I modified the method for iOS 12/Xcode 10.  

	func isRunningUnitTests() -> Bool {
		let env = ProcessInfo.processInfo.environment
		if let _ = env["XCInjectBundleInto"] {
			return true
		}
		return false
	}

**Comment by dipkasyap** [comment]
Same Here , cannot rum my test ,  Please refer the log below. 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Crashlytics", referenced from:
      objc-class-ref in AppDelegate+Extenssion.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chefnobody** [comment]
@halinebr's solution worked for me, though I'm not entirely certain why. For context, here's my pod file with the app target and test target nested within:

```
target 'PizzaApp' do
  # firebase pods ...

  target 'PizzaAppTests' do
    inherit! :search_paths
    # ...

  end
end
```

**Comment by anoop4real** [comment]
I am also facing this issue 
`inherit! :search_paths` didnt  work

**Comment by mpaillet3821** [comment]
> @halinebr's solution worked for me, though I'm not entirely certain why. For context, here's my pod file with the app target and test target nested within:
> 
> ```
> target 'PizzaApp' do
>   # firebase pods ...
> 
>   target 'PizzaAppTests' do
>     inherit! :search_paths
>     # ...
> 
>   end
> end
> ```

Make sure you nest the test targets inside the main app target like @chefnobody mentioned in his comment. It makes all the difference 😸
