### ISSUE TITLE
today iOS  FCM push was  "error": "InternalServerError",why?

### ISSUE THREAD

**Issue by zeqinjie** [firebase/quickstart-ios#476]
{
    "multicast_id": xxxxxxxx,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "InternalServerError"
        }
    ]
}
question:
It was normal one hour ago, but now there are problems. The certificate is also normal, and using Apple APN push is normal.

**Comment by morganchen12** [comment]
This likely indicates a bug on the FCM backend. Please file a support ticket at https://firebase.google.com/support/.
