### ISSUE TITLE
iOS Firebase Crashlytics not showing crash report

### ISSUE THREAD

**Issue by yliu342** [firebase/quickstart-ios#480]
I've followed the steps in the doc to integrate Firebase Crashlytics into our iOS app. Everything seems to be doing correctly in the app but there is Crash shown in Firebase Crashlytics. There are however shows the number of crash in the dashboard but when you clicked Crasyhlytics to see more, it says there are no crash and no events even though the crash free statics shows there is a crash.

Settings of my app:
`pod 'Firebase/Core', '5.2.0'`
`pod 'Fabric', '~> 1.7.7'`
`pod 'Crashlytics', '~> 3.10.2'`

I have also made my app to generate `dwarf-with-dsym`
I have added the run script `${PODS_ROOT}/Fabric/run`

The build log shows this for the Run script

> 2018-06-20 14:17:43.264 uploadDSYM[41223:259678] Fabric.framework/run 1.7.0 (208)
>2018-06-20 14:17:43.270 uploadDSYM[41223:259678] Firebase mode detected.
>2018-06-20 14:17:43.271 uploadDSYM[41223:259678] Using API Key: "xxxxxxxx"
>2018-06-20 14:17:43.271 uploadDSYM[41223:259678] Launched uploader in validation mode

Stop Xcode to make sure debugger is not attached, and run the app from simulator and force a crash.
Reopen the app to make sure it send the report.
The console shows
>[Crashlytics:Crash] report submission successful

But there is nothing shown in the Firebase Crashlytics.

I've also tried to set `enable bitcode` to `false` but it doesn't make a different.
I've checked the dsym tab and it shows there is no missing dsym.
I've also checked the bundle id matches what's in the GoogleService-info.plist

Can anyone help me out here is there something I'm missing?

**Comment by morganchen12** [comment]
You should file a support ticket at https://firebase.google.com/support/.

**Comment by mrikh** [comment]
Any updates for this?

Now the build logs don't show anything for the run script but i do get the follow message in the console:
`[Crashlytics:Crash] report submission successful`

**Comment by JuanCollin7** [comment]
I have the same problem.

**Comment by jcatink** [comment]
+1
