### ISSUE TITLE
silent notifications not delivered on iPhone X

### ISSUE THREAD

**Issue by fullyBoricua** [firebase/quickstart-ios#482]
Hi guys. I know there's a lot of _"notifications are not working"_ posts around... but just please bear with me.

I have an app already in the app store that works as expected. The app relies heavily on "only data" or "silent" notifications... no other type of notification are used, just "only data".

Thing is, I'm **NOT** receiving notifications on iPhone X... it works perfectly on other iPhones but no on X.

Now, if I run the app with the USB cable connected between Xcode and the iPhone X, just magically, the iPhone X start receiving the "only data" notifications... if I unplug the USB cable it just stop receiving them (???)

All the methods are in place (well, obviously since the app works on other iPhones), I also tried sending the notifications from Postman and I get a _messageID_ as a response from google (meaning the message was delivered).

I think the clue is in finding **WHY** does is work when running in debug mode, what is different in that scenario?

I have posted all the details here:
https://stackoverflow.com/questions/51031271/firebase-notifications-fcm-not-received-on-iphone-x

I even went into the trouble of creating a hidden "debug/log tableview" inside the app to know if the FIR functions are called when the message are delivered... they are not! I'm even logging the "granted notification" permission just to be extra sure... background fetch is also enabled.

It's been days troubleshooting this single issue and I'm kind of desperate.

Any hints will be greatly appreciated!!!

**Comment by fullyBoricua** [comment]
I manage to get some logs from the iPhone X while delivering a silent notification.
I posted the logs in the previous link.

So it appears that iOS receives the notification, along with the data (**hasContentAvailable: 1**) but it's not sending it to my app... 

Also, why this error: 
**<Error>: Ignoring notification with no alert, sound or badge**... a silent notification does not have alert / sound / badge!

Is FCM changing the payload based on the model of the receiving iPhone? Again, all of this is working like a charm on iPhone 6S with the same iOS 11.4 that the iPhone X

**Comment by morganchen12** [comment]
FCM doesn't change the payload based on the device receiving it. The payloads linked in your StackOverflow question seem to be missing the content-available flag.

Other than that, the system will throttle silent notifications to conserve power, so iOS may receive them but decide not to wake your app.

**Comment by fullyBoricua** [comment]
Hi Morganchen12

> The payloads linked in your StackOverflow question seem to be missing the content-available flag

That's not true... as per google documentation on [https://firebase.google.com/docs/cloud-messaging/concept-options](url) you only need to set `token` and `data` inside a `message` envelope... FCM will take care of adding the `content-available` tag.

And as a matter of fact FCM does it job since `content-available` is added to the message sent. I know this because:
- it works as expected in non-iPhone X devices
- if you check my iPhone X log on the SA post you can clearly see the `hasContent:1` and also `Passing content-available push to Duet`

I know the easy answer is **iOS is conserving power and it may or may not work** but this clearly isn't the case, since the iPhoneX log clearly shows that the message is being rejected because:

`<Error>: Ignoring notification with no alert, sound or badge`

This is not clear but we can think that the error means that the `notification part` is being ignored, not the `data part`. However, **the data part is never delivered to the delegate on the iPhone X**.

**Comment by morganchen12** [comment]
What happens if you try sending the same message through APNs without FCM?

**Comment by fullyBoricua** [comment]
Hi Morganchen
I never have tried to use APNS directly... In fact, I have no idea how to send a message without FCM.

I read that maybe Apple is starting to cut on data notifications on new devices, since the feature is being abused... I'll cut my loses and switch to a `notification + data` approach since no one seems to have any clues about whats happening behind the scenes on the iPhone.

In short, it's not FCM fault, the message is definitely formatted correctly.

Thank you for answering

**Comment by morganchen12** [comment]
Sounds good. Please let us know if this starts to occur on other devices.

**Comment by NySiya** [comment]
@fullyBoricua How are you solving it now? I am having the same problem here :(

**Comment by mstein11** [comment]
I would also be interested in how this was solved!
