### ISSUE TITLE
Unable to build an app by integrating a framework which has internally dependent on Firebase/Core and remoteconfig

### ISSUE THREAD

**Issue by chittaranjan-sahu** [firebase/quickstart-ios#484]
I am creating a  dynamic framework which is dependent on firebase core and remote config(through pod). If i build the framework after integrating firebase, it works fine. But once i integrate my framework in a sample app, and trying to build its giving error like unable to find -lFirebaseCore. Also as we know firebase core is downloaded as static library in pod. Please need help on this issue.

If i create a sample app and add firebase dependency directly, then its working fine. The problem comes when i wrap the dependency in a framework and add this framework in a sample app.

**Comment by paulb777** [comment]
It is not possible for a dynamic framework to depend on a static framework. To depend on the Firebase frameworks, use a static framework CocoaPod. More info at http://blog.cocoapods.org/CocoaPods-1.4.0/
