### ISSUE TITLE
firebasecore is added as static library

### ISSUE THREAD

**Issue by chittaranjan-sahu** [firebase/quickstart-ios#485]
I am creating one framework and want to share this framework to application. I see one issue like if i add firebase dependency in my framework podfile, its getting added as static library. but if i download a sample app from internet and their i try pod install, its added as dynamic framework only. Basically i want to do firebase AB testing. So i need firebase core as dynamic framework. Can you please help on this issue and also why in sample apps downloaded, it shows there dynamic framework.

**Comment by morganchen12** [comment]
- FirebaseCore is added as a static dependency regardless of how you integrate it. If you add the `use_frameworks!` flag in your Podfile, it'll get added as a framework module, but it's ultimately still linked statically.
- A/B testing doesn't depend on dynamic linking of dependencies, it'll work regardless of how your dependencies are structured provided there are no duplicate classes at runtime.
