### ISSUE TITLE
[iOS] MLVision Face Detection - Out of memory issue

### ISSUE THREAD

**Issue by youinmyheart** [firebase/quickstart-ios#486]
I tested MLVisionExample with face detection in live camera and saw the error "Terminated due to memory issue" when memory use increased continuously to crash app (> 1GB). Sample app runs OK when only me is in the camera frame (front camera). App will be crashed in the following cases:
+ Nobody in the camera frame. I let the device on the table, nobody was detected and memory increased continuously to crash.
+ There're 2 persons in the camera frame. App can detect 2 persons but it will crash soon
+ Use: options.modeType = FIRVisionFaceDetectorModeAccurate; in code

Is the problem in the SDK or sample app?

**Comment by morganchen12** [comment]
The sample app is pretty simple; at first glance this seems to be an issue in the SDK itself.

What device were you running this on?

**Comment by youinmyheart** [comment]
I run sample on iPhone 7

**Comment by bcdj** [comment]
Are you using CocoaPod to install the Firebase/MLVision?  If so, can you check your Podfile.lock to see which version of MLVision you are using?  Please make sure to use the latest version 0.10.0.  The OOM issue existed in 0.9.0, but should be fixed in 0.10.0.

**Comment by youinmyheart** [comment]
@bcdj : you're right. After updating to ver 0.10.0, the issue was fixed. Thanks guys!
