### ISSUE TITLE
Memory leak problem after fetch() using firebase remote config sdk.

### ISSUE THREAD

**Issue by vendys-jackdaw** [firebase/quickstart-ios#488]
Hi there.
I’m using the firebase remote config lib in my app.

I found  a memory leak problem as shown below screenshot during testing app.
The leak is found when I trying fetch method in remote config sdk.

My develop environment :
- Xcode 9.4.1
- Firebase (5.4.0)
- FirebaseRemoteConfig (3.0.0)

![2018-07-12 4 25 02](https://user-images.githubusercontent.com/29110258/42618984-a25589ae-85f1-11e8-8e2b-da91db8ac4b2.png)

**Comment by morganchen12** [comment]
This is fixed internally and will be out in the next ABTesting release. For the curious, we weren't invalidating our NSURLSessions.

Internal patch number cr/204376974

**Comment by morganchen12** [comment]
In the future, please file SDK bugs (even for closed-source components) at https://github.com/firebase/firebase-ios-sdk/issues.
