### ISSUE TITLE
Notification Not Shows iOS

### ISSUE THREAD

**Issue by pratikdonda** [firebase/quickstart-ios#489]
Hello there!

Let me know if i want to display notification to user so the notification payload object have contains notification object or not? right now i'm receiving notification payload from backend side like this 
[
            gcm.message_id: 123456
            payload: {
                title: Hey there!
                subtitle: Welcome to iOS App
            }
            type: message
            aps: {
                content-available: 1
            }
]
In this payload format i'm not able to shows notification to user

**Comment by morganchen12** [comment]
What FCM endpoint are you sending your notification to?

**Comment by morganchen12** [comment]
You're not able to display the notification because it contains a `content-available` flag set to `1`, which means it'll be sent as a silent notification. If you remove that flag it should work.
