### ISSUE TITLE
In Video mode smile,both eye open probablity getting 0.

### ISSUE THREAD

**Issue by pandeyshivang** [firebase/quickstart-ios#495]
the code is properly working on IMage but getting an issue like Smile, eye not getting zero always in MLVision.
Please reply as soon as possible because I am working on this project.
` for face in features {
        print("face ",face)
          
            print("face  smile ", smile)
        
        
        let normalizedRect = CGRect(
          x: face.frame.origin.x / width,
          y: face.frame.origin.y / height,
          width: face.frame.size.width / width,
          height: face.frame.size.height / height
            
        )
        let standardizedRect =
          self.previewLayer.layerRectConverted(fromMetadataOutputRect: normalizedRect).standardized
        UIUtilities.addRectangle(
          standardizedRect,
          to: self.annotationOverlayView,
          color: UIColor.green
        )
      }
    }`

**Comment by morganchen12** [comment]
Can you share your project?

**Comment by pandeyshivang** [comment]
It's your demo project.

**Comment by morganchen12** [comment]
Can you share the versions of MLKit and Firebase that you're using?

**Comment by jguinez** [comment]
You have to set 

```
        options.classificationType = .all
        let faceDetector = vision.faceDetector(options: options)
```

to capture those features
