### ISSUE TITLE
iOS 11.2.6 Push notification not calling any delegate on background?

### ISSUE THREAD

**Issue by GopiK14** [firebase/quickstart-ios#497]
Hi,

We are receive silent push notification and no delegate method is calling ?
In iOS 10 I was getting push notifications and application:didReceiveRemoteNotification:fetchCompletionHandler were getting called correctly.

But in iOS 11 no delegate called. we can able to receive push on delegate methods on debug mode.

Any idea?

` [AnyHashable("gcm.notification.type"): 0, AnyHashable("gcm.notification.msg"): {"extraType":"Text","content":"Test sound"}, AnyHashable("gcm.message_id"): 0:1531860472186830%c52fb209c52fb209, AnyHashable("google.c.a.e"): 1, AnyHashable("aps"): {
    alert =     {
        body = "text body";
        title = "Gopi k";
    };
    badge = 2;
    "content-available" = 1;
    sound = Default;
}]`

**Comment by morganchen12** [comment]
Can you try removing the `alert` key from your data payload? Silent notifications shouldn't also have alerts.

**Comment by GopiK14** [comment]
Ok, I will try that and update you

**Comment by GopiK14** [comment]
@morganchen12  We tried without alert , but app is not receive push on delegate methods? Any other suggestions?

And it is working fine in iOS.

**Comment by GopiK14** [comment]
No, Please check the code below,



> // [START ios_10_message_handling]
    @available(iOS 10, *)
    
extension AppDelegate : UNUserNotificationCenterDelegate {
        
      
        
        // Receive displayed notifications for iOS 10 devices.
        func userNotificationCenter(_ center: UNUserNotificationCenter,
                                    willPresent notification: UNNotification,
                                    withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
            //TODO: Handle foreground notification
            
            let cnt = UserDefaults.standard.integer(forKey: "PushCount_UN") + 1
            UserDefaults.standard.set(cnt, forKey: "PushCount_UN")
            
            self.scheduleLocalNotification(s: "willPresent iOS 10.0 BACKGROUND_CH_iOS")
            
           // self.scheduleLocalNotification(s: "200")
            UserDefaults.standard.set(200, forKey: "PushCount")
            UserDefaults.standard.synchronize()
            
            let userInfo = notification.request.content.userInfo
            
            // With swizzling disabled you must let Messaging know about the message, for Analytics
             //Messaging.messaging().appDidReceiveMessage(userInfo)
            
            // Print message ID.
            if let messageID = userInfo[gcmMessageIDKey] {
                print("iOS 10 Message ID: \(messageID)")
            }
            
            // Print full message.
            print("iOS 10 UN willPresent userInfo : \(userInfo)")
            
            if(UIApplication.shared.applicationState == UIApplicationState.inactive )
            {
                print( "iOS 10.0, INACTIVE" );
                completionHandler([.alert, .badge, .sound])
            }
            else if(UIApplication.shared.applicationState == UIApplicationState.background )
            {
                print( "iOS 10.0, BACKGROUND" );
                
                completionHandler([.alert, .badge, .sound]);
            }
            else
            {
                print( "iOS 10.0, FOREGROUND" );
                completionHandler([.alert, .badge, .sound]);

            }

            // Change this to your preferred presentation option
            completionHandler([.alert, .badge, .sound]);

        }
        
        func userNotificationCenter(_ center: UNUserNotificationCenter,
                                    didReceive response: UNNotificationResponse,
                                    withCompletionHandler completionHandler: @escaping () -> Void) {
            
            self.scheduleLocalNotification(s: "300")

            UserDefaults.standard.set(300, forKey: "PushCount")
            UserDefaults.standard.synchronize()
            CoreDataProcess.shared.countDataInBackground_DataPayload += 3;

            let userInfo = response.notification.request.content.userInfo
            //TODO: Handle background notification

            // Print message ID.
            if let messageID = userInfo[gcmMessageIDKey] {
                print("iOS 10 UN Message ID: \(messageID)")
            }
            
            // Print full message.
            print("iOS 10 UN didReceive userInfo : \(userInfo)")

            completionHandler()
        }
    }
    // [END ios_10_message_handling]

   func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        // If you are receiving a notification message while your app is in the background,
        // this callback will not be fired till the user taps on the notification launching the application.
        // TODO: Handle data of notification
        
        // With swizzling disabled you must let Messaging know about the message, for Analytics
         //Messaging.messaging().appDidReceiveMessage(userInfo)
        
        let cnt = UserDefaults.standard.integer(forKey: "PushCounts") + 1
        UserDefaults.standard.set(cnt, forKey: "PushCounts")
        UserDefaults.standard.synchronize()

        // Print full message. Open State, Min State iOS 11
        print("didReceiveRemoteNotification userInfo : \(userInfo)")
        
        let type:String = "0"
        
        self.scheduleLocalNotification(s: "iOS11 BACKGROUND_CH_PH \(type)")//iOS10 Calling
        completionHandler(UIBackgroundFetchResult.newData)

}

**Comment by morganchen12** [comment]
There's no huge issues with this code, but it looks like your implementation of `willPresent` is calling the completion handler multiple times.

**Comment by GopiK14** [comment]
Ok thanks!, i tried with single completion handler not entered in UNNotification delegates. Do we need to remove  -> 

>          func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        completionHandler(UIBackgroundFetchResult.newData)
    }

**Comment by morganchen12** [comment]
That should be fine.

**Comment by GopiK14** [comment]
Yes, push notifications are receiving on mobile. and tried APNS too. 

Thing is, If mobile device connected to mac means, we get push message and delegate methods but not when we disconnect the mobile from mac.

**Comment by eironeia** [comment]
Same here. Waiting for some answer that fix it.

**Comment by GopiK14** [comment]
Yes :(

**Comment by morganchen12** [comment]
If you're sending silent push notifications, they'll be throttled by the system whenever the device is not connected to power. The amount of throttling depends on a number of things including how you're handling silent notifications.

To clarify, you're able to receive silent push notifications while backgrounded and connected to power, right?

**Comment by GopiK14** [comment]
To clarify, you're able to receive silent push notifications while backgrounded and connected to power, right? - Yes correct

**Comment by morganchen12** [comment]
There's nothing wrong with your Firebase (or APNs) setup then. You can try to mitigate throttling by doing less work in your fetch completion handler, but that's about it. Apple doesn't release any information on throttling specifics.
