### ISSUE TITLE
FirebaseDatabaseUI.framework/FirebaseDatabaseUI(FirebaseCollectionViewDataSource.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by sabhay1996** [firebase/quickstart-ios#50]
Unable to archive . 
If I remove use bitcode , app thinning will not work.
Is there any workaround as I have to start beta testing :/

Pods/FirebaseUI/FirebaseUIFrameworks/Database/Frameworks/FirebaseDatabaseUI.framework/FirebaseDatabaseUI(FirebaseCollectionViewDataSource.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ianbarber** [comment]
Hi! I think this issue is best tracked over on the FirebaseUI library page: https://github.com/firebase/FirebaseUI-iOS

You should have the option of using the Firebase SDK directly, which (generally) does have bitcode support.
