### ISSUE TITLE
"Recipient time zone" based push notifications not working (Unity 3D)

### ISSUE THREAD

**Issue by stopiccot** [firebase/quickstart-ios#501]
Recepient time zone notifications are not working for me in my Unity3D project (Unity3D 2017.4.7, Firebase Messaging Unity plugin 4.4.1, Xcode 9.4.1, device with iOS 11.4). Send Now, and Scheduled without Recepient time zone checkmark enabled push notifications are working fine.

**Comment by stopiccot** [comment]
Is there any way to check that "recepient time zone" notification was actually received by the device, and was successfully rescheduled al local one?

**Comment by morganchen12** [comment]
You can check the queue of scheduled local notifications via these APIs:

- [`-[UIApplication scheduledLocalNotifications]`](https://developer.apple.com/documentation/uikit/uiapplication/1622993-scheduledlocalnotifications)
- [`-[UNUserNotificationCenter getPendingNotificationRequestsWithCompletionHandler:]`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649513-getpendingnotificationrequestswi)

**Comment by morganchen12** [comment]
@stopiccot please comment here if this is still an issue.
