### ISSUE TITLE
APNs auth key production is not working

### ISSUE THREAD

**Issue by avjiang** [firebase/quickstart-ios#503]
I can fire the push notification during the development using my own local devices.

But when I deploy the app to the app store and then download it. the push notification does not show up. Is there anything i missed ?

Hopefully someone will be able to guide me. thanks

**Comment by morganchen12** [comment]
Are you using certificates or auth key?

Make sure your entitlements have the push notification permission enabled.

**Comment by morganchen12** [comment]
Please comment with more information and I'll reopen this ticket.
