### ISSUE TITLE
FCM data message not received when app is in Terminated state

### ISSUE THREAD

**Issue by Yash2711** [firebase/quickstart-ios#508]
I am using FCM data push and the data will be triggered by a server. Everything seems to be working fine when the app is running in foreground and background. 

But when the app is completed closed, data push stops coming. 

Can someone please let me know How to fix the same.

**Comment by morganchen12** [comment]
Are you sending silent notifications?

**Comment by Yash2711** [comment]
No, the usual ones with data payload. Can you please point me to some document or some place where FCM data message is handled when app is in terminated state.

**Comment by Yash2711** [comment]
@morganchen12 I think I have put through in wrong way, I am using FCM of a type as a **data message** mentioned [here](https://firebase.google.com/docs/cloud-messaging/concept-options)

And the payload structure is similar to this - 

```
{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "data":{
      "body" : "Hello",
      "title" : "Hi"
    }
  }
}

```

As per my understanding, this payload is something app needs to process and handle. Which works both in the foreground and background mode but not when the app is completely closed. None of the delegates are called. Is this something a limitation of data type FCM message?

**Comment by morganchen12** [comment]
Data only notifications won't be sent by the system if the user force-quits your app. This isn't an FCM behavior, it's something iOS does to conserve resources. Unfortunately there's no workarounds to what you're seeing here.

[Here's](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1) Apple's docs on the subject.
