### ISSUE TITLE
[MLKit] Non-latin based support in On Device Text Recognition

### ISSUE THREAD

**Issue by joaomelo81** [firebase/quickstart-ios#528]
Hi,

is there any chance of having the MLKit On Device Text Recognition framework supporting the non-latin based languages such as asian ones (Japanese, Chinese, ...)?

**Comment by morganchen12** [comment]
This is something we'd like to add eventually, but I can't guarantee when or if it will be added in the near future. 

If you'd like to file a feature request, you can do so [here](https://firebase.google.com/support/contact/).

**Comment by sunlancerbow** [comment]
For non-latin text, it would be really good if it can just return blocks and lines positions for now, without character recognition. 
Then we can use other tools in mlkit / tensorflow to recognize these picture segments to get text.
