### ISSUE TITLE
Silent Push Notification not waking up the app.

### ISSUE THREAD

**Issue by NasrullahKhan** [firebase/quickstart-ios#529]
I tried silent push notification which is working on the foreground and background. but it is not working when the app is suspended/killed.

NOTE:
 I tested these ways 
1. FCM Token
2. Topic Subscription.

Using this method to fetch the data:
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void){}

Background mode is on and background fetch is checked.

**Comment by morganchen12** [comment]
Silent notifications will not be sent if your app has been manually killed by the user. Notifications may be throttled by the system if your app is suspended. If silent notifications are working in the foreground and background, then you've set up notifications correctly.

Unfortunately there's nothing that can be done about the system behavior, which exists to limit app wakeups and conserve battery.
