### ISSUE TITLE
MLModelInterpreter doesn't actually work due to incorrect NSStringEncoding

### ISSUE THREAD

**Issue by alexisapuli** [firebase/quickstart-ios#535]
Error encountered when trying to detect using a valid model : 

MLModelInterpreterExampleObjC[45794:2479647] Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.

![screen shot](https://user-images.githubusercontent.com/42930778/45262432-fe2ff180-b448-11e8-9c48-b83ff66d9be3.png)

**Comment by ulukaya** [comment]
fixed that issue in https://github.com/firebase/quickstart-ios/commit/858b21b583f970057cbe5aea8122287b0c8a60fd
but detection is actually blocked by another bug. On it.

**Comment by ulukaya** [comment]
fixed the whole issue. https://github.com/firebase/quickstart-ios/commit/8292e2c5b038a0e25c3d5521617283285e5e5f13

it was a reverse sorting.

**Comment by alexisapuli** [comment]
Thanks!
