### ISSUE TITLE
Firebase dynamic link not opening the app iOS9

### ISSUE THREAD

**Issue by starjang** [firebase/quickstart-ios#54]
I have developed & installed an iOS app locally on my device.
And have set custom scheme in the info.plist as mydlink
Set associated domains as weel: applinks:<myapp>.app.goo.gl
Created dynamic link on firebase as:
https://<myapp>.app.goo.gl/?link=http://<mysite.com>/&ibi=<app bundle id>&ius=mydlink&ifl=https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id%3D<app store id>%26mt%3D8&pt=<app store id>
When i open or click on dynamic link, it opens app page in the "App Store" app and not opening app itself though its installed.
Can you point out here what i am missing..

**Comment by heinrisch** [comment]
The top answer here solved it for me:
http://stackoverflow.com/questions/32751225/ios9-universal-links-does-not-work

I was trying to open the deeplink in safari and that is not working.

**Comment by lindsayHan** [comment]
HI I can open the iOS app locally when it's installed, but it opens the app stores also.

**Comment by xsoti** [comment]
I have similar Issue, when I open link in for example gmail app, it redirect it to my application, but when I'm openning it in standard iOS mail app it goes straight to Safari and then to custom page or Apple Store depends what user choose. 
After much digging I can't find what I could be missing.

**Comment by starjang** [comment]
When I use Chrome browse.  It is OK!

**Comment by ianbarber** [comment]
Some of this I think is just general universal link handling - safari entered links (and links from within your app) are going to go to the fallback view, but links within a webpage or using `openUrl` should work OK. I'll close this, but if anyone is having issues please open a specific issue (ideally with a complete long link that isn't working), or file an issue with Firebase Support: https://firebase.google.com/support/contact/troubleshooting/
