### ISSUE TITLE
No such module 'Firebase'

### ISSUE THREAD

**Issue by Lawris** [firebase/quickstart-ios#55]
I just cloned the repo, did a `pod install`.
I tried to run FCMSwift, in ViewController.swift it throws 

> No such module 'Firebase'

How can I fix this issue ?

**Comment by stwktw** [comment]
I have the same problem.

**Comment by dfezzie** [comment]
Make sure you are running FCM.xcworkspace not FCM.xcodeproj

**Comment by gabehoffman** [comment]
You have to go into the directory, and then do a pod install to create the workspace file

**Comment by levantAJ** [comment]
I ran into this problem as well, my case is I create new library which include Firebase (compile success). But when I integrate that library to our app, this error happen.
Anybody can help?
