### ISSUE TITLE
Getting incorrect x,y frame for image captured using camera ios

### ISSUE THREAD

**Issue by poojab** [firebase/quickstart-ios#551]
I am using on device text detection ,MLVisionTextModel.
in which I am capturing image using camera sending image to textdetector with metadata of image orientation.
When I print result , it shows in incorrect y position. line which is on top of other line has greater value than of line below it. 
where as if I directly embed image into the project architecture and load it for textdetection then it works well.
Not sure what is going wrong here.

>  var textDetector: VisionTextRecognizer!
>     lazy var vision = Vision.vision()
>  textDetector = self.vision.onDeviceTextRecognizer()
>   let visionImage = VisionImage(image: image)
>         let metadata = VisionImageMetadata()
>         metadata.orientation = self.detectorOrientation(in: image)
>         visionImage.metadata = metadata
>         textDetector.process(visionImage) { (features, error) in
>             if features != nil
>             {
>                 self.processResult(from: [features!], error: error)
>             }
>         }

>  //Detects orientation of the selected or captured image
>     func detectorOrientation(in image: UIImage) -> VisionDetectorImageOrientation {
>         
>         
>         switch image.imageOrientation {
>         case .up:
>             return .topLeft
>         case .down:
>             return .bottomRight
>         case .left:
>             return .leftBottom
>         case .right:
>             return .rightTop
>         case .upMirrored:
>             return .topRight
>         case .downMirrored:
>             return .bottomLeft
>         case .leftMirrored:
>             return .leftTop
>         case .rightMirrored:
>             return .rightBottom
>         }
>     }

**Comment by morganchen12** [comment]
Closing since this has staled. Please comment here and I'll reopen.
