### ISSUE TITLE
Latest firebase pod version + iOS 12 issue

### ISSUE THREAD

**Issue by avjiang** [firebase/quickstart-ios#554]
I am having issue where scheduled notification from firebase console will not send the notification to iOS devices (iOS 12). 

The devices will receive notification if the notification is "Send now" from the firebase console. can anyone help me please? thanks

**Comment by morganchen12** [comment]
Scheduled notifications rely on silent notification delivery behavior, which may have changed between iOS 11 and 12. If this is the case, there's unfortunately not much we can do about it.
