### ISSUE TITLE
Notification is not coming in iOS 12.

### ISSUE THREAD

**Issue by ParvendraSingh** [firebase/quickstart-ios#555]
Hi Team,
I am using FCM for Notification, i am getting notification on iOS version < 12 devices.
But not on devices having iOS 12.
I updated Firebase Core and Messaging pods, after that i face same problem.
I am getting Message packet 

func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        debugPrint(remoteMessage.appData)
 }

But not getting Message packet as APS.
Help me out if there are any changes for ios iOS 12.

Thanks

**Comment by kroikie** [comment]
@ParvendraSingh There should be no changes on how we send or how you receive messages on iOS 12. Could you include the request you are using to send the message?

**Comment by ParvendraSingh** [comment]
@kroikie Thanks for your kind reply, but i am still on same page.
I am getting FCM Message as APS in iOS 10 & 11 but not getting in iOS 12.
I replace my all code for UNUserNotification and FCM, i tried with new auth key but still i am getting message in delegate method only.

I am not able to call  UNUserNotification delegate method(willPresent notification),
will you please suggest me for this?

**Comment by morganchen12** [comment]
@ParvendraSingh are you able to send to your device directly through APNs?

**Comment by kroikie** [comment]
@ParvendraSingh the

```
func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
debugPrint(remoteMessage.appData)
}
```

method is only for [direct channel messages](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle-direct-fcm-channel-messages) from FCM. If you are sending messages through APNs then you will have to use one of the APNs callbacks to handle messages.

**Comment by ParvendraSingh** [comment]
Hey @kroikie and @morganchen12 ,
Thanks for your quick response, actually there was my mistake.
i forget to set apns token to messaging services.

Thanks you so much for your kind help

**Comment by manuelsBTS** [comment]
@ParvendraSingh You said

**I forget to set apps token to messagings services**

How did you that?

**Comment by morganchen12** [comment]
@manuelsBTS  if you have swizzling enabled, Messaging does this automatically. Otherwise, you'll have to set the `apnsToken` property on the `Messaging` singleton in the system APNs refresh callback.
