### ISSUE TITLE
InAppMessagingExampleSwift: crash on launching

### ISSUE THREAD

**Issue by bohachevskyy** [firebase/quickstart-ios#557]
Hello! 
I cloned the repo, pasted my bundle id and added `GoogleService-Info.plist` file. When I try to launch the app I get crash on launch:

`Terminating app due to uncaught exception 'com.firebase.inappmessaging', reason: 'Error happened API key must not be nil or empty.`

I'm getting the same crash on my real project.
Could you help me, how I can solve this issue?

**Comment by morganchen12** [comment]
Can you share the stack trace for this crash? Also, have you enabled the In-App Messaging API in console?

**Comment by bohachevskyy** [comment]
Hello @morganchen12 thank you for the response. I managed to solve the issue. I redownloaded file `GoogleService-Info.plist`. I setup firebase a couple years ago, and didn't update `GoogleService-Info.plist` file for years. I suppose it was a reason 😄
