### ISSUE TITLE
Memory Leak in the SDK when Performing Network Request 

### ISSUE THREAD

**Issue by tpeodndyy** [firebase/quickstart-ios#559]
Hi,

I'm working on the running project and found what I hope to me just minor leak related to FIRNetworkURLSession

Environment:
- XCode 10.0 (10A254a)
- iOS11, 12

Related Firebase Versions
  - Fabric (1.7.9)
  - Firebase/Core (5.4.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.0.1)
  - Firebase/CoreOnly (5.4.1):
    - FirebaseCore (= 5.0.6)
  - Firebase/Performance (5.4.1):
    - Firebase/Core
    - FirebasePerformance (= 2.0.1)
  - FirebaseAnalytics (5.0.1):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseCore (5.0.6):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (3.1.1):
    - FirebaseCore (~> 5.0)
  - FirebasePerformance (2.0.1):
    - FirebaseAnalytics (~> 5.0)
    - FirebaseInstanceID (~> 3.1)
    - FirebaseSwizzlingUtilities/ISASwizzling (~> 2.0)
    - FirebaseSwizzlingUtilities/MethodSwizzling (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.5)
  - FirebaseSwizzlingUtilities/ISASwizzling (2.0.0)
  - FirebaseSwizzlingUtilities/MethodSwizzling (2.0.0):
    - FirebaseCore (~> 5.0)
- Crashlytics (3.10.5):
    - Fabric (~> 1.7.9)

I understand FIRObjectSwizzler will perform Firebase tracking for any URLSession app done. 
Please check the screenshots below for what I captured from Instrument.

<img width="1450" alt="screen shot 2018-10-11 at 9 18 49" src="https://user-images.githubusercontent.com/4329532/46773994-2dcd6480-cd3b-11e8-8d9c-58a109acd51c.png">
<img width="1445" alt="screen shot 2018-10-11 at 9 17 31" src="https://user-images.githubusercontent.com/4329532/46773999-30c85500-cd3b-11e8-8e30-0523dbc7724c.png">
<img width="1444" alt="screen shot 2018-10-11 at 9 33 30" src="https://user-images.githubusercontent.com/4329532/46774001-36259f80-cd3b-11e8-9d4d-eca43eb30525.png">
<img width="1445" alt="screen shot 2018-10-11 at 9 35 51" src="https://user-images.githubusercontent.com/4329532/46774006-3c1b8080-cd3b-11e8-8bee-aa39c7888452.png">
<img width="1448" alt="screen shot 2018-10-11 at 9 35 31" src="https://user-images.githubusercontent.com/4329532/46774020-4d648d00-cd3b-11e8-9d86-1e8651f991b4.png">

Please lemme know if you need any further information.

Cheers!

**Comment by paulb777** [comment]
@tpeodndyy Thanks for the report. We're working on this at https://github.com/firebase/firebase-ios-sdk/issues/1917

**Comment by fbarraganef** [comment]
Same issue happening to me...
