### ISSUE TITLE
GULAppDelegateSwizzler compile time error

### ISSUE THREAD

**Issue by Steven4294** [firebase/quickstart-ios#561]
I'm trying to run the StorageExample project and I'm getting an error in `GULAppDelegateSwizzerl.m`. Just ran `pod install` and hit build...

It looks like there is an unexpected type 

```
- (void)application:(UIApplication *)application
    handleEventsForBackgroundURLSession:(NSString *)identifier
                      completionHandler:(void (^)())completionHandler API_AVAILABLE:(ios(7.0)) {
```

**Comment by morganchen12** [comment]
@Steven4294 can you share your pod versions?
