### ISSUE TITLE
Update to Swift 4.2

### ISSUE THREAD

**Issue by manuelsBTS** [firebase/quickstart-ios#568]
Some features of this are deprecated.  Needs an update

**Comment by morganchen12** [comment]
We're not updating temporarily since some of our internal testing infrastructure isn't compatible with the newest Xcode yet.

**Comment by ulukaya** [comment]
https://github.com/firebase/quickstart-ios/commit/2c7f4497dc3a2539b06fc17ba168553e5494b934
