### ISSUE TITLE
Manual SDK installation of Firebase 3.3.0 doesn't work

### ISSUE THREAD

**Issue by hacknicity** [firebase/quickstart-ios#57]
I'd rather not use Cocoapods so downloaded the SDK directly as described in the 'Integrate without CocoaPods' section here: https://firebase.google.com/docs/ios/setup#available_pods

At the time I did that, the link to the SDK was https://dl.google.com/firebase/sdk/ios/3_3_0/Firebase.zip

The README.md tells me that I should copy these frameworks from the Analytics SDK:

~~~~
## Analytics
  - frameworks
  - FirebaseInstanceID.framework
  - GoogleInterchangeUtilities.framework
  - GoogleSymbolUtilities.framework
  - GoogleUtilities.framework
~~~~

The zip file doesn't contain a 'frameworks' (whatever that is). I did copy the four analytics frameworks to my project and the two from the Message SDK:

~~~~
## Messaging (~> Analytics)
  - FirebaseMessaging.framework
  - GoogleIPhoneUtilities.framework
~~~~

I copied the `Firebase.h` header file and when I import that in my own project I get an error because the first line of `Firebase.h` tries to import a non-existent file:

~~~~
#import <FirebaseAnalytics/FirebaseAnalytics.h>
~~~~

There's no `FirebaseAnalytics` framework in the SDK download.

Is the zip file missing some framework(s)?

**Comment by hacknicity** [comment]
When I do use cocoa pods to setup the sample `quickstart-ios\messaging` app my `Pods` directory looks like this:

~~~~~
$ ls Pods
drwxr-xr-x+  4 geoff  staff   136  6 Jul 17:21 Firebase
drwxr-xr-x+  3 geoff  staff   102  6 Jul 17:21 FirebaseAnalytics
drwxr-xr-x+  6 geoff  staff   204  6 Jul 17:21 FirebaseInstanceID
drwxr-xr-x+  6 geoff  staff   204  6 Jul 17:21 FirebaseMessaging
drwxr-xr-x+  3 geoff  staff   102  6 Jul 17:21 GoogleIPhoneUtilities
drwxr-xr-x+  3 geoff  staff   102  6 Jul 17:21 GoogleInterchangeUtilities
drwxr-xr-x+  3 geoff  staff   102  6 Jul 17:21 GoogleSymbolUtilities
drwxr-xr-x+  3 geoff  staff   102  6 Jul 17:21 GoogleUtilities
drwxr-xr-x+  4 geoff  staff   136  6 Jul 17:21 Headers
drwxr-xr-x+  2 geoff  staff    68  6 Jul 16:55 Local Podspecs
-rw-r--r--+  1 geoff  staff  1475  6 Jul 17:21 Manifest.lock
drwxr-xr-x+  4 geoff  staff   136  6 Jul 17:21 Pods.xcodeproj
drwxr-xr-x+  5 geoff  staff   170  6 Jul 17:21 Target Support Files
~~~~~

I have these frameworks:

~~~~~
Josephine-3:messaging geoff$ find Pods -name \*.framework -print
Pods/FirebaseAnalytics/Frameworks/frameworks/FirebaseAnalytics.framework
Pods/FirebaseInstanceID/Frameworks/FirebaseInstanceID.framework
Pods/FirebaseMessaging/Frameworks/FirebaseMessaging.framework
Pods/GoogleInterchangeUtilities/Frameworks/GoogleInterchangeUtilities.framework
Pods/GoogleIPhoneUtilities/Frameworks/GoogleIPhoneUtilities.framework
Pods/GoogleSymbolUtilities/Frameworks/GoogleSymbolUtilities.framework
Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework
~~~~

It would seem the SDK download is simply missing the `FirebaseAnalytics` framework!

**Comment by baolocdo** [comment]
We are aware of this issue and we are working on the fix. Thanks for reporting.

**Comment by baolocdo** [comment]
The latest Firebase framework file should have all the frameworks. Can you try with Firebase 3.4.0 framework?

**Comment by hacknicity** [comment]
I can confirm that the `Analytics` directory now contains the `FirebaseAnalytics.framework` and the `README.md` has also been updated to mention it.

I've not had a chance to use the new framework yet, but I'm happy that the packaging issue with the standalone SDK appears to have been resolved. Thank you.

**Comment by AhmedShmmala** [comment]
@baolocdo  now with https://firebase.google.com/download/ios
there no also  FirebaseAnalytics.framework  
it's 1.2 GB ?!
