### ISSUE TITLE
Save Data to local database when app is in quit/exit stage Silent notification

### ISSUE THREAD

**Issue by maheshm504** [firebase/quickstart-ios#571]
Hi Am able to get Push notification when app is in foreground/background
but I want to save to payload when app is in quit/exit stage
This is about silent notification by setting the 

content_available: 1

but still no luck can you help me out to save the data to UserDefaults

**Comment by morganchen12** [comment]
There's not enough information here to debug. Please comment with the code you're using to save data from your notification handler as well as your application quit handler implementation, then I'll reopen the issue.
