### ISSUE TITLE
Compile Error : kFirLoggerSwizzler refrenced from

### ISSUE THREAD

**Issue by tripathishivam35** [firebase/quickstart-ios#578]
I am getting this error :
![screenshot 2018-11-09 at 4 32 45 pm](https://user-images.githubusercontent.com/13601158/48259962-c2f97100-e43f-11e8-9c40-378f4ca69b10.png)
My Pods File sdk's versions are these :

![screenshot 2018-11-09 at 12 43 45 pm](https://user-images.githubusercontent.com/13601158/48259992-dad0f500-e43f-11e8-9325-ff8177146552.png)

Clearly Firebase pods are greater than 5.0. Peoples are mentioning this issue was in firebase 4.0 pods only but i am still facing this .

Build active architetures only is set to No. Let me know if i need to add anything else.

**Comment by paulb777** [comment]
One problem is using the deprecated `Google` pod.  See https://stackoverflow.com/questions/44538472/cocoapods-ios-google-has-been-deprecated-how-to-get-rid-of-the-warning/44546794#44546794

**Comment by tripathishivam35** [comment]
Thanks for your help @paulb777  . By removing the google pod I get rid of the above error.
I am still checking whether removing Google pod creates any effect on project. Will close the issue soon.

**Comment by tripathishivam35** [comment]
To all the fellow readers. I am able to resolve this issue as per @paulb777  suggestions -

In the Podfile, remove the Firebase version specifier.

Alternatively, change the Firebase version specifier to lock to minor releases with ~> 5.0 instead the current locking to patch updates with ~> 5.0.0.

It seems that not all of the Firebase components properly updated their version dependency specifiers since the Firebase 5.0.1 release. It looks like your Podfile is locking to a 5.0.x patch release which exposes the issue for you.

If you're still having trouble, share the Podfile.

Source - [https://stackoverflow.com/a/53251591/6600624](url)
