### ISSUE TITLE
Share with Whatsup app

### ISSUE THREAD

**Issue by nitin-agam** [firebase/quickstart-ios#582]
In iOS, by default FirebaseInvites opens SMS and email option to invites our friends. But I have to invite my friends on Whatsup and other share apps also. How can I achieve this?

Thanks!

**Comment by morganchen12** [comment]
We're working on some content around this, but in short--generate a dynamic link that invites users to your app, then open the link in whatsapp via the system dialogue (UIActionViewController).

**Comment by nitin-agam** [comment]
Ok, thank you for your response. I'll look into this solution as you suggested.

**Comment by morganchen12** [comment]
No problem! Feel free to comment again here if you need any additional guidance.
