### ISSUE TITLE
Dynamic Links: 'Skip the app preview page' always take to App Store

### ISSUE THREAD

**Issue by kamrankhan07** [firebase/quickstart-ios#586]
Skip the app preview page always take to App Store even when app is installed. Does anyone else face the same issue? Its happening when you tap the link from a chat client such as messenger, workchat, and from links posted on facebook and accessed via facebook app.

**Comment by morganchen12** [comment]
Does it work when you just paste the link into Notes and try to open it from there?

**Comment by nvnmog** [comment]
Check this out, follow step by step
https://firebase.google.com/docs/dynamic-links/ios/receive

**Comment by joshwolff1** [comment]
Add &efr=1 to the end of your link

**Comment by joshwolff1** [comment]
To test how "&efr=1", you can check out your link's debug flow chart by appending "&d=1" to the end of your link. Try adding the debug parameter with and without "&efr=1" and notice how the flowchart excludes and includes the preview page in each case, respectively.

**Comment by joshwolff1** [comment]
If adding "&efr=1" results in the link always taking you to the App Store - even when ur app is installed - see my answer here: https://stackoverflow.com/questions/44252185/firebase-dynamic-link-always-goes-to-app-store-url-even-if-the-app-is-installed/59331408#59331408

**Comment by moKelani** [comment]
any solutions yet?

**Comment by andriymosin** [comment]
Faced the same issue, adding `&efr=1` always takes you to the App Store

**Comment by dembeEdward** [comment]
Any luck with this issue?

**Comment by sugitatestblue** [comment]
Google's bug?
