### ISSUE TITLE
Error "Command failed due to signal: Segmentation fault: 11"

### ISSUE THREAD

**Issue by DanielLe232** [firebase/quickstart-ios#60]
import Firebase
......
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
FIRApp.configure()
}

When I add firebase into my project via cocoa pod, It occurs error " Command failed due to signal: Segmentation fault: 11"
Please help me.
Thank!

**Comment by baolocdo** [comment]
Can you turn on debug mode by adding the argument flag -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu) and give us the log and stack trace? Thanks

**Comment by DanielLe232** [comment]
http://pastebin.com/TPBrV8PF
I run xcode 7.3
Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)

Thank.

**Comment by janderson-primary** [comment]
I am having the same problem.  After upgrading Firebase in our project, I get a segmentation fault.

func updateRealtimeFoo(snap: FIRDataSnapshot) {

}

This method declaration is causing the problem.

**Comment by baolocdo** [comment]
I have not encountered this issue before. It is probably the Swift compiler crashes due to initial project setup. Would you mind clearing the module cache, cleaning the build folder, and uninstalling and reinstalling the Pods? Please let us know if it works.

**Comment by MadeInFck** [comment]
I do have the same issue with FIRDataSnapshot. None of the solution suggested in the Baolocdo's comment link have helped.

**Comment by ianbarber** [comment]
Hi all - is anyone still seeing these issues with GM XCode 8 and the updated samples?

**Comment by jeremybroutin** [comment]
Yep, just implemented a copy of the FCM demo app (https://github.com/firebase/quickstart-ios/tree/master/messaging) and am getting the segmentation fault error. This also occurred in my own project while trying to implement FCM.

The error is located in the AppDelegate: "While deserializing AppDelegate".
I tried moving the extensions (to handle the delegates methods) into the class itself, but no better luck.

**Comment by 1amageek** [comment]
I also have same error.

Xcode 8.1 beta
Swift3

#### Command failed due to signal: Segmentation fault: 11

```
1.	While loading members for 'MyProtocol' at <invalid loc>
2.	While deserializing decl #28 (PATTERN_BINDING_DECL)
3.	While deserializing decl #29 (VAR_DECL)
```

#### Source code
```
// success
protocol MyProtocol {
    static var database: FIRDatabaseReference { get }
}

// fail
protocol MyProtocol {
    static var database: FIRDatabaseReference { get }
    var snapshot: FIRDataSnapshot { get } // add this code to fail
}
```

#### Podfile
```
// cocoapods version 1.0.1
platform :ios, '8.1'
pod 'Firebase'
pod 'Firebase/Database'
```

**Comment by DominikButz** [comment]
xcode 8 
swift 3
macOS Sierra

Same problem.   I actually didn't add my own code to the project - I'm just following the FriendlyChat tutorial instructions from Google Codelabs.... 

1.	While loading members for 'FCViewController' at <invalid loc>
2.	While deserializing decl #153 (PATTERN_BINDING_DECL)
3.	While deserializing decl #17 (VAR_DECL)

**Comment by jordibruin** [comment]
Same here when adding the Messaging delegates via the extensions

**Comment by jeremybroutin** [comment]
Trying updating cocoapod to the latest version, that was my issue ;)

**Comment by jordibruin** [comment]
@jeremybroutin I updated to 1.0.1 and dit a pod update but it didn't solve the issue. Also tried the 8.1 xcode beta to no avail 😞

**Comment by 1amageek** [comment]
Do you use the `use_frameworks!` ?
I was solved with this.

In the project that can not use the `use_frameworks!`, I used the static library.

[Firebase Integrate without CocoaPods](https://firebase.google.com/docs/ios/setup)

```
target 'YOUR_APP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Crash'
  pod 'Firebase/Auth'

  target 'YOUR_APP_Tests' do
    inherit! :search_paths
    # Pods for testing
  end 

  target 'YOUR_APP_UITests' do
    inherit! :search_paths
    # Pods for testing
  end 

end
```

**Comment by ianbarber** [comment]
Closing - I think this one is generally either use_frameworks! or old cocoapods, but there is a lot of stuff that seems to segfault the toolchain!
