### ISSUE TITLE
FireMessage's delegate messaging: didReceiveMessage: can't be called

### ISSUE THREAD

**Issue by 304164084** [firebase/quickstart-ios#602]
In my app. 
messaging:(FIRMessaging *)messaging
    didReceiveRegistrationToken:(NSString *)fcmToken can be called
 but messaging:(FIRMessaging *)messaging
    didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage can't be. 
why ?

I switched shouldEstablishDirectChannel to yes. for that, i can avoid APNS notification that i can use FCM message's delegate didreceivedMessage:  realize like IM.

**Comment by morganchen12** [comment]
Can you share your pod versions and codebase?

**Comment by morganchen12** [comment]
I see. The messaging delegate's [callback methods](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Protocols/FIRMessagingDelegate#/c:objc(pl)FIRMessagingDelegate(im)messaging:didReceiveMessage:) are used only to receive non-APNs data messages sent directly through the FCM direct channel. For all other messages you still need to implement the system notification handler methods.
