### ISSUE TITLE
facing some issue to generate shortenURL from firebase dynamic-links 

### ISSUE THREAD

**Issue by sombizbuzzz** [firebase/quickstart-ios#612]
facing some issue to generate shortenURL from firebase dynamic-links , I am able to get longDynamicLink url . but 

here is my code , I am using https://firebase.google.com/docs/dynamic-links/ios/create following steps DynamicLinkComponents.shortenURL completion not getting call and there is no error also  

    guard let longDynamicLink = linkBuilder.url else { return "test" }
    print("The long URL is: \(longDynamicLink)")
    
    DynamicLinkComponents.shortenURL(longDynamicLink, options: nil) { url, warnings, error in
        guard let url = url, error != nil else { return }
        print("The short URL is: \(url)")
    }

DynamicLinkComponents.shortenURL this part is not executing

**Comment by morganchen12** [comment]
Can you print the `error` parameter in the `shortenURL` completion handler?
