### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by arkilis** [firebase/quickstart-ios#62]
/Users/xx/xxx/ios_dev/quickstart-ios/storage/StorageExample/GoogleService-Info.plist:0: error: reading data: The file “GoogleService-Info.plist” couldn’t be opened because there is no such file.

**Comment by samtstern** [comment]
@arkilis check out the [Getting Started Guide](https://firebase.google.com/docs/ios/setup) which describes where to get the plist file and where it should go.
