### ISSUE TITLE
No Push notifications being sent

### ISSUE THREAD

**Issue by jcampbell05** [firebase/quickstart-ios#63]
I get them over FCM but when app is in background I don't get push notifications at all.

**Comment by ianbarber** [comment]
In the background they're sent over APNs - can you check the certificates are set up properly in the Firebase Console, and that you're using the right sandbox mode?

**Comment by sadh** [comment]
Can you explain what is "right sandbox mode"? because i am getting following log "deny(1) file-write-create /private/var/containers/Bundle/Application/FIREBASE_LAST_TIMESTAMP"

**Comment by ianbarber** [comment]
Hmm, that timestamp error is an odd one - it not related to FCM per-se, its part of the internal working of FIRApp. What sort of device is this happening on?

**Comment by ianbarber** [comment]
Just checked: sadh@ that issue should be fixed in the latest version. What library version are you using?

**Comment by sadh** [comment]
I am using Firebase 3.4.0, and FirebaseMessaging 1.1.1. It is working now :-) i am getting notifications.

**Comment by erdengurkan** [comment]
how did you fix? @sadh
