### ISSUE TITLE
Class are implemented in both,  One of the two will be used. Which one is undefined console messages.

### ISSUE THREAD

**Issue by Dinalli** [firebase/quickstart-ios#633]
When building the example and other projects you get the following in the console, for a number of 

Class GPBAnyRoot is implemented in both /private/var/containers/Bundle/Application/5122D7C4-688F-4585-9084-BA6E6651A5E8/MLVisionExample.app/Frameworks/Protobuf.framework/Protobuf (0x103b0b6b8) and /var/containers/Bundle/Application/5122D7C4-688F-4585-9084-BA6E6651A5E8/MLVisionExample.app/MLVisionExample (0x103221070). One of the two will be used. Which one is undefined.

From investigation this seems to stem from using the Label Model and Text Model in the same project.
They should work independently and not cause the issue.

Can recreate on the Example App. Issue was not present on version 0.13.0

**Comment by ulukaya** [comment]
Reported internally to triage and resolve.

**Comment by ulukaya** [comment]
b/123650332

**Comment by ulukaya** [comment]
Hi @Dinalli,
Issue is fixed internally and should be released with the next update of GMV. I'll be closing this for now but feel free to open up again if the issue exits past the next release of GMV.

**Comment by tocute** [comment]
Hi @ulukaya 
I met the same problem after I import FirebasePerformance and GoogleCast

Class GPBAnyRoot is implemented in both /***/Frameworks/GoogleCast.framework/GoogleCast (0x10d3e12f0) and /***/App_Name (0x10adfa7a8). One of the two will be used. Which one is undefined.

[Firebase/Crashlytics] Version 4.6.1
[Firebase/Analytics][I-ACS023007] Analytics v.60803000 started
