### ISSUE TITLE
MLVision scans random barcodes when idle, even when camera has no barcode in view.

### ISSUE THREAD

**Issue by SunillaShamas** [firebase/quickstart-ios#637]
Hi I am trying to use the MLVisiosn for barcode scanner for UPC-A/E, code128, QR, EAN8/13 and Interleave2of5, using camera feed. During development if my camera feed is on for barcode scanning, even when i dont scan a barcode, after some time the scanner scans a random barcode, sometimes a proper barcode format and sometimes like ->  iz"" "" " .

Please suggest why is the library detecting barcodes even when there is none in sight.
Thanks

**Comment by ulukaya** [comment]
reported internally. b/124051164

**Comment by SunillaShamas** [comment]
Hi there, is there any update on it?

**Comment by miworking** [comment]
Hi Sunilla,

Can I know the resolution of your camera when this is reproducible? Thanks!

Julie from MLKit

**Comment by morganchen12** [comment]
Sunilla, please comment here and we'll reopen the issue.
