### ISSUE TITLE
App reset at second launch on iOS 12.1.2

### ISSUE THREAD

**Issue by ink-spot** [firebase/quickstart-ios#638]
Hi there.

I followed [the instructions](https://firebase.google.com/docs/cloud-messaging/ios/client) to integrate Firebase notifications in my app. Everything work well on iOS 10, 11 and 12.0, but the behaviour under iOS 12.1.2 is weird.
At first launch, things go well, a FCM token is generated and I can send push to it.
But when killing the app and relaunching it, it acts like it was a fresh intall: on `[FIRApp configure]`, the app is reset and the token is disabled, but Firebase never gives me a new valid token. The `didReceiveRegistrationToken` callback is called with the same token as during first launch, but when I send a push to it, it never arrives and the API returns me a `notRegistered` error.
The result is the same if I send the push via the API or the Firebase Console.

Here are the debug logs of the second launch, where the app is reset.
```
5.16.0 - [Firebase/InstanceID][I-IID023000] No info is retrieved from Keychain OSStatus: -25300 with the keychain query {
    atag = <636f6d2e 676f6f67 6c652e69 69642d7c 4b7c>;
    class = keys;
    "r_Ref" = 1;
    type = 42;
}
5.16.0 - [Firebase/InstanceID][I-IID023000] No info is retrieved from Keychain OSStatus: -25300 with the keychain query {
    atag = <636f6d2e 676f6f67 6c652e69 69642d7c 507c>;
    class = keys;
    "r_Ref" = 1;
    type = 42;
}
5.16.0 - [Firebase/InstanceID][I-IID009000] No keypair info is retrieved with tag com.google.iid-|K|
5.16.0 - [Firebase/Messaging][I-FCM002000] FIRMessaging library version 3.3.0
5.16.0 - [Firebase/InstanceID][I-IID007006] Checkin parameters: {
    checkin =     {
        iosbuild =         {
            model = "iPhone11,2";
            "os_version" = "IOS_12.1.2";
        };
        "last_checkin_msec" = 0;
        type = 2;
        "user_number" = 0;
    };
    digest = "";
    fragment = 0;
    id = 0;
    locale = "fr_FR";
    "logging_id" = 969327929;
    "security_token" = 0;
    timezone = "Europe/Paris";
    "user_serial_number" = 0;
    version = 2;
}
5.16.0 - [Firebase/InstanceID][I-IID013002] Removed cached checkin preferences from Keychain.
5.16.0 - [Firebase/InstanceID][I-IID013006] App reset detected. Will delete server registrations.
5.16.0 - [Firebase/InstanceID][I-IID023002] Couldn't delete item from Keychain OSStatus: -25300 with the keychain query {
    acct = "com.google.iid.checkin-account";
    class = genp;
    gena = "com.google.iid";
    svce = "com.google.iid.checkin-service";
}
5.16.0 - [Firebase/InstanceID][I-IID003012] Provisioning profile has specifically provisioned devices, most likely a Dev profile.
5.16.0 - [Firebase/InstanceID][I-IID003013] APNS Environment in profile: development
5.16.0 - [Firebase/InstanceID][I-IID021000] Unregister request to https://iid.googleapis.com/iid/register content: X-osv=12.1.2&device=...&plat=2&app=...&app_ver=2.7.0&X-cliv=fiid-3.3.0&delete=true
5.16.0 - [Firebase/InstanceID][I-IID014007] Successfully deleted GCM server registrations on app reset
5.16.0 - [Firebase/InstanceID][I-IID007002] Invalid last checkin timestamp in future.
5.16.0 - [Firebase/InstanceID][I-IID007003] Checkin successful with authId: 5156457280410576815, digest: dKLj6wvX7g8BHtVBLSruwQ==, lastCheckinTimestamp: 1549558248000
5.16.0 - [Firebase/InstanceID][I-IID005004] Successfully got checkin credentials
5.16.0 - [Firebase/InstanceID][I-IID023002] Couldn't delete item from Keychain OSStatus: -25300 with the keychain query {
    acct = "...";
    class = genp;
    gena = "com.google.iid";
    svce = "com.google.iid.checkin";
}
5.16.0 - [Firebase/InstanceID][I-IID005002] Checkin success.
```

Tested on iPhone XS, iOS 12.1.2, with Firebase 5.16.0 (Firebase Messaging 3.3.0).

**Comment by morganchen12** [comment]
It's hard to tell what your issue might be without being able to look at your implementation, but this sounds similar to the issue described here: https://github.com/firebase/firebase-ios-sdk/issues/1339

**Comment by ink-spot** [comment]
Concerning the Firebase part, my implementation is the exact same code as in the instructions (and in the example project).
The issue you linked to is not the same, as in my case, the `didReceiveRegistrationToken` is called with a token. The only problem being that this token has just been unregistered and is not valid anymore.
On what conditions does the framework think it's a fresh install? Is the app reset triggered because of missing info in the keychain (as seen in the logs above)?

**Comment by ink-spot** [comment]
Thanks for you help!
After further investigation, the issue seemed to come from the UserVoice framework, which I was initializing after the `[FIRApp configure]`. For some reason (don't know why though), it made Firebase unregister the token.
I removed it and everything works fine now.

The fact that Firebase unregisters the token but doesn't give me a new valid one is still weird though.
