### ISSUE TITLE
Unable to Integrate with Existing project containing Google Sign in and Google Analytics Library

### ISSUE THREAD

**Issue by kalrashubham49** [firebase/quickstart-ios#64]
I was using seperate Frameworks for GoogleSignin Sdk and Google Analytics Lib. In order to Use Firebase for cloud messaging , opted out for Cocoa Pods and Getting Numberous problems ragarding duplicate symbols found in GoogleSignInSDK and Analytics Lib

Following Below Steps:

1. 1. Install pods for Firebase/Core and Firebase/Messaging
2. Added Google Service info plist in Project
3. Use $(Inherited) in other linker flags
4. When tried to access anything getting errors  like
"_OBJC_CLASS_$_FIRApp", referenced from:

Please help to integrate Firebase with existing Project

**Comment by baolocdo** [comment]
Can you please give us the log of errors? It is not very clear on number 4 what the errors are. Which Xcode version, iOS version and Pod library version you are using? Thank you.

**Comment by kalrashubham49** [comment]
I have created a samle project with above scenario , Please try
https://www.dropbox.com/s/tkg0sc7pnhzeqqb/FirebaseSample.zip?dl=0

i was getting duplicate symbols error

Pasting some errors 
_### _duplicate symbol _GSDK_kGTMABUnknownPropertyName in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)
    /Users/shubham/Desktop/FirebaseSample/Firebase/GoogleSignIn.framework/GoogleSignIn(GTMABAddressBook.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMABAddressBook in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)
    /Users/shubham/Desktop/FirebaseSample/Firebase/GoogleSignIn.framework/GoogleSignIn(GTMABAddressBook.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMABGroup in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)
    /Users/shubham/Desktop/FirebaseSample/Firebase/GoogleSignIn.framework/GoogleSignIn(GTMABAddressBook.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMABMultiValue in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)
    /Users/shubham/Desktop/FirebaseSample/Firebase/GoogleSignIn.framework/GoogleSignIn(GTMABAddressBook.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMABMultiValueEnumerator in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)
    /Users/shubham/Desktop/FirebaseSample/Firebase/GoogleSignIn.framework/GoogleSignIn(GTMABAddressBook.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMABMutableMultiValue in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)
    /Users/shubham/Desktop/FirebaseSample/Firebase/GoogleSignIn.framework/GoogleSignIn(GTMABAddressBook.o)
duplicate symbol _OBJC_CLASS_$_GSDK_GTMABPerson in:
    /Users/shubham/Desktop/FirebaseSample/Pods/GoogleUtilities/Frameworks/GoogleUtilities.framework/GoogleUtilities(GTMABAddressBook.o)__

**Comment by baolocdo** [comment]
I downloaded the project and I did see the duplicate symbols. I removed the frameworks of GoogleAnalytics and GoogleSignIn and added to the Podfile these:

> pod 'Firebase/Core'
> pod 'Firebase/Messaging’
> pod 'GoogleAnalytics'
> pod 'GoogleSignIn'

The duplicate symbol errors went away. Have you tried this path? May I ask the reason why you are not using CocoaPod for GA and GoogleSignIn?

**Comment by kalrashubham49** [comment]
Actually I am integrating firebase in a existing project , and Google
signin and analytics are integrated from a long time ago in our project ,
so thought not to change those and only integrate the messaging part of
firebase

Is it possible to build the project without removing individual SDK and
integrate only firebase cloud messaging service??

**Comment by baolocdo** [comment]
The problem is that the old version of GoogleSignIn SDK contains some symbols with GoogleUtilities framework. The newer version of GoogleSignIn 4.0 has a different structure from the older one. Can you try downloading the latest version of GoogleSignIn SDK?

**Comment by kalrashubham49** [comment]
Thanks It Worked.
