### ISSUE TITLE
Firebase Crashlystic couldn't update report

### ISSUE THREAD

**Issue by hungwei0331** [firebase/quickstart-ios#641]
I had read previous article, but couldn't solve this problem,

those steps I had done below,

1. 
installed by cocoa pods 
`pod 'Fabric', '~> 1.7.7'`
`pod 'Crashlytics', '~> 3.10.2'`

2. 
Add a new build phase, and select New Run Script Phase,
Build Setting > debug infomation format to DWARF with dlsym file,
Run script > ${PODS_ROOT}/Fabric/run
cause Xcode10, set input file to  $(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

3. 
writing fews codes in app delegate for testing
FirebaseApp.configure()
Fabric.sharedSDK().debug = true
Fabric.with([Crashlytics.self])
Crashlytics.sharedInstance().debugMode = true

4. 
call method for testing Crashlytics.sharedInstance().crash()

5. 
Xcode console log,
[Fabric] Settings are available for consumption
[Fabric] Starting onboarding with app update
[Fabric] completed application update
[Crashlytics] Version 3.12.0 (136)

but firebase crashlystic console couldn't update anything,

is there anything I missed, thanks in advance for any reply .

**Comment by morganchen12** [comment]
@hungwei0331, you should file this issue at the [official Firebase support channel](https://firebase.google.com/support/contact/?category=troubleshooting) so they can look at your Fabric/Firebase project and see if there are any errors there.
