### ISSUE TITLE
ML Kit run time error with custom TF lite model "Thread 2: EXC_BAD_ACCESS (code=1, address=0x11f7f4000)"

### ISSUE THREAD

**Issue by kautham** [firebase/quickstart-ios#643]
I re-trained a mobilnet model just like the [Tensorfow for Poets ](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0) codelabs and then created a Tessorflow lite file just as it is said in the [Tensorflow for poets 2 iOS](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-ios/#2). It works fine with the included Objective C++ iOS source code. But if i try to use it in the ML kit swift source i get a run time exception. 
![screenshot 2019-02-19 at 6 28 33 pm](https://user-images.githubusercontent.com/17590053/53016722-3ca7ee80-3474-11e9-8eb9-047047687398.png)

My Swift code is fairly simple just like mentioned in the Firebase [ML Kit Docs](https://firebase.google.com/docs/ml-kit/ios/use-custom-models) , but instead of uploading the model file to firebase console i registered the model locally and used it. My Code is as below,

```
func initWorkingMLModel(){
        /*Initializing local TFLite model*/
        guard let modelPath = Bundle.main.path(forResource: "mobilenet_v1.0_224_quant", ofType: "tflite") else {
            return
        }

        let myLocalModel = LocalModelSource.init(name: "Inception", path: modelPath)
        if ModelManager.modelManager().register(myLocalModel)
        {
            let options = ModelOptions(cloudModelName: nil, localModelName: "Inception")
            let interpreter = ModelInterpreter.modelInterpreter(options: options)

            let ioOptions = ModelInputOutputOptions()
            do {
                try ioOptions.setInputFormat(index: 0, type: .uInt8, dimensions: [1, 224 , 224, 3])
                try ioOptions.setOutputFormat(index: 0, type: .uInt8, dimensions: [1, 1001])
                print("Setting the Input and Output formats Success")
            } catch let error as NSError {
                print("Failed to set IO \(error.debugDescription)")
            }

            let inputs = ModelInputs()
            do {
                let image = UIImage.init(named: "tennis.jpg")
                guard let imageData =
                    self.scaledImageData(from: image!,
                                         componentsCount: 3) else {
                                            return
                }
                try inputs.addInput(imageData)

            } catch let error as NSError {
                print("Cannot get audio file data \(error.debugDescription)")
                return
            }

            interpreter.run(inputs: inputs, options: ioOptions) { (outputs, error) in
                if error != nil {
                    print("Error running the model \(error.debugDescription)")
                    return
                }
                do {
                    let output = try outputs!.output(index: 0) as? [[NSNumber]]
                    let probabilities = output?[0]

                    guard let labelsPath = Bundle.main.path(forResource: "labels", ofType: "txt") else { return }
                    let fileContents = try? String.init(contentsOf: URL.init(fileURLWithPath: labelsPath))
                    guard let labels = fileContents?.components(separatedBy: "\n") else {return}

                    for i in 0 ..< labels.count {
                        if let probability = probabilities?[i] {
                            print("\(labels[i]) : \(probability)")
                        }
                    }
                }catch let error as NSError {
                    print("Error in parsing the Output \(error.debugDescription)")
                    return
                }
            }
        } else {
            print("model registration failed")
        }
    }
```
I am calling this function on a button press action.  The error originates from the line `interpreter.run(inputs: inputs, options: ioOptions) { (outputs, error) in`.

I am using Xcode 10.1 Stable
Swift 4.2

Pod install versions (All updated to latest)
Firebase 5.16.0
Firebase core 5.2.0
FirebaseMLCommon 0.14.0
FirebaseMLModelInterpeter 0.14.0
TensorflowLite 1.12.0

**Comment by ulukaya** [comment]
We actually used the same model on https://github.com/firebase/quickstart-ios/tree/master/mlmodelinterpreter Do you mind trying your model with this sample? If you register locally, it should work without needing to push your model to cloud. EXC_BAD_ACCESS is usually a memory issue, you may be creating some race condition, trying to read/write an invalid address. If it doesn't resolve feel free to drop your full stack trace here so we can look at.
