### ISSUE TITLE
Client SDK source repository?

### ISSUE THREAD

**Issue by a13xb** [firebase/quickstart-ios#65]
Not only related to iOS but other platforms too, could not find any other place to ask.

I'm struggling to find the actual source repositories of client SDKs. Do they exist?

**Comment by ianbarber** [comment]
The SDKs are closed source, sorry!

**Comment by a13xb** [comment]
Yikes.

If you don't mind me asking, what could possibly be gained in using a closed client for a hosted service? How do you propose third-party client libraries reliably implement the protocol if it's closed?

**Comment by King42com** [comment]
I guessing they will have to restart there account

Sent from my MetroPCS 4G LTE Android device
On Aug 10, 2016 06:03, Alexander Bolodurin <notifications@github.com> wrote:Yikes.

If you don't mind me asking, what could possibly be gained in using a closed client for a hosted service? How do you propose third-party client libraries reliably implement the protocol if it's closed?
