### ISSUE TITLE
Have problem to run the iOS example

### ISSUE THREAD

**Issue by zhouhao27** [firebase/quickstart-ios#650]
Get the following error message:

> /Users/XXXX/Projects/mlvision/MLVisionExample/ViewController.swift:789:19: Use of unresolved identifier 'VisionOnDeviceImageLabelerOptions'

**Comment by morganchen12** [comment]
Does running `pod update` fix your issue?

**Comment by zhouhao27** [comment]
No. It didn't fix the problem.

**Comment by ulukaya** [comment]
Can you try "pod deintegrate; pod cache clean --all; pod update"?

This sounds like a old version of Firebase is loaded.
