### ISSUE TITLE
firebase crash successfully enabled, but report is not working on console

### ISSUE THREAD

**Issue by Carodora** [firebase/quickstart-ios#66]
I was set firebase to my ios project. But crash report is not upload in my firebase console.
I don't know what is not upload data. Please somebody tell me why. 

xcode shows me following logs 

**Log Messages.**

```
VLunch[715:254725] Configuring the default app.
VLunch[715:254725] Firebase Crash Reporting: Successfully enabled
...
```

and i set run script in xcode

**Run Script**

```
JSON_FILE=/projectname/VlocallyMealCoupon-faf0272917f8.json

GOOGLE_APP_ID=1:244xxxxxxxx7:ios:0754xxxxxxxxa805

defaults write com.google.SymbolUpload version -integer 1   # creates file if it does not exist
JSON=$(cat "${JSON_FILE}")
/usr/bin/plutil -replace "app_${GOOGLE_APP_ID//:/_}" -json "${JSON}" "$HOME/Library/Preferences/com.google.SymbolUpload.plist"
"${PODS_ROOT}"/FirebaseCrash/upload-sym
```

and i was set plist / json file.
Is it correct path of plist / json? (Actually, I do not know well)

[Screenshot](https://s31.postimg.org/onqgqkivv/2016_08_04_11_28_31.png)

added init and force crash code to AppDelegate

```
#import "AppDelegate.h"
@import Firebase;

@interface AppDelegate ()
@end

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [FIRApp configure];
    assert(false);
...
```

**Comment by ianbarber** [comment]
The crash is only sent on the next app start, and it can take a little while for it to appear in the console. Has it turned up since?
