### ISSUE TITLE
Hey all, if anyone is having FCM issues, please open a new issue. Don't tack +1 comments with few details on months-old issues that may or may not be related.

### ISSUE THREAD

**Issue by Bhagyasri0402** [firebase/quickstart-ios#661]
Hey all, iam is having FCM issue, Whenever i'm trying to send notification manually i get  the toast like "the Compaign was successfully saved". how to solve this issue.
Thank you in advance

**Comment by morganchen12** [comment]
This is most likely a configuration issue and would be better answered on StackOverflow.
