### ISSUE TITLE
Deep link is being distorted in iOS

### ISSUE THREAD

**Issue by subbota-a** [firebase/quickstart-ios#670]
I make the follow deep link
https://<hidden>.app.goo.gl/?link=https%3a%2f%2flocalhost%3a80%2fmobiledashboard%3flogin%3droot%26invitation%3db%25f5%25cd%2591%25242%25a7%25d8%25f0%25d2%2594c%25d2K%2515%25f1&apn=com.fingrad.dashboard&amv=26&ibi=com.fingrad.dashboard&isi=1240399529
Where <hidden> is my app.
I open this link in iOS, install the app and open it for the first time.
AppDelegate.OpenUrl is called and argument url is the following

com.fingrad.dashboard://google/link/?deep_link_id=https%3A%2F%2Flocalhost%3A80%2Fmobiledashboard%3Flogin%3Droot%26invitation%3Db%25EF%25BF%25BD%25CD%2591%242%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%25D2%2594c%25EF%25BF%25BDK%2515%25EF%25BF%25BD&match_type=unique&match_message=Link%20is%20uniquely%20matched%20for%20this%20device%2E

So, my invitation argument is corrupted!

**Comment by subbota-a** [comment]
Compare
invitation%3db%25f5%25cd%2591%25242%25a7%25d8%25f0%25d2%2594c%25d2K%2515%25f1
invitation%3Db%25EF%25BF%25BD%25CD%2591%242%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%25D2%2594c%25EF%25BF%25BDK%2515%25EF%25BF%25BD

**Comment by morganchen12** [comment]
There isn't enough information here to debug this issue.
