### ISSUE TITLE
Sample Project didn't work

### ISSUE THREAD

**Issue by foxsin10** [firebase/quickstart-ios#676]
Hi there. After download the project, I just run pod install, and after pod generated the workspace, I found the result, which shown in the pictures below.
![20190409215015](https://user-images.githubusercontent.com/11630650/55805691-81b1de00-5b11-11e9-8982-49107a2cd07a.jpg)
![20190409214955](https://user-images.githubusercontent.com/11630650/55805696-85456500-5b11-11e9-9cf6-94de805816e6.jpg)

I read the doc carefully, and I think there wasn't anything wrong. Can you tell me how to make it work?

**Comment by morganchen12** [comment]
It looks like you're using an old version of Firebase. What's the output of running `pod install`?

**Comment by foxsin10** [comment]
The output is down here.
![20190410090332](https://user-images.githubusercontent.com/11630650/55844379-89a06b00-5b6f-11e9-9e84-729d2b4b2ea8.jpg)
This is the latest version, right?

**Comment by foxsin10** [comment]
hi there, just did a little digging and reset my cocoapods, and it works
