### ISSUE TITLE
Support for apns-collapse-id

### ISSUE THREAD

**Issue by daveanderson** [firebase/quickstart-ios#68]
In the [WWDC 2016 Session 707](https://developer.apple.com/videos/play/wwdc2016/707/#_4) the http/2 header `apns-collapse-id` is introduced as a way to update (or remove) push notifications.

When will FCM support this capability? Will it leverage the `collapse_key` parameter or be exposed in an alternative manner?

**Comment by kroikie** [comment]
@daveanderson thanks for the feature request, the team is aware of this feature and will look into how it can be used with FCM.

**Comment by mcaldas** [comment]
@kroikie any update on this?

**Comment by gtsifrikas** [comment]
Any update about apns-collapse-id? Thanks

**Comment by sorenandersen** [comment]
Also looking for updates on how and when Firebase is able to support `apns-collapse-id`. Any pointers? Thanks.

**Comment by dileep-mathilakath** [comment]
Any update on apns-collapse-id feature Integration in FCM? Thanks

**Comment by dunqi** [comment]
Still waiting for apns-collapse-id 👎

**Comment by rightaboveit** [comment]
I'm looking for this as well

**Comment by jonathanfishner** [comment]
also waiting for that. `apns-collapse-id`

**Comment by kroikie** [comment]
Hi all, `apns-collapse-id` as well as all other APNs features are now supported in the new [FCM HTTP API](https://firebase.google.com/docs/cloud-messaging/concept-options#when_to_use_platform-specific_keys). See the docs for more on how you can use platform-specific options like `apns-collapse-id`

**Comment by ashishkumar070** [comment]
Hi @kroikie  I tried to use the apns-collapse-id , but it didn't collapsed my notifications.

I used  apns-collapse-id as a header in the http call.

**Comment by pimnijman** [comment]
I tried the following, but without success. Notification sent with the same apps-collapse-id are delivered as separate notifications.

```
{
	"to": "{fcmRegistrationToken}",
	"priority": "high",
	"notification": {
		"title": "Test Title",
		"body": "Test Body",
		"sound": "default"
	},
	"apns": {
       "headers": {
         "apns-collapse-id": "test"
       }
   }
}
```

What could I be missing?

**Comment by jombie** [comment]
I also tried the apns-collapse-id but it does not work, below is my part of json that I am sending to firebase api
`"apns":{
      "headers":{
        "apns-collapse-id":"message_update"
      }
    },`

Is there any change required in app or in api call?

**Comment by pimnijman** [comment]
Make sure you're using the new [v1 API](https://firebase.google.com/docs/cloud-messaging/send-message).

If you're POSting your data to https://fcm.googleapis.com/fcm/send you're still using the lagacy API.

**Comment by darko55555** [comment]
Do we have a functioning structure that contains `apns-collapse-id` that successfully collapses notifications that are being sent using firebase cloud functions ?

**Comment by Winghin2517** [comment]
This is my json message using the apns-collapse-id. It seems to work:

    values = {
  "message":{
    "topic" : "home_sub",
    "notification" : {
      "body" : "Flash sale on home item: Toaster!",
      "title" : "Sale",
      },
    "apns":{
        "headers":{
            "apns-collapse-id":"1"
        }
    }
   }
}

**Comment by jahnaviwisdom** [comment]
@Winghin2517  can you please tell me how to pass from backend ? Currently im using this:
$headers = array(
            'Authorization: key=' . $FIREBASE_API_KEY,
            'Content-Type: application/json',
                         'apns-collapse-id':'1'
        );

but  its not working . How to pass it in header from backend

**Comment by AnushkaMishra** [comment]
> @Winghin2517 can you please tell me how to pass from backend ? Currently im using this:
> $headers = array(
> 'Authorization: key=' . $FIREBASE_API_KEY,
> 'Content-Type: application/json',
> 'apns-collapse-id':'1'
> );
> 
> but its not working . How to pass it in header from backend

Did you find any solution for this? I am doing the same.

**Comment by sergeymild** [comment]
> This is my json message using the apns-collapse-id. It seems to work:
> 
> ```
>     values = {
>   "message":{
>     "topic" : "home_sub",
>     "notification" : {
>       "body" : "Flash sale on home item: Toaster!",
>       "title" : "Sale",
>       },
>     "apns":{
>         "headers":{
>             "apns-collapse-id":"1"
>         }
>     }
>    }
> }
> ```

it doesn't work
