### ISSUE TITLE
FCM iOS not working after a while

### ISSUE THREAD

**Issue by sneps85** [firebase/quickstart-ios#691]
On some iOS devices, the FCM messages aren't delivered after some amount of time (months), which worked before without having the app or server changed.

The strangest thing is, that sending a notification through APNs itself remakes the FCM notifications working properly for the FCM token coupled with the APNs token.

I have swizzling disabled an i set the APNs token properly to FIRMessaging (Objective-C). So the summary is:

Send push through FCM - success, not received
Send push through APNs - success, received
Send again push through FCM - success, received

and that without changing anything on the app. How can that be?

**Comment by morganchen12** [comment]
@sneps85, can you try disabling swizzling and manually associating the FCM and APNs tokens?

**Comment by sneps85** [comment]
I have already disabled swizzling and  I am already associating the APN token to FCM.. The app worked fine fir months, but since the end of March 2019 on more and more iOS devices this behaviour occurs...

**Comment by itumeleng-mabote** [comment]
I've got the same issue
Currently using FirebaseMessaging (= 3.1.2)

**Comment by morganchen12** [comment]
There was an issue recently where a bug in the SDK could cause instance IDs to become corrupted on the client. Can you all try updating to the latest version of Firebase Messaging and seeing if the issue still occurs?

The title of this issue is somewhat vague, so it may start drawing attention from people with similar but unrelated issues. If you have a similar issue, don't comment here. File a [support ticket](https://firebase.google.com/support) instead.

**Comment by sneps85** [comment]
When the issue began, Firebase/Messaging version 5.8.1 was used. We then updated the Pods to 5.20.1 hoping it will resolve the issues, but without any changes. It did not help, more and more devices are still suffering from the issue.

**Comment by sneps85** [comment]
> There was an issue recently where a bug in the SDK could cause instance IDs to become corrupted on the client. Can you all try updating to the latest version of Firebase Messaging and seeing if the issue still occurs?
> 
> The title of this issue is somewhat vague, so it may start drawing attention from people with similar but unrelated issues. If you have a similar issue, don't comment here. File a [support ticket](https://firebase.google.com/support) instead.

When the issue began, Firebase/Messaging version 5.8.1 was used. We then updated the Pods to 5.20.1 hoping it will resolve the issues, but without any changes. It did not help, more and more devices are still suffering from the issue.

**Comment by morganchen12** [comment]
If you add a one-time instance ID reset (by deleting the local instance ID on the client) does it help?

**Comment by sneps85** [comment]
Unfortunately not. We did use this method to delete the Instance ID:

`[FIRInstanceID instanceID] deleteIDWithHandler:^(NSError *error) {
  if error != nil {
    NSLog(@"Error deleting instance ID: %@", error);
  }
}];`

And then regained a new Instance ID. FCM messages still not received on devices affected by the issue.

As already mentioned, the only thing to make FCM work again properly was to send one notification with APN directly. By doing this, FCM and APN token remained the same, but worked after. Any clue?

**Comment by sneps85** [comment]
People are reporting from this moment on, that it is working again without any intervention. Did the FCM service change in any way?

**Comment by morganchen12** [comment]
Not in the time between your last reports. In the future, you can follow the support link I posted above and the FCM team will be able to look at the instance ID tokens in your project directly and tell you why the sends are failing.

**Comment by sneps85** [comment]
> Not in the time between your last reports. In the future, you can follow the support link I posted above and the FCM team will be able to look at the instance ID tokens in your project directly and tell you why the sends are failing.

I did contact the support too, which told me that they are resolving the issue regarding the FCM notifications and it may be possible that my case is affected and that they will recontact me once all is fixed.
