### ISSUE TITLE
Swizzling UIViewController.viewDidAppear()?

### ISSUE THREAD

**Issue by claybridges** [firebase/quickstart-ios#692]
Just to be clear, Firebase Analytics is swizzling `UIViewController.viewDidAppear()` with `fira_viewDidAppear()`, right?

**Comment by morganchen12** [comment]
Yes. In future versions of Firebase we plan on making Analytics optional, so you can completely remove this functionality if desired (instead of relying on setting flags in plist files to disable it).

**Comment by morganchen12** [comment]
Analytics is optional in Firebase 6.
