### ISSUE TITLE
FCM Token changed after fetching values from FIRRemoteConfig 

### ISSUE THREAD

**Issue by populius** [firebase/quickstart-ios#696]
1. Launch and Initialize app with 
`[FIRApp configure] and [FIRMessaging messaging].delegate = self;`
2. Receive token via 
`- (void)messaging:(FIRMessaging *)messaging didReceiveRegistrationToken:(NSString *)fcmToken`
3. Fetch values from remote config with expiration = 0
`[FIRRemoteConfig remoteConfig] fetchWithExpirationDuration:0 completionHandler:handler]`
4. Relaunch App and didReceiveRegistrationToken return new FCM token

**Comment by morganchen12** [comment]
Please file a [support ticket](https://firebase.google.com/support) for this issue, that way the support staff will be able to look at your project's instance ID tokens and find out why they're being invalidated.
