### ISSUE TITLE
facebook auth updates

### ISSUE THREAD

**Issue by squm** [firebase/quickstart-ios#698]
https://github.com/firebase/quickstart-ios/blob/841d6ac81d24380f25ba883b2346d1bb194a26be/authentication/AuthenticationExample/MainViewController.m#L195

'logInWithReadPermissions:fromViewController:handler:' is deprecated: Use -logInWithPermissions:fromViewController:handler: instead.

'linkAndRetrieveDataWithCredential:completion:' is deprecated: Please use 'linkWithCredential:completion:' instead.

'signInAndRetrieveDataWithCredential:completion:' is deprecated: Please use 'signInWithCredential:completion:' instead.

**Comment by morganchen12** [comment]
Looks like this was fixed in https://github.com/firebase/quickstart-ios/commit/1d28beae30c0ff0cc00f4da6f67f55526acbcff4.
