### ISSUE TITLE
App crash at Firebase Anaytics

### ISSUE THREAD

**Issue by travoux** [firebase/quickstart-ios#7]
<FIRAnalytics/INFO> Firebase Analytics enabled
fatal error: unexpectedly found nil while unwrapping an Optional value

<img width="755" alt="screen shot 2016-05-22 at 3 56 26 pm" src="https://cloud.githubusercontent.com/assets/1425461/15453001/fbe2122c-2035-11e6-81fc-3db89fed193f.png">

**Comment by ianbarber** [comment]
Is this in the Analytics sample app?

**Comment by paulb777** [comment]
@travoux How is classtree different from AnalyticsExample? What are the steps needed to reproduce?

**Comment by travoux** [comment]
@paulb777  It happened only one time. Could not reproduce it. Classtree did not use any of the analytics APIs from the sdk. If we have time, we will try to find out and let you know

**Comment by baolocdo** [comment]
@travoux It could crash at some points after Firebase Analytics was enabled but it does not mean that Firebase Analytics created the crash. It would be best to have some stack trace to pin point which crashed the app. Is your app using Swift? I looked up the crash but it seems to come mostly from Swift and Firebase Analytics is not Swift.
