### ISSUE TITLE
Support for "mutable-content": true

### ISSUE THREAD

**Issue by daveanderson** [firebase/quickstart-ios#70]
The documentation for `UNNotificationServiceExtension` indicates 

> • The remote notification’s `aps` dictionary includes the `mutable-content` key with the value set to `1`.

The FCM documentation at https://firebase.google.com/docs/cloud-messaging/http-server-ref#send-downstream does not make reference to the `mutable-content` key or a way to set the `mutable-content` key.

if I include `"mutable-content": true` as part of the `notification` dictionary within the payload submitted to FCM, the value is received (outside of the `aps` dictionary) on iOS as

```
    "gcm.notification.mutable-content" = true;
```

When will FCM support the mutable-content capability? How will I need to specify this within the FCM payload so that it will be received on iOS and allow the use of a `UNNotificationServiceExtension` to pre-process the received notification?

**Comment by Atheros1** [comment]
(bump)
Without this support in the HTTP API we cannot pre-process the received notification either. Setting the message in the notification body is not possible in our case.

**Comment by t0rr3sp3dr0** [comment]
Same problem here

**Comment by simsimmal** [comment]
Same here

**Comment by kjpublic01** [comment]
This is a big problem and needs to be fixed ASAP. Without it we can't make any progress on iOS 10 notification service and content extensions.

**Comment by HiroshiHorie** [comment]
I can not believe this is not fixed yet, should have been ready while iOS 10 was in beta.

**Comment by ianbarber** [comment]
Thanks - we have a FR for it internally, and are looking at the server side changes now. No specific timelines I can share, but should be in a future release.

**Comment by jdivittorio3** [comment]
@ianbarber any update on this?

**Comment by ianbarber** [comment]
No update, sorry

**Comment by baims** [comment]
we've been waiting for 3 months now, any updates at least ?

**Comment by jaumevn** [comment]
@ianbarber any news on this?

**Comment by adrian-oaida** [comment]
@ianbarber is there a timeline for this feature ?

**Comment by BasantAshraf** [comment]
Any Updates please ?

**Comment by simsimmal** [comment]
Any updates? Issue is closed now??
Firebase seems a bad choice as a push service provider if you care about ios. We really want to support rich notifications.

**Comment by ianbarber** [comment]
Hi all - no update. Issue is closed as the tracker is for bugs on the samples. Support is still being worked on but we don't have a timeline - best place to check is the Firebase Release Notes and the firebase-talk Google group: https://firebase.google.com/support/ - sorry nothing more definitive right now!

**Comment by atulvuliv** [comment]
This is so bad. We moved everything to FCM and now its lacking the basic features. Why to change the payload to  `"gcm.notification.mutable-content" = true;` ?

**Comment by ianbarber** [comment]
Appreciate your frustration - we should have been ahead of this one, sorry.

**Comment by priyeshmarvi** [comment]
@ianbarber but why did you closed this issue .. you need to set bug or enhancement tag on it

**Comment by ianbarber** [comment]
Because this issue tracker is for samples, and this is not an issue with
the samples.

**Comment by daveanderson** [comment]
Not trying to be disagreeable, but the sample _should_ show how to do this.

**Comment by ianbarber** [comment]
Yeah, I get that, but the max the sample should show how to do is things
the product does. If we supported mutable-content, and the sample didn't
show it, that would be a clear sample bug. Its worth noting there is a
specific place for filing product bugs and feature requests too (
https://firebase.google.com/support/contact/bugs-features/) so I'm not
trying to shut down otherwise useful feedback!

**Comment by hopye** [comment]
omg, still no fix ?

**Comment by ianbarber** [comment]
Just an update for anyone checking the new release for this: its being worked on, but we wont have anything until next year, sorry.

**Comment by cuonghero** [comment]
sorry sir,
currently i need to feature send notification with image, but the firebase it not support now, so can you tell me when firebase support this feature?
i need to time clear that have timeline for my project, so please answer ASAP
thank so much!

**Comment by grioja** [comment]
@ianbarber can you open up the API so we aren't relying on the SDK to whitelist adding these kinds of attributes to payloads? For future-proofing if the SDK isn't going to move as fast as client feature releases.

**Comment by tomaskraina** [comment]
@ianbarber Thanks for the heads up. Is there any way to escalate this issue? Anything I can do, e.g. file anything similar to Apple's radar?

**Comment by erudonja1** [comment]
So basically, If I understood well, we can't use rich notifications on ios 10, because FCM client can't find "mutable-content" in "aps -> notification" node of push message?

NotificationService and NotificationContent extension in that case are not triggered and rich notifications are not created by the iOS 10...

This will be possible next year?

**Comment by ianbarber** [comment]
@tomaskraina https://firebase.google.com/support/contact/bugs-features/ is the closest thing to a radar.

**Comment by hc-kim** [comment]
I hope this to be fixed ASAP as well. I write a bug report to above link also.
(Everyone who enters this thread should send one bug report for each one. So they can quickly recognize how this is huge bug.)

**Comment by chengsam** [comment]
Is it possible to include the image URL in the data message and create a local notification with image downloaded?

**Comment by grioja** [comment]
@ianbarber is there any update on rich notification support?

**Comment by N0un** [comment]
@ianbarber Hi, have you an idea about when this fix will be released ?

**Comment by aronse** [comment]
Hey guys, just migrated from Parse and found out that 'mutable-content' is not supported. Thought it'd be working out of the box considering iOS10 was released nearly 5 months ago... Anyway, any idea/update about when this will be added? @ianbarber

**Comment by N0un** [comment]
@aronse I contacted Firebase support team few hours ago and I just received that : 

> Many developers have already requested this feature for iOS. It is still being discussed by our engineering team and is being prioritized accordingly. I cannot provide any timeline and details regarding this feature, but you can keep track of our release notes.

**Comment by aronse** [comment]
@N0un Thanks! Well I can't really wait to see this implemented (or not) in the release notes... Also not exactly confident about using something that's 5 months late feature-wise (especially for something as trivial as this) so I guess I'll use something else.

**Comment by Gujci** [comment]
Will we ever have any update on this? Or should I consider using other solutions as soon as possible?

**Comment by debayanb** [comment]
Is there any update on this? We need rich notifications support from firebase.

**Comment by tomaskraina** [comment]
@debayanb You can have iOS10 rich notification working on Firebase with little bit more work. Hint: Use [`click_action`](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support).

What's missing is being able to mutate the content of the notification, like add an image, for example without implementing `Notification Content` target.

**Comment by Gujci** [comment]
@tomaskraina that's great, but as far as I know click action was here before iOS 10, what we can't do now is, as you mentioned, mutating the content, like loading and configuring the notification to present in a notification content extension with rich data (which is iOS 10 specific) since our notification service extension never gets called. Please correct me, if I'm wrong.

**Comment by tomaskraina** [comment]
@Gujci You don't need to mutate the content in order to use the `Notification Content Extension` and show custom UI. Notification Content extension can be triggered via `click-action`, which translates into `category` when sent to APNS. That's what I do in my current app.

Only `Notification Service Extension` can't be triggered at the moment as you need the `mutable-content` flag.

**Comment by Gujci** [comment]
@tomaskraina that is cool, but in my case the `Notification Content Extension` needs more data, basically the `Notification Service Extension` has to ask the server for more data. But I'll try to skip this step or just use the node apns module on the server. Thanks anyway :)

**Comment by tomaskraina** [comment]
@Gujci Sure, no prob :) You can request the additional data in the `Notification Content Extension`.

**Comment by debayanb** [comment]
@tomaskraina thanks man. I'll try it out.

**Comment by CharlesAE** [comment]
I guess im not the only one waiting on a fix

**Comment by hopye** [comment]
When are we getting a fix on this ? Please!!!

Lg

**Comment by pinireisman** [comment]
Come on Firebase... 
People are waiting for this for a long long time now.
Please deliver on your statements of being truly a cross platform solution for us mobile developers.
This is a very important feature that we REALLY need supported.

so PLEASE!!!

**Comment by johngithubby** [comment]
Really, after more than 5 months, nothing???

**Comment by tomaskraina** [comment]
Hey all,

For anyone missing this feature badly, don't hesitate to file an official feature request with critical urgency at https://firebase.google.com/support/contact/bugs-features/

I recommend using the same title as this github issue and adding a link to the description.

I believe that this could help the engineers and/or managers at Firebase prioritize this issue internally, after seeing how many people need this.

**Comment by felipesabino** [comment]
@tomaskraina Did that on Friday and sadly got a sad feedback

> Hi Felipe,
>
> Thanks for reaching out. We're definitely aware that many users, such as yourself, would like the support for the "mutable-content" key for iOS available through FCM. We're exploring potential solutions, but I can't share any details or timelines at this time. We'll keep your feedback in consideration moving forward though.
>
> Keep an eye out on our [release notes](https://firebase.google.com/support/releases) for any further updates.
>
> Cheers,
> Firebase Support

Well, if you are counting on it be aware that it looks like it is not even is not even in development yet, let alone scheduled to be released shortly.

---

[Speculation] 

Well, it is kind of understandable as adding this mutable tag to the payload is more than meets the eye. I initially thought it would be just adding a `mutable` tag to the notification payload until we started doing it on our own push sender mechanism. 

When dealing with an app extension while having data on a local database means that you need to use an [app group](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW19) to share data between the app and the extension. Also, you have to migrate the data manually from the app to the app group and, if I had to guess, I would say that they want to make this step as straightforward as possible for developers, which can lead to a lot of complications, resulting in the humungous delay on delivering it.

**Comment by kroikie** [comment]
Hi All,

We added the [`mutable_content`](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json) field to FCM API.  Notification messages sent with `mutable_content` set to true can be intercepted on iOS 10+ clients and be updated before being presented to the user.

The `mutable_content` field maps to the `mutable-content` field on APNs.

**Comment by felipesabino** [comment]
That's great news! I am not even sad anymore that the support team had no idea of what was going on

@kroikie Do you know if we can expect Firebase SDKs to behave properly even with this [app group issue](https://github.com/firebase/quickstart-ios/issues/70#issuecomment-279380765) when sharing content data between app and app extensions? If not, do you know who can provide this kind of information?

**Comment by kroikie** [comment]
Hi @felipesabino from an FCM perspective the app group should not have any impact on the receipt of messages. I would assume the same for the other SDKs but I'm less sure about it's impact on them. I will raise it with my team and we will be sure to address any issues that come up, thanks for flagging it.

**Comment by johngithubby** [comment]
@kroikie thanks. Did you guys add this to the Notifications UI console? That's where I need it first.

**Comment by Atheros1** [comment]
According to the [release notes](https://firebase.google.com/support/release-notes/ios) they appear to have added this feature. 

> Added the mutable_content field to FCM API. When set to true, a notification message can be updated on an iOS 10+ client before it is presented to the user using the Notification Service app extension. The mutable_contentfield in the FCM API corresponds to the mutable-content APNs field.

**Comment by hopye** [comment]
This is just embarrassing! . Such a quick and easy implementation. And yet we are waiting for 6 months. 

Lg

**Comment by bhavukjain1** [comment]
Works perfectly for the rich notifications.

**Comment by ianbarber** [comment]
Locking this thread as it is now available in the API. Feel free to raise other feature requests with support - or open issues for other concerns!
