### ISSUE TITLE
where is apm_UTF32Length?

### ISSUE THREAD

**Issue by rigroch** [firebase/quickstart-ios#701]
I've got an error with crash.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString apm_UTF32Length]: unrecognized selector sent to instance 0x103598930'
```

I have experience for similar situations that "gtm_httpArgumentsString..."... already fixed it with -force_load.

I didn't using Cocoapods, becuase my environment without Internet Connection.
So I did download frameworks "Firebase-6.0.0.zip" from https://firebase.google.com/docs/ios/setup?hl=ko#frameworks

How can I fix it?

**Comment by morganchen12** [comment]
Have you added the `-ObjC` linker flag to `Other Linker Flags` in Xcode?
