### ISSUE TITLE
Can’t add Firebase as a dependency to private pod

### ISSUE THREAD

**Issue by Picioasa** [firebase/quickstart-ios#702]
I’m trying to make a private pod dependent on Firebase, but when I do ‘pod repo lib lib.podspec —sources=source_path’ I’m getting the error: “Unable to find a specification for ‘Firebase/Core’ dependent upon by myLib”

I followed all the steps on creating a private pod. Am I missing anything?
Is it because it’s a static library?
Are there any workarounds?

Any answers are appreciated!
Thanks!

**Comment by morganchen12** [comment]
The error doesn't seem to be related to the action you're taking here. Can you share a sample project with podspec that reproduces this issue?
