### ISSUE TITLE
Is there a way we can also write the raw .crash report in app directory when crash happens.

### ISSUE THREAD

**Issue by shyamjimishra1993** [firebase/quickstart-ios#703]
We have a requirement, where we want to create a crash log report in App Support Bundle as well along with uploading it to Firebase Crashlytics portal. So that when the customer reports a bug and shares the logs with us, We will have Crash logs report there as well.

Using PLCrashReporter, This is how we can achieve it.

```
PLCrashReporter * crashReporter = [[PLCrashReporter alloc] initWithConfiguration:[PLCrashReporterConfig defaultConfiguration]];
NSData * crashData = [crashReporter loadPendingCrashReportDataAndReturnError:&error];
PLCrashReport *plCrashReport = [[PLCrashReport alloc] initWithData:crashData error:&error];
NSString *report = [PLCrashReportTextFormatter stringValueForCrashReport:plCrashReport
withTextFormat:PLCrashReportTextFormatiOS];
BOOL flag = [report writeToFile:@"appDirectoryPathGoesHere.crash"
atomically:YES
encoding:NSUTF8StringEncoding
error:&err];
```

This will create a .crash file in App support bundle at a specified path location.

Is there a way to achieve something similar using Firebase Crashlytics SDK.

Problem Statement:-
Along with uploading crashes to Firebase Crashlytics portal, We also want to have few(ex. 10 last crashes) to be stored into app support bundle. So that we could get them when the user reports an issue and shares the logs.

Any lead on this would be really appreciated. Looking forward to hearing back!!

The assumption here is that we can't have multiple crash reporting tool at the same time, So If we are using Firebase Crashlytics SDK, we can't have PLCRashReporter to send us the raw Crash Report Data and store it to the app directory. So if we are going with Firebase Crashlytics, We will lose the functionality of getting few last crashes from App directory when the customer shares the logs.

Thanks and regards
Shyam Ji Mishra

**Comment by shyamjimishra1993** [comment]
**The issue got created prematurely by mistake. Adding missing description below. Any lead would be appreciated.**


We have a requirement, where we want to create a crash log report in App Support Bundle as well along with uploading it to Firebase Crashlytics portal. So that when the customer reports a bug and shares the logs with us, We will have Crash logs report there as well.

Using PLCrashReporter, This is how we can achieve it.

PLCrashReporter * crashReporter = [[PLCrashReporter alloc] initWithConfiguration:[PLCrashReporterConfig defaultConfiguration]];
NSData * crashData = [crashReporter loadPendingCrashReportDataAndReturnError:&error];
PLCrashReport *plCrashReport = [[PLCrashReport alloc] initWithData:crashData error:&error];
NSString *report = [PLCrashReportTextFormatter stringValueForCrashReport:plCrashReport
withTextFormat:PLCrashReportTextFormatiOS];
BOOL flag = [report writeToFile:@"appDirectoryPathGoesHere.crash"
atomically:YES
encoding:NSUTF8StringEncoding
error:&err];

This will create a .crash file in App support bundle at a specified path location.

Is there a way to achieve something similar using Firebase Crashlytics SDK.

**Problem Statement:-
Along with uploading crashes to Firebase Crashlytics portal, We also want to have few(ex. 10 last crashes) to be stored into app support bundle. So that we could get them when the user reports an issue and shares the logs.**

Any lead on this would be really appreciated. Looking forward to hearing back!!

**The assumption here is that we can't have multiple crash reporting tool at the same time, So If we are using Firebase Crashlytics SDK, we can't have PLCRashReporter to send us the raw Crash Report Data and store it to the app directory. So if we are going with Firebase Crashlytics, We will lose the functionality of getting few last crashes from App directory when the customer shares the logs.** 

Thanks and regards
Shyam Ji Mishra

**Comment by morganchen12** [comment]
You can use [this protocol method](https://firebase.google.com/docs/reference/ios/crashlytics/api/reference/Protocols/CrashlyticsDelegate#/c:objc(pl)CrashlyticsDelegate(im)crashlyticsDidDetectReportForLastExecution:) to write some crash data wherever when Crashlytics detects a crash. However, the `CLSReport` class unfortunately won't allow you to access any stack trace data.
