### ISSUE TITLE
for cordova or js

### ISSUE THREAD

**Issue by moblizeit** [firebase/quickstart-ios#705]
why they are only for native ios or android?  is there a js sdk available ? I am specifically looking for firebase object detection and tracking to capture most prominent object using phone camera without manually tapping a button

**Comment by morganchen12** [comment]
The JS quickstart can be found here: https://github.com/firebase/quickstart-js

**Comment by viksakshum** [comment]
This is just firebase quick start.  Nothing to do with object detection api sdk

**Comment by morganchen12** [comment]
ML Kit doesn't have a web component. You'll have to write native code and bridging calls to your hybrid app's JS layer.
