### ISSUE TITLE
Can't set user ID

### ISSUE THREAD

**Issue by da-manifest** [firebase/quickstart-ios#707]
I am trying to set a user ID for Firebase Crashlytics reports.

Currently I send a user ID only if it's not sent or is changed (very rare event). And there is no user ID in crash reports.

My code:

```
 + (void)setCrashlyticsUserData:(User *)user
{
    if (user == nil) { return; }
    NSString *userIdKey = @"CRASHLYTICS_SENT_USER_ID";
    NSUserDefaults *userDefaults = NSUserDefaults.standardUserDefaults;
    NSInteger sentUserId = [userDefaults integerForKey:userIdKey];
    if (sentUserId == user.userId) { return; }

    [CrashlyticsKit setUserIdentifier:[NSString stringWithFormat:@"%i", user.userId]];
    [userDefaults setInteger:user.userId forKey:userIdKey];
}
```
If this line is commented `if (sentUserId == user.userId) { return; }` I receive a user ID in crash reports.

Should I call `[CrashlyticsKit setUserIdentifier:]` every app launch? I can't find any information about it in the documentation.

**Comment by morganchen12** [comment]
Yes, this method should be called on app launch. It's not automatically persisted by Crashlytics.
