### ISSUE TITLE
iOS Notification not working when app is killed

### ISSUE THREAD

**Issue by mrithula-ancy** [firebase/quickstart-ios#71]
Hi,
I still don't get the notifications where the app is killed. I had set the field "priority": "high" in my payload, but no luck. I get the notifications when the app is in foreground and background.
Does anyone has the same issue? Someone please help me out with this, I have been on this for quite sometime.

Thanks,
Mrithula

**Comment by kroikie** [comment]
Hi @mrithula-ancy this is working as intended, when the user takes action to close an app by for example swiping it away from the multitasking view then messages are not delivered to that application till the app is restarted by the user.

From the [Apple developer docs](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveRemoteNotification:fetchCompletionHandler:):

> However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.

**Comment by mrithula-ancy** [comment]
Hi,
Yes the above said is true, but I should be getting the notifications in my notification tray right? Iam not getting the notifications in tray. So the app is killed and when the notification is clicked by the user in the notification tray the app will be re-launched.

**Comment by ravi-culturealley** [comment]
Hi @mrithula-ancy 

I just solved this issue. Just check, have you uploaded the **.p12** file on **Firebase console** ?
The link is below: [(https://firebase.google.com/docs/cloud-messaging/ios/first-message#upload_your_apns_certificate)]
