### ISSUE TITLE
Authentication- Microsoft authentication sign out is not clearing user credentials

### ISSUE THREAD

**Issue by yugandh** [firebase/quickstart-ios#710]
[READ] Step 1: Are you in the right place?
For issues or feature requests related to the code in this repository
file a Github issue.
If this is a feature request make sure the issue title starts with "FR:".
For general technical questions, post a question on StackOverflow
with the firebase tag.
For general Firebase discussion, use the firebase-talk
google group.
For help troubleshooting your application that does not fall under one
of the above categories, reach out to the personalized
Firebase support channel.
[REQUIRED] Step 2: Describe your environment
Xcode version: Version 10.2 (10E125)
Firebase SDK version: 6.1.0 (latest version)
Firebase Component: Auth
Component version: GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 FIRAuth_VERSION=6.0.0 FIRAuth_MINOR_VERSION=6.0
[REQUIRED] Step 3: Describe the problem
Microsoft authentication sign out feature is not working.

Steps to reproduce:
install latest firebase-ios-sdk(this github repo)
add your googleinfo.plist file(you can get it from your firebase project console)
run pod install for this project path
click on signIn button and you will see a list of providers and select Microsoft authentication
WebView will open and give your Microsoft email and password and after successful authentication, user will go to a new screen where sign out button and token refresh button will be there.
Click on sign out button and user will go to sign in page.
Actual:
click on sign in button and select Microsoft provider and WebView will open and without adding your email and password it is automatically taking you to the sign out page.

Expected:
After sign out button clicked, user need to start enter his credentials for sign in again.

To reproduce issue you need to sign in and sign out and again sign in and it will not ask to add username and password.

Another issue: sign in with microsoft authentication and you will on new signout screen and delete the app and install you will be on sign out page instead of sign in page.
I am facing same for google sign also.

Relevant Code:
@IBAction func didTapSignOut(_ sender: AnyObject) {
// [START signout]
let firebaseAuth = Auth.auth()
do {
try firebaseAuth.signOut()
} catch let signOutError as NSError {
print ("Error signing out: %@", signOutError)
}
// [END signout]
}

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/14207417/58283553-6ca9ab00-7d5d-11e9-8456-e6bd5ff03bd4.gif)

**Comment by morganchen12** [comment]
@yugandh This sounds like a bug. Can you file this at [the main SDK repo](https://github.com/firebase/firebase-ios-sdk/issues)? GitHub's transfer issue feature isn't working right now.
