### ISSUE TITLE
GTMSessionFetcher

### ISSUE THREAD

**Issue by fantasma10** [firebase/quickstart-ios#712]
To the mlvision example, the TMSessionFetcher library is not synchronizing correctly because when compiling the project it is not found

Decription then error:
GTMSessionFetcher.framework: errSecInternalComponent

Configuration then pod:
platform :ios, '9.0'
use_frameworks!

# [START base_dependencies]
pod 'Firebase/Analytics'
pod 'Firebase/MLVision'
# [END base_dependencies]
pod 'Firebase/MLVisionAutoML'
pod 'Firebase/MLVisionObjectDetection'
pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLVisionTextModel'

target 'MLVisionExample' do
end

target 'MLVisionExampleObjc' do
end
<img width="848" alt="Captura de pantalla 2019-05-24 a la(s) 18 15 09" src="https://user-images.githubusercontent.com/8526963/58360722-e7eb8980-7e4f-11e9-984e-de04692d384e.png">

**Comment by morganchen12** [comment]
Looks like a code signing issue. I'm not able to reproduce this. Have you tried deleting derived data and cleaning the project and rebuilding?

**Comment by morganchen12** [comment]
For others running into this issue, try https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen
