### ISSUE TITLE
Could not build module 'Firebase'

### ISSUE THREAD

**Issue by anonym24** [firebase/quickstart-ios#727]
![Screenshot at Jun 09 17-36-30](https://user-images.githubusercontent.com/8851301/59160325-4ca81480-8add-11e9-87cb-df1f1e7c5d15.png)

![image](https://user-images.githubusercontent.com/8851301/59160339-6a757980-8add-11e9-91e1-48e4e715da69.png)

I tried with original podfile:

```
# Firebase Cloud Messaging (FCM)

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

target 'MessagingExample' do
end
target 'MessagingExampleSwift' do
end
target 'MessagingExampleTests' do
end
```

and with edited:

```
# Firebase Cloud Messaging (FCM)

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

target 'MessagingExample' do
    pod 'Firebase/Core'
end
target 'MessagingExampleSwift' do
    pod 'Firebase/Core'
end
target 'MessagingExampleTests' do
    inherit! :search_paths
    pod 'Firebase/Core'
end

target 'MessagingExampleSwiftUITests' do
    inherit! :search_paths
    pod 'Firebase/Core'
end

target 'MessagingExampleUITests' do
    inherit! :search_paths
    pod 'Firebase/Core'
end
```

**Comment by morganchen12** [comment]
Looks like you were able to solve this issue in #728.

**Comment by anonym24** [comment]
@morganchen12 I just copied example to a working project with firebase

**Comment by morganchen12** [comment]
What version of CocoaPods are you using? The sample builds and runs without issues on Travis. You can see the build log here: https://travis-ci.org/firebase/quickstart-ios/jobs/542903202

**Comment by anonym24** [comment]
@morganchen12 the latest

**Comment by morganchen12** [comment]
Can you share your project that fails to build?

**Comment by anonym24** [comment]
@morganchen12 I just git clone `https://github.com/firebase/quickstart-ios`

then `cd quickstart-ios/messaging` and `pod install --repo-update`

I change `Bundle Identifier` and when I try to build Swift version (`MessagingExampleSwift`) it gives that error. 

So the project is the same

**Comment by morganchen12** [comment]
I'm unable to reproduce the build error on my machine. What version of Xcode are you using?

**Comment by anonym24** [comment]
Xcode 10.2.1
