### ISSUE TITLE
Messaging - There is no notification. I can see the message only in logs but not on screen

### ISSUE THREAD

**Issue by anonym24** [firebase/quickstart-ios#728]
I receive messages but they are only printed:

https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExampleSwift/AppDelegate.swift#L90

How to show Notification on the screen and sound?

**Comment by morganchen12** [comment]
https://stackoverflow.com/questions/30852870/displaying-a-stock-ios-notification-banner-when-your-app-is-open-and-in-the-fore

**Comment by anonym24** [comment]
@morganchen12 so this example doesn't have it?

**Comment by anonym24** [comment]
@morganchen12 I'm not asking about foreground. App was minimized and I still didn't see any notification

**Comment by morganchen12** [comment]
This sample just demonstrates how to receive a notification from Firebase. It's up to you to decide and implement the displaying of the notification. In some cases, like when receiving silent notifications, you  may not want to display a notification at all.

**Comment by anonym24** [comment]
@morganchen12 
So in this sample I just receive strings (when I send them from my Java Firebase Admin Backend).

And I'm trying to find out how to show notification on iPhone screen with title and subtitle. I don't know why but it's quite hard.

In Android I could easy make a notification, add icon, title, subtitles. But here it's difficult to figure out

**Comment by anonym24** [comment]
@morganchen12 from backend I send my message like this:

        Message message = Message.builder()
                .putData("title", "test title")
                .putData("subtitle", "test message")
                .setTopic("bahBlah")
                .build();
        String response = FirebaseMessaging.getInstance().send(message);

I found the following article and it talks about specific structure like

```
{
  "aps": {
    "alert": "Breaking News!",
    "sound": "default",
    "link_url": "....."
  }
}
```

https://www.raywenderlich.com/8164-push-notifications-tutorial-getting-started

What is that? I don't get...

In Android I manually set title and subtitle

```
val builder = NotificationCompat.Builder(this, channelId)
                    .setSmallIcon(R.drawable.ic_notify_icon)
                    .setContentTitle(App.appContext.getString(R.string.new_video_msg, title))
                    .setContentText(subtitle)
...
with(NotificationManagerCompat.from(this)) {
    notify(0, builder.build())
}
```

In iOS do I have to send a specific structure (json) to display notification or what? Do iOS parse such message and automatically create notification? Is there any notification builder like in Android?

**Comment by anonym24** [comment]
@morganchen12 so I have finally get notificaiton by sending a message from Firebase Console: https://stackoverflow.com/questions/56531630/how-to-send-notification-with-fcm-only-for-users-who-are-subscribed-to-a-topic

But now I have to find out how to send it programmatically form my server. What to change here:

    `Message message = Message.builder()
            .putData("title", "test title")
            .putData("subtitle", "test message")
            .setTopic("bahBlah")
            .build();
    String response = FirebaseMessaging.getInstance().send(message);`

**Comment by morganchen12** [comment]
You'll need to set the Apple-specific parameters using [this class](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/messaging/ApnsConfig.html).

**Comment by anonym24** [comment]
@morganchen12 yes I finally found out how to do it:

   private void sendMessage(String title, String subtitle) throws Exception {
        Message message = Message.builder()
                .setNotification(new Notification(title, subtitle))
                .setApnsConfig(ApnsConfig.builder().setAps(Aps.builder().setSound("default").build()).build())
                .setTopic("topicTitle")
                .build();
        String response = FirebaseMessaging.getInstance().send(message);
    }

The only bad thing that I have to send two topics: some users prefer notification with sound and some without sound (silent). So one notification topic in my server will be with sound `setSound("default")` and another one without it.

In Android I need only one topic and to find out if I should make sound on user's device I can use Preferences to enable/disable it notification builder when message arrives:

val channelId = if (Prefs.isNotificationSound) "kpoptube2019" else "kpoptube2019mute"

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                val channelName = ...
                val descriptionText = ...
                val importance = if (Prefs.isNotificationSound) NotificationManager.IMPORTANCE_DEFAULT else NotificationManager.IMPORTANCE_LOW
                ...
                // Register the channel with the system
                ...
            }

            val builder = NotificationCompat.Builder(this, channelId)
                    ....
                    .setContentTitle(App.appContext.getString(R.string.notify_title_locale_format, title))
                    .setContentText(subtitle)
                    ....
                    .setPriority(if (Prefs.isNotificationSound) NotificationCompat.PRIORITY_DEFAULT else NotificationCompat.PRIORITY_LOW)
                    .setDefaults(if (Prefs.isNotificationSound) NotificationCompat.DEFAULT_SOUND else NotificationCompat.DEFAULT_LIGHTS)
                    ....

But iOS doesn't have a notification builder, we can only configure notification on server side and we don't know what users prefer

**Comment by morganchen12** [comment]
Send a notification with sound on iOS and if users would like to silence your notifications they can do so by revoking sound permissions in your app's notification settings via the Settings app.

**Comment by anonym24** [comment]
Yeah but it's quite a long path, not all users go there.
