### ISSUE TITLE
Unable to get notification after Subscribe and unsubscribe for multiple times 

### ISSUE THREAD

**Issue by CearsKhush** [firebase/quickstart-ios#730]
I am working on app which has two user for example 1 is private user and 2 is public user now I had provided facilities to switch user using button click. I have used USER id as topic to get notification for that particular user. on Click of switch button I am Unsubscribing old topic and subscribing new topic using user ID but if doesn't work for me.
I have used following code on switch button 

        if Messaging.messaging().fcmToken != nil {
            
            var subscribeKey:String = ""
            if APP_DELEGATE.get_User_isSwitch() == false {
                subscribeKey = “App \(APP_DELEGATE.get_UserInfo(.ID))"
            } else {
                subscribeKey = UserDefaultManager.getStringFromUserDefaults(key: kAppUser_TeamMember_UserID)
                subscribeKey = "App \(subscribeKey)"
            }
            
            print("subToken:~\(get_DeviceToken())")
            
            let oldSubScribeKey = UserDefaultManager.getStringFromUserDefaults(key: kSubscibedKey)
            print("oldSubScribeKey: \(oldSubScribeKey)")
            print("subscribeKey: \(subscribeKey)")

            if subscribeKey != oldSubScribeKey && oldSubScribeKey != ""{
                Messaging.messaging().unsubscribe(fromTopic: oldSubScribeKey) { error in
                    print("UNSubscribed----> \(oldSubScribeKey) topic")
                    runAfterTime(time: 0.5, block: {
                        Messaging.messaging().subscribe(toTopic: subscribeKey) { error in
                            UserDefaultManager.setStringToUserDefaults(value: subscribeKey, key: kSubscibedKey)
                            print("Subscribed-----> \(subscribeKey) topic")
                        }
                        
                    })
                }
            } else {
                Messaging.messaging().subscribe(toTopic: subscribeKey) { error in
                    UserDefaultManager.setStringToUserDefaults(value: subscribeKey, key: kSubscibedKey)
                    print("Subscribed-----> \(subscribeKey) topic")
                }
            }
        }

**NOTE: Without switching I am getting notifications.**

Please Help

**Comment by morganchen12** [comment]
What version of Firebase and FirebaseMessaging are you using? Are you sending to the right topics?
