### ISSUE TITLE
Questions: iOS background notification messages

### ISSUE THREAD

**Issue by cinatic** [firebase/quickstart-ios#74]
Hello,

after a small odysee reading and testing notifications in iOS and Android. I would like to ask you directly:

In ***Android*** a data-message (w/o notification data) will shown and processed always via / through the app. So i have the chance to make changes inside the app e.g. to localize the notification content.

In ***iOS*** a data-message (w/ content_available flag) will shown only in foreground and background. But not in killed state?

Is this sum up correct? So basically i have absolutely no chance to send notification localized except like register to language code channels?

BTW. i really like the whole firebase components, great work!

**Comment by ianbarber** [comment]
I think that summary is correct, notification type messages will be sent by APNs. In the future we should add support for mutable_content which will give you some options. Alternatively, consider using topics for the different languages so send localised notifications to different groups directly.
