### ISSUE TITLE
Quickstarts should use `Firebase` module for imports

### ISSUE THREAD

**Issue by ryanwilson** [firebase/quickstart-ios#743]
https://github.com/firebase/quickstart-ios/blob/ff664aa42f2bce91fe7d1605780d8f44ae2ad16d/mlmodelinterpreter/MLModelInterpreterExample/AppDelegate.swift#L18

Here and in multiple other locations, we're referencing the specific module import instead of the umbrella Firebase import. We should update them to simply use `import Firebase`.

**Comment by ulukaya** [comment]
I actually used there as a lazy workaround for a script to catch these import. I’ll update them shortly and use a different method to catch them.

**Comment by ulukaya** [comment]
https://github.com/firebase/quickstart-ios/commit/d857613ef4bd84d309d2d26bf69a4a1507478216
