### ISSUE TITLE
Import error in Objective C

### ISSUE THREAD

**Issue by jobinsjohn** [firebase/quickstart-ios#745]
When I am importing firebase into my objective C project, I am getting the following error

<img width="818" alt="Screen Shot 2019-07-08 at 8 12 33 AM" src="https://user-images.githubusercontent.com/3398498/60782590-582c4100-a158-11e9-985c-ffd66504b308.png">

This error is also there in the example that is given in this repo.

**Comment by morganchen12** [comment]
What versions of Xcode/CocoaPods are you using?

**Comment by paulb777** [comment]
Does the error persist after doing a build in Xcode?

**Comment by jobinsjohn** [comment]
@morganchen12 XCode 10.1. I am not using cocoapods.

@paulb777 Yes. I tried cleaning the project, quit and open XCode etc etc

**Comment by morganchen12** [comment]
Can you share your project?

**Comment by jobinsjohn** [comment]
@morganchen12 Unfortunately I cant do that since the company doesnt permit that

**Comment by Spiderixius** [comment]
@jobinsjohn 

Try the suggestions from https://github.com/firebase/quickstart-ios/issues/672

> try "pod cache clean --all"

> Also try "pod deintegrate" "pod update", delete derived folder and doing a "clean build folder" on Xcode. Sometime Xcode can get stuck and create this kind of errors.

I remember having a similar issue and that fixed it for me.

**Comment by jobinsjohn** [comment]
@Spiderixius I am not using Cocoapds

**Comment by morganchen12** [comment]
We can't really help you without a reproducible example. You can try replacing your Firebase umbrella import with individual component imports (i.e. `import FirebaseCore`).
