### ISSUE TITLE
mention dynamicLinkDomain property

### ISSUE THREAD

**Issue by arielelkin** [firebase/quickstart-ios#751]
This will affect users who have added more than one URL prefix in their Firebase console. 

Calling `sendSignInLinkToEmail:actionCodeSettings:completion` will result in an email being sent with a passwordless authentication URL. 

If you don't specify the `dynamicLinkDomain` property of the `ActionCodeSettings` object passed to `sendSignInLink`, the URL you receive in the email may not point to the right domain, and so iOS will not detect it as a universal link. 

In this part of the docs:

https://github.com/firebase/quickstart-ios/blob/3a8875720b55785d662bbd37b45ea4ce919cc9c4/authentication/AuthenticationExampleSwift/PasswordlessViewController.swift#L65-L71

**Comment by morganchen12** [comment]
That's mentioned in these docs [here](https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions).

**Comment by arielelkin** [comment]
@morganchen12 I think you're missing the point. 

The issue isn't that an explanation of the `dynamicLinkDomain` property is missing from the docs as a whole, the issue is that it's missing from the docs' discussion of `sendSignInLinkToEmail:actionCodeSettings:completion` (i.e. [here](https://firebase.google.com/docs/auth/ios/email-link-auth))  where it'd be relevant. 

So please consider reopening this issue.

**Comment by morganchen12** [comment]
It's in the document you linked, right above the first code sample.
