### ISSUE TITLE
Inference on input data when using custom tensorFlow Lite model on iOS

### ISSUE THREAD

**Issue by SophieMBerger** [firebase/quickstart-ios#755]
I implemented the example code in the documentation, to set-up my input images for my model: 
<img width="503" alt="Screenshot 2019-07-17 at 11 45 44" src="https://user-images.githubusercontent.com/28648975/61365695-6da41800-a888-11e9-9652-ffcf8ba9facd.png">

However, the line
<img width="573" alt="Screenshot 2019-07-17 at 11 46 36" src="https://user-images.githubusercontent.com/28648975/61365759-8b717d00-a888-11e9-8d4f-b4faab8e2eb6.png">
often, but not always, throws the below error:
<img width="362" alt="Screenshot 2019-07-17 at 11 44 50" src="https://user-images.githubusercontent.com/28648975/61365648-52390d00-a888-11e9-919d-26169b5b6886.png">

**Comment by ulukaya** [comment]
Hi,
It seems like you are having an issue while accessing byte pointers of your image. You may be trying to access an invalid address or the image/bytes may have changed/removed by the time you access them.
You can try using the helper methods in https://github.com/firebase/quickstart-ios/blob/master/mlmodelinterpreter/MLModelInterpreterExample/MLKitExtensions.swift
