### ISSUE TITLE
iOS Notification not appearing in the notification tray when app is killed 

### ISSUE THREAD

**Issue by mrithula-ancy** [firebase/quickstart-ios#76]
Hi,
I don't receive notifications in my notification tray when the app is killed from the background. Can someone let me know how can I fix this issue?

Thanks,
Mrithula

**Comment by sadh** [comment]
I am also having similar problem. When i send notification from console its shows in device logs in emulator.  But when i am running in testflight it is showing nothing.

**Comment by bardonadam** [comment]
I had same issue, setting notification priority to high worked for me

**Comment by protikhonov** [comment]
Hi! I have this issue too. Could you help me, please!

**Comment by sadh** [comment]
Make sure you have enabled "push notification" in xcode capabilities and "remote notification" is added in background mode which is also is xcode capabilities.

**Comment by protikhonov** [comment]
@sadh Of course this is implemented. App receives push notifications when it is in background mode. But if I kill the app, it doesn't receive notifications. Also the error appears with title "Failed to fetch APNs token". All certificates loaded to Firebase console.

**Comment by ivanpetrov16130** [comment]
Same problem (iOS 8, 9, 10). 
"Foreground" & "background" modes work as expected, but iOS doesn't even show notifications for "killed"(Home+Swipe Up) app. Another strange behaviour: if you send notifications while app is killed and then run it, sent notifications are delivered sometimes(very rarely, 1/80 chance). 
Tried both own server and Firebase console. 
Setting "priority" property to "high" resolves the problem, but it's unwelcome solution.

**Comment by ianbarber** [comment]
This sounds like its just the behavior of APNs/iOS when apps are receiving lower priority messages in a killed state. Definitely feel free to raise a feature request if there is an alternative approach you'd like FCM to take, but otherwise I'm not sure this is directly addressable: https://firebase.google.com/support/contact/bugs-features/
