### ISSUE TITLE
Binary Rejected by App Store due to Crash on Open after Firebase Addition

### ISSUE THREAD

**Issue by glenn-jocher** [firebase/quickstart-ios#762]
We have an iOS app [iDetection](https://apps.apple.com/us/app/idetection/id1452689527) which we recently attempted to add Firebase to. Everything works well locally (iPhone Xs with iOS 12) and with Test Flight after the addition (i.e. we can see our iPhone appear in Firebase Analytics), but on submission to the app store Apple rejects the binary due to the app crashing on launch:
<img width="880" alt="Screenshot 2019-07-26 at 14 20 26" src="https://user-images.githubusercontent.com/26833433/61951186-89a66880-afb0-11e9-8128-b55452bfa0b8.png">

The only change we have made since the last build (which was accepted without issue at the app store) was the addition of Firebase. Our podfile is here, and we've attached the crash logs below.
```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iD https://firebase.google.com/docs/ios/setup
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleSignIn'

end
```

[attachment-8789548599042445084crashlog-24A0A95E-62AE-4FCF-B6E2-121749F70382.txt](https://github.com/firebase/quickstart-ios/files/3435700/attachment-8789548599042445084crashlog-24A0A95E-62AE-4FCF-B6E2-121749F70382.txt)
[attachment-7838067473562352558crashlog-AE04810D-ADCE-4269-9F36-9DD04AA8052A.txt](https://github.com/firebase/quickstart-ios/files/3435701/attachment-7838067473562352558crashlog-AE04810D-ADCE-4269-9F36-9DD04AA8052A.txt)

**Comment by morganchen12** [comment]
Please share your Firebase version and symbolicate your crash logs.

**Comment by glenn-jocher** [comment]
The issue appears due to another change, unrelated to Firebase. Our apologies.
