### ISSUE TITLE
Location Permissions required for using Firebase Analytics?

### ISSUE THREAD

**Issue by glenn-jocher** [firebase/quickstart-ios#763]
We recently added firebase analytics to our iOS app [iDetection](https://apps.apple.com/us/app/idetection/id1452689527), and were surprised to see that our test device is locatable on a world map despite the app not receiving location sharing permissions. There is no privacy location setting even present in info.plist for the app. How is this possible? 

Could this be related to our app crashing on App Store review, but working fine locally? We've raised a separate issue https://github.com/firebase/quickstart-ios/issues/762 on this topic. Thank you!

<img width="1577" alt="Screenshot 2019-07-24 at 17 31 26" src="https://user-images.githubusercontent.com/26833433/61951509-7778fa00-afb1-11e9-9fb2-1807d86fcbae.png">

**Comment by morganchen12** [comment]
iirc the streamview geolocates via your device's IP. It's not related to your app crashing.

**Comment by glenn-jocher** [comment]
So to clarify, there are no privacy settings required to use Firebase Analytics for iOS?

**Comment by morganchen12** [comment]
That's correct. Analytics will pull in extra information from the user's advertising identifier if the AdSupport framework is linked, but that doesn't require extra permissions.
