### ISSUE TITLE
[ML Text Recognition] Swift-version works much slower compared Objective C

### ISSUE THREAD

**Issue by and20** [firebase/quickstart-ios#768]
Hello! 
MLVisionExample Swift on-device text recognition works much slower MLVisionExampleObjc Objective C. 

MLVisionExample Swift: https://www.dropbox.com/s/smxd1mf4oojarxy/swift.mp4?dl=0
MLVisionExampleObjc Objective C: https://www.dropbox.com/s/0wrjk306h0wo7uj/objectivec.mp4?dl=0

iPhone XS Max.

Why?

**Comment by ulukaya** [comment]
One video is the live cam, the other video is photo detection.
