### ISSUE TITLE
FCM "NotRegistered" unless Bundle version changed

### ISSUE THREAD

**Issue by kachi1227** [firebase/quickstart-ios#77]
I want to note that this issue was not happening until I switched to Xcode 8-beta.

When I uninstall and re-install an app, and try to send a push notification to the ID returned by  FIRInstanceID.instanceID().token(), I always get a response saying the request failed with a NotRegistered error

When I change the bundle version (from whatever it initially was when the app was first installed on the phone), upload the app to the phone, and try to send another push notification, it sends with no problem. 

Keep in mind I've literally tried dozens of other solutions (code signing + provisioning profile permutations, etc) before stumbling upon the Bundle version hack.

Please advise on what might be causing this.

**Comment by bingjiang** [comment]
Just updated to Xcode 8 and have the same problem. Bundle version hack do not work for me. My Fcm server is returning the same error. 

I am using iOS 9

**Comment by bingjiang** [comment]
Found the solution to the problem. Nothing to do with FCM, turns out the upgrade to Xcode 8's process made the certificate invalid. Just recreate and reupload the .p12 certificate solved my problem

**Comment by KanybekMomukeyev** [comment]
@bingjiang, Good, you are absolutely correct!

**Comment by kachi1227** [comment]
Turns out for me that this was due to XCode 8 no longer using the Entitlements from the Provision profile. You now have to set it manually to receive push notifications. You can do this by going to App > Capabilities and turning "Push Notifications" on. 

If "Push Notifications" is already on, then just make sure there is a checkmark next to "Add the Push Notifications entitlement to your entitlements file" is checked.

**Comment by PurnimaNaik** [comment]
I was facing the same issue. Here is how I fixed it (iOS specific, android was working out of the box)-

 1. Uninstall the app from your phone
 2. Clear ALL the tokens stored in your database for this particular account(or however you have set it up in your backend. In my case, tokens are tied to the account)
 3. In componentDidmount-

```
      async componentDidMount() {
        this.checkPermission();
        this.createNotificationListeners();
      }
```

4.

      async checkPermission() {
        const enabled = await firebase.messaging().hasPermission();
        if (enabled) {
          this.getToken();
        } else {
          this.requestPermission();
        }
      }

      async requestPermission() {
        try {
          await firebase.messaging().requestPermission();
          // User has authorised
          this.getToken();
        } catch (error) {
          // User has rejected permissions
          console.log('permission rejected');
        }
      }

      async getToken() {
        try {
          const enabled = await firebase.messaging().hasPermission();
          if (!enabled) {
            await firebase.messaging().requestPermission();
          }
    
          const fcmToken = await firebase.messaging().getToken();
          if (fcmToken) {
            console.log("got token");
            console.log('fcm token:', fcmToken); //-->use this token from the console to send a post request via postman
            this.setState({ fcmToken });
            return fcmToken;
          }
        } catch (error) {
          console.warn('notification token error', error);
        }
      }

5.

     async createNotificationListeners() {
        /*
        * Triggered when a particular notification has been received in foreground
        * */
        this.notificationListener = firebase.notifications().onNotification((notification) => {
            const { title, body } = notification;
            this.showAlert(title, body);
        });
      
        /*
        * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
        * */
        this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
            const { title, body } = notificationOpen.notification;
            this.showAlert(title, body);
        });
      
        /*
        * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
        * */
        const notificationOpen = await firebase.notifications().getInitialNotification();
        if (notificationOpen) {
            const { title, body } = notificationOpen.notification;
            this.showAlert(title, body);
        }
        /*
        * Triggered for data only payload in foreground
        * */
        this.messageListener = firebase.messaging().onMessage((message) => {
          //process data message
          console.log(JSON.stringify(message));
        });
      }

6. Finally, use the token that you see in the console as a value for the "to" key in your post request. You should no longer see the "notRegistered" error and should be getting push notifications.
Done!!

For a more detailed setup/citation-
https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591
