### ISSUE TITLE
[(cloud-)messaging] NO NOTIFICATION

### ISSUE THREAD

**Issue by Klingens13** [firebase/quickstart-ios#778]
Set everything up with a fresh firebase project. Firebase Analytics is working, but if I send a notification, there's no sign of a notification arriving. Even started fresh, with a new project, new apns certificate etc. but still : NO NOTIFICATION. Tested on a iPhone Xr Simulator and real iPhone SE. No notification is arraving...

Could someone please help me with this?

![Screen Shot 2019-08-18 at 01 33 25](https://user-images.githubusercontent.com/40038209/63218318-58a4f800-c158-11e9-8882-cb1317f4460e.png)
![Screen Shot 2019-08-18 at 01 32 10](https://user-images.githubusercontent.com/40038209/63218319-58a4f800-c158-11e9-93b8-36602a09e2a1.png)
![Screen Shot 2019-08-18 at 01 34 41](https://user-images.githubusercontent.com/40038209/63218320-58a4f800-c158-11e9-8917-981d15401aa5.png)
![Screen Shot 2019-08-18 at 01 34 51](https://user-images.githubusercontent.com/40038209/63218321-58a4f800-c158-11e9-9579-9bd49de04cfb.png)
![Screen Shot 2019-08-18 at 01 35 08](https://user-images.githubusercontent.com/40038209/63218322-593d8e80-c158-11e9-8a29-81429c7fbb9e.png)
![Screen Shot 2019-08-18 at 01 37 11](https://user-images.githubusercontent.com/40038209/63218342-bafdf880-c158-11e9-95ef-db222a7b1673.png)
![Screen Shot 2019-08-18 at 01 36 51](https://user-images.githubusercontent.com/40038209/63218344-bcc7bc00-c158-11e9-9b3a-e45f83e7da53.png)

**Comment by morganchen12** [comment]
Are you able to send notifications through APNs (without Cloud Messaging)?

**Comment by morganchen12** [comment]
If you're still unable to figure out notifications, try building the messaging quickstart in this repository to rule out any client-side issues.
