### ISSUE TITLE
legacy fcm protocol

### ISSUE THREAD

**Issue by hhs1120** [firebase/quickstart-ios#780]
I'm using fcm direct channel. 
And server side is using legacy fcm http protocol.
I wonder that legacy fcm http protocol will be deprecation?
and if yes, how about fcm direct channel? it will be supported in new fcm http protocol?

**Comment by morganchen12** [comment]
The legacy FCM http protocol will continue to be available for the foreseeable future. I can't speak to plans for adding direct channel to HTTP v1.
