### ISSUE TITLE
Fetch blank string from remote config

### ISSUE THREAD

**Issue by Samiksha-Toshniwal** [firebase/quickstart-ios#786]
After upgrading to Remote Config 6+, the stringValue fetch is blank. The same code was working for earlier versions. Please suggest.

This is the response I am getting after the upgrade.

`po remoteConfig[FORCE_UPDATE_REDIRECTION_URL]

<FIRRemoteConfigValue: 0x60000277a260, Boolean: 0, String: , Number: 0, JSON:(null), Data: <>, Source: 2>`

**Comment by morganchen12** [comment]
Can you share a minimal project that reproduces this?

**Comment by Samiksha-Toshniwal** [comment]
This is the value on my Remote config console.

![Screenshot 2019-08-30 at 12 59 21 PM](https://user-images.githubusercontent.com/46564658/64001725-100d1780-cb26-11e9-9a72-1821e8e93ece.png)

Then what I am doing is:

`func setupConfig() {
        remoteConfig = RemoteConfig.remoteConfig()
        let settings = RemoteConfigSettings()
        remoteConfig.configSettings = settings
        var dict = [String: NSObject]()
        dict[VERSION_NUMBER] = fetchVersionNumber()
        dict[BUILD_NUMBER] = fetchBuildNumber()
        remoteConfig.setDefaults(dict)
    }
    
    func fetchConfig() {
        let expirationDuration = 0
        remoteConfig.fetch(withExpirationDuration: TimeInterval(expirationDuration)) { [weak self] (status, error) -> Void in
            if status == .success {
                self?.remoteConfig.activate(completionHandler: { (error) in
                    if error != nil {
                       print("Config not activated. Error: \(error?.localizedDescription ?? "No error available.")")
                    } else {
                        self?.activateUpdateAlert()
                    }
                })
            } else {
                print("Config not fetched. Error: \(error?.localizedDescription ?? "No error available.")")
            }
        }
    }

func activateUpdateAlert() {
        let remoteConfigVersion = remoteConfig.configValue(forKey: VERSION_NUMBER)
        let remoteConfigBuild = remoteConfig.configValue(forKey: BUILD_NUMBER)
        let isForceUpdateRequired = remoteConfig.configValue(forKey: IS_FORCE_UPDATE_REQUIRED)
    let forceUpdateRedirectionUrl = remoteConfig.configValue(forKey: FORCE_UPDATE_REDIRECTION_URL).stringValue
}`

And since I am not able to fetch value over here, my force update functionality breaks. 

I have a major dependency over remote config variables for other functionalities too.

**Comment by morganchen12** [comment]
Is there any error printed to console?

**Comment by ToddKerpelman** [comment]
Hey, it looks like your code never calls `activate` after you've successfully downloaded the new set of values from Remote Config. Think that might be it? Check out step 5 here: https://firebase.google.com/docs/remote-config/use-config-ios

**Comment by ToddKerpelman** [comment]
(Comment deleted because I can't read.)

**Comment by Samiksha-Toshniwal** [comment]
No. There is no error on console.

**Comment by morganchen12** [comment]
This sounds like a bug in Remote Config. I'll try to take a look sometime next week to reproduce it. In the meantime you can try copy-pasting your config values and running the [quickstart app](https://github.com/firebase/quickstart-ios/tree/master/config) to see if the issue is reproducible.

**Comment by morganchen12** [comment]
@Samiksha-Toshniwal were you able to repro this issue with the sample app?
