### ISSUE TITLE
Firebase/MLVision uses deprecated UIWebView APIs

### ISSUE THREAD

**Issue by machl** [firebase/quickstart-ios#788]
Frameworks `FirebaseMLCommon (0.17.0)` and `GoogleMobileVision (1.6.0)` (dependencies of `Firebase/MLVision (6.7.0)`) use deprecated UIWebView APIs, which trigger App Store Connect issue during deployment:

> **ITMS-90809: Deprecated API Usage** - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

We won't be able to ship apps with Firebase MLVision to App Store soon, please fix.

**Comment by paulb777** [comment]
Filed internally at b/140396933

**Comment by machl** [comment]
@paulb777 There is same issue with `Crashlytics (3.13.4)` - also uses UIWebView APIs.

**Comment by paulb777** [comment]
b/140424496 for Crashlytics. Thanks @machl

**Comment by paulb777** [comment]
Closing in favor of https://github.com/firebase/firebase-ios-sdk/issues/3780
