### ISSUE TITLE
Push notification not shown when iOS app is closed/killed

### ISSUE THREAD

**Issue by plastic-kartik** [firebase/quickstart-ios#790]
Hello @morganchen12 / Everyone,

I cannot receive the FCM push when the app is closed/killed. I receive the notifications when the app is in foreground or background, but I also want to receive like how whatsapp/facebook notify even when the app is closed.

I can get the notifications in this scenario if i directly publish it from the FCM console, but I can't get the notification when server tries to push.

This is the aps dictionary at the server side:

{
"to":"***fcm device token***",
"data":
   {"title":"Exclusive Offers at CF Masonville Place",
     "body":"Look for the 'CF NOW Zone' signs across the mall ...",
     "sound":"default",
     "click_action":"Launch"
    },
"notification":
   {"title":"Exclusive Offers at CF Masonville Place",
     "body":"Look for the 'CF NOW Zone' signs across the mall ...",
     "sound":"default",
     "click_action":"Launch"
},
"content_available":true,
"priority":"high",
}

Also, want to point out that I receive a push notification when publishing from the firebase console with "content_available" key set to true.(Also works without the key from the console)

Any help would be greatly appreciated. Thanks

**Comment by morganchen12** [comment]
If you remove the `content_available` key, does the notification show up?

**Comment by isha04** [comment]
Facing the same issue. :(

**Comment by plastic-kartik** [comment]
@isha04 Did you try removing the content_available key from your payload?

**Comment by plastic-kartik** [comment]
@morganchen12 Still didn't work for me. Am I missing something on the payload?

**Comment by morganchen12** [comment]
Could you clarify how you're receiving these notifications? Are they user-visible notifications? The `content_available` key causes FCM to try to send them as [silent notifications](https://firebase.google.com/docs/cloud-messaging/http-server-ref), which may not be what you want.

**Comment by isha04** [comment]
We never had the content-avialable key to begin with as the idea was to send push notifications and not silent notification. 
But we had data in our payload. On conversation with Firebase support i found that push notifications are not expected to be delivered on iOS when app is in killed state and payload is data.

@plastic-kartik does your payload consist of notification messages with optional data payload?

**Comment by plastic-kartik** [comment]
Well to receive Push Notifications when the app is closed, I had to implement some other methods which monitors Region. Enabled Background Fetch and added implementation in the App Delegate to wake the app up in background mode which then can call my request to the server for push. I found this helpful: 
https://github.com/yoman07/SwiftBackgroundLocation

**Comment by morganchen12** [comment]
Closing this since it's staled. Please open a new issue if you're still stuck.
