### ISSUE TITLE
Firebase token nil in iOS 13

### ISSUE THREAD

**Issue by NirajCapermint** [firebase/quickstart-ios#793]
Hi,
I recently update my device OS to iOS 13 and after that I noticed one issue that it is not able to get device token for push notification. `FIRInstanceID.instanceID().token()` is always nil. On the other hand I have devices with iOS 11.x.x and iOS 12 which doesn't have this issue. Does anyone having the same issue?

**Comment by morganchen12** [comment]
Please include your Firebase versions and a reproducible sample project.
