### ISSUE TITLE
[ML Kit bug] PDF417 Barcode with invalid characters are not parsed correctly

### ISSUE THREAD

**Issue by francoismarceau29** [firebase/quickstart-ios#794]
**Problem**
When scanning Ontario Health Card barcode (PDF417), the raw value is not parsed correctly. It is missing the birth date, expiration dates, and gender. I have tried on multiple cards with the same results while other readers return the correct information.

**How to reproduce**
Scan latest Ontario Health Card's barcode

**Raw value from the card barcode (read from other barcodes reader)**
@ON HC01.10RZ97400751234567891JOHN JUNIOR SMITH196009101201608252021091001VP10<̈́-|kC-q2\8yt?ORB(7BjdTEmM!^:$D@&#xѲg蛠r    Mե4w4/Zz”&h8qnWRd?O44dѓFM4dѓFM4dѓN)֒(4wJ)CޝESJkuy<h1Up”E<tZJW8Pg׭b[dtH”:S[!ۜʐS:CL4:ʾƭJiQc&NM4>}NTZt^@)S-izջsǵX)֪)3֜    FGi֧<VJku    AB*sJx”ix94Bz@)ҟ2HIZE)RzVN4xfUX[5=M;G”bRS0*@HUi|=AqڣݚRNG8~MnaWW#uMUYJ
rROZiZr}4(qV(JkusPH>Zx#jI4F\UxMn)UzQ֔qK)hjXUxMn՟S%уKzJQSV)RmebgJ<Gҏ>8s~P+

**Raw value from MLKit barcode reader**
`@ON HC01.10RZ97400751234567891JOHN JUNIOR SMITH`

Any help would be appreciated!

**Comment by ulukaya** [comment]
Have you tried with the latest Firebase? (6.10.0)

**Comment by francoismarceau29** [comment]
I just tried it and it is much better! The display and raw values still do not return the correct values, but I can find them in the new _rawData_ property using the correct encoding.

Thank you very much!
