### ISSUE TITLE
[ML Vision] RawValue doesn't retrieve all characters

### ISSUE THREAD

**Issue by cabarique** [firebase/quickstart-ios#795]
[RawValue ](https://firebase.google.com/docs/reference/swift/firebasemlvision/api/reference/Classes/VisionBarcode#rawvalue) doesn't retrieve all information due to its encoding. Is there a way to get [**RawData**](https://developer.apple.com/documentation/foundation/data)  so the encoding can be decided by the developer?

**Comment by francoismarceau29** [comment]
Firebase version 6.10.0 now includes a RawData property on VisionBarcode. You can it to decode the string with the encoding of your choice
