### ISSUE TITLE
Dynamic link not working with facebook

### ISSUE THREAD

**Issue by manu89ft** [firebase/quickstart-ios#798]
From 5 days our links are broken in Facebook and Instagram Webview...
For example https://dyn.bantoa.com/rniX

Here you will find two screencasts: https://we.tl/t-IvB5aYtKfv

**Comment by morganchen12** [comment]
Can you describe the broken behavior?

**Comment by manu89ft** [comment]
On ios without preview page a blank page is shown. Instead with the preview page the app store is always opened even if the app is installed without deep linking. It happens only on facebook and instagram webview. Only a blank page is shown on android.

**Comment by DanGDroid** [comment]
same with our app - dynamic links fail to open from Facebook browser in app, only if opening from Chrome browser.
link example: https://farmerdirecto.page.link/EZmK
![WhatsApp Image 2019-10-15 at 12 38 32](https://user-images.githubusercontent.com/10976856/66820542-8c7a7f00-ef49-11e9-9dc0-83e8dae4996a.jpeg)
![WhatsApp Image 2019-10-15 at 12 39 03](https://user-images.githubusercontent.com/10976856/66820543-8d131580-ef49-11e9-94d0-86b208607107.jpeg)

**Comment by goneale** [comment]
This problem is still occuring via the Facebook iOS App as well. 
We've been received customer reports that our dynamic links had stopped working on Facebook (opens in a blank white screen). This is only occurring for us on iOS, Android is launching the dynamic link fine. I would have thought it was a FB app issue, or recent changes to dynamic link processing on Google (.link) service?
You can observe this white screen behavior if you hit "See More" on this video in Facebook and click the go.wowapps link try doing the call to action on the landing page. https://www.facebook.com/watch/?v=1332661800249739

Could this be a Facebook App issue if in fact Android is processing fine?

**Comment by morganchen12** [comment]
Thanks all, I've filed this bug to the dynamic links team internally and will update this thread accordingly.

The internal bug number is b/143880690.

**Comment by morganchen12** [comment]
It looks like this is intended behavior for links with `efr=1`. To make dynamic links work in the Facebook browser you'll need to remove this parameter.

**Comment by manu89ft** [comment]
All the dynamic links in the facebook webview doesn't work.

**Comment by morganchen12** [comment]
Can you share an unshortened link without the `efr` parameter?

**Comment by kkusanagi** [comment]
Dynamic link for IOS and Android is not working at all within facebook.

**Comment by manu89ft** [comment]
@kkusanagi  It's true. I also reported it but no one solves the problem.

**Comment by kkusanagi** [comment]
Currently i'm being force to use redirect page. 
Within redirect web page, add javascript below to check if it is facebook browser. 
Then show an instruction to open link in chrome or default browser. This method also being use to solve the wechat browser too. 

```
navigator.userAgent.indexOf('FBAN') > -1 || this.userAgent.indexOf('FBAV') > -1
```

**Comment by joshwolff1** [comment]
This is still an issue. It should work with efr=1.  Please reopen

**Comment by morganchen12** [comment]
afaik it is currently not possible to open an app via universal link out of the Facebook, Messenger, or WeChat apps without using a preview page. If you are experiencing other bugs, like opening the App Store when your app is installed, please file a new issue.

**Comment by joshwolff1** [comment]
Ok, thank you for getting back to me.

**Comment by manjuy124** [comment]
> Thanks all, I've filed this bug to the dynamic links team internally and will update this thread accordingly.
> 
> The internal bug number is b/143880690.

@morganchen12 any update on this bug?

**Comment by martynovskij** [comment]
+1
Any updates?

**Comment by ahmadalzdwr** [comment]
هل هاذ البرنامج نقدر نسحب منه حوالات  او   لا  ردوني خبر لم افهم اي شي

**Comment by dan-o3h** [comment]
We're also seeing this issue with Instagram/Facebook stories on iOS 14+. For example, pressing the "See More" button in an Instagram story, the Dynamic Link page opens in the in app browser to a blank page and then immediately closes. The link is designed to resolve either to the app store or fallback to a website. Clicking the "See More" link a second time works as expected, however the analytics is showing a big drop off in UA because of this issue.

**Comment by BurningAXE** [comment]
> Can you share an unshortened link without the `efr` parameter?

@morganchen12 Here is one:
https://app.helpapaw.org/?link=https://www.helpapaw.org/app?signal=3B9A24D1-70CC-4687-B56F-E5DF4AC1F717&ibi=com.helpapaw.helpapaw&apn=org.helpapaw.helpapaw

It works in Messenger with a preview page but on Facebook it opens a blank screen. 
iOS 14.8, Facebook 336.1.0.29.116, FirebaseDynamicLinks 8.7.0
Let me know if you need any more info and please reopen this issue - Facebook will be one of our main channels and currently this issue renders dynamic links useless for us!

**Comment by DennisAshford** [comment]
This is still an issue. Dynamic links are supposed to solve 'all of the issues with deep links' and yet they don't work properly on the largest social networks in the world...

What is odd is when you first go to share the link, the preview and everything look fine. However, once it is shared, it shows a black image. There has to be a work around from the Firebase team!

**Comment by dhimansham** [comment]
Still Same issue.

https://github.com/firebase/firebase-ios-sdk/issues/9375

**Comment by Jim0604xcode** [comment]
<meta property="fb:app_id" content="<fbappid>"
<meta property="al:android:package" content="<appId>" />
<meta property="al:android:app_name" content="<appName>" />
<meta property="al:android:url" content="https://<android:host>" />
Add above into <head></head>

https://user-images.githubusercontent.com/108716984/177266450-29d826ca-4aca-4b07-b27b-3386726b4434.mp4

https://user-images.githubusercontent.com/108716984/177266547-5c5dbc31-bf3e-498c-a0a6-5e80d727c3f9.mp4



ensure <head></head> include above before share post to facebook.[](url)

**Comment by Jim0604xcode** [comment]
https://user-images.githubusercontent.com/108716984/177267097-745e7582-f571-48f7-80f2-3f2665b49321.mp4

**Comment by Jim0604xcode** [comment]
meta property="fb:app_id" content="fb app id"
meta property="al:android:package" content="app id" 
meta property="al:android:app_name" content="app name"
meta property="al:android:url" content="https://xyz.page.link"
ensure head tag include the above meta tag before share post to facebook

intent-filter android:autoVerify="true"
                action android:name="android.intent.action.VIEW"
                category android:name="android.intent.category.DEFAULT"
                category android:name="android.intent.category.BROWSABLE"
                data android:scheme="https" android:host="xyz.page.link"
            intent-filter
