### ISSUE TITLE
linkWithCredential not working on swift

### ISSUE THREAD

**Issue by xhiza** [firebase/quickstart-ios#80]
I have been trying to link two account with same email address and still got 17007 error code (FYI have been using authentication method base on quickstart code)

**Comment by ianbarber** [comment]
I don't think this is a Swift issue. The error code there is FIRAuthErrorCodeEmailAlreadyInUse -

make sure you are linking in the right order: e.g. you should be linking the new credential to the one already associated with the Firebase account.

**Comment by morganchen12** [comment]
stale; closing. @xhiza reopen if you've still running into trouble.
