### ISSUE TITLE
I try to compile auth sample and get #import <FirebaseCore/FirebaseCore.h> error

### ISSUE THREAD

**Issue by saulex** [firebase/quickstart-ios#803]
I clone git.
$ pod install
open AuthenticationExample.xcodeproj
and compile and get this error

Swift Compiler Error Group
/Users/----/Documents/quickstart-ios/authentication/Pods/Firebase/CoreOnly/Sources/Firebase.h:1:9: 'FirebaseCore/FirebaseCore.h' file not found
/Users/----/Documents/quickstart-ios/authentication/AuthenticationExampleSwift/PasswordlessViewController.swift:17:8: Could not build Objective-C module 'Firebase'

**Comment by paulb777** [comment]
`open AuthenticationExample.xcworkspace`

**Comment by saulex** [comment]
Yes, Thank you, I'm starting in swift.
