### ISSUE TITLE
headEulerAngleY work incorrectly

### ISSUE THREAD

**Issue by IlovingCode** [firebase/quickstart-ios#809]
Hello team,

I tried the face tracking sample and worked with **headEulerAngleY** value. I realized that the value worked incorrectly. Actually, it took a delayed time (~0.2s, 15 frames) to make the **headEulerAngleY** value to be correct. The other values (face position, headEulerAngleZ) also worked well.

Could you please take a look on this issue?

Regards.

**Comment by bishalg** [comment]
@IlovingCode : 
how did u measure the latency ? 
Maybe if you can share the code it would be helpful. Coz sometimes it might be the graph plot issue or some other memory leaks that causing the delay.
So much so that on debug mode even the logger can cause frame drops.

**Comment by IlovingCode** [comment]
Hello,
I turned on landmark (landmarkMode = FIRVisionFaceDetectorLandmarkModeAll) and it worked right. Is it expected behavior? Anyway, you can close this issue because it was fixed on my side.
Thank you.
