### ISSUE TITLE
iOS | FCM not receiving topic & Segment Notification while Single Device working Fine

### ISSUE THREAD

**Issue by shehzadq** [firebase/quickstart-ios#81]
Hi I am trying to use FCM for topic Notifications. Topics Subscribed successfully and shown as well in console. When I send message using console for Single device it works fine. While when I send message to topic or Segment it is not received.

My Topics being shown in console as well. Can anybody help.

**Comment by daveanderson** [comment]
What does your payload (JSON format) look like? There are certain FCM keys that if you include them in the payload the _may_ result in a push that is not sent to iOS devices. Start with a very simple payload and successively add keys (and values).

**Comment by ianbarber** [comment]
Closing - please reopen with details of the message you're sending if still having issues!

**Comment by BhavinBhadani** [comment]
@ianbarber it's not working even with a console ... iOS 11.0.2 and messaging 2.0.4 .. working only when I am tried with token

**Comment by morganchen12** [comment]
If you've got a new issue, please file it (with the relevant code or a project that reproduces the issue) over at https://github.com/firebase/firebase-ios-sdk/issues.

**Comment by jaigtz88** [comment]
@BhavinBhadani did you solve the problem? im still struggle with this issue
