### ISSUE TITLE
Crashes are not appearing in Firebase Crashlytics

### ISSUE THREAD

**Issue by Rahulkhandal** [firebase/quickstart-ios#811]
I am getting exactly same issue specified in the link :
https://github.com/firebase/quickstart-ios/issues/791#issuecomment-535601638

Can you please help to figure the above issue.

Description: **Same description as of above link**
In the beginning I wasn't getting any log about Crashlytics on Xcode. The reason was my old integration with Fabric. I had to remove the Fabric key that was in the plist and the key that was in the build fase run script. If I try to follow just the tutorial I was getting:

Mismatched configuration: Fabric entry found in app's Info.plist, but no API Key provided to the run script. If this app was set up in Fabric, or linked to Firebase, pass your API key to the run script as the first argument. If this app was onboarded via Firebase, remove the Fabric entry in your Info.plist

After that I could start getting logs about Crashlytics. But now I think I have the same bug, because the logs say that it's working. (The log is from an old version, but the result in the same with the Crashlytics version 3.14.0):

**[Crashlytics] Version 3.13.4 (143)
[Crashlytics] Running on iPhone9,3, 12.3.1 (16F203)
[Answers] Initialized
[Fabric] Initialized with kit versions: {
"com.twitter.answers.ios" = "1.4.1";
"com.twitter.crashlytics.ios" = "3.13.4";
"io.fabric.sdk.ios" = "1.10.2";

[Crashlytics:Crash:Reports] Packaged report with id '9e06ebd6aae240108cead10eafda56e1' for submission
[Crashlytics:Crash:Reports] Submitting report
[Crashlytics:Crash:Reports] Submitting async /var/mobile/Containers/Data/Application/744E4402-3A20-4D6C-9E8A-972F37050CBA/Library/Caches/com.crashlytics.data/APP_NAME/v3/prepared/9FDBC984-17B9-408A-84FE-77BF8EE7C5C6.multipartmime
[Crashlytics:Crash:Reports:Event] Sending event.
[Crashlytics:Crash:Reports] completed submission of /var/mobile/Containers/Data/Application/744E4402-3A20-4D6C-9E8A-972F37050CBA/Library/Caches/com.crashlytics.data/APP_NAME/v3/prepared/9FDBC984-17B9-408A-84FE-77BF8EE7C5C6.multipartmime
[Crashlytics:Crash] report submission successful**

**Comment by morganchen12** [comment]
Please file a support ticket as suggested in the linked issue.
