### ISSUE TITLE
Can not find class reference when clicking on function with "cmd+{left click}".

### ISSUE THREAD

**Issue by allenlinli** [firebase/quickstart-ios#82]
Can not find class/function reference when clicking on function with "cmd+{left click}".

It shows the error: 

> Couldn't Generate Swift Representation.
> Error (from SourceKit):
> Could not load module: FirebaseAnalytics

How can I solve this problem so I don't need to look up reference on document every time?

**Comment by allenlinli** [comment]
When I created my own project using Firebase pod, I succeeded looking up the reference.
Somehow it shows the error when I try the "AuthenticationExample". But the issue doesn't bother me now.

**Comment by allenlinli** [comment]
I found out the cause was I have a space in my Xcode project name, and then Xcode can not find the correct path of the frameworks.

This is the reference.
http://stackoverflow.com/questions/32894901/xcode-couldnt-generate-swift-representation-for-my-own-framework

**Comment by ianbarber** [comment]
Closing - sounds like that fixed it?

**Comment by allenlinli** [comment]
Yes, thanks. I feel embarrassed.
