### ISSUE TITLE
0% of potential users are eligible for this campaign: 0

### ISSUE THREAD

**Issue by NaveenReddy1** [firebase/quickstart-ios#831]
I just integrated the Firebase Cloud Messaging , when I tried to create cloud message in Firebase Console its showing like **0% of potential users are eligible for this campaign: 0**. Also I installed the app in multiple devices but no use. I cross checked with bundle id and GoogleService-Info file. I am using Xcode 11.2.

**Comment by Nikita-Filonov** [comment]
Make sure you have only one firebase project configured for this app (if no then delete one you dont plan to use)
Go to firebase setiings -> Left top angle -> settings icon -> Project settings -> scroll to bottom, then make sure to add SHA certificate fingerprints  Type. How to get it
Then (still on this page) press See SDK instructions button. And place google-services.json file in your project.
If all this steps passed for you and you still getting this error then just wait a little bit, for me it take 2 days, before it started working.
