### ISSUE TITLE
FcmToken change

### ISSUE THREAD

**Issue by mingios** [firebase/quickstart-ios#832]
FcmToken changes every time the APP Launch，is OK?

**Comment by mingios** [comment]
IOS   ver FirebaseMessaging 4.1.9

**Comment by morganchen12** [comment]
FCM token changing every time the app is launched is unusual. Check your APNs token to see if the token is being refreshed on each app launch, causing the FCM token to change. Otherwise this may be a bug in your implementation of Firebase or a bug in Firebase Messaging.

**Comment by morganchen12** [comment]
Closing since this issue has had no new responses in a while. Please comment here if this is still an issue.

**Comment by FrankB1708** [comment]
I am having the same problem on my app, although it used to work just fine.
Did you find a solution to that ?
