### ISSUE TITLE
settings efr=1 always redirects to app store

### ISSUE THREAD

**Issue by aniruddhambarkar** [firebase/quickstart-ios#836]
I have added efr=1 into my dynamic link. Adding this disables app preview page but always redirects link to app store page event though I have app installed on my device.
On removing this param app receives dynamic link, but I want to remove preview page

**Comment by morganchen12** [comment]
If you have the app installed, dynamic links should be using the platform-specific universal link behavior. See [Apple's universal link docs](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links) to make sure you've set up universal linking correctly.

**Comment by aniruddhambarkar** [comment]
@morganchen12 
if I remove this (efr=1) param it works perfectly fine. It takes me to app and store according to if app is installed. But when I add this params it always asks me to open on app store.

**Comment by morganchen12** [comment]
Can you share the Apple App Site Association file generated by Firebase?

**Comment by aniruddhambarkar** [comment]
{"applinks":{"apps":[],"details":[{"appID":"M65MBW7XAC.{App ID of App}","paths":["NOT /_/*","/*"]}]}}

I have checked that the app id here matched exactly to my app

**Comment by morganchen12** [comment]
The site association app looks fine. Can you share the link you're trying to open?

**Comment by derbra1513** [comment]
I am also having this issue.

**Comment by Yogiyadavmca** [comment]
I am too having the same issue. Did anyone resolve it?

**Comment by steve28100** [comment]
Same issue here

**Comment by esp10mm** [comment]
Did anyone solve this ?

**Comment by thepearl** [comment]
same issue, I want to get rid of that ugly preview page ! but setting efr = 1 always redirects me to App Store

**Comment by Saran-J** [comment]
Same issue here

**Comment by genaronuno25** [comment]
Same issue here!!! :c

**Comment by radvansky-tomas** [comment]
Same here, any update ?

**Comment by kcj30906** [comment]
Same issue here !!!!!
