### ISSUE TITLE
Dynamic Links does not open app on iOS 13

### ISSUE THREAD

**Issue by Sushhi** [firebase/quickstart-ios#843]
Hello,

So I'm trying to create a dynamic link for my app. I created this project under iOS 13 target so I have the `SceneDelegate` file.

I believe everything is well setted in my firebase console, bundle id, team id, app id, ...

I successfully created the link and no error are detected with `DynamicLinks.performDiagnostics`.
I added the capability and setted the "associated domains" to "applinks:https://mydomain.page.link" (also tried "applinks:mydomain.page.link").

After this process, when I try to open the link from iMessage, i got redirected to the preview page, then when I click on "Open", I got redirected to the App Store, showing me a message that says the app is unavailable (since it's not on store yet). 

I heard the apps created after iOS 13 release don't use the `"application" delegates` but the `"scene" delegates` but I have no idea how to implement it and I'm not even sure that it comes from this part.

Anyone have an idea of what i'm missing ?

**Comment by morganchen12** [comment]
If the app is already installed, opening it via the dynamic link uses the system universal link behavior and bypasses Firebase entirely. If you long-press the link in iMessage, does it show an `Open in Your App` option?

**Comment by Sushhi** [comment]
> If you long-press the link in iMessage, does it show an `Open in Your App` option?

Nope, it doesn't

**Comment by Sushhi** [comment]
Should it be `applinks:https://mydomain.page.link` or `applinks://mydomain.page.link` ?

**Comment by morganchen12** [comment]
According to [Apple's docs](https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains#3001207), it should be `applinks:mydomain.page.link`.

**Comment by Sushhi** [comment]
Thank for your response.

Do you know where I can see an example of dynamic links implementation `using scene delegate` somewhere ? I can't find any...

**Comment by morganchen12** [comment]
For the time being Firebase doesn't have any, but we plan on adding UIScene samples soon (ideally by the end of January).

**Comment by morganchen12** [comment]
Issue may be related to https://github.com/firebase/firebase-ios-sdk/issues/4914.
