### ISSUE TITLE
Disable FCM-only messaging

### ISSUE THREAD

**Issue by daveanderson** [firebase/quickstart-ios#85]
If a user has iOS notifications disabled it is still possible for FCM-based messages to be received when the app is in the foreground. 

What is the recommended approach for disabling/suppressing FCM-based messaging when APNs-based notifications are disabled?

**Comment by ianbarber** [comment]
Not sure we have a specific recommendation there - you can choose not to respond to messages in applicationReceivedRemoteMessage. Are you seeing some unexpected behavior?

**Comment by daveanderson** [comment]
We thought we were but haven't seen this for a while.
