### ISSUE TITLE
FCM Payload does not accept 1 as a value for content_available

### ISSUE THREAD

**Issue by daveanderson** [firebase/quickstart-ios#86]
When converting a Swift3 dictionary of type `[String: Any]` to JSON via JSONSerialization, JSONSerialization will translate a _swift_ dictionary containing 

`"content_available":true`

into the JSON representation of

`"content_available":1`

(This is not a new problem: http://stackoverflow.com/questions/13615451/how-do-i-get-nsjsonserialization-to-output-a-boolean-as-true-or-false )

I've filed a Radar against JSONSerialization, however I must also file an issue here where FCM rejects the push payload (returns a 400) if it contains `"content_available":1` instead of `"content_available":true`.

It would be nice if the FCM API were slightly more robust and interoperated better with the JSON serialized via (NS)JSONSerialization.

**Comment by ianbarber** [comment]
Thanks - in general this tracker is for quickstart issues and feature requests best go to https://firebase.google.com/support/contact/bugs-features/ - I'll raise this directly as well though
