### ISSUE TITLE
[ML Translate] ModelManager download -- is there an implementation for preventing re-downloading ongoing downloads

### ISSUE THREAD

**Issue by om-ha** [firebase/quickstart-ios#865]
Amazing library and API as always.

As we don't have access to the source code, I have few points that are ambiguous related to _MLKit Translate_'s `ModelManager`:
1.  When downloading a model ahead of time using [`download`](https://github.com/firebase/quickstart-ios/blob/master/translate/TranslateExampleObjC/ViewController.m#L170) method, do you guys check if a download is already in progress? or we have to track downloads on our end to prevent re-downloading a currently-downloading translate model (language model).
2.  Same question in the first point applies to [`isModelDownloaded`](https://github.com/firebase/quickstart-ios/blob/master/translate/TranslateExampleObjC/ViewController.m#L196). This one's answer is rather predictable from the property name.

Happy new year

**Comment by om-ha** [comment]
@morganchen12  appreciate assigning the label and ulukaya as a participant.

**Comment by morganchen12** [comment]
Hey @om-ha, from what I understand the answers are:

1. Yes, ML Kit does check. However, ML Kit will cancel and restart the download if it finds that the current download is for an older version of the model and a newer version is available remotely.
2. No, `isModelDownloaded` will be false if the download is still in progress.

**Comment by om-ha** [comment]
Spot-on, thank you Morgan.
