### ISSUE TITLE
[ML Kit Bug] Can't detect face from sampleBuffer, when i set videoOrientation to 「.portrait」

### ISSUE THREAD

**Issue by kim68666343** [firebase/quickstart-ios#873]
Hello.
I just got a strange bug: when I set the videoOrientation to portrait, I can't use VisionFaceDetector to detect face.

And I try my other efforts:
1. I changed the VisionImage's orientation from rawValue 1 to 8, and it still can't detect any face.
2. Face can be detected when I rotate my iPhone.
3. When I set videoOrientation to LandscapeRight, everything goes right.
4.When I   rotate my sampleBuffer by vImage, everything goes right too.

Did I miss something? Can someone tell me what's wrong about this bug.

Here are my environments:
Firebase (5.20.2)
FirebaseCore (5.4.1)
FirebaseMLVision (0.15.0)
FirebaseMLVisionFaceModel (0.15.0)

**Comment by morganchen12** [comment]
Looks like you're using a very old version of Firebase. Can you try updating to Firebase 6.0 or higher and see if the issue still exists?

**Comment by kim68666343** [comment]
> Looks like you're using a very old version of Firebase. Can you try updating to Firebase 6.0 or higher and see if the issue still exists?

Thanks for your quick response and advice, I am trying that. And I'll tell you my result after I update them.
Regards.

**Comment by kim68666343** [comment]
> Looks like you're using a very old version of Firebase. Can you try updating to Firebase 6.0 or higher and see if the issue still exists?

Hello Morgan.

I updated my frameworks, and I think all of them are lately version. But this issue still exists.

Here are my new environments:
```
Installing Firebase (6.14.0)
Installing FirebaseAnalytics (6.1.7)
Installing FirebaseCore (6.5.0)
Installing FirebaseCoreDiagnostics (1.1.2)
Installing FirebaseCoreDiagnosticsInterop (1.1.0)
Installing FirebaseInstanceID (4.2.8)
Installing FirebaseMLCommon (0.19.0)
Installing FirebaseMLVision (0.19.0)
Installing FirebaseMLVisionFaceModel (0.19.0)
Installing GTMSessionFetcher (1.3.1)
Installing GoogleAPIClientForREST (1.3.10)
Installing GoogleAppMeasurement (6.1.7)
Installing GoogleDataTransport (3.2.0)
Installing GoogleDataTransportCCTSupport (1.2.3)
Installing GoogleToolboxForMac (2.2.2)
Installing GoogleUtilities (6.4.0)
Installing Protobuf (3.11.2)
Installing nanopb (0.3.9011)
```


What's more, I've wrote a demo to repeat this issue:
[FIRFaceDetectionTest.zip](https://github.com/firebase/quickstart-ios/files/4047614/FIRFaceDetectionTest.zip)

Usage:
1. Add the 'GoogleService-Info.plist' file to the project.
2. Run 'Pod install' to install the frames.

I'm truly grateful for your help. :)

**Comment by morganchen12** [comment]
It doesn't look like there's anything wrong with your sample code. I've filed b/148094225 internally to the ML Kit team. I'll keep this issue updated with any progress.

**Comment by kim68666343** [comment]
> It doesn't look like there's anything wrong with your sample code. I've filed b/148094225 internally to the ML Kit team. I'll keep this issue updated with any progress.

Thanks a lot.

**Comment by miworking3** [comment]
- setting `connection.videoOrientation = .portrait` is unnecessary as face detector can detect sample buffers correctly without setting this. 
If it is to be set, then in `captureOutput(_ output:, didOutput sampleBuffer:, from connection:) `, it has to be set as well.

- Removing `connection.videoOrientation = .portrait`, there is only one change to make it work:
in 
```
private func detect(sampleBuffer: CMSampleBuffer, with orientation: VisionDetectorImageOrientation) {
        let img = VisionImage(buffer: sampleBuffer)
        let meta = VisionImageMetadata()
        meta.orientation = orientation
```
assign the new `meta` to `img`:
```
private func detect(sampleBuffer: CMSampleBuffer, with orientation: VisionDetectorImageOrientation) {
        let img = VisionImage(buffer: sampleBuffer)
        let meta = VisionImageMetadata()
        meta.orientation = orientation
        img.metadata = meta
```
