### ISSUE TITLE
Cant detect faces without MLVisionFaceModel

### ISSUE THREAD

**Issue by jpedrouy** [firebase/quickstart-ios#874]
Hello,

I was wondering if they could help me, I would like to use your test app without [MLVisionFaceModel](https://github.com/firebase/quickstart-ios/blob/master/mlvision/Podfile#L11) as directed [here](https://firebase.google.com/docs/ml-kit/ios/detect-faces#before-you-begin) but the array of [faces](https://github.com/firebase/quickstart-ios/blob/master/mlvision/MLVisionExample/ViewController.swift#L825) is empty when i run whit this configuration. Can you tell me, what did i do wrong?

best regards.

**Comment by kim68666343** [comment]
I have same issue.

**Comment by morganchen12** [comment]
The model framework contains the actual tflite model that ML Kit uses to perform on-device inference. If the model is not present, then you will receive no results.

This is true for all the other ML model frameworks as well.
