### ISSUE TITLE
Firebase in app messaging stopped working 

### ISSUE THREAD

**Issue by Narendra-Pandey** [firebase/quickstart-ios#878]
Hello,

Firebase InAppMessaging stopped working. As it was working from one month.
i updated the pod, previously FirebaseInAppMessagingDisplay was 0.13.1 and now it’s 0.15.5

As there isn’t any single line of code for that just followed this steps

https://firebase.google.com/docs/in-app-messaging/get-started?platform=ios 

As i can able to get instance id, previously i can able to test on simulator as well as device

but now i didn’t Please help

it also says in log : *No auto data collection enable setting entry detected.So no FIAM programmatic setting from the app.* *No programmatic or plist setting at FIAM level. Fallback to global Firebase level setting*

what does this log mean?

**Comment by morganchen12** [comment]
The log means FIAM is using the default global Firebase data collection settings. How are you testing in-app message display?
