### ISSUE TITLE
how can draw  rectangle around text  when I detect text with live camera 

### ISSUE THREAD

**Issue by amralkhayat** [firebase/quickstart-ios#879]
Hello ,
now I am creating project using text detection , my problem is how can I draw rectangle around the text I have detected I am  using live camera not take a picture and then draw the shape I want to draw it live during use the camera.

**Comment by morganchen12** [comment]
To draw geometric shapes on a view, you should use Apple's [Core Graphics](https://developer.apple.com/documentation/coregraphics) framework. StackOverflow may be able to give you more advice.

Closing this since it's not a Firebase question.
