### ISSUE TITLE
FIRStorageDownloadTask pause problem

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-ios#88]
I can download a file with no problem using:

``` objective-c
FIRStorageDownloadTask* task = [ref writeToFile:[NSURL fileURLWithPath:destinationFile]];
```

However, if I call the `pause` method, the download pauses for a few seconds and then resumes automatically! I am not calling the `resume` method but it resumes automatically.

I wonder what could be the problem?

**Comment by salmaanrizvi** [comment]
I am also having this problem. Upon checking the status of the download task after pausing, it is set to .Resume

Can't seem to figure out why it auto restarts the download

**Comment by mcdonamp** [comment]
That's a pretty interesting bug--definitely shouldn't be doing that! I'll take a look and see if I can resolve.

**Comment by JannyKul** [comment]
seeing the same issue, for what its worth the `cancel` method doesn't seem to work either. thanks in advance

**Comment by schmidt-sebastian** [comment]
We have been able to reproduce this issue and are working on a fix. Thanks for your patience.

**Comment by onurtekin** [comment]
It seems that downloadTask is not actually cancelling itself after completing its task.

Here is the case:

1. download a file by:
`FIRStorageDownloadTask *downloadTask = [bubbleRef writeToFile:localURL completion:^(NSURL *URL, NSError *error){
//....
}];`

2. delete the local file by:
`[[NSFileManager defaultManager] removeItemAtPath:filePath error:nil];`

3. downloadTask downloads the file again!!!

but:
1. download a file by:
`FIRStorageDownloadTask *downloadTask = [bubbleRef writeToFile:localURL completion:^(NSURL *URL, NSError *error){
//....
}];`

2. re-run app again.

3. delete the local file by:
`[[NSFileManager defaultManager] removeItemAtPath:filePath error:nil];`

4. no problems!

Any progress with the issue @schmidt-sebastian and @mcdonamp?

**Comment by mcdonamp** [comment]
I believe that the fix for `pause` went into the latest release of Firebase ([3.10.0 release notes](https://firebase.google.com/support/release-notes/ios#3.10.0)). Do you mind updating and letting us know if this fixes your issue?

**Comment by myflashlab** [comment]
Yes, I can confirm that this problem is now fixed. We also updated our ANE to 3.10.0 and the pause/resume now works correctly on iOS too just like the Android side. Thanks.

**Comment by onurtekin** [comment]
Thanks for the quick reply but i've noticed that it was my fault and removed the comment already. It works solid with the latest release.
