### ISSUE TITLE
Short URL not handled in dynamicLinks

### ISSUE THREAD

**Issue by hiko-prod** [firebase/quickstart-ios#895]
I have defined a dynamic link on my firebase project : 

The application is correctly configured and the link open the application:

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray *restorableObjects))restorationHandler rootViewController:(UIViewController*)rootVC {
    
           BOOL handled = [[FIRDynamicLinks dynamicLinks] handleUniversalLink:userActivity.webpageURL
                                                                  completion:^(FIRDynamicLink * _Nullable dynamicLink,
                                                                               NSError * _Nullable error) {
            NSLog(@"[dynamic Links] - link %@", dynamicLink);
            NSLog(@"[dynamic Links] - erro %@", error);
            
          }];
     
    return handled;
}

```

When I use long dynamicLink url everything is OK, I can access the URL defined as parameter.
When I use short dynamicLink url,  handleUniversalLink return true but the dynamicLink created has not url.

As indicated in documentation:  
https://firebase.google.com/docs/dynamic-links/debug

I have added `?d=1` at the end of url but I didn't find any différence between the short and long URL.

Possible associated bug:
https://github.com/firebase/quickstart-ios/issues/105

**Comment by morganchen12** [comment]
Are you able to reproduce this using the dynamic links quickstart in this repository?

**Comment by hiko-prod** [comment]
Hello thanks for your answer.

As you recommended I use the dynamic links quick start project du reproduce my problem.

I followed this video to configure the demo as I did for my project:
https://www.youtube.com/watch?v=KLBjAg6HvG0&t=686s

When I use the dynamic link : 
Short:
`https://app.xxxmy-domainexxx.fr/test`

Long:
`https://app.xxxmy-domainexxx.fr/?link=https://www.xxxmy-domainexxx.fr/samplePath&apn=com.reversBundleID&isi=123456789&ibi=fr.reversebundleID&ius=urlScheme&efr=1`
 
With my App : 
On click both link open the app.
Long : Handled by handleUniversalLink
short : **NOT Handled** by handleUniversalLink

With demo App : 
On click both link open the app.
Long : **NOT Handled** by handleUniversalLink
short : **NOT Handled** by handleUniversalLink

With the demo App I have more logs , that com from analytics

On Long Link:
```
[Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    apn = "com.reversBundleID";
    efr = 1;
    ibi = "fr.reversBundleID";
    isi = 123456789;
    ius = urlScheme;
    link = "https://www.xxxmy-domainexxx.fr/samplePath";
}
```

On short Link:
`[Firebase/Analytics][I-ACS023000] Deep Link Web URL query is empty`


For information when I open :
` https://app.xxxmy-domainexxx.fr/test?d=1 `

I can see the correct graph and click the link from the phone open the application.
 
I also tried : 
`[FIRDynamicLinks performDiagnosticsWithCompletion:nil];`

Result : 
```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 4.0.6
System information: OS iOS, OS version 12.3.1, model iPhone
Current date 2020-02-04 10:11:35 +0000
Device locale en-FR (raw en_FR), timezone Europe/Paris
	Specified custom URL scheme is fr.reverseBundle.id and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: XXXXXXXXX, Team ID: XXXXXXXXX, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----
```

**Comment by morganchen12** [comment]
If you resolve the short link with [this method](https://firebase.google.com/docs/reference/ios/firebasedynamiclinks/api/reference/Classes/FIRDynamicLinks#/c:objc(cs)FIRDynamicLinks(im)resolveShortLink:completion:) and then pass the resulting URL to `handleUniversalLink`, is the URL handled successfully?

**Comment by hiko-prod** [comment]
After the use resolveShortLink the result is still the same:
The result of the method return no error, but this url:
`fr.reversebundleID://google/link/?match_type=unique`

**Comment by diogo10** [comment]
We are having the same issue over here. It used to work properly. Somehow, it stopped.

> Deep Link Web URL query is empty

But the performDiagnostics is:

> ---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 2.3.2
System information: OS iOS, OS version 13.3.1, model iPhone
Current date 2020-02-17 17:10:32 +0000
Device locale en-GB (raw en_GB), timezone Europe/Lisbon
	Specified custom URL scheme is com.edp.edpx.smaapp.pre and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: XXXXXXXXXX, Team ID: XXXXXXXXXX, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----

On Android, it's working fine. We are happing this issue only on IOS.

**Comment by krishnastvSMSC** [comment]
Hello Team,
We are also facing same issue, short url is not working, and for long link no method is trigged in Appdelegate. How we can process the long link in out iOS application.

**Comment by mats-claassen** [comment]
Same issue here

**Comment by morganchen12** [comment]
@hiko-prod can you [file a support case](https://firebase.google.com/support/troubleshooter/contact/)? They'll be able to look at your project directly and help you debug more effectively.

For other people running into this issue, make sure that your link shows no issues when opening it in a browser with `?d=1` appended to the parameters and `[FIRDynamicLinks performDiagnosticsWithCompletion:nil]` shows no errors.
