### ISSUE TITLE
Firebase analytics <FIRAnalytics/ERROR> Inconsistent state, raw event is expected.

### ISSUE THREAD

**Issue by vlider** [firebase/quickstart-ios#91]
At the very start of the program I call [FIRApp configure]; 
It sends the automatic analytics events, but it is failed for some reason.
Also such the issue happens if I send my custom events.

Configuring the default app.
<FIRAnalytics/DEBUG> Debug mode is on
<FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
<FIRAnalytics/INFO> Firebase Analytics v.3301000 started
<FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
<FIRAnalytics/DEBUG> Debug logging enabled
<FIRAnalytics/DEBUG> Monitoring the network status
<FIRAnalytics/INFO> Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
<FIRAnalytics/DEBUG> Network status has changed. Code, status: 2, Connected
<FIRAnalytics/DEBUG> Successfully parsed a configuration. Version: 1472454938029000
<FIRAnalytics/DEBUG> Firebase Analytics is ready to receive events
<FIRAnalytics/DEBUG> Timer scheduled to fire in approx. (s): -537.0911269783974
<FIRAnalytics/DEBUG> Upload task scheduled to be executed in approx. (s): -537.0911269783974
<FIRAnalytics/DEBUG> Scheduling user engagement timer
<FIRAnalytics/DEBUG> Timer scheduled to fire in approx. (s): 3600
<FIRAnalytics/INFO> Firebase Analytics enabled
<FIRAnalytics/DEBUG> Timer fired
<FIRAnalytics/DEBUG> Canceling active timer
<FIRAnalytics/DEBUG> Starting data upload
<FIRAnalytics/ERROR> Inconsistent state, raw event is expected. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=2 "Cannot create an event from database. Missing origin parameter" UserInfo={NSLocalizedDescription=Cannot create an event from database. Missing origin parameter}
<FIRAnalytics/ERROR> Transaction failed
<FIRAnalytics/DEBUG> No data to upload

What might be the problem here? I could not find in the Internet any useful info how to fix that or what conditions or Xcode settings maybe, might interrupt the uploading?
"Cannot create an event from database. Missing origin parameter". What is the origin parameter?

Please, suggest the solution. Thanks in advance

**Comment by baolocdo** [comment]
vlider@, can you please post a full debug log? Not sure which auto events were causing this problem. Usually, when an event is logged, it will show the detail of the event with params. It will be easier for us to debug. Thanks.

**Comment by morganchen12** [comment]
closing because this issue has staled. @vlider reopen if you're still having trouble.

**Comment by DmitryArbuzov** [comment]
I have the same issue.

**Comment by Sourcebits-Ravik** [comment]
Is the above issue resolved i am facing the same issue

**Comment by baolocdo** [comment]
Please provide the SDK version, and your Podfile. It could be something funky with the way multiple SDKs interact with each other or some low level implementation. Thanks
