### ISSUE TITLE
Dynamic links not opening on older devices

### ISSUE THREAD

**Issue by sagarcia31** [firebase/quickstart-ios#915]
Hello everybody!

I'm an iOS developer, and currently I needed to use Universal iOS links using Firebase's Dynamic Links platform, before upgrading to iOS 13, when we clicked on the link sent and generated from dynamic links, we were redirected to the application that we are developing, it worked perfectly. 
After the update, when testing on iPhones 8 and 8 plus, we click on the link created and are redirected to the safari, and soon afterwards to the Appstore, but the correct behavior would be to be directed to our application. This behavior happens in newer devices like the Iphone X, and the Iphone 11. When using the Chrome mobile browser, we are directed to our application, as the chrome does not use Universal links, but the URL Schemes.
 I found a topic on an apple developer forum addressing this problem but until February 16th it had not been resolved. https://forums.developer.apple.com/thread/123554

**Comment by morganchen12** [comment]
Hey @sagarcia31, this is a known issue and we're working on resolving it; see https://github.com/firebase/firebase-ios-sdk/issues/4914.

**Comment by sagarcia31** [comment]
Thanks
