### ISSUE TITLE
Firebase Dynamic Linking for iOS version 9.0 and above unable to get URL using object FIRDynamicLink object. Its giving nil value

### ISSUE THREAD

**Issue by dipaksm** [firebase/quickstart-ios#923]
Please refer below link and give me solution if anybody have.

https://stackoverflow.com/questions/39701757/firebase-dynamic-linking-for-ios-version-9-0-and-above-unable-to-get-url-using-o

**Comment by morganchen12** [comment]
Looks like someone has answered your question on StackOverflow.
