### ISSUE TITLE
[ML Kit translate] Feature request : support macos

### ISSUE THREAD

**Issue by sachaarbonel** [firebase/quickstart-ios#927]
Hi, [FlutterFire](https://github.com/FirebaseExtended/flutterfire), which is an unofficial Firebase plugins repository for Flutter apps started supporting more and more macos plugins for Fluttter Desktop apps. Would it be possible to support macos as well ?
In an effort to do so I tried to port an ios plugin to macos but I'm getting this error : `The platform of the target 'Runner' (macOS 10.11) is not compatible with 'Firebase/MLNaturalLanguage (6.12.0)', which does not support 'macOS'.`.

**Comment by morganchen12** [comment]
Adding macOS support for ML Kit is unlikely to happen in the near future. Currently the closest thing is to use Firebase Storage to download TF Lite models on macOS.

**Comment by sachaarbonel** [comment]
Thank's for the hint I'll do that then. Do you know where I can find the source code of Ml kit to get all the urls/or some firebase storage code I can port in order to download the models?

**Comment by morganchen12** [comment]
ML Kit is not open-source, but Firebase Storage is. The source code for Storage is [here](https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseStorage), and its documentation is [here](https://firebase.google.com/docs/storage).

Many of ML Kit's models are available on the TF Lite website [here](https://www.tensorflow.org/lite/models).
