### ISSUE TITLE
MessagingRemoteMessage is deprecated.

### ISSUE THREAD

**Issue by JaredHalpern** [firebase/quickstart-ios#932]
https://github.com/firebase/quickstart-ios/blob/cef37defb946d04b9b7d0ec0414457b7200d95a6/messaging/MessagingExampleSwift/AppDelegate.swift#L173

`MessagingRemoteMessage` is deprecated: FCM direct channel is deprecated.
We should be using use APNs for downstream message handling.

**Comment by paulb777** [comment]
cc: @chliangGoogle

**Comment by JaredHalpern** [comment]
Thanks for looking into this + handling! :)
