### ISSUE TITLE
Crashlytics shows missing line 

### ISSUE THREAD

**Issue by seanliu1** [firebase/quickstart-ios#933]
Crashed: com.apple.main-thread
0  TestApp                          0x1006d4d74 (Missing)
1  TestApp                          0x1006d4d98 (Missing)
2  CoreFoundation                 0x18e6f6288 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
3  CoreFoundation                 0x18e6f62d0 ___CFXRegistrationPost1_block_invoke + 64
4  CoreFoundation                 0x18e6f5630 _CFXRegistrationPost1 + 368
5  CoreFoundation                 0x18e6f52e8 ___CFXNotificationPost_block_invoke + 104
6  CoreFoundation                 0x18e67159c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1416
7  CoreFoundation                 0x18e6f4c38 _CFXNotificationPost + 1244
8  Foundation                     0x18ea510c8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 60
9  UIKitCore                      0x192815a9c -[UIApplication _stopDeactivatingForReason:] + 1188
10 UIKitCore                      0x191febdf4 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2 + 104

dYSM is uploaded, but it still shows as missing 

0  TestApp                          0x1006d4d74 (Missing)
1  TestApp                          0x1006d4d98 (Missing)

**Comment by morganchen12** [comment]
Have you checked that the uploaded dSYM matches the UDID of your release bundle?
