### ISSUE TITLE
Revert to previous version of Firebase

### ISSUE THREAD

**Issue by bakshioye** [firebase/quickstart-ios#937]
Due to some crash happening in current version of **Firebase** `Firebase/Core (6.20.0)`, I want to revert to a previous version of **Firebase** `Firebase/Core (6.15.0)` that was working for my project. Is there a way to revert to previous version ?

**Comment by morganchen12** [comment]
Specify the version in CocoaPods.

```ruby
pod 'Firebase', '= 6.15.0'
```
