### ISSUE TITLE
Error "Undefined symbols for architecture x86_64:   "___isOSVersionAtLeast"" after adding Firebase (Xcode/Swift)

### ISSUE THREAD

**Issue by EvanMurphy17** [firebase/quickstart-ios#941]
Xcode: Version 11.3.1 (11C504)
Toolchain: Swift 5.1.3 Release 2019-12-13 (a)

Full error:

`Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      ___54+[GULSceneDelegateSwizzler proxyOriginalSceneDelegate]_block_invoke in GULSceneDelegateSwizzler.o
      +[GULSceneDelegateSwizzler handleSceneWillConnectToNotification:] in GULSceneDelegateSwizzler.o
      -[GULSceneDelegateSwizzler scene:openURLContexts:] in GULSceneDelegateSwizzler.o
      +[GULSecureCoding unarchivedObjectOfClasses:fromData:error:] in GULSecureCoding.o
      +[GULSecureCoding archivedDataWithRootObject:error:] in GULSecureCoding.o
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by paulb777** [comment]
This looks like the result of linking Xcode 11 built objects with Xcode 10.

**Comment by EvanMurphy17** [comment]
Thanks @paulb777, how would I go about doing that? Sorry, I am new to Xcode and Swift

**Comment by morganchen12** [comment]
How are you integrating Firebase? Also, what version of Firebase are you using?

**Comment by EvanMurphy17** [comment]
@morganchen12 integrated using cocoa pods and using Firebase version 6.21.0

**Comment by morganchen12** [comment]
If you're using CocoaPods, you can probably just delete the artifacts in your build cache and try rebuilding. Run `rm -rf ~/Library/Developer/Xcode/DerivedData` and clean your Xcode build, then try again.

**Comment by EvanMurphy17** [comment]
@morganchen12 thanks Morgan. I just tried that and the build still failed with the same error.

**Comment by EvanMurphy17** [comment]
@morganchen12 @paulb777 any other thoughts on how I could fix this? Thanks

**Comment by EvanMurphy17** [comment]
Moved to ios-sdk
