### ISSUE TITLE
Translate project and iPhone Dark Mode

### ISSUE THREAD

**Issue by abokhalel2** [firebase/quickstart-ios#942]
Thank you for the amazing project!

I downloaded the quickstart sample for the translate feature:
https://github.com/firebase/quickstart-ios/tree/master/translate/TranslateExample

and I added the required element, and the project ran smoothly without errors. However, the main page appeared like this:
![TranslateProject](https://i.postimg.cc/PqzzYKXp/IMG-5433.png)

The application looked like a mess, and I wasn't able to see the languages list. After investigating the issue, I discovered that the issue is related to the Dark Mode in the iPhone system being Active. Once I deactivate it, the application looked great, and everything was appearing as it should be.

My suggestion: consider supporting iPhone Dark Mode or disable its effect on your examples to avoid confusion.

**Comment by ulukaya** [comment]
You are right, sample doesn't support Dark Mode.
We'll update all quickstarts to support Dark mode soon. However this sample is moved to https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/translate
