### ISSUE TITLE
Can I configure FirebaseApp outside didFinishLaunchingWithOptions on first installation of App

### ISSUE THREAD

**Issue by bakshioye** [firebase/quickstart-ios#945]
My app supports multiple clients(or businesses) using same App. For each client we have a separate `GoogleService-Info.plist`. 

Since there is a Single app and multiple `GoogleService-Info.plist`, I was thinking to make the user select their client(or business, say `branch1`) and then upon their selection, I will download that particular client's data including the data that goes inside `GoogleService-Info.plist` file, save it into `Documents Directory` and later use `FirebaseOptions(contentsOfFile: )` to configure the FirebaseApp.

Now for the very first time, when client selection is to be done, there will be no data( like the one we have in `GoogleService-Info.plist`) already present with us. So we cannot configure inside `didFinishLaunchingWithOptions`. But after client selection is done and data is downloaded and saved in `Documents Directory`, now with every launch of our app, we can configure inside `didFinishLaunchingWithOptions`

So my main question whether, for the very first time can I configure from outside the `didFinishLaunchingWithOptions` method , maybe from some other `ViewController` or should I adopt some other approach ?

**Comment by morganchen12** [comment]
Yes, you can do this. You may run into some Analytics issues, but pretty much every other service should work without issue.
