### ISSUE TITLE
Firebase Analytics - How does the request suspend?

### ISSUE THREAD

**Issue by tantran-phdv** [firebase/quickstart-ios#956]
I don't know the Firebase Analytics have any api to process requests which that failed?

**Comment by morganchen12** [comment]
Analytics will retry uploads that fail automatically, but I am not sure what the mechanism for this is.

**Comment by ToddKerpelman** [comment]
Yep -- Analytics does incremental back-up-and-retry when the app is opened again. I might recommend watching [this video](https://youtu.be/XrltP8bOHT0?t=1091) for more information.
