### ISSUE TITLE
can I applied 3D model or texture and materials on Face detection 

### ISSUE THREAD

**Issue by kushwaha03** [firebase/quickstart-ios#959]
Generally I got all face points and we have create  Layer for Face Points shape (eye, lip, eyebrow, nose). 
and I want to applied Materials and texture 
is that possible ??

**Comment by morganchen12** [comment]
ML Kit does not provide any utilities for drawing extra stuff on this face, but you can do this manually by (for example) applying a filter to the pixel buffers before displaying them.

**Comment by kushwaha03** [comment]
> y (for example) apply

Please help me, I'm new here. i tried but nothing is working.
simply i want to use materials or image in face detection points

**Comment by morganchen12** [comment]
Drawing on the face is pretty complex and outside of the scope for Firebase support. You may be able to find more help on StackOverflow.

**Comment by kushwaha03** [comment]
> Drawing on the face is pretty complex and outside of the scope for Firebase support. You may be able to find more help on StackOverflow.

already asked question in stackoverflow,  didin't get help please see
https://stackoverflow.com/questions/61285687/try-makeup-using-mlkit-ios-swift
