### ISSUE TITLE
Reconfigure FirebaseApp instance after first time initialisation

### ISSUE THREAD

**Issue by bakshioye** [firebase/quickstart-ios#960]
For this [use case](https://github.com/firebase/quickstart-ios/issues/945), Since I am not initialising in `AppDelegate`, for the very first time, I cannot get **FCM_TOKEN** right away. The Actual `GoogleServiceInfo.plist` file's data will be available to me after I successfully login where I was planning to configure at that point. But the problem is, while login, I need **FCM_TOKEN** to be passed as a parameter.

To overcome that I added a dummy `GoogleServiceInfo.plist` (which belongs to a different project), initialised using this `GoogleServiceInfo.plist ` file and then got the **FCM_TOKEN** right away. Performed the Login and got the real(the one that I need for the client using my app currently, which I figure out during login) `GoogleServiceInfo.plist` data. But now when I'm trying to reconfigure the app using the new data, it says

> *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'

Is reconfiguration somehow possible, like disabling the previous one and initialising a new one or is there some other approach to resolve this ( other than not requiring **FCM_TOKEN** as parameter for the Login API call)

Also, If I change the approach the avoid FCM_TOKEN at login, when I reconfigure, I get this warning in console

> Analytics requires Google App ID from GoogleService-Info.plist. Your data may be lost. Google App ID has been changed. Original, new ID: <GoogleServiceInfo.plist's App ID>, <App ID of actual project>

**Comment by morganchen12** [comment]
Hey @bakshioye, this is currently not (cleanly) possible. You can delete the default app and reconfigure it, but it may result in lost Analytics events.

**Comment by bakshioye** [comment]
How do I delete it and reconfigure? I'm trying  `FirebaseApp.app() = nil` but gives the following error :

> Expression is not assignable: function call returns immutable value

**Comment by morganchen12** [comment]
Use [this method](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRApp#/c:objc(cs)FIRApp(im)deleteApp:).

**Comment by bakshioye** [comment]
Also, ` func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` method is being called multiple times, 3 to be precise, during fresh installation of the app with 3 different tokens. After fresh installation of the app, I am configuring the FirebaseApp twice, one at start of the app and second after Login. After this, for every following launch of the app, FirebaseApp is configured only once and this method is called only once

When exactly is this method called? What triggers it?

**Comment by morganchen12** [comment]
It's called when the system supplies a new APNs token. You can check when your app receives a new device token with [this method](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application).

**Comment by bakshioye** [comment]
@morganchen12  No I'm talking about the one that Apple Push Notification framework generates, that is only generated once, I am talking about the one that Firebase generates, the FCM_TOKEN, which is generated 3 times and in that too, all the 3 are completely different.

**Comment by morganchen12** [comment]
It's called whenever Firebase gives you a new FCM token, and is guaranteed to be called (asynchronously) when your app receives a new device token. It may be called more often than that though. You should use the latest token you receive.

**Comment by bakshioye** [comment]
@morganchen12  Is there a way to *disable* the incoming FCM token? Like the FCM token linked to the Device token is generated and now I tell Firebase *please don't generate anymore FCM tokens* ? Also, is it called/ generated (or in short, the above delegate method is called) when I configure the `FirebaseApp` ? Because **after** initial app setup (First time installation), **I am not generating the device token on subsequent app launches** but the delegate method is still called every time so I think it is somehow linked to the FirebaseApp initialisation as well because that is the only thing that I am performing on each app launch.

Also, I send the FCM Token to the backend in the Login API, at that point I have already generated 2 different FCM tokens (one from FirebaseApp init and one from Device token, I think) and the **second one** gets sent to the backend. 

Now, I get the actual(related to the client) Firestore data in the login response and then reconfigure FirebaseApp using that data and then another FCM token is generated and on each subsequent launch of the app, this token(last, the third one) is provided via delegate method every time. But since I have already sent the FCM token to the server during login, this one is of no use but it is the latest one !  What should I do in this scenario ?

**Comment by morganchen12** [comment]
Messaging will return the existing token on each app launch, but this token should not be different from previous tokens on every app launch. When you get a new token, you should just overwrite the previous one in Firestore.

**Comment by bakshioye** [comment]
@morganchen12  But rather than each *launch* of the app, is it linked to *Firebase's initialisation* (as Firebase is also initialised during app launch) ? Because the thing I observed is the following:

During fresh(first) installation of the app:
1 FCM token(say *abc*) generated when the app is launched
1 FCM token(say *def*) generated when device token is generated
1 FCM token(say *ghi*) is generated when I reconfigure the default Firebase instance with other data (i.e. data fetched from the backend rather than `GoogleServiceInfo.plist` inside the app)

On each subsequent launch:
1 FCM Token (*ghi*) is generated on the launch of the app (Using the data that came in from the backend)

*By generating, I mean **Messaging's** `func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)` is called*

Now, after fresh installation, for each subsequent launch, I am **not** performing the following two tasks (or one can say the following tasks were **only performed on fresh installation a.k.a first time app installation**):

- Reconfigure firebase app (meaning only configured once when inside `didFinishLaunchingWithOptions`) rather than twice as compared to first time installation
- Device token generation 

Since these two events are **not** performed for the subsequent launch, I think FCM token is **not** generated 2 more times i.e only generated 1 time compared to the 3 times for first time installation

So I think *Firebase initialisation* also triggers the delegate method and since I am initialising with the same data on each subsequent launch, the FCM token remains the same. Is the assumption correct ?

**Comment by morganchen12** [comment]
Messaging requires FirebaseApp to be initialized before it can run, so it should not return a new token before the FirebaseApp has been initialized. Each Messaging token is tied to a particular FirebaseApp, so it should give you a new token if you reconfigure Firebase with a new app.

**Comment by bakshioye** [comment]
Thank you @morganchen12 for the detailed explanation
