### ISSUE TITLE
Can't add Firebase to my private pod as dependency

### ISSUE THREAD

**Issue by xsoti** [firebase/quickstart-ios#97]
I added Firebase to *.podspace file in my private Pod, installation finished with success but I can't see Firebase under Pods/Frameworks in Swift project where I'm using my private Pod. I checked and I can add and see other pods without problems, also those wrote in ObjC so I assume that issue has something to do with Firebase.

I'm using cocoapods-1.0.1, Xcode 7.3.1 and Firebase 3.6.0

**Comment by mcdonamp** [comment]
It's actually a problem with how CococaPods handles pods, see: https://github.com/CocoaPods/CocoaPods/issues/5368 for more info.

**Comment by OnurVar** [comment]
Why is this thread closed ? They're refering this problem to you, and you are refering to them ? You can also check my git repo to see the problem : [https://github.com/OnurVar/LockBase](Repo)

**Comment by morganchen12** [comment]
This is an issue on our (Firebase's) end; in order for developers to use Firebase libraries as dependencies of dependencies we must ship our frameworks as dynamic frameworks, which we currently don't. There are plans to in the future, but I can't give you any dates or promises.

**Comment by OnurVar** [comment]
@morganchen12 Thx, I will be waiting for the update 👍

**Comment by mradzinski** [comment]
Any updates on this? It's a very sad limitation. We really need to use Firebase as a dependency for one of our internal pods and we are looking for other alternatives because of this issue.

**Comment by OnurVar** [comment]
I don't think so. We are also moving out from Firebase. Any news @morganchen12 ?

**Comment by morganchen12** [comment]
Nope, Firebase continues to ship as a static framework.

**Comment by benoy** [comment]
After 2 months any update on this?
because of same issue, we are also moving out from Firebase

**Comment by morganchen12** [comment]
We're working on a solution, but I can't give a timeframe. In the meantime, if you absolutely must use Firebase as a dependency of a dependency, you can hack around this limitation the way FirebaseUI-iOS does.

**Comment by azmeuk** [comment]
I am feeling very concerned by this issue too.

**Comment by benoy** [comment]
Could you please give a clue about what hack FirebaseUI-iOS does

**Comment by morganchen12** [comment]
FirebaseUI distributes itself as a static framework binary with a static dependency on Firebase. Take a look at the [build script](https://github.com/firebase/FirebaseUI-iOS/blob/master/build.swift) and [podspec](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseUI.podspec) files for more info.

**Comment by tirrorex** [comment]
One other option seems to be to include firebase framework directly as a binary

**Comment by tunds** [comment]
We seem to be having a similar issue where we have an internal library which references this pod as a dependency using the `dependency` option provided by Cocoapods. Whenever we try to validate if this podspec is valid we seem to be getting an error. **Unable to find a specification for ‘Firebase/Core’ dependent upon by myLib** could this be related to the comment above about Firebase being a static library? When developing internal libraries that are private would we be better off adding the framework binary manually to the Cocoapods? What would you advise?
