### ISSUE TITLE
[ML Text Recognition] Different result on different iOS device

### ISSUE THREAD

**Issue by artemsivcev** [firebase/quickstart-ios#970]
Hey there! I have 2 same images and 2 iPhones: 8 and X. UIImage have scale set to 1 and cropped width and height by app. Then I send this image in onDeviceTextRecognizer() and get 2 different maps with all different results. Why so? Is there some scale dependence in ML KIT library?
Images is not too small. height = 2048, width = 1383.
I have same result without cropping image.

**Comment by morganchen12** [comment]
Closing this in favor of https://github.com/firebase/firebase-ios-sdk/issues/5575.
