### ISSUE TITLE
iOS 10 FCM code doesn't work (Xcode 8.0 GM)

### ISSUE THREAD

**Issue by Benjaminm5** [firebase/quickstart-ios#98]
The code at the bottom of the FCMSwift/AppDelegate.swift for Messaging handling on iOS10 doesn't work. If i try to build or run my app I get a Swift Compiler Error:

> Command failed due to signal: Segmentation fault: 11

If i remove that code i don't get that error.

**Comment by lethianqt94** [comment]
I got the same error.

**Comment by SweetBloodyDuck** [comment]
Yea I got the same. When I remove all ios10 code from demo, it works fine...

**Comment by nanonetAndroid** [comment]
I've upgraded to Cocoa pod 1.0.1 and all seems to work.

**Comment by vinamelody** [comment]
I'm using Cocoa pod 1.0.1, XCode Version 8.0 (8A218a) and having this error Ambiguous reference to member 'subscript' on line `print("Message ID: \(userInfo["gcm.message_id"]!)")`

**Comment by ianbarber** [comment]
I'm not seeing that error in xcode 8.1, so the linting may be fixed in the latest version.

**Comment by choiks14** [comment]
same here

**Comment by kiwi07** [comment]
This is solution.
To be able to receive notification when the app in background. You must implement this method in your AppDelegate

**- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(nonnull void (^)())completionHandler**

This is my code snippet that works:
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(nonnull void (^)())completionHandler
{
    // Print message ID.
    NSDictionary *userInfo = response.notification.request.content.userInfo;
    NSLog(@"Message ID: %@", userInfo[@"gcm.message_id"]);
    
    NSString* strURL = userInfo[@"URL"];
    NSString* strMessageTitle = [[[userInfo valueForKey:@"aps"] valueForKey:@"alert"] valueForKey:@"title"];
    NSString* strMessage = [[[userInfo valueForKey:@"aps"] valueForKey:@"alert"] valueForKey:@"body"];
    
    // Print full message.
    NSLog(@"%@", userInfo);
}

**Comment by jingchc** [comment]
Thanks @vinamelody ! It's work for me !

**Comment by jordibruin** [comment]
Updating Cocoapods to 1.0.1 doesn't fix this for me. Also the 8.1 beta doesn't fix the issue.

**Comment by rickythefox** [comment]
Still getting segfaults in XCode 8.1

**Comment by ianbarber** [comment]
Closing  on the basis of use_frameworks! and updated cocoapods. If people are still getting an issue, probably easiest to file a new one with explicit error you're seeing at this point.
