### ISSUE TITLE
Messaging demo app not compiling

### ISSUE THREAD

**Issue by GitteM** [firebase/quickstart-ios#99]
Messaging demo app not compiling
<img width="455" alt="screen shot 2016-09-19 at 4 47 10 pm" src="https://cloud.githubusercontent.com/assets/3731374/18636698/0a30a304-7e8a-11e6-8dd3-3d57062dadaf.png">

**Comment by SweetBloodyDuck** [comment]
do you install pod?

**Comment by lethianqt94** [comment]
Image for me. Using pod install.
![screen shot 2016-09-20 at 11 50 02 am](https://cloud.githubusercontent.com/assets/10287585/18657871/723a634c-7f28-11e6-9e64-0971760f3280.png)

**Comment by Benjaminm5** [comment]
Can you send a screenshot from the top of that file? and the podfile also?

**Comment by GitteM** [comment]
I ran pod install before opening the workspace - the project did not compile.

<img width="917" alt="screen shot 2016-09-20 at 9 41 50 am" src="https://cloud.githubusercontent.com/assets/3731374/18661560/a3f57c58-7f16-11e6-81bf-623bb2587a06.png">

**Comment by Benjaminm5** [comment]
did you import Firebase at the top of AppDelegate file?

**Comment by GitteM** [comment]
The demo project imports the following:
@import Firebase;
@import FirebaseInstanceID;
@import FirebaseMessaging;

**Comment by Benjaminm5** [comment]
Yeah found that...got the same error. I commented those lines (if #available(iOS 10.0, *, etc.) out for the moment but would be nice if Firebase finds a solution here!

**Comment by lethianqt94** [comment]
@Benjaminm5: I imported <import UserNotifications> to avoid compile errs. But those functions are a bit outdated with Swift 3.

**Comment by Benjaminm5** [comment]
Tried that but that I still get that error :/

**Comment by SweetBloodyDuck** [comment]
do you have Xcode 8?

**Comment by lethianqt94** [comment]
@SweetBloodyDuck yes, I use Xcode 8.

**Comment by joaocruz04** [comment]
Same here. XCode 8, same imports, same pods, same errors.

**Comment by GitteM** [comment]
Yes, Xcode 8.

**Comment by joaocruz04** [comment]
I have figured it out. I saw that I'm using Using FirebaseMessaging (1.1.0) when the latest version is 1.2.0. you have to update your cocoa pods repos.

> pod repo update
then
> pod update

It may take a while though.
