### ISSUE TITLE
rnfirebase messaging().getToken(); | [messaging/unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.)

### ISSUE THREAD

**Issue by WiharlleyWill** [firebase/quickstart-ios#995]
Hello! I've already done all the settings for firebase and Apple, Keys, .p8 certificate ... Two days ago the notifications were arriving correctly and I was also able to recover the token, however, it stopped working and the return of the .getToken () function is the following error:

`[messaging / unknown] The operation couldn’t be completed. (com.firebase.iid error 1001.)
`
I am attentive to the forums, however none of the solutions provided solved my situation or that of others.

* Yes, I am using a real device, it is not via emulator.

```
async getTokenIOS() {
        const authStatus = await messaging().requestPermission();

        if (authStatus) {
            try {
                console.log('Inicio TRYCATCH')

                const token = await messaging().getToken();
                console.log('token: ' + token)

                AsyncStorage.setItem('token', '' + token);
            } catch (err) {
                console.log('err: ' + err)
            }
        }
    }
```

**Comment by morganchen12** [comment]
1001 is [defined here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/InstanceID/NSError%2BFIRInstanceID.h#L43) and indicates InstanceID wasn't able to receive a device token. Can you implement the APNs token handler and confirm you're getting and APNs token from iOS?

**Comment by WiharlleyWill** [comment]
Apparently to get back to work, I had to upload a version for TestFlight. After testing "officially" getToken () also worked again in debug mode (Developer).

The reason is unknown, perhaps some key authorization bug from Apple and Firebase

**Comment by morganchen12** [comment]
Thanks for sharing the results of your investigation!
